[ALLI-5682] Record image changes
NatLibFi/NDL-VuFind2 pull request #1287
Opened 2019-04-11 08:18 UTC by LuomaJuha

Opened pull request for keeping track of needed things to check
TODO:
/* Record page changes */
- [ ] Record page no image working
- [x] Record page image working
- [x] Paginator working
- [ ] Record page style set
- [ ] Record page translations
- [ ] Show fewer items on certain widths

/* Modal */
- [ ] Modal non zoomable styles set 
- [ ] Modal zoomable styles set
- [ ] Jump to next paginator if there is no image set
- [x] Image information area working

/* Lists General */
- [ ] Stylings

/* List */
- [x] List paginator working

/* List grid */
- [x] Masonry now correctly works, fixes a problem with old version where image was bigger
- [x] Paginator works

/* List condensed */
- [x] paginator works

/* Favorites list * /

/* General */
- [ ] Translations
- [ ] Clean unused less files
- [ ] Check all image sizes

2019-04-16 07:25 UTC, EreMaijala commented on themes/finna2/js/finna-image-paginator.js
> +  var previousRecordButton = '<button class="mfp-arrow mfp-arrow-left previous-record" type="button"><</button>';
< pitäisi olla &lt;

2019-04-16 07:26 UTC, EreMaijala commented on themes/finna2/js/finna-image-paginator.js
> +  var nextRecordButton = '<button class="mfp-arrow mfp-arrow-right next-record" type="button">></button>';
&gt;

2019-04-16 07:32 UTC, EreMaijala commented on themes/finna2/js/finna-image-paginator.js
> +    _.recordId = settings.recordId;
Jos asetukset laittaisi erilliseen memberiin, niin voisi käyttää jQueryn extend():iä niiden laittamiseen (ks. vaikka finna-map.js:22)

2019-04-16 10:13 UTC, EreMaijala requested changes

2019-04-16 10:13 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/record-image-popup-information.phtml
> +</script>
rivinvaihto uupuu

2019-06-03 07:52 UTC, samuli approved these changes

2019-06-03 08:07 UTC, merged