[ALLI-5649] Axiell Aurora loanhistory implementation
NatLibFi/NDL-VuFind2 pull request #1448
Opened 2019-10-23 14:08 UTC by LuomaJuha

Allows users to view their transaction history. Requires loanAurora.wsdl to work properly.

2019-11-15 13:25 UTC, EreMaijala requested changes

2019-11-15 13:25 UTC, EreMaijala commented on module/Finna/src/Finna/ILS/Driver/AxiellWebServices.php
> +        $transActions = $this->objectToArray(
pienellä A:lla transaction

2019-11-15 13:25 UTC, EreMaijala commented on module/Finna/src/Finna/ILS/Driver/AxiellWebServices.php
> +            ? ($params['page'] - 1) * $pageSize : 0,
sisennä rivi

2019-11-15 13:25 UTC, EreMaijala commented on module/Finna/src/Finna/Controller/MyResearchController.php
> +        $view->purgeAllowed = $catalog->checkCapability(
Tän tarkistuksen voisi tehdä templatessa (vrt. menu.phtml) niin ei tarvitse yliajaa tätä metodia.

2019-11-15 13:25 UTC, EreMaijala commented on module/Finna/src/Finna/ILS/Driver/AxiellWebServices.php
> +    protected $loansaurora_wsdl = '';
supportsMethod:n pitäisi palauttaa false, jos tämä on tyhjä.

2019-11-18 08:40 UTC, LuomaJuha commented on module/Finna/src/Finna/ILS/Driver/AxiellWebServices.php
> +    protected $loansaurora_wsdl = '';
Lisätty supportsMethodiin tarkastus onko kyseinen linkki tyhjä. Tehty sama patronaurora wsdl:lle

2019-11-18 08:42 UTC, LuomaJuha commented on module/Finna/src/Finna/ILS/Driver/AxiellWebServices.php
> +        $transActions = $this->objectToArray(
done

2019-11-18 08:42 UTC, LuomaJuha commented on module/Finna/src/Finna/ILS/Driver/AxiellWebServices.php
> +            ? ($params['page'] - 1) * $pageSize : 0,
done

2019-11-18 08:43 UTC, LuomaJuha commented on module/Finna/src/Finna/Controller/MyResearchController.php
> +        $view->purgeAllowed = $catalog->checkCapability(
done, siirretty historicloans.phtml

2019-11-20 11:07 UTC, EreMaijala commented on themes/finna2/templates/myresearch/historicloans.phtml
> +    $purgeAllowed = $catalog->checkCapability('purgeTransactionHistory');
checkCapability tarvitsee patron:n kuten menu.phtml:ssä. Muuten tarkistetaan oletusajurilta..

2019-11-20 11:20 UTC, LuomaJuha commented on themes/finna2/templates/myresearch/historicloans.phtml
> +    $purgeAllowed = $catalog->checkCapability('purgeTransactionHistory');
Done

2019-11-20 12:05 UTC, EreMaijala approved these changes

2019-11-20 12:05 UTC, merged