[ALLI-6338] Pagination improvements
NatLibFi/NDL-VuFind2 pull request #1614
Opened 2020-05-08 06:29 UTC by LuomaJuha

Removed magnificpopup
Moved popup specific code to new finnaPopup js, paginator should just be paginator
Person should no longer be required to tab again to focus next or previous popup buttons
Simplifies reindexin of paginators, should be tested with authors
Finnapopup can be used to embed stuff inline to elements
Video buttons are now initialized with finnapopup js
Removes not needed hidden triggers if no images are shown
iFrame videos now also open inside popup as does normal videos if record popup is open

2020-05-12 07:50 UTC, LuomaJuha commented
Ready for checking, userlistembed and authorities tested and working. Fixed a problem in userlistembed => video links are now properly initialized when new content via show all links button

2020-05-12 10:40 UTC, EreMaijala requested changes

2020-05-12 11:12 UTC, LuomaJuha commented on themes/finna2/js/finna-image-paginator.js
> +    var popupHidden = $.fn.finnaPopup.isOpen() === false;
Lyhennetty

2020-05-12 11:12 UTC, LuomaJuha commented on themes/finna2/js/finna-popup.js
> +    var tmp = params.id;
tmp on nykyään perus id

2020-05-12 11:13 UTC, LuomaJuha commented on themes/finna2/js/finna-popup.js
> +        if (typeof p.id === 'string') {
Tätä tarkastusta ei itseasiassa tarvittu koska nuo on määritelty ylempänä joten poistin tuosta muutaman turhan rivin

2020-05-12 11:19 UTC, EreMaijala approved these changes

2020-05-12 11:44 UTC, samuli approved these changes

2020-05-12 12:18 UTC, pasitii commented on themes/finna2/js/finna-popup.js
> +var closeTemplate = '<button class="finna-popup close-button" title="close_translation">X</button>';
Aiemmin X oli pienellä. Nyt sulkupainike on mielestäni liian voimakas (pidin vanhasta asettelusta enemmän, jossa sulkupainike oli linjassa modal-ikkkunan kanssa). Voisiko sulkupainikkeen tehdä saavutettavammin?

2020-05-13 06:00 UTC, LuomaJuha commented on themes/finna2/js/finna-popup.js
> +var closeTemplate = '<button class="finna-popup close-button" title="close_translation">X</button>';
Ruksia muokkailtu!

2020-05-13 06:20 UTC, pasitii commented on themes/finna2/js/finna-popup.js
> +var closeTemplate = '<button class="finna-popup close-button" title="close_translation">X</button>';
näyttää paremmalta

2020-05-13 06:30 UTC, pasitiis approved these changes

2020-05-13 06:38 UTC, merged