[ALLI-6307] Advanced search target list updates
NatLibFi/NDL-VuFind2 pull request #1622
Opened 2020-05-19 11:01 UTC by LuomaJuha

Adjusted translations and added a search target option for description

2020-05-20 10:45 UTC, LuomaJuha commented
Closed due to stuck travis tasks

2020-06-03 12:05 UTC, EreMaijala requested changes

2020-06-03 12:05 UTC, EreMaijala commented on local/config/finna/searches.ini.sample
> -;JournalTitle        = adv_search_journaltitle
Nyt kun ottaa puolipisteen pois, menee sisennys vinoon.

2020-06-03 12:05 UTC, EreMaijala commented on local/languages/finna/fi.ini
> +adv_search_geographic = "Alue/Paikka"
P pienellä

2020-06-03 12:05 UTC, EreMaijala commented on local/languages/finna/fi.ini
> +adv_search_title = "Nimeke/Otsikko"
O pienellä.

2020-06-03 12:05 UTC, EreMaijala commented on local/languages/finna/sv.ini
> +adv_search_geographic = "Ort/Plats"
P pienellä

2020-08-19 09:18 UTC, samuli approved these changes

2020-08-19 09:18 UTC, merged