[ALLI-6464] AOE: Learning material recommendation module
NatLibFi/NDL-VuFind2 pull request #1664
Opened 2020-07-16 13:45 UTC by aleksip

2020-10-21 09:44 UTC, EreMaijala requested changes
Saadaanko käännöstekstit vai pitääkö kehitellä jotain?

2020-10-21 09:44 UTC, EreMaijala commented on module/Finna/src/Finna/Recommend/LearningMaterial.php
> +    const LEARNING_MATERIAL_FILTER_FIELDS = [
const:eille ja protected:eille dokkarikommentit

2020-10-21 09:44 UTC, EreMaijala commented on module/Finna/src/Finna/Recommend/LearningMaterial.php
> +                    && $facet['value'] == self::LEARNING_MATERIAL_FILTER_VALUE
Tämä toimii vain, jos on valittu formaatin päätaso. Entä jos käyttäjä valitsee jonkin LearningMaterial-alaformaatin? Voi olla, ettei sellaisia juuri nyt ole, mutta pitäisi varautua siihen, että on. Eli tässä pitäisi tarkistaa, että hierarkian ylin taso on LearningMaterial riippumatta valitusta tasosta.

2020-10-21 09:44 UTC, EreMaijala commented on module/Finna/src/Finna/Recommend/LearningMaterial.php
> +                if (isset($tab['id']) && $tab['id'] == 'L1' && isset($tab['url'])) {
Tabilla on pakko olla id jolloin isset turha, eikö? Voisi joka tapauksessa yksinkertaistaa hiukan: `if (($tab['id'] ?? '' === 'L1' && isset($tab['url'])) {`

2020-10-21 11:29 UTC, aleksip commented
> Saadaanko käännöstekstit vai pitääkö kehitellä jotain?

Käännöstekstit tulevat tosiaan vielä. Lisäksi vielä on päättämättä mitä tehdään, jos ollaankin tarkennetussa haussa. Voi olla että suosittelijaa ei näytetä ollenkaan, mutta jos näytetään, pitäisi ilmeisesti ohjata tavallisen L1-haun välilehdelle. Nyt tarkennetussa haussa saatu välilehtilinkki vie L1-haun kotisivulle, koska backend ei tue tarkennettua hakua. Sinne ei kuitenkaan haluta linkittää.

2020-10-21 11:59 UTC, EreMaijala commented
Kotisivuhan on se L1-haun aloitussivu, eli meillä ei välttämättä ole parempaakaan paikkaa. Ellei sitten tehdä sinne jotain erillistä yksinkertaista hakusivua. Tai tarkennetun haun sivua, jolla onkin vain perushaku.

2020-10-22 09:34 UTC, aleksip commented
Tästä päätettiin nyt että ei näytetä tarkennetun haun puolella ollenkaan. Pyydetyt muutokset tehty.

2020-10-26 09:14 UTC, EreMaijala approved these changes

2020-11-13 12:10 UTC, aleksip commented
Nyt pitäisi olla kaikki tehtynä.

2020-11-13 12:16 UTC, merged