[ALLI-6447] Aoe result list stylings
NatLibFi/NDL-VuFind2 pull request #1666
Opened 2020-07-21 07:28 UTC by LuomaJuha

2020-11-09 09:38 UTC, EreMaijala requested changes

2020-11-09 09:38 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/SolrLrmi/result-list.phtml
> +                <?php $urlHelper = $this->results->getUrlQuery()->removeAllFilters(); ?>
Turha?

2020-11-09 09:38 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/SolrLrmi/result-list.phtml
> +                    foreach ($field as $i => $subfield) {
Mihin tässä tarvitaan foreach:ia, jos mitään ei ikinä näytetä kuin ensimmäiselle alkiolle (`$i < 1`) jos sillekään (array_unique säilyttää avaimet, ja ilman array_values:ia sen on mahdollista tuottaa array, jossa ei ole 0-alkiota).

2020-11-09 09:38 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/SolrLrmi/result-list.phtml
> +  $topics = $this->driver->getTopics('yso');
Ei haeta rights, level, topics ennen kuin niitä oikeasti tarvitaan.

2020-11-09 10:17 UTC, LuomaJuha commented on themes/finna2/templates/RecordDriver/SolrLrmi/result-list.phtml
> +                    foreach ($field as $i => $subfield) {
Hmm, tää on näköjään jokin todella vanha tapa DefaultRecord/result-list.phtml:115 3 vuotta sitten tullut pohjaan mukana, joten kuulostaa että on vain copy-pastettu. Muokkaan nuo 2 vanhaa tuosta sitten samalla vastaamaan parempaa tapaa

2020-11-09 11:54 UTC, LuomaJuha commented on themes/finna2/templates/RecordDriver/SolrLrmi/result-list.phtml
> +                <?php $urlHelper = $this->results->getUrlQuery()->removeAllFilters(); ?>
Joo, ei tarttettu enää

2020-11-09 11:54 UTC, LuomaJuha commented on themes/finna2/templates/RecordDriver/SolrLrmi/result-list.phtml
> +                    foreach ($field as $i => $subfield) {
Pieni päivitys

2020-11-09 11:54 UTC, LuomaJuha commented on themes/finna2/templates/RecordDriver/SolrLrmi/result-list.phtml
> +  $topics = $this->driver->getTopics('yso');
kyseiset kohdat siirretty omille if kohdilleen.

2020-11-13 08:26 UTC, EreMaijala requested changes

2020-11-13 08:26 UTC, EreMaijala commented on themes/finna2/less/finna/search.less
> +  .targeted-informations {
luokan nimeksi targeted-information. Informaatio on informaatiota, eikä ole informaatioita.

2020-11-13 08:26 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/SolrLrmi/result-list.phtml
> +                <div class="learning-material">
Outo luokan nimi, kun sisällä on vain käyttöoikeudet. Voisiko poistaa ja käyttää less:ssä selektorina esim. `.record-type-lrmi .material-rights`?

2020-11-13 11:27 UTC, EreMaijala approved these changes

2020-11-16 12:26 UTC, merged