[ALLI-6316] Ignore hidden filters in collection module
NatLibFi/NDL-VuFind2 pull request #1670
Opened 2020-08-11 06:48 UTC by LuomaJuha

2020-08-11 12:55 UTC, samuli commented
@LuomaJuha hiddenFiltterit täytyy initoida myös Collection-sivulla, koska muuten rajaukset eivät tule mukaan sivun kautta tehtyyn uuteen hakuun. Nämä tarvitaan kun Collection-sivulle on siirrytty sellaisen hakuvälilehden kautta, missä on määritelty rajauksia (config.ini > `SearchTabsFilters`). Silloin hiddenFilttereiden avulla ohjataan käyttäjä takaisin oikean välilehden hakutuloksiin. Ilman initointia siirrytään aina "oletus" välilehden hakutuloksiin.

2020-08-11 12:58 UTC, samuli commented on themes/finna2/templates/search/searchbox.phtml
@LuomaJuha hiddenFiltterit täytyy initoida myös Collection-sivulla, koska muuten rajaukset eivät tule mukaan sivun kautta tehtyyn uuteen hakuun. Nämä tarvitaan kun Collection-sivulle on siirrytty sellaisen hakuvälilehden kautta, missä on määritelty rajauksia (config.ini > SearchTabsFilters). Silloin hiddenFilttereiden avulla ohjataan käyttäjä takaisin oikean välilehden hakutuloksiin. Ilman initointia siirrytään aina "oletus" välilehden hakutuloksiin.

2020-08-11 12:59 UTC, samuli requested changes
@LuomaJuha hiddenFiltterit täytyy initoida myös Collection-sivulla, koska muuten rajaukset eivät tule mukaan sivun kautta tehtyyn uuteen hakuun. Nämä tarvitaan kun Collection-sivulle on siirrytty sellaisen hakuvälilehden kautta, missä on määritelty rajauksia (config.ini > SearchTabsFilters). Silloin hiddenFilttereiden avulla ohjataan käyttäjä takaisin oikean välilehden hakutuloksiin. Ilman initointia siirrytään aina "oletus" välilehden hakutuloksiin.

2020-08-12 11:18 UTC, LuomaJuha commented
Ah, sitten toinen keino

2020-08-12 11:18 UTC, closed without merging