R2: search connector
NatLibFi/NDL-VuFind2 pull request #1697
Opened 2020-08-31 12:47 UTC by samuli

2020-09-14 07:07 UTC, EreMaijala requested changes

2020-09-14 07:07 UTC, EreMaijala commented on module/FinnaSearch/src/FinnaSearch/Backend/R2/Connector.php
> +    protected $username;
Alusta muuttujat, joita ei aseteta constructorissa.

2020-09-14 07:07 UTC, EreMaijala commented on module/FinnaSearch/src/FinnaSearch/Backend/R2/Connector.php
> +        if ($this->httpConfig['ssl_allow_selfsigned'] ?? false) {
Tarvitaanko tällaista viritystä oikeasti? Ja eikö toimi, jos config.ini:n Http-sektioon laittaa culr:n kanssa `sslverifypeer=false` tai socket-adapterissa `sslallowselfsigned=true` ?

2020-09-18 09:51 UTC, samuli commented on module/FinnaSearch/src/FinnaSearch/Backend/R2/Connector.php
> +        if ($this->httpConfig['ssl_allow_selfsigned'] ?? false) {
Tätä muutettu. Connectorin createClient asettaa clientille asetukset, jotka saa R2BackendFactoryltä:
https://github.com/NatLibFi/NDL-VuFind2/pull/1697/files#diff-782d8d729e73b9831cac80431de65a37R257
https://github.com/NatLibFi/NDL-VuFind2/pull/1701/files#diff-b3dc90195e127bd4763f7e9e7d53d824R120

2020-09-18 17:22 UTC, EreMaijala approved these changes

2020-09-18 17:22 UTC, merged