R2: REMS-registration
NatLibFi/NDL-VuFind2 pull request #1698
Opened 2020-08-31 14:10 UTC by samuli

2020-09-14 09:36 UTC, EreMaijala requested changes

2020-09-14 09:36 UTC, EreMaijala commented on local/config/finna/FeedbackForms.yaml.sample
>  #   or a different set of fields is configured in 'fields' list):
Olisi siistimpi, jos R2:n lomakkeet määriteltäisiin irrallaan FeedbackForms-lomakkeista. Ja toiminto voisi olla erillinen ja vain periä normaalin feedbackin. Silloin ei tarvitsisi tavallisen feedbackin puolelle sekoittaa R2:n maagisia tunnisteita yms.

2020-09-14 09:36 UTC, EreMaijala commented on local/languages/finna/fi.ini
> +R2_register_form_datasource = "(tiedot saatu suomi.fi-tunnistuspalvelusta)"
Suomi.fi kirjoitetaan ainakin suomi.fi:ssä isolla alkukirjaimella.

2020-09-14 09:36 UTC, EreMaijala commented on local/languages/finna/fi.ini
> +R2_register_form_help_pre_html = "<p><a href="%%url%%" data-lightbox-ignore>Lue lisää Finna-tutkijasalista</a></p><h4>Finnan tutkijasali aineistotiedon käyttöehdot</h4><p><strong>Finnan tutkijasalin
Puuttuuko tästä jotain tms.: "Finnan tutkijasali aineistotiedon käyttöehdot"? Kuulostaa oudolta.

Tuplaväli pois: "tutkijasalin  sisältämiä"

2020-09-14 09:36 UTC, EreMaijala commented on local/languages/finna/fi.ini
> +R2_register_form_title = "Käyttösitoumus Finnan tutkijasalin sisältöihin"
Kirjoitusasu joko "Finnan tutkijasali" tai "Finna-tutkijasali", nyt on molempia.

2020-09-14 09:36 UTC, EreMaijala commented on local/languages/finna/fi.ini
> +R2_register_form_usage_help_tooltip_html = "<h4>Käyttötarkoitus</h4><p>Valitse parhaiten käyttötarkoitustasi kuvaava yllä olevasta listasta.</p><p>Käyttötarkoitus tulee ilmoittaa lain mukaan aina tie
Tuplaväli: "Myös  aineistotietojen"

2020-09-14 09:36 UTC, EreMaijala commented on module/Finna/src/Finna/Controller/R2ControllerTrait.php
> +            $firstname = !empty($user->firstname)
Jos nämä kentät ovat read only, ei niitä pidä ottaa parametreista koskaan, vai?

2020-09-14 09:36 UTC, EreMaijala commented on module/Finna/src/Finna/Controller/R2ControllerTrait.php
> +            // Logged but not authorized (wrong login method etc), close form
Onko lomakkeen suora sulkeminen oikea ratkaisu? Pitäisikö näyttää ennemmin ilmoitus siitä, ettei kirjautumistapa kelpaa?

2020-09-14 09:36 UTC, EreMaijala commented on module/Finna/src/Finna/Controller/R2ControllerTrait.php
> +        if (!$user = $this->getUser()) {
sulut !()

2020-09-14 09:36 UTC, EreMaijala commented on module/Finna/src/Finna/Controller/R2ControllerTrait.php
> +        if (! \Finna\Form\Form::isR2RegisterForm($formId, true)) {
väli pois ! jälkeen

2020-09-14 09:36 UTC, EreMaijala commented on module/Finna/src/Finna/Controller/R2ControllerTrait.php
> +            $user = $this->getUser();
$user on jo haettu aiemmin

2020-09-14 09:36 UTC, EreMaijala commented on module/Finna/src/Finna/Controller/R2ControllerTrait.php
> +            if (! $form->isValid()) {
väli pois ! jälkeen

2020-09-14 09:36 UTC, EreMaijala commented on module/Finna/src/Finna/Controller/R2ControllerTrait.php
> +                $this->flashMessenger()->addErrorMessage($e->getMessage());
Yleensä exceptionit logataan, mutta ei näytetä käyttäjälle, ettei vahingossa paljasteta mitään ylimääräistä.

2020-09-14 09:36 UTC, EreMaijala commented on module/Finna/src/Finna/Form/Form.php
> +     * Check if the given form is a R2 registratioin form.
typo

2020-09-14 09:36 UTC, EreMaijala commented on module/Finna/src/Finna/Form/Form.php
> +     * @param boolean $checkOnlyNewUserForm Check only new user registration form?
Ei tohon kysymysmerkkiä tartte, mutta parempi selitys voisi olla. Olisko siistimpi, jos palauttaisi tiedon siitä, millainen form annettu lomake on booleanin sijaan?

2020-09-18 12:51 UTC, samuli commented on module/Finna/src/Finna/Controller/R2ControllerTrait.php
> +            $firstname = !empty($user->firstname)
Jeps, muutin ottamaan aina profiilista.

2020-09-21 10:55 UTC, EreMaijala commented on module/Finna/src/Finna/Form/Form.php
> +     * Check if the given form is a R2 registratioin form.
typo: registratioin

2020-09-21 11:59 UTC, samuli commented on local/config/finna/FeedbackForms.yaml.sample
>  #   or a different set of fields is configured in 'fields' list):
Erottelin R2-lomakkeiden käsittelyn R2FeedbackControlleriin, joka käsittelee R2Form:eja (joilla oma asetustiedostostosto). Tämä vaatii pienen muutoksen yläjuoksulle, mihin voin laittaa PR:n jos mennään tällä ratkaisulla:
https://github.com/NatLibFi/NDL-VuFind2/pull/1698/files#diff-ca0eb2be2fe3bb9c784e596a8538a127R30

2020-09-21 12:07 UTC, samuli commented on module/Finna/src/Finna/Controller/R2ControllerTrait.php
> +            // Logged but not authorized (wrong login method etc), close form
Käyttöliittymässä ei näytetä lomakkeen avaus-nappia mikäli jokin ehdoista ei toteudu (käyttäjä on kirjautunut Suomi.fillä, ei ole blocklistattu jne). Eli tähän tilanteeseen ei normaalisti pitäisi päätyä. Erikoistilanteita löytyy toki (lomakkeen voi avata manuaalisesti urlin kautta, blocklistaus voi aktivoitua lomakkeen avaamisen jälkeen jne) mutta ajattelin että nämä eivät vaadi tarkempaa hallintaa?

2020-09-21 17:26 UTC, EreMaijala commented on local/config/finna/FeedbackForms.yaml.sample
>  #   or a different set of fields is configured in 'fields' list):
Joo, parempi. Yläjuoksulle noin, tai sitten jopa erillinen metodi, joka luo formin.

2020-09-21 17:27 UTC, EreMaijala commented on module/Finna/src/Finna/Controller/R2ControllerTrait.php
> +            // Logged but not authorized (wrong login method etc), close form
Jos ei pitäisi tapahtua, niin ok.

2020-09-22 07:41 UTC, samuli commented on local/config/finna/FeedbackForms.yaml.sample
>  #   or a different set of fields is configured in 'fields' list):
Lisäsin yläjuoksun PR:n riippuvuuksiin.

2020-09-23 08:41 UTC, samuli commented on local/languages/finna/fi.ini
> +R2_register_form_title = "Käyttösitoumus Finnan tutkijasalin sisältöihin"
Muutettu muotoon "Finna Tutkijasali".

2020-09-23 13:25 UTC, samuli commented on local/config/finna/FeedbackForms.yaml.sample
>  #   or a different set of fields is configured in 'fields' list):
Tällaisen jouduin vielä lisäämään Finnan FeedbackControlleriin koska formin action määritellään VuFindin templatessa. 
https://github.com/NatLibFi/NDL-VuFind2/pull/1698/files#diff-a038c3a11e015d3817cc49cf30ed702cR78
Tämän voisi välttää muuttamalla yläjuoksun controlleria niin että action asetetaan jo siellä.

2020-09-28 10:45 UTC, samuli commented on local/languages/finna/fi.ini
> +R2_register_form_help_pre_html = "<p><a href="%%url%%" data-lightbox-ignore>Lue lisää Finna-tutkijasalista</a></p><h4>Finnan tutkijasali aineistotiedon käyttöehdot</h4><p><strong>Finnan tutkijasalin
Muutin "Finna Tutkijasalin aineistotiedon...".

2020-09-28 11:32 UTC, EreMaijala requested changes

2020-09-28 11:32 UTC, EreMaijala commented on module/Finna/src/Finna/Controller/R2FeedbackController.php
> +class R2FeedbackController extends FeedbackController
Lisää `implements \Laminas\Log\LoggerAwareInterface` niin ei tartte constructorissa tehdä loggeria.

2020-09-28 11:32 UTC, EreMaijala commented on module/Finna/src/Finna/Controller/R2FeedbackController.php
> +    protected $formClass = \Finna\Form\R2Form::class;
Doc comment puuttuu

2020-09-28 11:32 UTC, EreMaijala commented on module/Finna/src/Finna/Controller/R2FeedbackController.php
> +        if (!\Finna\Form\R2Form::isR2RegisterForm($formId)) {
Ota R2Form use-lausekkeella mukaan, niin helpompi lukea ja alempana saa rivityksen nätimmäksi.

2020-09-28 11:32 UTC, EreMaijala commented on module/Finna/src/Finna/Controller/R2FeedbackController.php
> +        $inLightbox
Controllereilla on inLightbox()-metodi, käytä sitä.

2020-09-28 11:32 UTC, EreMaijala commented on module/Finna/src/Finna/Controller/R2FeedbackController.php
> +        if (!($user = $this->getUser())) {
Voisiko tämä olla jo aiemmin?

2020-09-28 11:32 UTC, EreMaijala commented on module/Finna/src/Finna/Controller/R2FeedbackController.php
> +            $form = $this->serviceLocator->get(\Finna\Form\R2Form::class);
Miksei $this->formClass?

2020-09-28 11:32 UTC, EreMaijala commented on module/VuFind/src/VuFind/Controller/FeedbackController.php
> +    /**
Mergeä uusin dev, näiden pitäisi olla siellä.

2020-10-05 10:16 UTC, EreMaijala approved these changes

2020-10-05 10:17 UTC, merged