R2: Related module based on record driver data
NatLibFi/NDL-VuFind2 pull request #1699
Opened 2020-09-02 11:32 UTC by samuli

2020-09-16 12:48 UTC, EreMaijala requested changes
Sitä myös mietin, onko mitään rajaa sille, paljonko related recordseja voi olla? Eli voiko tulla ihan hullun pitkä lista?

2020-09-16 12:48 UTC, EreMaijala commented on module/Finna/src/Finna/AjaxHandler/GetRecordDriverRelatedRecords.php
> +                        } catch (\Exception $e) {
Laita joku kommentti tähän, miksei poikkeuksilla tehdä mitään

2020-09-16 12:48 UTC, EreMaijala commented on local/config/finna/config.ini.sample
> -;    RecordDriverRelated - Related records based on RecordDriver metadata
Jos ei ole tarvetta tukea ei-ajax-versiota, niin ei tätä nimeä tartte muuttaa. Sitä on käytetty vain erottelemaan kaksi versiota toisistaan.

2020-09-16 12:48 UTC, EreMaijala commented on module/Finna/src/Finna/AjaxHandler/GetRecordDriverRelatedRecords.php
> +                    } elseif ($id = ($id['wildcard'] ?? null)) {
Kaipaisi jotain kommenttia siitä, mitä tässä tapahtuu. Mistä wildcard tulee ja miksi?

2020-09-16 12:48 UTC, EreMaijala commented on module/Finna/src/Finna/AjaxHandler/GetRecordDriverRelatedRecords.php
> +                                    'datasource_str_mv:' . $driver->getDatasource()
Jos haetaan id:llä, ei filtteriä pitäisi tarvita.

2020-09-16 12:48 UTC, EreMaijala commented on module/Finna/src/Finna/AjaxHandler/GetRecordDriverRelatedRecords.php
> +        return $this->formatResponse($html);
Palauta html omassa elementissä, esim. `return formatResponse(compact('html'));`

2020-09-16 12:48 UTC, EreMaijala commented on module/Finna/src/Finna/AjaxHandler/GetRecordDriverRelatedRecords.php
> +                    'Related/RecordDriverRelated.phtml',
Tää voisi olla sitten esim. 'Related/RecordDriverRelatedRecordList.phtml',

2020-09-16 12:48 UTC, EreMaijala commented on themes/finna2/templates/Related/RecordDriverRelatedDeferred.phtml
> +  <i class="fa fa-spinner fa-spin"></i>
Laita niin, että spinneri näytetään vasta kun haku aloitetaan.

2020-09-16 12:48 UTC, EreMaijala commented on themes/finna2/js/finna-record.js
> +        spinner.addClass('hidden');
Olisiko tarpeen näyttää virheilmoitus? Se perusilmoitus "Tapahtui virhe" varmaan riittäisi.

2020-09-22 13:00 UTC, samuli commented on module/Finna/src/Finna/AjaxHandler/GetRecordDriverRelatedRecords.php
> +                        } catch (\Exception $e) {
Tämä siltä varalta mikäli metadatassa on tunniste, mitä ei saada ladattua. Ohitetaan ja näytetään muut.

2020-09-22 13:02 UTC, samuli commented on themes/finna2/js/finna-record.js
> +        spinner.addClass('hidden');
Lisätty. Tulee samalla SimilarRecordsiin.

2020-09-22 13:09 UTC, samuli commented on module/Finna/src/Finna/AjaxHandler/GetRecordDriverRelatedRecords.php
> +                                    'datasource_str_mv:' . $driver->getDatasource()
Wildcard-haussa voi muuten tulla tuloksia tietueen oman datasourcen ulkopuolelta.

2020-09-22 13:11 UTC, samuli commented
> Sitä myös mietin, onko mitään rajaa sille, paljonko related recordseja voi olla? Eli voiko tulla ihan hullun pitkä lista?

Ei tietoa, mutta tähänkin pitänee varautua. Lisäsin nyt aluksi rajoittimen:
https://github.com/NatLibFi/NDL-VuFind2/pull/1699/files#diff-20105644aabc81574bcd934c0c49c494R115

2020-09-28 12:09 UTC, EreMaijala requested changes

2020-09-28 12:09 UTC, EreMaijala commented on module/Finna/src/Finna/AjaxHandler/GetRecordDriverRelatedRecords.php
> +                                    'datasource_str_mv:' . $driver->getDatasource()
Ok.

2020-09-28 12:09 UTC, EreMaijala commented on module/Finna/src/Finna/AjaxHandler/GetRecordDriverRelatedRecords.php
> +                        if (!$results instanceof \VuFind\Search\EmptySet\Results
laita sulut !(...)

2020-09-28 12:09 UTC, EreMaijala commented on module/Finna/src/Finna/AjaxHandler/GetRecordDriverRelatedRecords.php
> +                            && count($results->getResults())
Refaktoroi niin, että if:ssä tehdään vaikka `&& ($results = $results->getResults())` niin ei tarvitse kutsua kahteen kertaan. Kun lukumäärää ei tarvita, niin toimisiko !empty()?

2020-09-28 12:09 UTC, EreMaijala commented on module/Finna/src/Finna/AjaxHandler/GetRecordDriverRelatedRecords.php
> +        $this->sessionSettings = $ss;
Tätä ei ole määritelty eikä käytetä

2020-09-28 12:09 UTC, EreMaijala commented on themes/finna2/js/finna-record.js
> +  function loadRecommendedRecords(selector, method)
Selector on vähän hämäävä parametrina, kun se ei ole kokonainen. Voisiko sen tilalla välittää suoraan container:n, jota käytetään el:n sijaan (jolla on vähän merkityksetön nimi)? container tai holder on tyypillinen parametri muissa vastaavissa.

2020-09-28 12:09 UTC, EreMaijala commented on themes/finna2/templates/Related/RecordDriverRelatedRecordList.phtml
> +        <p><?=$this->transEsc("record_driver_related:$type")?></p>
Pitäisikö olla jotain oletuskäännöksiä? Namespace ennemmin vaikka RelatedRecordType.

2020-09-29 12:01 UTC, samuli commented on themes/finna2/templates/Related/RecordDriverRelatedRecordList.phtml
> +        <p><?=$this->transEsc("record_driver_related:$type")?></p>
Jep, tekstit puuttuivat.

2020-10-05 10:28 UTC, EreMaijala requested changes

2020-10-05 10:28 UTC, EreMaijala commented on local/languages/finna/en-gb.ini
> +RelatedRecordType:part-of = ""
Näiden pitäisi olla local/languages/finna/RelatedRecordType/en-gb.ini:ssä ilman prefiksiä.

2020-10-05 10:28 UTC, EreMaijala commented on local/languages/finna/fi.ini
> +RelatedRecordType:part-of = "Sisältyy"
Näiden pitäisi olla local/languages/finna/RelatedRecordType/fi.ini:ssä ilman prefiksiä.

2020-10-05 10:28 UTC, EreMaijala commented on local/languages/finna/sv.ini
> +RelatedRecordType:part-of = ""
Näiden pitäisi olla local/languages/finna/RelatedRecordType/sv.ini:ssä ilman prefiksiä.

2020-10-05 10:28 UTC, EreMaijala commented on module/Finna/src/Finna/AjaxHandler/GetRecordDriverRelatedRecords.php
> +        Loader $loader, SearchRunner $searchRunner,
Nämä mahtuisivat yhdelle riville.

2020-10-05 10:28 UTC, EreMaijala commented on module/Finna/src/Finna/Related/RecordDriverRelated.php
> +    protected $driver;
Dok-kommentti kuntoon?

2020-10-05 10:28 UTC, EreMaijala commented on themes/finna2/js/finna-record.js
>        .done(function onGetSimilarRecordsDone(response) {
Funktion nimen voisi vaihtaa.

2020-10-26 13:31 UTC, EreMaijala approved these changes

2020-10-26 13:31 UTC, merged