R2: record loader
NatLibFi/NDL-VuFind2 pull request #1702
Opened 2020-09-03 13:22 UTC by samuli

2020-09-18 17:54 UTC, EreMaijala requested changes

2020-09-18 17:54 UTC, EreMaijala commented on module/Finna/src/Finna/Record/Loader.php
> +        if ($mode) {
Pitäisi varmaan poistaa toi R2Restricted => true, jos $mode === false. Tai poistaa parametri ja kutsua vain, jos on authenticated.

2020-09-22 11:32 UTC, samuli commented
Korjasin tarkistamaan käyttäjän REMS-rekisteröinnin kun pyydetään suojattua metadataa. Aiemmin käytettiin R2Service::isAuthenticated:ia, joka toteutuu jos käyttäjä on Suomi.fi kirjautunut. 
https://github.com/NatLibFi/NDL-VuFind2/pull/1702/files#diff-b5ba6952a127bbbc00c5388635f842d3R66

(Indeksi varmistaa käyttäjän luvituksen joten tämä ei vaikuta lopputulokseen, mutta estää turhat pyynnöt suojattuun dataan silloin kun REMS-rekisteröintiä ei ole tehty.)

2020-10-07 07:50 UTC, EreMaijala requested changes

2020-10-07 07:50 UTC, EreMaijala commented on module/Finna/src/Finna/Record/LoaderFactory.php
> +        }
Joku kommentti ainakin, miksei poikkeuksia käsitellä mitenkään.

2020-10-07 07:50 UTC, EreMaijala commented on module/Finna/src/Finna/Record/Loader.php
> +    public function loadBatch(
Luenko nyt tämän väärin, vai menevätkö parametrit R2:n alle aina, kun REMS kertoo, että käyttäjällä on pääsy? Ts. haku tavallisesta indeksistä hajoaa?

2020-10-08 12:51 UTC, samuli commented
AuthenticationListenerin yksinkertaistettu versio (https://github.com/NatLibFi/NDL-VuFind2/pull/1701/commits/6e1fd7be98cb67da3e6d32ebf7ba71066d72d215#diff-51dc833a657699b23602a769d65e60caR134) ei tarkista kontekstia, joten tätä PR:ää ei enää tarvita.

2020-10-08 12:51 UTC, closed without merging