R2: R2Ead3 record export and save
NatLibFi/NDL-VuFind2 pull request #1703
Opened 2020-09-03 13:45 UTC by samuli

- R2-tietueiden viennissä lähetetään ainoastaan linkki tietuesivulle. Toteutettu muokatuilla export-sivupohjilla. Toimintavarmempi ja mukavampi ratkaisu olisi ladata ja käyttää tietueen vapaata versiota. Tämä kuitenkin vaatii muokkausta yläjuoksun export-toimintoon ja lisäksi pitäisi hallita tilanne missä vapaata versiota ei ole (käyttää Missing-tietueajuria tms).
- Suosikin tallennuksessa tietokantaan tallennetaan ainoastaan tunniste.

2020-09-21 16:49 UTC, EreMaijala requested changes

2020-09-21 16:49 UTC, EreMaijala commented on module/Finna/src/Finna/Db/Row/Resource.php
> +
Tyhjennys pitäisi varmaan tehdä (myös?) save-metodissa. Muuten on vaarana, että jossain asetetaan attribuutteja käsin.

2020-09-23 06:10 UTC, samuli commented on module/Finna/src/Finna/Db/Row/Resource.php
> +
Totta. Siirsin tyhjennyksen save-metodiin.

2020-09-23 06:28 UTC, samuli commented
Lisäsin R2-ajuriin varmistuksen tuetuista export-formaateista:
https://github.com/NatLibFi/NDL-VuFind2/pull/1705/files#diff-fec5854021eea64872f34a98f1267246R103

2020-10-07 07:58 UTC, EreMaijala approved these changes

2020-10-07 07:59 UTC, merged