R2: MyResearch
NatLibFi/NDL-VuFind2 pull request #1706
Opened 2020-09-03 14:21 UTC by samuli

- Oman tilin Tutkijasali-sivut
- R2-tietueen muokkaus suosikkilistalla.

**Riippuvuudet**
- [ ] https://github.com/NatLibFi/NDL-VuFind2/pull/1694
- [ ] https://github.com/NatLibFi/NDL-VuFind2/pull/1704

2020-11-05 11:22 UTC, EreMaijala requested changes

2020-11-05 11:22 UTC, EreMaijala commented on local/languages/finna/fi.ini
> +R2_session_usage_purpose = "Tälle sessiolle ilmoittamasi käyttötarkoitus"
Puhutaan vielä sessiosta. Pitäisi käyttää istunto-sanaa.

2020-11-05 11:22 UTC, EreMaijala commented on module/Finna/src/Finna/AjaxHandler/EditListResource.php
>          list($source, $id) = explode('.', $listParams['id'], 2);
Tämä else-blokin sisään, ja `, $id` voisi samalla jättää pois.

2020-11-05 11:22 UTC, EreMaijala commented on module/Finna/src/Finna/Controller/MyResearchController.php
> +
Tämä pitää tehdä tarkistamalla suoraan kannasta, löytyykö R2:ia. Muuten toimii vain, jos on korkeintaan yksi sivu tietueita.

2020-11-05 11:22 UTC, EreMaijala commented on themes/finna2/templates/myresearch/r2accessrights.phtml
> +  $currPage = 'R2AccessRights';
Aika turha muuttuja?

2020-11-05 11:22 UTC, EreMaijala commented on themes/finna2/templates/myresearch/r2accessrights.phtml
> +    $hasAccess = $this->rems->hasUserAccess(true);
Nämä voisi tarjota view:lle controllerissa.

2020-11-05 11:22 UTC, EreMaijala commented on themes/finna2/templates/myresearch/r2accessrights.phtml
> +          <div><i class="fa fa-info3 fa-lg"></i></div><div><?= $this->translate('R2_change_usage_purpose_html', ['%%url%%' => $this->url('myresearch-logout')])?></div>
Sisempi div omalle rivilleen, niin on vähän selkeämpi.

2020-11-11 14:36 UTC, samuli commented on module/Finna/src/Finna/Controller/MyResearchController.php
> +
Korjattu. Lisäsin samalla tarkistuksen onko R2 enabloitu.

2020-11-17 18:37 UTC, EreMaijala requested changes

2020-11-17 18:37 UTC, EreMaijala commented on local/languages/finna/fi.ini
> +R2_termsofuse_content_html = "Finnan Tutkijasalin sisältämiä aineistotietoja (kuvailutietoa, luettelointitietoa, metatietoja) voi käyttää tietosuoja-asetuksen ja tietosuojalain asettamin rajoituksin.
Pitäisi varmaan olla "Finna Tutkijasalin"?

2020-11-17 18:37 UTC, EreMaijala commented on local/languages/finna/fi.ini
> +R2_your_accessrights = "Pääsyoikeutesi"
Onko pakko olla oma käännös vai voisiko käyttää R2_accessrights kaikkialla? Sama oikeastaan R2_menu_heading/R2_accessrights_title.

2020-11-17 18:37 UTC, EreMaijala commented on module/Finna/src/Finna/Controller/MyResearchController.php
> +                    $resources = $this->getTable('Resource')->getFavorites(
Tätä varten voisi tehdä ihan oman metodin Resource-tauluun, ettei tarvitse iteroida potentiaalisesti isoa määrää rivejä, kun onnistuisi yhdellä sql-kutsulla.

2020-11-17 18:37 UTC, EreMaijala commented on local/languages/finna/fi.ini
> +R2_accessrights_blocklisted_html = "Hyvä %%name%%,<br>sinut on asetettu käyttökieltoon Finna Tutkijasalipalvelussa. Käyttökieltoon asettamisesta voit kysyä tietoa <a href="%%url%%">Suomalaisen Kirjal
Ei kai SKS ole ainoa arkisto? Ja vaikka olisikin, ei oikein kuulosta oikealta kovakoodata geneerisen kuuloiseen käännösavaimeen.

2020-11-24 07:20 UTC, samuli commented on local/languages/finna/fi.ini
> +R2_your_accessrights = "Pääsyoikeutesi"
Yhdistin käännökset.

2020-11-24 07:21 UTC, samuli commented on module/Finna/src/Finna/Controller/MyResearchController.php
> +                    $resources = $this->getTable('Resource')->getFavorites(
Lisäsin Resource-tauluun metodin `doesListIncludeRecordsFromSource`

2020-11-24 07:32 UTC, samuli commented on local/languages/finna/fi.ini
> +R2_accessrights_blocklisted_html = "Hyvä %%name%%,<br>sinut on asetettu käyttökieltoon Finna Tutkijasalipalvelussa. Käyttökieltoon asettamisesta voit kysyä tietoa <a href="%%url%%">Suomalaisen Kirjal
Muutettiin teksti geneeriseksi. Mailto-linkin osoite noudetaan Rems.inistä R2-view helpperin factoryssä:
https://github.com/NatLibFi/NDL-VuFind2/pull/1781/files#diff-e45ecf4d7dd3b7ed825219f868cb5cb8ba5a58900a6a23b6d121301cd4f8e756R68

2020-11-30 08:51 UTC, EreMaijala requested changes

2020-11-30 08:51 UTC, EreMaijala commented on module/Finna/src/Finna/AjaxHandler/EditListResource.php
> +            list($source) = explode('.', $listParams['id'], 2);
Turha? Heti seuraava koodirivi yliajaa tämän.

2020-11-30 08:51 UTC, EreMaijala commented on themes/finna2/templates/navibar.phtml
> +              <?php $registered = $this->R2()->isRegistered(); ?>
Sisennykset pielessä

2020-11-30 10:05 UTC, samuli commented
Lisäsin linkin content-sivulle:
https://github.com/NatLibFi/NDL-VuFind2/pull/1706/files#diff-23475b9366b6253ca1b539c6c0bc6297ed38a84c1871eb3ca00b3b8acbe2bbc0R40

Sivu löytyy toistaiseksi vain Tutkijasali-näkymän custom-teemasta.

2020-11-30 12:55 UTC, EreMaijala approved these changes

2020-12-01 14:09 UTC, merged