R2: EAD3 external data record tab
NatLibFi/NDL-VuFind2 pull request #1708
Opened 2020-09-04 06:19 UTC by samuli

TODO
- [ ] Käännökset

2020-11-05 11:27 UTC, EreMaijala requested changes

2020-11-05 11:27 UTC, EreMaijala commented on local/languages/finna/fi.ini
> +external_data_tab_images = "Täysresoluutiokuvat, verkossa saatavilla"
Käännösavain ...fullres_images tms. jos on vain täysresoluutiokuville. Muuten on taas vaikeeta, jos tulee muitakin kuvia.

2020-11-05 11:27 UTC, EreMaijala commented on local/languages/finna/sv.ini
> +external_data = """
Extra-lainausmerkki

2020-11-05 11:27 UTC, EreMaijala commented on themes/finna2/templates/RecordTab/external_data_table.phtml
> +        <li><?= $infoItem ?></li>
sisennys

2020-11-05 11:27 UTC, EreMaijala commented on themes/finna2/templates/RecordTab/external_data_table.phtml
> +    <div role="row" class="tbl-row">
sisennys

2020-11-18 10:59 UTC, EreMaijala requested changes

2020-11-18 10:59 UTC, EreMaijala commented on local/languages/finna/fi.ini
> +external_data_not_digitized_html = "Tätä aineistoa ei ole digitoitu, voit tiedustella aineiston käyttöä <a data-lightbox href="%%url%%">ottamalla yhteyttä aineistontarjoajaan</a>"
Mä laittaisin pisteen pilkun tilalle. Ja loppuun.

2020-11-18 10:59 UTC, EreMaijala commented on themes/finna2/templates/RecordTab/external_data_table.phtml
> +<div role="table" class="external-data <?= $this->type ?>" aria-label="<?= $this->transEsc("external_data_tab_{$type}")?>">
attribuutteihin `$this->escapeHtmlAttr($this->translate(...))`

2020-11-18 10:59 UTC, EreMaijala commented on themes/finna2/templates/RecordTab/external_data_table.phtml
> +  <div role="row" class="tbl-col headers"><span role="columnheader"><?= $this->transEsc("external_data_tab_{$type}")?></span></div>
Pitäisikö laittaa oletuskäännökseksi pelkkä $type, jos ei käännöstä löydy?

2020-11-18 10:59 UTC, EreMaijala commented on themes/finna2/templates/RecordTab/external_data_table.phtml
> +            <li><?= $infoItem ?></li>
Escape, siivous tai kommentti, miksei tarvita.

2020-11-18 10:59 UTC, EreMaijala commented on themes/finna2/templates/RecordTab/externaldata.phtml
> +<div role="table" class="external-data physical-items" aria-label="<?= $this->transEsc('external_data_tab_physical_items')?>">
sisennys

2020-11-18 10:59 UTC, EreMaijala commented on themes/finna2/templates/RecordTab/externaldata.phtml
> +  <?php endforeach; ?>
puuttuuko `</div>`?

2020-11-18 11:52 UTC, samuli commented on themes/finna2/templates/RecordTab/externaldata.phtml
> +  <?php endforeach; ?>
Jep, lisäsin.

2020-11-18 11:57 UTC, samuli commented on themes/finna2/templates/RecordTab/external_data_table.phtml
> +  <div role="row" class="tbl-col headers"><span role="columnheader"><?= $this->transEsc("external_data_tab_{$type}")?></span></div>
Parempi niin, muutin.

2020-11-18 13:04 UTC, EreMaijala approved these changes

2020-11-18 13:20 UTC, merged