[ALLI-6523] Fix library mail address on organisation info page
NatLibFi/NDL-VuFind2 pull request #1712
Opened 2020-09-07 10:49 UTC by rajaro

Also fix email & phone tooltips in organisationInfo widget

2020-09-09 11:40 UTC, EreMaijala requested changes

2020-09-09 11:40 UTC, EreMaijala commented on themes/finna2/js/finna-organisation-info.js
> +      var mailStreet = getField(data.address.mailAddress, 'street');
Eikö näissä getField-kutsuissa voisi käyttää tuota ylempänä haettua mail-muuttujaa?

2020-09-09 11:40 UTC, EreMaijala commented on module/Finna/src/Finna/OrganisationInfo/OrganisationInfo.php
> +                    $address['mailAddress'] = [
Onko jokin erityinen syy laittaa mailAddress address:n sisään? Olisi ehkä selkeämpi omana elementtinään, kun muuten address sisältää (käynti?)osoitteen kenttiä.

2020-09-09 11:40 UTC, EreMaijala commented on themes/finna2/templates/Helpers/organisation-info-phone-widget.phtml
> +<h4><?= $this->transEsc('organisation_info_phone_numbers') ?></h4>
Nämä muutokset eivät näytä liittyvän tikettiin eikä PR:n kuvaukseen..

2020-09-09 11:40 UTC, EreMaijala commented on themes/finna2/templates/Helpers/organisation-info-email-widget.phtml
> +<h4><?= $this->transEsc('Email') ?></h4>
Nämä muutokset eivät näytä liittyvän tikettiin eikä PR:n kuvaukseen..

2020-09-09 11:40 UTC, EreMaijala commented on themes/finna2/js/finna-organisation-info-page.js
> -        address.show().find('> p').html(data.address);
Jos address on käyntiosoite, niin eikö se ole yleensä käyttäjälle olennaisempi kuin postiosoite?

2020-09-10 07:53 UTC, rajaro commented on themes/finna2/js/finna-organisation-info-page.js
> -        address.show().find('> p').html(data.address);
Joo. Nythän näkyy molemmat, käyntiosoite siinä kirjaston nimen alla ja yhteystiedoissa postiosoite -otsikon alla postiosoite. Upokkeessa näkyy käyntiosoite. Pitäisköhän yhteystiedoissa listata molemmat?

2020-09-10 08:01 UTC, EreMaijala commented on themes/finna2/js/finna-organisation-info-page.js
> -        address.show().find('> p').html(data.address);
Ai joo. Olisi ehkä hyvä listata siinä käyntiosoite ja postiosoite erikseen. Se voi jäädä huomaamatta nimen alta.

2020-09-14 06:20 UTC, pasitii commented on themes/finna2/js/finna-organisation-info-page.js
> -        address.show().find('> p').html(data.address);
Listaisin myös käyntiosoitteen ja postiosoitteen erikseen (yhteystietoihin). Käyttäjälle pitää olla selvää mistä on kysymys.

2020-09-14 06:23 UTC, EreMaijala requested changes

2020-09-14 06:23 UTC, EreMaijala commented on themes/finna2/templates/Helpers/organisation-info-contacts.phtml
> +  <div class="mail-address-contact info-element">
Näytetään käyntiosoite vielä ennen postiosoitetta.

2020-09-16 09:46 UTC, EreMaijala approved these changes

2020-09-16 10:19 UTC, pasitii approved these changes

2020-09-16 10:23 UTC, merged