[ALLI-6512] Hide SFX-links from authority search results
NatLibFi/NDL-VuFind2 pull request #1714
Opened 2020-09-07 12:24 UTC by samuli

2020-09-09 11:45 UTC, EreMaijala requested changes

2020-09-09 11:45 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/result-online-urls.phtml
> +    $openUrlActive = $openUrl->isActive() && $this->driver->supportsOpenUrl();
Tätä muutosta ei pitäisi tarvita. `$openUrl->isActive()` palauttaa false, jos driverin getOpenUrl ei anna parametreja, ja se tarkistaa jo supportsOpenUrl:n.

2020-09-14 08:09 UTC, samuli commented on themes/finna2/templates/RecordDriver/DefaultRecord/result-online-urls.phtml
> +    $openUrlActive = $openUrl->isActive() && $this->driver->supportsOpenUrl();
Totta, revertoin tämän muutoksen.

2020-09-14 08:45 UTC, merged

2020-09-14 08:46 UTC, EreMaijala reviewed
Ok.