SolrLrmi driver implementation
NatLibFi/NDL-VuFind2 pull request #1730
Opened 2020-09-25 06:56 UTC by aleksip

2020-10-07 07:36 UTC, EreMaijala requested changes
Yhtenäistä xml:n lukeminen. Nyt on vähän kirjavasti, kommenteissa lisää. Esim.

        foreach ($xml->description as $d) {
vs.
        if ($eduUses = $xml->educationalUse) {
            foreach ($eduUses as $use) {

Vaikea katsoa loppuun näin vakuumissa, kun en löytänyt mitään käyttöä suurelle osalle metodeista. Olisi hyvä ottaa samaan PR:ään myös templatet ym.

2020-10-07 07:36 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrLrmi.php
> + * @author   Jaro Ravila <jaro.ravila@helsinki.fi>
Jaro?

2020-10-07 07:36 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrLrmi.php
> +    protected $aoeUrl = 'https://aoe.fi/#/materiaali/';
URL ja siihen tuleva sisältö konfiguraatioon. Ks. ead_external_link_template. Mukaan myös käyttökieli, jos AOE tukee.

2020-10-07 07:36 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrLrmi.php
> +    public function getAccessRestrictionsType($language = 'fi')
Jos ei tarvita muita kuin nykyinen käyttöliittymän kieli, niin tehdään kuten SolrForward-ajurissa, jolloin ei tarvitse välittää toivottua kieltä:

`list($locale) = explode('-', $this->getTranslatorLocale());`

Sama kaikissa muissa metodeissa, jotka ottavat kielikoodin.

2020-10-07 07:36 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrLrmi.php
> +    public function getDescription()
Suositellaan getSummary-metodia ennemmin. Missä tämän tulosta käytetään? Tarvitaanko kaikkia kieliä, vai voisiko ottaa nykyisen käyttökielen mukaan?

2020-10-07 07:36 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrLrmi.php
> +            if ($lang === 'en') {
Yllä mainittuun viitaten, jos pitää palauttaa kaikki kielet, niin varminta olisi kopioida en-gb:hen eikä laittaa vain siihen.

2020-10-07 07:36 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrLrmi.php
> +        return $this->fields['educational_audience_str_mv'] ?? '';
`... ?? [];`

2020-10-07 07:36 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrLrmi.php
> +        foreach ($this->fields['educational_level_str_mv'] ?? [] as $key => $level) {
$key turha

2020-10-07 07:36 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrLrmi.php
> +    public function getAoeLink()
Ei sidota mitään driverissa yksittäiseen lähteeseen (ks. aiempi kommentti konfiguroitavasta linkistä).

2020-10-07 07:36 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrLrmi.php
> +    public function getYsoTopics()
Olisiko parempi `getTopics($type = 'yso')` tms.?

2020-10-07 07:36 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrLrmi.php
> +        if ($eduUses = $xml->educationalUse) {
Tätä if:iä ei kai tarvita?

2020-10-07 07:36 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrLrmi.php
> +        $xml = $this->getSimpleXML();
Pitäisi siirtyä käyttämään XmlReaderTrait:ia. Toki edellyttää myös SolrQdc:n päivittämistä, mutta se pitäisi tehdä ennemmin kuin lisätä tämän meidän oman vanhan tavan käyttöä.

2020-10-07 07:36 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrLrmi.php
> +        // If nothing has been found, then try t
Aika paha cliffhangeri. Apua!

2020-10-07 07:36 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrLrmi.php
> +    public function checkAllowedFileFormat($format)
Tartteeko olla public?

2020-10-07 07:36 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrLrmi.php
> +    public function getFileFormat($filename)
Tartteeko olla public?

2020-10-21 12:04 UTC, LuomaJuha commented on module/Finna/src/Finna/RecordDriver/SolrLrmi.php
> + * @author   Jaro Ravila <jaro.ravila@helsinki.fi>
Siitä taitaa puuttuu pari kappaletta muitakin. Pitänee lisätä kun moni henkilö on tätä tehnyt.

2020-10-23 06:59 UTC, LuomaJuha commented
Jatkan tätä toisessa pr:ssä ja suljen kun muutokset ovat tehtyjä, kommentoin tehtyjä asioita kuitenkin tähän

2020-10-23 06:59 UTC, LuomaJuha commented on module/Finna/src/Finna/RecordDriver/SolrLrmi.php
> +    public function getDescription()
Vaihdettu summary:ksi ja otetaan vain localen mukainen kieli mukaan.

2020-10-23 07:07 UTC, LuomaJuha commented on module/Finna/src/Finna/RecordDriver/SolrLrmi.php
> +        $xml = $this->getSimpleXML();
Tiketti tehty.

2020-10-23 07:09 UTC, LuomaJuha commented on module/Finna/src/Finna/RecordDriver/SolrLrmi.php
> +        // If nothing has been found, then try t
Enää ei tarvitse odottaa jatko-osaa saadakseen selville, mitä on tapahtumassa

2020-10-23 11:25 UTC, LuomaJuha commented on module/Finna/src/Finna/RecordDriver/SolrLrmi.php
> +    protected $aoeUrl = 'https://aoe.fi/#/materiaali/';
No eihä se sitä tue ku käännökset haetaan jollaki ihmekikalla js:llä.

2020-10-23 11:26 UTC, LuomaJuha commented on module/Finna/src/Finna/RecordDriver/SolrLrmi.php
> +    public function getAoeLink()
Vaihdettu muotoon getExternalLink ja asetus ;lrmi_external_link = '';

2020-10-23 11:34 UTC, LuomaJuha commented
Noni, muutokset paketissa. Jatketaan tätä Aoe-tietuesivu pr:ssä

2020-10-23 11:34 UTC, closed without merging