[ALLI-6491] Three-level menu support for content pages
NatLibFi/NDL-VuFind2 pull request #1746
Opened 2020-10-12 09:17 UTC by aleksip

2020-12-08 11:37 UTC, pasitiis approved these changes

2021-01-19 12:59 UTC, samuli commented on themes/finna2/templates/content/help-tabs.phtml
> +    'ariaLabel' => 'Ohjenavigaatio',
Käännös.

2021-01-21 14:02 UTC, aleksip commented on themes/finna2/templates/content/help-tabs.phtml
> +    'ariaLabel' => 'Ohjenavigaatio',
@pasitiis Tarvitaanko tätä?

2021-01-22 07:35 UTC, pasitiis commented on themes/finna2/templates/content/help-tabs.phtml
> +    'ariaLabel' => 'Ohjenavigaatio',
Tarvitaan jos tulee role="navigation" tai <nav> yhteyteen. aria-labeliksi riittää lyhyt muoto (Help käännösavain), koska ruudunlukija lukee Help + (navigation).

2021-01-22 07:57 UTC, aleksip commented on themes/finna2/templates/content/help-tabs.phtml
> +    'ariaLabel' => 'Ohjenavigaatio',
@pasitiis @samuli Jes, nyt on käännös.

2021-01-26 07:40 UTC, samuli approved these changes

2021-02-03 11:34 UTC, EreMaijala requested changes

2021-02-03 11:34 UTC, EreMaijala commented on themes/finna2/less/finna/content.less
> -    & ul:not(.nav-tabs.help-tabs) li {
Vanhat tyylit täytyy säilyttää, jotta ei rikota näkymissä kustomoituja sivuja.

2021-02-03 11:34 UTC, EreMaijala commented on themes/finna2/less/finna/content.less
> -ul.nav-tabs.help-tabs {
Vanhat tyylit täytyy säilyttää, jotta ei rikota näkymissä kustomoituja sivuja.

2021-02-03 11:34 UTC, EreMaijala commented on themes/finna2/templates/components/molecules/navigation/finna-nav-item/finna-nav-item.phtml
> +  $attributes = $this->htmlAttributes($attributes ?? []);
Jos täällä muokataan annettuja muuttujia, täytyy niille antaa sitten nimeämiskäytännön mukaisesti __ -alkuiset nimet. Nimessä saa toki olla muutakin eroa esim. sen käyttökohteen pohjalta, jolloin se erottuu vielä paremmin annetuista parametreista.

Tämä koskee vastaavia tapauksia kaikissa templaateissa.

2021-02-03 11:34 UTC, EreMaijala commented on themes/finna2/templates/components/organisms/navigation/finna-tabs-nav/finna-tabs-nav.phtml
> +<?php $this->headScript()->appendFile('components/organisms/navigation/finna-tabs-nav/finna-tabs-nav.js'); ?>
Kaikki js:t pitää lisätä teeman configiin. Muuten ne jäävät pois perus-bundlesta ja aiheuttavat sen, että sivuilla, jotka lisäävät omia js-tiedostoja, käytetään toista bundlea.

2021-02-03 15:39 UTC, aleksip commented on themes/finna2/less/finna/content.less
> -    & ul:not(.nav-tabs.help-tabs) li {
Nyt säilytetty.

2021-02-03 15:39 UTC, aleksip commented on themes/finna2/less/finna/content.less
> -ul.nav-tabs.help-tabs {
Nyt säilytetty.

2021-02-03 15:40 UTC, aleksip commented on themes/finna2/templates/components/molecules/navigation/finna-nav-item/finna-nav-item.phtml
> +  $attributes = $this->htmlAttributes($attributes ?? []);
Muutettu tämä ja toivottavasti kaikki muutkin vastaavat tapaukset.

2021-02-03 15:42 UTC, aleksip commented on themes/finna2/templates/components/organisms/navigation/finna-tabs-nav/finna-tabs-nav.phtml
> +<?php $this->headScript()->appendFile('components/organisms/navigation/finna-tabs-nav/finna-tabs-nav.js'); ?>
Tämä lisätty `components.config.php`:hen joka lisätään teeman configissa.

2021-02-04 11:18 UTC, EreMaijala approved these changes

2021-02-04 11:19 UTC, merged