[ALLI-6501] Add LIDO classifications to record view
NatLibFi/NDL-VuFind2 pull request #1749
Opened 2020-10-15 18:52 UTC by tmikkonen

2020-10-26 09:13 UTC, EreMaijala requested changes

2020-10-26 09:13 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +        foreach ($this->getSimpleXML()->xpath(
Tämä meni ristiin toisen PR:n kanssa. getSimpleXML-metodia ei enää ole, käytä `getXmlRecord()`.

2020-10-26 09:13 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +            $term = $node->term;
Pitäisi varmaan varmistaa, että $node->term on määritelty.

2020-10-26 09:13 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +                $results[] = (string)$term . "::($label)";
Metodin pitäisi palauttaa ennemmin array, jossa on avaimilla eri elementit, esim. `$results[] = compact('term', 'label');`. Siten ei templatessa tarvitse tehdä vippaskonsteja elementtien selvittämiseksi.

2020-10-26 09:13 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/data-otherClassification.phtml
> +<?php //Don't add START and END comments ?>
Tämähän on melkein kuin data-keywords label:lla höystettynä. Voisiko käyttää samaa templatea, mutta tarkistaa siellä, onko $data:ssa pelkkiä stringejä vai term+label -yhdistelmiä? Olisi yksi template vähemmän ylläpidettäväksi.

2020-10-28 13:31 UTC, EreMaijala requested changes

2020-10-28 13:31 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/data-keywords.phtml
> +        <?php if (array_key_exists('term', $keyword)): ?>
array_key_exists:iä ei pitäisi kutsua, jos ei ole varma, että $keyword on array. is_array on turvallisempi vaihtoehto, ja silloin voidaan jättää array_key_exists-tarkistus pois, koska arrayssa pitää olla oikea sisältö (eikä sitä voi näyttää stringinä, vaikka term-elementti puuttuisi).

2020-11-09 13:10 UTC, EreMaijala requested changes

2020-11-09 13:10 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +                $term = $node->term;
Castaa tässä stringiksi

2020-11-09 13:10 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +                $label = null;
turha rivi

2020-11-09 13:10 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +                    $results[] = compact((string)'term', (string)'label');
string-castaukset pois, ne eivät toimi compact:n kanssa.

2020-11-09 13:10 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/data-keywords.phtml
> +          <a class="backlink" title="<?=$this->escapeHtmlAttr($keyword['term'])?>" href="<?=$this->record($this->driver)->getLink('keyword', $keyword['term'])?>"><?=$this->escapeHtml($keyword['term']
Käytä array_key_exists:n sijaan `if (!empty($keyword['label']))`

2020-11-09 13:10 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +                    $results[] = (string)$term;
tästä voi sitten ottaa castauksen pois, kun se on tehty jo yllä

2020-11-09 13:10 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +            if (isset($node->term)) {
Pitäisikö olla !empty() isset:n sijaan?

2020-11-13 13:17 UTC, tmikkonen commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +                $term = $node->term;
Ok. Muuttujaa ei sitten voi käyttää seuraavalla rivilä, mutta tuskin ongelma käyttää pidempää muotoa.

2020-11-13 13:18 UTC, tmikkonen commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +                    $results[] = compact((string)'term', (string)'label');
Poistettu.

2020-11-13 13:18 UTC, tmikkonen commented on themes/finna2/templates/RecordDriver/DefaultRecord/data-keywords.phtml
> +          <a class="backlink" title="<?=$this->escapeHtmlAttr($keyword['term'])?>" href="<?=$this->record($this->driver)->getLink('keyword', $keyword['term'])?>"><?=$this->escapeHtml($keyword['term']
Vaihdettu.

2020-11-13 13:18 UTC, tmikkonen commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +            if (isset($node->term)) {
Vaihdettu.

2020-11-13 17:39 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +                $term = $node->term;
Attribuutit olisi voinut ottaa siitä ensin tai käyttää eri nimistä muuttujaa stringille. Mutta toimii se noinkin.

2020-11-13 17:40 UTC, EreMaijala approved these changes

2020-11-13 17:40 UTC, merged