Record image: simplify handling of record source.
NatLibFi/NDL-VuFind2 pull request #1750
Opened 2020-10-19 08:24 UTC by samuli

Nykyisin RecordImage-helpperin render-metodille tulee antaa tietueen source mikäli tämä on eri kuin Solr. Parametri voidaan kuitenkin selvittää suoraan helpperissä käyttämällä driverin `getSourceIdentifieriä`, mikä yksinkertaistaa sivupohjia.

Muutos vaikuttaa toimijatietueisiin. Tulevaisuudessa NKR- ja AOE -tietueisiin, joilla on oma source.

Testaus: 
- tietuekuvat näkyvät oikein 
    - Solr-haku: tietuesivu, hakutulos, modaali
    - Toimija-haku (esim. kavin tietueilla): toimijasivu /AuthorityRecord, toimijahakutulos
    - Solr-haun AuthorityRecommend-suosittelija (kavin tietueilla): 
          - config.ini > Authority > authority_links[*] = search
- korkeareso-kuvan lataaminen toimii

2020-10-19 10:08 UTC, LuomaJuha approved these changes

2020-10-21 10:04 UTC, EreMaijala requested changes
Tämä on muuten hyvä, mutta meidän on varmaan pakko jättää source-parametri poistamatta, koska muuten tulee aika paha yhteensopivuusongelma custom-templaattien kanssa. Tai sitten tehdään uusi metodi ilman sitä, mutta jätetään vanha wrapperiksi yhteensopivuuden takia.

2020-10-27 09:18 UTC, samuli commented
Palautin render-metodin ennalleen ja lisäsin renderImage:n mitä voi kutsua ilman sourcea. En muuttanut sivupohjia muuta kuin SolrAuthin osalta, muissa käytetään edelleen renderiä.

Pohdintaa: renderImagen myötä eri backendien tietueita varten ei tarvitse monistaa omaa sivupohjaa ainastaan tietuekuvaa varten. PR:n hyöty ei ole vielä kovin suuri, mutta tilanne voi muuttua jos sivupohjia yhtenäistetään.

2020-10-28 11:18 UTC, EreMaijala requested changes

2020-10-28 11:18 UTC, EreMaijala commented on module/Finna/src/Finna/View/Helper/Root/RecordImage.php
> +    public function renderImage(
Tämä mahtuu yhdelle riville

2020-10-28 11:18 UTC, EreMaijala commented on module/Finna/src/Finna/View/Helper/Root/RecordImage.php
> +        return $this->render(
render on deprekoitu, sitä ei siis pitäisi enää kutsua. Tehtävä joko niin, että render on vain wrapperi renderImage:lle, ja tiputtaa source-parametrin pois, tai sitten varsinainen toiminnallisuus erilliseen protected-metodiin.

2020-11-03 13:19 UTC, samuli commented on module/Finna/src/Finna/View/Helper/Root/RecordImage.php
> +        return $this->render(
Totta, muutin renderin kutsumaan renderImagea ilman sourcea.

2020-11-05 11:30 UTC, EreMaijala approved these changes

2020-11-05 11:30 UTC, merged