[ALLI-6286] Separate account settings into own pages
NatLibFi/NDL-VuFind2 pull request #1761
Opened 2020-10-28 13:13 UTC by LuomaJuha

2020-10-30 10:13 UTC, EreMaijala requested changes
Terminologia vaatii vielä miettimistä: monissa näkymissä ei Finna-termiä käytetä, vaan on brandattu jotenkin muuten. Finna-tili voi myös sekoittua Finna-tunnukseen. "Kirjastokortin asetukset" taas sotkeutuu Kirjastokortit-kohtaan, eikä siitä välttämättä tajua, että kyse on tiedoista kirjastossa eikä Finnaan tallennetussa kortissa.

2020-10-30 10:13 UTC, EreMaijala commented on themes/finna2/templates/myresearch/menu.phtml
> +      'profilelibrary' => [
Kirjastokortin asetukset -kohtaa ei pitäisi näyttää, jos käyttäjällä ei ole kirjastokorttia. Tämän pitäisi välittyä tietysti myös navibarin valikkoon.

2020-10-30 11:04 UTC, LuomaJuha commented on themes/finna2/templates/myresearch/menu.phtml
> +      'profilelibrary' => [
Hmm, se on totta. Tuohon sivuun on ennen tullut, että liitä kirjastokortti, mutta josko sen sitten lisäisi tuohon "finna-tili" osioon?

2020-11-03 07:31 UTC, pasitiis commented on themes/finna2/templates/myresearch/menu.phtml
> +      'profilelibrary' => [
Lisätään finna-tili osioon uuden kirjastonkortin liittäminen.

2020-11-04 17:55 UTC, pasitiis commented on themes/finna2/templates/myresearch/menu.phtml
> +      'profilelibrary' => [
Testailin tätä. Ei oikein toimi käytettäyyden kannalta. Nykyinen on jopa mielestäni selkeämpi. Hankaluus on mobiilivalikko , navbar sekä uusin termien käyttö.

2020-11-05 06:59 UTC, LuomaJuha commented
Suljetaan hämmentävänä

2020-11-05 06:59 UTC, closed without merging