[ALLI-6638] Fix OrganisationInfo page HTML-validation errors.
NatLibFi/NDL-VuFind2 pull request #1765
Opened 2020-11-03 15:48 UTC by tmikkonen

2020-11-05 11:38 UTC, EreMaijala requested changes

2020-11-05 11:38 UTC, EreMaijala commented on themes/finna2/templates/organisationinfo/home-consortium.phtml
> +  <?php $consortiumSearch = $this->url('search-results') . "?" . urlencode("&filter[]={$this->buildingFacetOperator}building:\"{$building}\"")?>
Laita parametrit url-helperille, niin se huolehtii ne oikein. Esimerkki: https://github.com/NatLibFi/NDL-VuFind2/blob/dev/themes/finna2/templates/RecordDriver/DefaultRecord/image-download.phtml#L46

2020-11-09 13:05 UTC, EreMaijala requested changes

2020-11-09 13:05 UTC, EreMaijala commented on themes/finna2/templates/organisationinfo/map-information.phtml
> +      <p><span class="office-links address"></span>
<p> ja </p> omille riveilleen allekkain.

2020-11-09 13:05 UTC, EreMaijala commented on themes/finna2/templates/organisationinfo/home-consortium.phtml
> +      ['query' => '&filter[]=' . $this->buildingFacetOperator . 'building:"'
Tarkista esimerkki uudelleen. Välitä query:ssä array tyyliin `['query' => ['parametri' => 'arvo' ]]`

2020-11-10 12:15 UTC, tmikkonen commented on themes/finna2/templates/organisationinfo/map-information.phtml
> +      <p><span class="office-links address"></span>
Rivitin uudestaan, paragraphien sulkeminen oli muutenkin omituisesti, vaikka mielestäni muutin jo aiemmin.

2020-11-10 12:15 UTC, tmikkonen commented on themes/finna2/templates/organisationinfo/home-consortium.phtml
> +      ['query' => '&filter[]=' . $this->buildingFacetOperator . 'building:"'
Muutettu.

2020-11-13 08:09 UTC, EreMaijala requested changes

2020-11-13 08:09 UTC, EreMaijala commented on themes/finna2/templates/organisationinfo/home-consortium.phtml
> +      ['query' => ['filter' => $this->buildingFacetOperator . 'building:"'
Laita vielä yhdelle riville tai sisennä sisäkkäiset arrayt nätisti. Muuten on vähän vaikea lukea.

2020-11-13 13:30 UTC, tmikkonen commented on themes/finna2/templates/organisationinfo/home-consortium.phtml
> +      ['query' => ['filter' => $this->buildingFacetOperator . 'building:"'
Siirretty yhdelle riville.

2020-11-13 17:41 UTC, EreMaijala approved these changes

2020-11-13 17:42 UTC, merged