Alli 6431
NatLibFi/NDL-VuFind2 pull request #1774
Opened 2020-11-05 17:46 UTC by tmikkonen

2020-11-13 08:07 UTC, EreMaijala requested changes
Osa muutoksista ei näytä suoraan liittyvän ALLI-6431:een, tarvitaan perusteluja ja lisää testausta.

2020-11-13 08:07 UTC, EreMaijala commented on themes/finna2/less/finna/record.less
> -  .sidebar .organisation-menu {
Tämä vaikuttaa muihinkin large-image-layout:ia käyttäviin kuin LIDO-tietueisiin (ead, forward, forwardauthority). Ei liene tarkoitus, että niissä yhtäkkiä näkyykin?

2020-11-13 08:07 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/SolrLido/core.phtml
> -    <?php if ($this->resolver('record/record-organisation-menu.phtml') && $this->driver->getSourceIdentifier() == 'Solr'): ?>
Tämä taas aiheuttaa sen, että kuvattomilta katoaa sidebar..

2020-11-13 18:04 UTC, tmikkonen commented on themes/finna2/less/finna/record.less
> -  .sidebar .organisation-menu {
Joo, ei. Muutin toteutusta.

2020-11-13 18:06 UTC, tmikkonen commented on themes/finna2/templates/RecordDriver/SolrLido/core.phtml
> -    <?php if ($this->resolver('record/record-organisation-menu.phtml') && $this->driver->getSourceIdentifier() == 'Solr'): ?>
Palautin ja lisäsin ehdon, ettei lidolla näytetä.

2020-11-18 11:42 UTC, EreMaijala requested changes

2020-11-18 11:42 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/SolrLido/core.phtml
> -    <?php if ($this->resolver('record/record-organisation-menu.phtml') && $this->driver->getSourceIdentifier() == 'Solr'): ?>
Tämä on Lidon core.phtml, eli tarkistus on turha. Ota siis koko koodinpätkä pois.

2020-11-18 11:42 UTC, EreMaijala commented on themes/finna2/less/finna/record.less
> +    display: initial;
Eikö nämä kaikki voi ottaa pois? Eli .sidebar .organisation-menu -kohdasta lähtien kun nämä vain kumoavat toisensa?

2020-11-18 13:01 UTC, tmikkonen commented on themes/finna2/less/finna/record.less
> +    display: initial;
Ao. tietue(et) tuntui menevän aina ristiin testatessa ja jommassa kummassa kenttä tuplaantui. Nyt en saanut sitä enää toistettua, joten jostain välistä testejä on ehkä unohtunut aiemmin less-käännös pois. Poistettu.

Record/museovirasto.46dd8112-29de-4f7d-a5ed-864a4444d94d
Record/museovirasto_testi.46dd8112-29de-4f7d-a5ed-864a4444d94d

2020-11-18 14:05 UTC, EreMaijala approved these changes

2020-11-18 14:06 UTC, merged