R2: REMSService updates
NatLibFi/NDL-VuFind2 pull request #1781
Opened 2020-11-12 14:31 UTC by samuli

- Approver-käyttäjä poistettu. Toimintoja käytetään joko käyttäjän omalla tunnisteella tai admin-käyttäjällä.

2020-11-30 13:56 UTC, EreMaijala requested changes

2020-11-30 13:56 UTC, EreMaijala commented on local/config/finna/permissions.ini.sample
> +; Needed for Suomi.fi single-sign-on logout notification
Kommentissa pitäisi olla mainittuna myös HAKA, ja käytössä pitäisi olla IP-rajaus. Shibbolethilla meillä on tällainen, ja sen pitäisi kai riittää tässäkin:

```
[api.ShibbolethLogoutNotification]
permission = access.api.ShibbolethLogoutNotification
require = ANY
ipRange[] = '127.0.0.1'
ipRange[] = '::1'
ipRange[] = '[finnan palvelinten-alue]'
```

2020-12-01 11:37 UTC, samuli commented on local/config/finna/permissions.ini.sample
> +; Needed for Suomi.fi single-sign-on logout notification
Revertoin tämän, voidaan lisätä yleisenä muutoksena mikäli tarpeen. 
Yllä oleva toimii kehityspalvelimella Suomi.fi:n kanssa jos muutan osion nimeksi `[access.api.ShibbolethLogoutNotification]`

2020-12-01 13:53 UTC, EreMaijala approved these changes

2020-12-01 13:53 UTC, merged