[ALLI-6655] Update content/about_finna
NatLibFi/NDL-VuFind2 pull request #1790
Opened 2020-11-16 11:41 UTC by pasitiis

2020-11-16 12:49 UTC, EreMaijala requested changes

2020-11-16 12:49 UTC, EreMaijala commented on themes/finna2/less/finna/content.less
> +    }.organisation-list-item img, .finna-screenshot {
Rivitys ja sisennys kuntoon

2020-11-16 14:28 UTC, pasitiis commented on themes/finna2/less/finna/content.less
> +    }.organisation-list-item img, .finna-screenshot {
Käännöksiin tulee vielä korjauksia.

2020-11-17 09:36 UTC, EreMaijala approved these changes

2020-11-17 09:37 UTC, merged