[ALLI-6378] Add LIDO related publications to record view
NatLibFi/NDL-VuFind2 pull request #1800
Opened 2020-11-18 19:38 UTC by tmikkonen

Tein kokonaan uuden PR:n (vanha on vielä draftina)

2020-11-19 06:50 UTC, EreMaijala requested changes

2020-11-19 06:50 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/data-relatedPublications.phtml
> +      <div class="subjectLine" property="related-publications">
class voisi olla tuo related-publications. property ei näytä ainakaan schema.org:n creativeWork:iin kuuluvalta, eli jos ei löydy sopivaa, niin pois kokonaan.

2020-11-19 09:03 UTC, tmikkonen commented on themes/finna2/templates/RecordDriver/DefaultRecord/data-relatedPublications.phtml
> +      <div class="subjectLine" property="related-publications">
Ah, property tulee sieltä. Mietin sopiiko 'publication' tähän, mutta sen kuvauksesta sai vaikutelman, että julkaisu keskittyisi/liittyisi suoraan kys. teokseen enemmän kuin sitä, että teos mainittaisiin julkaisussa, niin jätin pois.

2020-11-23 09:42 UTC, EreMaijala requested changes

2020-11-23 09:42 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/data-relatedPublications.phtml
> +      <div class=="related-publications">
== ??

2020-11-27 07:42 UTC, EreMaijala approved these changes

2020-11-27 07:42 UTC, merged