Alli 6663
NatLibFi/NDL-VuFind2 pull request #1821
Opened 2020-12-10 00:32 UTC by tmikkonen

2020-12-14 12:00 UTC, EreMaijala requested changes

2020-12-14 12:00 UTC, EreMaijala commented on local/languages/finna/en-gb.ini
> +image_creditLine = "Photocredit"
Photo Credit?

2020-12-14 12:00 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/data-imageResources.phtml
> +        <?=$this->transEsc('image_' . $key)?>: <?php if ($key == "rightsHolder"): ?><?php if (!empty($resource['link'])): ?><a href="<?=$this->escapeHtml($resource['link'])?>" target="_blank"><?php e
Jos ei ole pakko laittaa kaikkea yhdelle riville (esim. ettei tule pilkun eteen väliä), niin jaa useammalle riville.

Attribuuteissa escapeHtmlAttr. Laita mieluummin niin, että jos on esim. `$resource['link']` olemassa, niin tuotetaan koko linkki yhdellä kertaa ja sitten linkitön versio else-haarassa.

Missä tilanteessa $resource on stringi (viimeinen tapaus)? Ja miksi?

2020-12-14 12:00 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/data-imageResources.phtml
> +      <?php if (!empty($resource)): ?>
Miksi tällainen tarkistus tarvitaan? $data:n tuottajan pitäisi olla lisäämättä tyhjiä elementtejä.

2020-12-14 12:00 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +            $results['resourceID'] = isset($node->resourceID)
Tässä on jotain pielessä. Jokainen foreach-luupin kierros ylikirjoittaa edelliset tiedot.

Mun käsittääkseni silloin, kun olemassaolevalta nodelta pyytää jonkin elementin, jota ei ole olemassa, voi sen castata stringiksi ilman isset-tarkistusta, eli isset:n voisi poistaa niistä kohdista, joissa luetaan suoraan $node:n child-elementti. Silloin toki pitää tarkistaa, kun on useampi taso (esim. $node->resourceType->term)

2020-12-14 12:00 UTC, EreMaijala commented on local/languages/finna/fi.ini
> +image_resourceDateTaken = "Luomisaika"
Kuvausaika? Tai luontiaika.

2020-12-14 12:00 UTC, EreMaijala commented on local/languages/finna/fi.ini
> +image_resourceType = "Resurssin tyyppi"
Resurssille parempi termi? Pelkkä tyyppi?

2020-12-14 12:00 UTC, EreMaijala commented on local/languages/finna/en-gb.ini
> +image_resourceRelType = " Relationship"
Ylimääräinen välilyönti.

2020-12-14 12:00 UTC, EreMaijala commented on local/languages/finna/en-gb.ini
> +Image Resources = "Image information"
Miksi tämänniminen käännösavain eikä "Image Information"?

2020-12-14 12:00 UTC, EreMaijala commented on local/languages/finna/fi.ini
> +image_resourceID = "ID"
Tunniste?

2020-12-14 12:00 UTC, EreMaijala commented on local/languages/finna/sv.ini
> +image_resourceID = "ID"
Identifikationskod?

2020-12-15 08:18 UTC, tmikkonen commented on local/languages/finna/sv.ini
> +image_resourceID = "ID"
Vaihdettu.

2020-12-15 08:18 UTC, tmikkonen commented on local/languages/finna/fi.ini
> +image_resourceID = "ID"
Vaihdettu.

2020-12-15 08:18 UTC, tmikkonen commented on local/languages/finna/en-gb.ini
> +Image Resources = "Image information"
Vaihdettu.

2020-12-15 08:18 UTC, tmikkonen commented on local/languages/finna/en-gb.ini
> +image_resourceRelType = " Relationship"
Poistettu.

2020-12-15 08:19 UTC, tmikkonen commented on local/languages/finna/fi.ini
> +image_resourceType = "Resurssin tyyppi"
Vaihdettu.

2020-12-15 08:20 UTC, tmikkonen commented on local/languages/finna/fi.ini
> +image_resourceDateTaken = "Luomisaika"
Vaihdettu 'luontiaika'.

2020-12-15 08:20 UTC, tmikkonen commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +            $results['resourceID'] = isset($node->resourceID)
Looppi oli ajateltu huonosti.

2020-12-15 08:21 UTC, tmikkonen commented on themes/finna2/templates/RecordDriver/DefaultRecord/data-imageResources.phtml
> +      <?php if (!empty($resource)): ?>
Tyhjät elementit poistettu välitettävästä datasta, samoin seiten turha tarkistus.

2020-12-15 08:23 UTC, tmikkonen commented on themes/finna2/templates/RecordDriver/DefaultRecord/data-imageResources.phtml
> +        <?=$this->transEsc('image_' . $key)?>: <?php if ($key == "rightsHolder"): ?><?php if (!empty($resource['link'])): ?><a href="<?=$this->escapeHtml($resource['link'])?>" target="_blank"><?php e
Rivitys lisätty. $data muodostettu koodissa nyt toisella tavoin.

2020-12-15 08:23 UTC, tmikkonen commented on local/languages/finna/en-gb.ini
> +image_creditLine = "Photocredit"
Vaihdettu.

2020-12-16 09:41 UTC, EreMaijala requested changes
Muiden kohtien lisäksi kokonaisuudessa herää kysymys, voidaanko tietoja näyttää erillään kuvista. Ts. jos on useampi kuva, jolla eri tiedot, niin tiedot eivät yhdisty kuvaan.

2020-12-16 09:41 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +        if ($rights) {
Elementtejä voi olla useampia, eikä voi luottaa siihen, että copyright löytyy ensimmäisestä. Ei siis voi jättää käymättä niitä kaikkia läpi.

2020-12-16 09:41 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +            if (!empty($resourceSet->rightsResource->rightsType->conceptID)) {
Sama kuin yllä. Ei voi lähteä siitä, että näitä elementtejä on vain yksi ja copyright löytyy siitä.

2020-12-16 09:41 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +     * Get image resources
Nyt kun tätä mietin, niin tämän pitäisi olla ennemmin vaikka getImageInformation, koska "resources" sekoittuu helposti varsinaiseen kuvadataan.

2020-12-16 09:41 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/data-imageResources.phtml
> +    <?php foreach ($resources as $key => $resource): ?>
Mä tätä pohdin ja tulin siihen tulokseen, että tämä luuppi pitää muuttaa normaaliksi templaattirakenteeksi niin, että jokainen taulukon kohta käsitellään omanaan. Silloin käännösavaimet voi tehdä standardimuotoisiksi (esim. `image_date_taken`) riippumatta taulukon avaimista. Lisäksi templaatissa voi määritellä järjestyksen, jossa tiedot näytetään sen sijaan, että joudutaan käyttämään taulukon järjestystä. Myös se, että alkiot ovat erilaisia (array vs. string) tukee tätä.

2020-12-16 09:41 UTC, EreMaijala commented on module/Finna/src/Finna/View/Helper/Root/RecordDataFormatterFactory.php
> +                'context' => ['class' => 'image-resources']
Tässäkin sitten luokaksi esim. `image-information`.

2020-12-17 12:41 UTC, EreMaijala commented
Superceded by #1837.

2020-12-17 12:41 UTC, closed without merging