[ALLI-6615] Merged links into separate field
NatLibFi/NDL-VuFind2 pull request #1823
Opened 2020-12-10 13:01 UTC by LuomaJuha

Tweaked truncate code, there was some calls which didn't make any sense. Truncate fields now accept a class to add for more or less buttons for extra customization. Link buttons can now be forced to be on top all times.

2020-12-28 07:32 UTC, pasitiis approved these changes

2021-01-08 13:19 UTC, EreMaijala requested changes

2021-01-08 13:19 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/core.phtml
> +        <?php if (!empty($onlineURLs) || !empty($mergedData['urls'])): ?>
Jotta tämä ei olisi liian helppoa, sisältää $onlineURLs tietueen omia linkkejä, joten niitä ei pitäisi laittaa muiden organisaatioiden linkkien alle.

2021-01-08 13:20 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/core.phtml
> +        <!-- adjust this -->
Tämä kommentti lienee turha?

2021-01-18 09:19 UTC, LuomaJuha commented on themes/finna2/templates/RecordDriver/DefaultRecord/core.phtml
> +        <!-- adjust this -->
aivan turha kommentti kyllä, poistanpas sen

2021-01-18 12:25 UTC, closed without merging

2021-01-18 12:25 UTC, LuomaJuha commented
nyt meni näköjään pahemman kerran jokin pieleen