[ALLI-6646] Add rights statement icons
NatLibFi/NDL-VuFind2 pull request #1824
Opened 2020-12-10 14:18 UTC by samuli

Huom: tämä PR toteuttaa vain osan linkatun taskin speksistä (toteutusta laajennetaan myöhemmin):

- Uusi Rights statement ikoni, toteutus kuten CC-ikoneilla
- Pari muutosta rightsStatement-elementtien etsimiseen, missä huomioidaan se että elementtejä voi olla useita 

Testaukseen (testi-indeksissä):
emma_testi.CE6C3CD941A345038586F44437F30EF6#details
muusa_tampere.urn:uuid:3FE50B9C-FE31-4763-8099-429C3CFDD865?lng=sv#details

2020-12-10 14:31 UTC, aleksip approved these changes

2020-12-14 12:03 UTC, EreMaijala requested changes

2020-12-14 12:03 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +                        $conceptID = $resourceSet->rightsResource->rightsType
Väärä polku? Ja tarvitaan vasta, jos type on oikea, joten voi hakea myöhemmin.

2020-12-14 14:36 UTC, EreMaijala approved these changes

2020-12-14 14:40 UTC, merged