[ALLI-6156] Use SolrMarc::getPrimaryAuthorForSearch
NatLibFi/NDL-VuFind2 pull request #1828
Opened 2020-12-15 15:12 UTC by LuomaJuha

2020-12-16 10:09 UTC, EreMaijala reviewed
Pitäisikö kuitenkin näyttää getPrimaryAuthor:n palautta tieto?

2020-12-16 11:35 UTC, LuomaJuha commented
Totta, voisin vielä sen siihen yrittää sommitella

2020-12-16 12:18 UTC, LuomaJuha commented
Nyt näyttää taas

2021-01-08 13:21 UTC, EreMaijala approved these changes

2021-01-08 13:26 UTC, EreMaijala requested changes
Äh. Olin je mergeämässä kun tajusin, että tässä pitäisi varmaan käyttää Record-helperin getAuthorityLinkElement:iä, jotta tulee oikeanlainen hakulinkki silloin, kun auktoriteetit ovat käytössä (esim. Fikassa).

2021-01-20 06:49 UTC, LuomaJuha commented
Tässä ilmesty record helperin kanssa jotain ihmeellisyyksiä, kestää hetki selvitellä.

2021-05-12 07:02 UTC, EreMaijala approved these changes

2021-05-12 07:02 UTC, merged