EAD3: extend to support generic EAD3 format
NatLibFi/NDL-VuFind2 pull request #1829
Opened 2020-12-16 09:42 UTC by samuli

Nykyinen EAD3-ajuri tukee AHAAn formaattia. Tämä PR laajentaa toteutuksen tukemaan myös yksinkertaisempaa mallia, jota on testattu FSD:n aineistolla.

Muutoksia:
- Kielikoodien mappausta laajennetu
- accessrestrict-elementtien polku
- unitid:llä ei tarvitse olla label-attribuuttia

2021-01-08 13:49 UTC, EreMaijala requested changes

2021-01-08 13:49 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrEad3.php
> +                $id = (string)$attr->href;
Tästä voisi tehdä saman tien return:n, jos $name on kunnossa. Sitten alempana ei tarvita mitään tarkistuksia eikä $name tai $id tarvitse määritellä ylempänä.

2021-01-08 13:49 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrEad3.php
> +                    => $this->translate("Unit ID:$label", [], $label ?? 'unique')
Onko $label:lla nyt varmasti järkevä arvo, kun sitä ei erikseen aseteta tuossa identifier-casessa?

2021-01-08 13:49 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrEad3.php
> +        if (isset($record->relations->relation)) {
Näitä voisi ehkä samalla siistiä tyyliin `foreach ($record->relations->relation ?? [] as $relation) {`

2021-01-08 13:49 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrEad3.php
> +            $result[]
ennemmin 
```
$result[] = [
    'id' => '..',
    'title' => '..'
];
```

2021-01-08 13:49 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrEad3.php
> +                   'title' => $attr->title];
castaus stringiksi?

2021-01-11 09:02 UTC, samuli commented on module/Finna/src/Finna/RecordDriver/SolrEad3.php
> +                    => $this->translate("Unit ID:$label", [], $label ?? 'unique')
Tässä oli virhe. Nyt `detail` jätetään tyhjäksi ainoastaan kun tietueella on vain yksi tunniste eikä label-attribuuttia ole määritelty.

2021-01-15 08:53 UTC, samuli commented
Lisäsin mukaan rajoitusajan parsimisen accessrestrict-elementeistä: https://jira.kansalliskirjasto.fi/browse/ALLI-6759

2021-01-18 18:49 UTC, EreMaijala approved these changes

2021-01-18 18:50 UTC, merged