Paginator update
NatLibFi/NDL-VuFind2 pull request #1839
Opened 2020-12-22 11:19 UTC by LuomaJuha

2021-02-12 12:02 UTC, EreMaijala requested changes

2021-02-12 12:02 UTC, EreMaijala commented on themes/finna2/js/finna-image-paginator.js
> +var timeOut = null;
Voisiko timeOut:n jättää kuitenkin yksittäisen paginaattorin sisälle siltä varalta, että useampi latautuisi samanaikaisesti ja saattaisi sotkea toisiaan?

2021-02-17 09:11 UTC, pasitiis approved these changes
En huomannut mitään käyttöliittymässä, joka olisi mennyt rikki.

2021-02-26 09:58 UTC, EreMaijala approved these changes

2021-02-26 10:01 UTC, merged