[ALLI-6733] Fix showing of time in ead records
NatLibFi/NDL-VuFind2 pull request #1845
Opened 2020-12-29 07:26 UTC by LuomaJuha

'Date' was declared twice

2020-12-29 08:08 UTC, samuli commented
`Dates` avaimelle pitää vielä lisätä käännökset. Näin aluksi voi kopioida `Date`sta:
https://github.com/NatLibFi/NDL-VuFind2/blob/dev/local/languages/finna/fi.ini#L200

2020-12-30 12:03 UTC, samuli approved these changes

2020-12-30 13:27 UTC, samuli commented
@LuomaJuha Muistin vastaavaa bugia korjatessani että käännösavaimen voi yliajaa context:in kautta: https://github.com/NatLibFi/NDL-VuFind2/pull/1851
Samoin voi tehdä tässä.

2021-01-11 12:21 UTC, EreMaijala requested changes

2021-01-11 12:21 UTC, EreMaijala commented on module/Finna/src/Finna/View/Helper/Root/RecordDataFormatterFactory.php
> +            'Dates', 'getUnitDates', 'data-lines-with-detail.phtml'
Voisi olla parempi laittaa tähän jokin avain, jota ei ole käännöksissä, ja palauttaa oikea avain labelFunction:lla (ks. esim. https://github.com/NatLibFi/NDL-VuFind2/blob/dev/module/Finna/src/Finna/View/Helper/Root/RecordDataFormatterFactory.php#L161). Näin ei tarvitsisi tuota tuplakäännöstä.

2021-01-11 13:57 UTC, EreMaijala commented on module/Finna/src/Finna/View/Helper/Root/RecordDataFormatterFactory.php
> +            'Dates', 'getUnitDates', 'data-lines-with-detail.phtml'
Itse asiassa senhän saa meidän templaateissa vielä helpommin laittamalla contextiin title-kentän tähän tapaan: https://github.com/NatLibFi/NDL-VuFind2/blob/dev/module/Finna/src/Finna/View/Helper/Root/RecordDataFormatterFactory.php#L457

2021-01-18 09:55 UTC, LuomaJuha commented
@Ere oliskoha näin

2021-01-28 13:59 UTC, EreMaijala approved these changes

2021-01-28 13:59 UTC, merged