[ALLI-6750] Adjust caching of autocomplete
NatLibFi/NDL-VuFind2 pull request #1846
Opened 2020-12-29 07:52 UTC by LuomaJuha

Reproduce the problem: Put something to search field, wait for autocomplete to show, click somewhere else and then click back to search field.

2021-01-11 13:18 UTC, EreMaijala requested changes

2021-01-11 13:18 UTC, EreMaijala commented on themes/finna2/js/lib/autocomplete.js
>                  hide();
Tässä pitäisi cacheen laittaa tyhjä objekti, ettei yritä hakea uudelleen samaa tyhjää tulosta.

2021-01-18 09:12 UTC, LuomaJuha commented
@EreMaijala nyt on laitettu tyhjä objekti tyhjälle hakutulokselle, tuolla oli myös tuplana tehty `term.push(getPreserveFiltersMode(...` joten otin sen pois

2021-01-18 13:37 UTC, EreMaijala approved these changes

2021-01-18 13:37 UTC, merged