[ALLI-6748] Add major landmarks, reposition breadcrumb
NatLibFi/NDL-VuFind2 pull request #1847
Opened 2020-12-29 10:57 UTC by pasitiis

Muutokset koskee enimmäkseen haun etusivua ja hakutulossivua. Teen erillisen PR:n hakutulosivulle.

2020-12-29 11:39 UTC, LuomaJuha requested changes
Pari tyylihommaa löyty

2020-12-29 11:39 UTC, LuomaJuha commented on themes/finna2/templates/search/results.phtml
> +        <div role="region" aria-label="<?= $this->transEsc('Search Controls'); ?>" class="control-container text-right hidden-print">
Voidaan jättää välit `<?= ?>` jälkeen ja ennen pois

2020-12-29 11:39 UTC, LuomaJuha commented on themes/finna2/templates/Recommend/SideFacetsDeferred.phtml
> +  <h1 id="side-facet-caption"><i class="fa fa-arrow-down visible-xs pull-left"></i> <?=$this->transEsc($this->slot('side-facet-caption')->get('Narrow Search')) ?><?php if (null === $this->slot('side-
Voi laittaa `<h1>` vielä yhdellä tabilla sisemmälle, kun div omaa sen

2020-12-29 11:39 UTC, LuomaJuha commented on themes/finna2/templates/layout/layout.phtml
> +                    <?php if(count($this->layout()->breadcrumbs) > 1): ?>
Näissä voi laittaa välilyönnin `if (`

2020-12-31 18:52 UTC, tmikkonen reviewed
Käytin Firefoxin add-onia http://matatk.agrip.org.uk/landmarks/ ja landmarkit näytti selkeiltä ja loogisilta. Ainoa, mikä pisti silmään oli kuvassakin näkyvä Päänavigaation sijoittuminen Bannerin "alle" eli onko se kuinka loogista vai onko se vain pakko tehdä näin?

<img width="150" alt="Screenshot 2020-12-31 at 20 44 28" src="https://user-images.githubusercontent.com/1330453/103422320-8651dc00-4ba9-11eb-84ad-b464cf8270cb.png">

2021-01-04 08:02 UTC, pasitiis commented
Päänavigaatio on koodissa sijoitettu headeriin sisälle (banneriin). En lähtisi tätä muuttamaan, on kuitenkin yleisesti käytetty tapa.

2021-01-11 07:02 UTC, pasitiis commented
Muutin main-landmarkin sisällä olevat roolit complementaryksi. Search-osion rakennetta yksinkertaistin.

2021-01-11 13:40 UTC, EreMaijala approved these changes

2021-01-11 13:41 UTC, merged