[ALLi-6543] Show list tags in MyResearch also when not in edit-mode
NatLibFi/NDL-VuFind2 pull request #1853
Opened 2021-01-05 07:51 UTC by samuli

Nykyisin suosikkilistan tagit näytetään vain tagien muokkaus-tilassa. PR:n myötä tagit näytetään (ei-editoitavina) myös listan kuvauksen alla.

Toteutus:

- Tagi-listan sivupohja `mylist-tags.phtml` laajennettu vastaanottamaan `editable`-attribuutti, joka määritää toimiiko listan yksittäinen tagi nappina. Tagi-listan molemmat tapaukset sijoitetaan omiin kohtiinsa `mylist.phtml`ssä. 
- Tagien tallennuksessa `Editlist` palauttaa tagi-listan molemmat tapaukset uudelleen renderoituna ja finna-mylist.js päivittää nämä domiin.
- Luku-tilan tagit tyylitelty kuten listan julkisessa näkymässä.

2021-01-11 14:24 UTC, EreMaijala requested changes

2021-01-11 14:24 UTC, EreMaijala commented on themes/finna2/less/finna/mylist.less
> +        .public-list-tag();
Tällä pitäisi olla jokin muu nimi, kun se vaikuttaa muuallekin kuin julkiseen listaan.

2021-01-11 14:24 UTC, EreMaijala commented on themes/finna2/templates/myresearch/mylist-tags.phtml
> +    <li class="tag"><span class="text" data-tag="<?=$this->escapeHtmlAttr(urlencode($tag->tag))?>"><?= $this->escapeHtmlAttr($tag->tag) ?></span>
Miksi tarvitaan urlencode? Jälkimmäisen escapeHtmlAttr:n pitäisi varmaan olla escapeHtml?

2021-01-11 14:24 UTC, EreMaijala commented on themes/finna2/templates/myresearch/mylist-tags.phtml
> +        <button class="delete-tag" aria-label="<?=$this->transEsc('Delete')?>"><i class="fa fa-button fa-times"></i></button>
i-elementillä pitäisi olla `aria-hidden="true"`

2021-01-11 14:24 UTC, EreMaijala commented on themes/finna2/templates/myresearch/mylist.phtml
> +                      <input type="text" class="new-tag" name="new-tag" value="" aria-required="true" required aria-label="<?= $this->transEsc('list-tags-info')?>" placeholder="<?= $this->transEsc('l
attribuuteissa pitää olla escapeHtmlAttr(translate(..))

2021-01-11 14:24 UTC, EreMaijala commented on themes/finna2/templates/myresearch/mylist.phtml
> +              <div class="toggle" title="<?=$this->transEsc('edit-list-tags')?>">
attribuuteissa pitää olla escapeHtmlAttr(translate(..))

2021-01-11 14:24 UTC, EreMaijala commented on themes/finna2/templates/myresearch/mylist.phtml
> +                      <?php $listTags = $list->getListTags() ?>
Tämä ylemmäs, niin ei tartte hakea kahteen kertaan (rivi 61)

2021-01-11 14:24 UTC, EreMaijala commented on themes/finna2/templates/myresearch/mylist.phtml
> +                      <p><?=$this->transEsc('list-tags-count', ['%%count%%' => count($listTags)])?></p>
Onko tämä avainsanojen lukumäärä ollenkaan tarpeellinen?

2021-01-11 14:24 UTC, EreMaijala commented on themes/finna2/templates/myresearch/mylist.phtml
> +                <span><?=$this->transEsc('edit-list-tags')?> </span><i class="fa fa-tag"></i>
Tämä on tosi näkymätön varsinkin silloin, kun ei ole yhtään tagia. Eli käytännössä näkyy vain pieni kuvake. Onko tarkoitus?

2021-01-12 09:00 UTC, samuli commented on themes/finna2/templates/myresearch/mylist-tags.phtml
> +    <li class="tag"><span class="text" data-tag="<?=$this->escapeHtmlAttr(urlencode($tag->tag))?>"><?= $this->escapeHtmlAttr($tag->tag) ?></span>
`urlencode` on luultavasti unohtunut, poistin.

2021-01-12 09:09 UTC, samuli commented on themes/finna2/templates/myresearch/mylist.phtml
> +                      <p><?=$this->transEsc('list-tags-count', ['%%count%%' => count($listTags)])?></p>
Ei ole, päätettiin poistaa koko "Tallennetut avainsanat" -teksti.

2021-01-12 09:11 UTC, samuli commented on themes/finna2/templates/myresearch/mylist.phtml
> +                <span><?=$this->transEsc('edit-list-tags')?> </span><i class="fa fa-tag"></i>
Kyllä, tagitus on toistaiseksi testivaiheessa. Ominaisuutta on tarkoitus korostaa myöhemmin.

2021-01-12 10:00 UTC, EreMaijala requested changes

2021-01-12 10:00 UTC, EreMaijala commented on themes/finna2/templates/myresearch/mylist-tags.phtml
> +        <button class="delete-tag" aria-label="<?=$this->transEsc('Delete')?>"><i aria-hidden="true" class="fa fa-button fa-times"></i></button>
escapeHtmlAttr(translate(..))

2021-01-29 08:20 UTC, EreMaijala approved these changes

2021-01-29 08:20 UTC, merged