Alli 6685
NatLibFi/NDL-VuFind2 pull request #1866
Opened 2021-01-13 16:52 UTC by tmikkonen

2021-01-18 18:31 UTC, EreMaijala requested changes

2021-01-18 18:31 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +                            ->latestDate : '';
Käytä isset:n sijaan ?? -operaattoria ($role:n voisi korjata samalla).

2021-01-18 18:31 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +                            'role' => $role,
castaa stringeiksi

2021-01-18 18:31 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/data-mainFormat.phtml
> +            <?=$this->escapeHtml($actor['name'])?><?php if (!empty($actor['role'])): ?>, <?=$this->escapeHtml($actor['role'])?><?php endif; ?><?php if (!empty($actor['birth'])): ?>, <?=$this->escapeH
Välimerkitys ei toimi, jos on vain kuolinvuosi.

2021-01-19 10:55 UTC, tmikkonen commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +                            ->latestDate : '';
Ok.

2021-01-19 10:56 UTC, tmikkonen commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +                            'role' => $role,
Ok.

2021-01-19 11:06 UTC, tmikkonen commented on themes/finna2/templates/RecordDriver/DefaultRecord/data-mainFormat.phtml
> +            <?=$this->escapeHtml($actor['name'])?><?php if (!empty($actor['role'])): ?>, <?=$this->escapeHtml($actor['role'])?><?php endif; ?><?php if (!empty($actor['birth'])): ?>, <?=$this->escapeH
Joo, välimerkkejä (& kuolinvuotta) ei näytetty ollenkaan pelkän kuolinvuoden tapauksessa - oletin ehkä liian toiveikkaasti, ettei kys. tilannetta tulisi vastaan. Lisäsin pelkälle kuolinvuodelle merkinnän "k. xxxx" koska "--xxxx" ei kai ole käytössä (voin olla väärässä, mutta en löytänyt kys. merkintää käytettävän) ja esim. "? - xxxx" ei tuntunut luontevalta. Tietuetiedoissa ei ilmeisesti myöskään erotella onko henkilö kuollut vai eikö kuolinvuosi vain ole tiedossa (yleensä kai tiedossa toisin kuin syntymävuosi), joten pelkän syntymävuoden tapauksessa merkinäksi tulee aina "xxxx--"

2021-01-19 11:24 UTC, EreMaijala requested changes

2021-01-19 11:24 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +                    $appellationValue = (string)trim(
Castaus tässä on turha, koska trim:n tuloksena on aina string.

2021-01-19 11:24 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +                        $role = (string)$actor->actorInRole->roleActor->term ?? '';
Jos castauksen tekee tässä, niin null coalescing pitää olla suluissa tähän tapaan: `$role = (string)($actor->actorInRole->roleActor->term ?? '');`

2021-01-19 11:24 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/data-mainFormat.phtml
> +            <?=$this->escapeHtml($actor['name'])?><?php if (!empty($actor['role'])): ?>, <?=$this->escapeHtml($actor['role'])?><?php endif; ?><?php if (!empty($actor['birth'])): ?>, <?=$this->escapeH
'k.' ei toimi ruotsiksi tai englanniksi. Jos oletetaan, että pelkkä kuolinaika on harvinaisempi, niin ehkä voisi silti käyttää '--' etuliitteenä. 

Tässä voisi olla siistimpää tehdä ensin php-blokissa lopullinen stringi, joka sitten näytetään yhdellä escapeHtml-kutsulla. Näiden ehtojen lukeminen tässä pötkössä on muuten aika työläs.

Logiikkana voisi olla jotain tällaista pseudokoodina:
$str = name
if (!empty(role)) {
  $str .= ', ' . role;
}
if (!empty(birth)) || !empty(death)) {
  $str .= ', ';
  $sep = !empty(birth)) && !empty(death) ?? ' - ' : '--';
  $str .= (birth ?? '') . $sep . (death ?? '');
}

2021-01-19 12:37 UTC, tmikkonen commented on themes/finna2/templates/RecordDriver/DefaultRecord/data-mainFormat.phtml
> +            <?=$this->escapeHtml($actor['name'])?><?php if (!empty($actor['role'])): ?>, <?=$this->escapeHtml($actor['role'])?><?php endif; ?><?php if (!empty($actor['birth'])): ?>, <?=$this->escapeH
Mietin kieliasiaa, mutta kun ne detaljitiedot on muutenkin (usein) suomeksi UI:sta riippumatta, niin sopi joukkoon.
Voi sen "--"-etuliitteeksi toki vaihtaa, tuntui vain vieraalta merkinnältä.

2021-01-19 12:40 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/data-mainFormat.phtml
> +            <?=$this->escapeHtml($actor['name'])?><?php if (!empty($actor['role'])): ?>, <?=$this->escapeHtml($actor['role'])?><?php endif; ?><?php if (!empty($actor['birth'])): ?>, <?=$this->escapeH
Kuvailun sisällölle ei mahda mitään, mutta ei kuitenkaan tehdä siitä, mikä on meidän hallinnassa, sidottua suomeen.

2021-01-19 14:57 UTC, tmikkonen commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +                    $appellationValue = (string)trim(
Ok, poistettu.

2021-01-19 14:58 UTC, tmikkonen commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +                        $role = (string)$actor->actorInRole->roleActor->term ?? '';
Ah, sulut lisätty.

2021-01-19 15:00 UTC, tmikkonen commented on themes/finna2/templates/RecordDriver/DefaultRecord/data-mainFormat.phtml
> +            <?=$this->escapeHtml($actor['name'])?><?php if (!empty($actor['role'])): ?>, <?=$this->escapeHtml($actor['role'])?><?php endif; ?><?php if (!empty($actor['birth'])): ?>, <?=$this->escapeH
Totta joo.
PHP-blokki lisätty ja "k." korvattu.

2021-01-22 10:35 UTC, EreMaijala approved these changes

2021-01-22 10:37 UTC, merged