Add lang nav landmark, remove menu role
NatLibFi/NDL-VuFind2 pull request #1868
Opened 2021-01-14 10:31 UTC by pasitiis

Lisätään kielivalikolle landmark ja poistetaan menu-role.

Testattu Firefox + NVDA, safari + voiceover

2021-01-14 12:42 UTC, rajaro requested changes

2021-01-14 12:42 UTC, rajaro commented on themes/finna2/templates/navibar.phtml
> +                  <a class="preserve-anchor" lang="<?=$this->escapeHtmlAttr($langCode)?>" href="<?=$this->escapeHtmlAttr($this->navibar()->getLanguageUrl($langCode))?>"><?=$this->displayLanguageOptio
Linkissä voisi olla aria-label esim. "valitse kieli x"

2021-01-14 14:19 UTC, EreMaijala requested changes

2021-01-14 14:19 UTC, EreMaijala commented on themes/finna2/templates/navibar.phtml
> +      <div role="navigation" aria-label="<?=$this->escapeHtmlAttr($this->translate('select_language'))?>">
Käytä transEscAttr

2021-01-14 14:19 UTC, EreMaijala commented on themes/finna2/templates/navibar.phtml
> +                  <a class="preserve-anchor" lang="<?=$this->escapeHtmlAttr($langCode)?>" href="<?=$this->escapeHtmlAttr($this->navibar()->getLanguageUrl($langCode))?>"><?=$this->displayLanguageOptio
En kannata. Se pitäisi sitten kääntää ko. kielen mukaisesti, mikä lisää monimutkaisuutta.

2021-01-15 08:13 UTC, pasitiis commented on themes/finna2/templates/navibar.phtml
> +                  <a class="preserve-anchor" lang="<?=$this->escapeHtmlAttr($langCode)?>" href="<?=$this->escapeHtmlAttr($this->navibar()->getLanguageUrl($langCode))?>"><?=$this->displayLanguageOptio
Selkeyden kannalta Jaron ehdotus on hyvä, mutta monimutkaistaisi toteutusta melkoisesti.

2021-01-15 08:23 UTC, rajaro approved these changes

2021-01-15 08:45 UTC, EreMaijala approved these changes

2021-01-15 08:45 UTC, merged