[ALLI-6615] Separate merged links
NatLibFi/NDL-VuFind2 pull request #1877
Opened 2021-01-19 07:47 UTC by LuomaJuha

New pull request as the old one had some issues

2021-01-20 09:43 UTC, EreMaijala requested changes

2021-01-20 09:43 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/core.phtml
> +            <div class="fulltextField"><a class="fulltext" href="<?=$this->escapeHtmlAttr($this->proxyUrl($url['url'])) ?>" target="_blank" aria-label="<?=$this->escapeHtmlAttr($this->translate('exte
Käytä escapeHtmlAttr+translate:n sijaan transEscAttr (kuten alkuperäisessä äskettäin tulleen uutuuden myötä)

2021-01-20 09:43 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/core.phtml
> +              <div class="fulltextField"><a class="fulltext" href="<?=$this->escapeHtmlAttr($this->proxyUrl($url['url'])) ?>" target="_blank" aria-label="<?=$this->escapeHtmlAttr($this->translate('ex
Käytä escapeHtmlAttr+translate:n sijaan transEscAttr (kuten alkuperäisessä äskettäin tulleen uutuuden myötä)

2021-01-20 09:43 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/core.phtml
> +          <?php foreach ($filteredOnlineURLs as $url): ?>
Lisää $filteredOnlineURLs:n sisältämät url:t $renderedUrls:iin. Ei tartte näyttää mahdollisia tuplia sitten muista organisaatioista.

2021-01-20 10:37 UTC, LuomaJuha commented on themes/finna2/templates/RecordDriver/DefaultRecord/core.phtml
> +          <?php foreach ($filteredOnlineURLs as $url): ?>
nyt o lisätty

2021-01-28 14:06 UTC, EreMaijala approved these changes

2021-01-28 14:08 UTC, merged