[ALLI-6280] LIDO: translate record fields
NatLibFi/NDL-VuFind2 pull request #1884
Opened 2021-01-21 13:26 UTC by samuli

LIDO-tietuekenttien näyttäminen käyttäjän kielivalinnan mukaan:

- Nimeke käsitellään kuten Marcissa: `getUniformTitles` palauttaa kieliversiot ja ne tulevat sen myötä näkyviin hakutulokseen ja tietuesivulle. 
- Tietuesivulla näytetään seuraavista kentistä kieliversio: asiasana, luokitus, kuvaus.
- Image-poparissa näytetään kieliversio nimekkeestä ja kuvauksesta.
- Jos käyttäjän kielivalinnalla ei löydy kieliversiota, näytetään kaikki vaihtoehdot.

2021-02-08 07:25 UTC, EreMaijala requested changes
Uniform titles (yhtenäistetyt nimekkeet) on vähän eri asia kuin nimekkeet. Pitää varmaan tehdä jotain vastaavaa uutta, kuten getOtherLanguageTitles.

2021-02-10 08:11 UTC, EreMaijala requested changes

2021-02-10 08:11 UTC, EreMaijala commented on module/Finna/src/Finna/View/Helper/Root/RecordDataFormatterFactory.php
> +        $setTemplateLine(
Jos tätä ei näytetä millekään aineistotyypille, tartteeko asettaakaan?

2021-02-10 10:45 UTC, samuli commented on module/Finna/src/Finna/View/Helper/Root/RecordDataFormatterFactory.php
> +        $setTemplateLine(
Ei tarvita, poistin.

2021-02-10 12:27 UTC, EreMaijala approved these changes

2021-02-10 12:27 UTC, merged