EAD3: record images and ExternalData tab
NatLibFi/NDL-VuFind2 pull request #1887
Opened 2021-01-28 09:42 UTC by samuli

- Korjaus: `localtype` attribuuttia yritettiin mapata kahteen keraan:
https://github.com/NatLibFi/NDL-VuFind2/compare/dev...samuli:ead3-fix-record-image-localtype?expand=1#diff-a7a8a3396cedb3aa3baac7bb8d1f7eb9beab156058fb34d1c8f5eebd1540ea5bL535 
- Muutos: Aineistot-välilehdellä näytetään "ei digitoitu" teksti vain jos tietueesta ei ole saatavilla kuvia missään koossa. Aiemmin pelkkä näyttökuva ei riittänyt. Välilehti kätketään jos aineistoja ei ole ja ei ole tarvetta näyttää "ei digitoitu" tekstiä.

2021-03-17 12:39 UTC, EreMaijala requested changes

2021-03-17 12:39 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrEad3.php
> +        $OCRImages = $this->getOCRImages();
Muuttujat alkavat pienellä, vaikka olisi lyhennekin. Eli `$ocrImages`.

2021-03-17 12:39 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrEad3.php
> +        $result = ['items' => []];
items-elementtiä ei tartte lisätä, niin ei sitten tartte poistaakaan tyhjää

2021-03-17 12:57 UTC, samuli commented on module/Finna/src/Finna/RecordDriver/SolrEad3.php
> +        $result = ['items' => []];
Totta, en muistanut että taulukon kenttiä voi asettaa kerralla useammalle tasolle...

2021-03-18 06:35 UTC, EreMaijala approved these changes

2021-03-18 06:36 UTC, merged