Some javascript cleaning
NatLibFi/NDL-VuFind2 pull request #1937
Opened 2021-03-02 15:19 UTC by LuomaJuha

Reduced find calls, more things to variables. Try to clean clicks to on('clicks' etc. Still much to go

2021-03-03 11:01 UTC, EreMaijala commented on themes/finna2/js/finna-daterange-vis.js
> +    $(window).on('resize', function onResizeScreen() {
Tuo resize.screen.finna-eventti on tehty debouncaamaan resize-eventin, jotta ei kutsuta hillittömän usein. Poistaminen ei ole hyvä juttu.

2021-03-03 11:05 UTC, EreMaijala commented on themes/finna2/js/finna-layout.js
>        $('.myresearch-row .checkboxFilter .checkbox').each(function setupCheckbox() {
Tähän ei muuten varmaan tartte luuppia, kun voisi suoraan hakea `.checkbox.checked`:iä ja katsoa, löytyikö jotain, eikö?

2021-03-03 11:06 UTC, EreMaijala commented on themes/finna2/js/finna-layout.js
> +    win.on('resize', function checkFiltersEnabled() {
tässäkin voisi käyttää finnan debouncettua eventtiä.

2021-03-04 08:02 UTC, LuomaJuha commented on themes/finna2/js/finna-daterange-vis.js
> +    $(window).on('resize', function onResizeScreen() {
Selvä homma, katselinki et mitäs siinä oikein haetaan takaa.

2021-03-04 08:38 UTC, LuomaJuha commented on themes/finna2/js/finna-layout.js
>        $('.myresearch-row .checkboxFilter .checkbox').each(function setupCheckbox() {
Hyvä huomio

2021-03-04 11:39 UTC, LuomaJuha commented on themes/finna2/js/finna-daterange-vis.js
> +    $(window).on('resize', function onResizeScreen() {
Noh, tein siihe ny kokonaan oman triggerin, ku tuo vanha ei tainnu alunalkaenkaan toimia tuolla tavalla

2021-03-04 11:46 UTC, LuomaJuha commented
Eiköhän tässä olis nyt alkuun vähän viilauksia, joitaki funktioita löyty mille ei näkyny enää käyttötarkotusta

2021-03-05 11:03 UTC, LuomaJuha commented
Itseasiassa, koitin vielä muokata joitakin klikkauskutsuja niin, että elementtejä ei haeta vaan klikattaessa elementtiä katsotaan voiko tapahtua .('click', 'selector', function

tarvii vähän tutkailua

2021-03-11 10:09 UTC, EreMaijala requested changes
Olisi kiva, jos tästä voisi poimia ihan erikseen systemaattiset yksinkertaiset muutokset (tyyliin `.click() => .on(click...)`) ja sitten erikseen refaktoroidut osat.

2021-03-11 10:09 UTC, EreMaijala commented on themes/finna2/js/finna-common.js
> +        searchInput.val(searchInput.val() + letter).focus();
Toimiiko tämä aina? Vanha rakenne oli sitä varten, että kursori menisi aina loppuun.

2021-03-11 10:09 UTC, EreMaijala commented on themes/finna2/js/finna-layout.js
> +        $(window).trigger('customresize.finna', [data]);
Ei vaihdeta eventin nimeä, ettei mahdolliset muokatut skriptit hajoa.

2021-03-11 10:09 UTC, EreMaijala commented on themes/finna2/js/finna-layout.js
>        var modal = $('#modal');
Minkähän takia me muuten kikkaillaan perus-modalin kanssa tässä? Voisi varmaan saman tien lisätä oman modalin location servicelle, niin ei tarvitsisi säätää luokkien kanssa.

2021-03-11 10:09 UTC, EreMaijala commented on themes/finna2/js/finna-layout.js
> +  function truncateFields(_holder) {
Kaipaisi vähän selvennystä, mitä eroa on initTruncate:lla  ja truncateFields:llä.

2021-03-11 10:09 UTC, EreMaijala commented on themes/finna2/js/finna-layout.js
> +      $('i', this).toggleClass('fa-arrow-up');
Mun mielestä pitäisi togglettaa molempien nuolien luokat. Toimiminen muuten liian pienestä kiinni.

2021-03-11 10:09 UTC, EreMaijala commented on themes/finna2/js/finna-layout.js
> +    $(document).on('click', '.cookie-consent-dismiss', function dismiss() {
Miksi bindata, jos ei cookie-baria näytetä?

2021-03-11 10:09 UTC, EreMaijala commented on themes/finna2/js/finna-map-facet.js
>    function initMapFacet(_options){
Aaltosulun eteen voisi laittaa samalla välilyönnin kaikkiin kohtiin.

2021-03-11 10:09 UTC, EreMaijala commented on themes/finna2/js/finna-mylist.js
> +      $(this).attr('open', $(this).attr('open') === 'open');
Menee aina falseksi, eikö?

2021-03-11 10:09 UTC, EreMaijala commented on themes/finna2/js/finna-organisation-info-page-consortium.js
> +        console.log('2ewsres');
pois

2021-03-11 11:48 UTC, LuomaJuha commented
Lisää siivousta on tulossa

2021-03-11 11:55 UTC, LuomaJuha commented
Teen palasina tätä js:n siivousta. suljen tämän

2021-03-11 11:55 UTC, closed without merging