[ALLI-6832] Add more right statements
NatLibFi/NDL-VuFind2 pull request #1942
Opened 2021-03-09 12:06 UTC by samuli

2021-03-11 10:11 UTC, EreMaijala requested changes

2021-03-11 10:11 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/image-rights.phtml
> +            <?=$this->partial('Helpers/copyright-icons.phtml', ['copyright' => $copyright]);?><?php if ($hasLink): ?><a target="_blank" aria-label="<?=$this->transEscAttr('external_online_link')?>" h
Tän voisi muuttaa niin, että katenoidaan stringi erikseen tai kootaan osaset taulukkoon, joka sitten implodetaan tohon. Alkaa olla vähän hurja muuten.

2021-03-11 14:19 UTC, samuli commented on themes/finna2/templates/RecordDriver/DefaultRecord/image-rights.phtml
> +            <?=$this->partial('Helpers/copyright-icons.phtml', ['copyright' => $copyright]);?><?php if ($hasLink): ?><a target="_blank" aria-label="<?=$this->transEscAttr('external_online_link')?>" h
Nyt on toivottavasti hieman selkeämpi. Jätin translaten jälkeisen isset-tarkistuksen pois. Laitetaan takaisin jos tälle on oikea tarve:
https://github.com/NatLibFi/NDL-VuFind2/pull/1942/files#diff-9458723851c67ae79cec72cc1d678f3bf93dd9d5ca8b5cd70f81f1750c7eee0dL13

2021-03-15 10:32 UTC, EreMaijala approved these changes

2021-03-15 10:32 UTC, merged