Javascript cleaning events
NatLibFi/NDL-VuFind2 pull request #1947
Opened 2021-03-11 11:56 UTC by LuomaJuha

Tässä paneudutaan enemmän eventtien vaihtamiseksi on click, muotoon

2021-03-11 12:03 UTC, LuomaJuha commented on themes/finna2/js/finna-common.js
> +        searchInput.val(searchInput.val() + letter).focus();
Jatkoa edellisestä pr:stä. Tämä ainakin itsellä asettaa valitsimen loppuun

2021-03-15 13:17 UTC, EreMaijala requested changes

2021-03-15 13:17 UTC, EreMaijala commented on themes/finna2/js/finna-common.js
> +    $(window).on('keypress', function onSearchInputKeypress(e) {
Pitäisiköhän vaihtaa toiseen eventtiin? Piti tutkia noita parametreja, niin kävi ilmi, että keypress on deprekoitu.

2021-03-15 13:17 UTC, EreMaijala commented on themes/finna2/js/finna-common.js
> +      if (ev && (!ev.is('input, textarea, select, div.CodeMirror-code'))
Tämä tarkistus ei ole sama kuin aiempi, jossa tarkistettiin `e`. `ev` lienee aina truey, eli pitäisi ennemmin tarkistaa ev.length, vai?

2021-03-15 13:17 UTC, EreMaijala commented on themes/finna2/js/finna-common.js
> +        searchInput.val(searchInput.val() + letter).focus();
Joo, toimii se mullakin.

2021-03-15 13:17 UTC, EreMaijala commented on themes/finna2/js/finna-content-feed.js
> +          if (data.item && data.item.html) {
Tämä ei ole sama asia kuin aiemmassa testissä. Nyt jos vaikka data.item.html on tyhjä stringi, käsitellään se virheenä tuolla else-haarassa. Jos se on tarkoituskin, niin ok, mutta onko?

2021-03-15 13:17 UTC, EreMaijala commented on themes/finna2/js/finna-common.js
> +    $(window).on('keypress', function onSearchInputKeypress(e) {
Tai sitten tarkistaa Pasilta, pitäisikö tämä nyt ottaa pois. Jossain vaiheessa oli puhetta, että häiritsee esteettömyyttä.

2021-03-17 08:44 UTC, LuomaJuha commented on themes/finna2/js/finna-common.js
> +      if (ev && (!ev.is('input, textarea, select, div.CodeMirror-code'))
jes

2021-03-17 09:00 UTC, pasitiis commented on themes/finna2/js/finna-common.js
> +    $(window).on('keypress', function onSearchInputKeypress(e) {
https://jira.kansalliskirjasto.fi/browse/ALLI-6712 . Poisto korjaisi ongelman.

2021-03-17 09:59 UTC, LuomaJuha commented on themes/finna2/js/finna-common.js
> +    $(window).on('keypress', function onSearchInputKeypress(e) {
Pasi sano että voi ottaa pois kokonaan joten deletoin tuon

2021-03-17 09:59 UTC, LuomaJuha commented on themes/finna2/js/finna-common.js
> +      if (ev && (!ev.is('input, textarea, select, div.CodeMirror-code'))
jooh, totta

2021-03-22 09:05 UTC, merged