[ALLI-6867] Adjust LIDO summaries
NatLibFi/NDL-VuFind2 pull request #1961
Opened 2021-03-23 10:47 UTC by LuomaJuha

test: Record/museovirasto.C8DC08AB3E5E1F5CEC88C479E68B8C10?imgid=1#details

2021-03-23 10:58 UTC, EreMaijala requested changes

2021-03-23 10:58 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/SolrLido/core.phtml
> +  $summary = !empty($summaries);
Tarvitaanko tätä, vai voisiko vain tarkistaa `if ($summaries)`? Jos tarvitaan, niin $hasSummary olisi paremp.

2021-03-23 11:16 UTC, LuomaJuha commented on themes/finna2/templates/RecordDriver/SolrLido/core.phtml
> +  $summary = !empty($summaries);
tuunataan

2021-03-24 11:28 UTC, LuomaJuha commented on themes/finna2/templates/RecordDriver/SolrLido/core.phtml
> +  $summary = !empty($summaries);
ny o tuunattu

2021-03-26 07:57 UTC, EreMaijala approved these changes

2021-03-26 07:58 UTC, merged