[ALLI-6781] Public condensed list note adjustments
NatLibFi/NDL-VuFind2 pull request #1962
Opened 2021-03-24 08:09 UTC by LuomaJuha

2021-03-29 07:13 UTC, EreMaijala requested changes
Toimii, mutta mua vähän häiritsee Muistiinpano-nappulan kuvake varsinkin nyt, kun se näkyy tiivistetyssä listassakin. Onko meillä mitään muuta nappulaa, jossa olisi kuvake samalla tavalla? Esim. Lataa kuva -nappulassa ei ole, ja se on selkeämmän näköinen (siinä on toki vasemmalla puolella se latauskuvake, mutta se on enempi bulletin oloinen toimintolistassa). Lisäksi marginaalit on erilaiset.

Vielä yhtenäisyydestä, kuva-popupissa muistiinpanot ovat otsikolla "Kuvaus". Jos nyt käytetään Muistiinpano-merkintää kaikkialla, niin se pitäisi muuttaa.

2021-03-29 07:13 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/SolrEad/result-condensed.phtml
>      <?php $trees = $this->driver->tryMethod('getHierarchyTrees'); if (!empty($trees)): ?>
Tämän olisi pitänyt olla enemmän sisennettynä, kaikki muu oli kunnossa...

2021-03-29 10:15 UTC, LuomaJuha commented on themes/finna2/templates/RecordDriver/SolrEad/result-condensed.phtml
>      <?php $trees = $this->driver->tryMethod('getHierarchyTrees'); if (!empty($trees)): ?>
Mitähä mää oon tässä kahtonu.

2021-04-09 07:42 UTC, EreMaijala requested changes
Nyt toimii ja on muuten ok, mutta huomasin testatessani vähän hämmentävän jutun: Jos klikkaa kuvaa suosikkilistalla, näytetään muistiinpano sivupalkissa, mutta jos klikkaa julkisen listan puolella, niin ei näytetäkään. Vaikka se siis näkyy gridissä ihan hienosti. Pitäisi varmaan näkyä julkisen listan popupissakin?

2021-04-12 07:48 UTC, LuomaJuha commented
Hmm, katotaas

2021-04-12 08:25 UTC, LuomaJuha commented
Jah, tuo listan id näköjään asetettiin muuttujaan ja popupissa katottiin onko se elementissä, pitäis olla fiksattu.

2021-04-12 12:22 UTC, EreMaijala commented on themes/finna2/js/finna-image-paginator.js
> +    // eslint-disable-next-line no-undef
Tämän sijaan voisi lisätä listId:n ekan rivin global-määrittelyyn.

2021-04-13 12:23 UTC, EreMaijala approved these changes

2021-04-13 12:27 UTC, merged