[ALLI-6784] EAD3: include archive file hierarchy
NatLibFi/NDL-VuFind2 pull request #1966
Opened 2021-04-06 14:05 UTC by samuli

Lisää "Kuuluu arkistoyksikköön" kaikkialle missä käytetään "Kuuluu arkistoon" / " Kuuluu sarjaan".

2021-04-09 07:50 UTC, EreMaijala requested changes
Mahdollisten tulevien tarpeiden kannalta voisi olla parempi, jos `$archiveFiles` -parametrin sijaan metodit saisivat `array $levels = ['series', 'subseries']` -parametrin. Silloin kutsuja voisi pyytää tarvittaessa muitakin leveleitä.

Uusiin metodeihin mukaan type hintit parametreihin ja paluuarvoihin.

2021-04-09 09:58 UTC, samuli commented
Otin takaisin käyttöön aiemman version $levels-attribuuttien kera ja siirsin levelit constanteiksi. Lienee tosiaan kestävämpi ratkaisu näin.

2021-04-09 09:59 UTC, EreMaijala requested changes

2021-04-09 09:59 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrEad.php
> +    const SERIES_LEVELS = ['series', 'subseries'];
Laita `public const`

2021-04-13 11:53 UTC, EreMaijala approved these changes
Pidemmän päälle voisi olla vielä siistimpi, jos hierarkiadatan saisi niin, että level, id ja title ovat yhdessä, mutta tämä kelpaa nyt.

2021-04-13 11:53 UTC, merged