[ALLI-6699] Accessability changes to Record View holdings information
NatLibFi/NDL-VuFind2 pull request #1968
Opened 2021-04-07 17:07 UTC by tmikkonen

2021-04-13 05:58 UTC, pasitiis approved these changes

2021-04-13 12:19 UTC, EreMaijala requested changes

2021-04-13 12:19 UTC, EreMaijala commented on themes/finna2/less/finna/holdings.less
> +//        transform: translateY(-2.12em);
Ei jätetä kommentoituja palasia.

2021-04-13 12:19 UTC, EreMaijala commented on themes/finna2/less/finna/holdings.less
> +//            transform: translateY(-1.65em);
Tämä myös pois.

2021-04-13 12:19 UTC, EreMaijala commented on themes/finna2/templates/RecordTab/holdingsils.phtml
> +      <div class="clearfix" aria-hidden="true"></div>
Onko tällä oikeasti merkitystä? Pitäisikö vastaava olla muuallakin?

2021-04-13 12:19 UTC, EreMaijala commented on themes/finna2/templates/RecordTab/holdingsils.phtml
> +<div class="table record-holdings-table" role="table" aria-label="<?=$this->escapeHtmlAttr($this->translate('Holdings'));?>" tabindex="0">
Käytä transEscAttr

2021-04-13 12:19 UTC, EreMaijala commented on themes/finna2/less/finna/holdings.less
> +            flex: .8;
Löytyisikö parempaa tapaa jakaa leveydet? Fraktionaaliset flex:t ovat vähän kamalia.

2021-04-13 12:24 UTC, tmikkonen commented on themes/finna2/less/finna/holdings.less
> +//        transform: translateY(-2.12em);
Mun moka, kun kommentit oli jo kertaalleen pois, mutta otin liikaa muutoksia takaisin.

2021-04-13 12:29 UTC, tmikkonen commented on themes/finna2/templates/RecordTab/holdingsils.phtml
> +      <div class="clearfix" aria-hidden="true"></div>
NVDA luki "blank" (vähän kuin aiemmin ylänavissa liikkuessa) aina tiettyyn kohtaan ja tuolla sen sai pois. Saattaa johtua browse-moodista, että silloin noita tyhjiä luetaan, mutta tarkistan nyt vielä mitä ilman hiddeniä tapahtuu.

2021-04-13 12:30 UTC, tmikkonen commented on themes/finna2/templates/RecordTab/holdingsils.phtml
> +<div class="table record-holdings-table" role="table" aria-label="<?=$this->escapeHtmlAttr($this->translate('Holdings'));?>" tabindex="0">
Ok.

2021-04-13 12:35 UTC, tmikkonen commented on themes/finna2/less/finna/holdings.less
> +            flex: .8;
Muulla eivät tuntuneet asettuvan oikein millään. Katsotaan nyt vielä, mutta en ihmeitä lupaa.

2021-04-13 14:22 UTC, tmikkonen commented on themes/finna2/less/finna/holdings.less
> +//            transform: translateY(-1.65em);
ok

2021-04-14 10:27 UTC, EreMaijala approved these changes

2021-04-14 10:28 UTC, merged