[ALLI-6878] EAD3: recordfield relations
NatLibFi/NDL-VuFind2 pull request #1986
Opened 2021-04-23 12:17 UTC by samuli

Näyttää AHAAn relations-elementit linkkilistana tietuekenttien joukossa. Ei vaikuta RecordDriverRelated-suosittelijaan, koska nämä kaksi käsittelevät eri relaatioita (valinta tehdään encodinganalog-attribuutin mukaan).

RecordDriver-helpperin muutoksista:
- identifier-laajennus voidaan yrittää saada mukaan yläjuoksulle.
- filter-optio estää eri tietolähteiden tunnisteiden törmäykset. Tälle ei ehkä ole tarvetta yläjuoksulla, mutta meidän olisi hyvä varautua?

Related Materials -käännökset: https://github.com/NatLibFi/NDL-VuFind2/pull/1981

2021-04-30 12:56 UTC, EreMaijala requested changes

2021-04-30 12:56 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrEad3.php
> +     * @return null|array
Onko mitään syytä olla palauttamatta aina arrayta, vaikka sitten tyhjää?

2021-04-30 12:56 UTC, EreMaijala commented on module/Finna/src/Finna/View/Helper/Root/RecordDataFormatter.php
> +            'Publisher or Distributor Number', 'Record Links', 'Related Materials',
Aakkosjärjestykseen

2021-04-30 12:56 UTC, EreMaijala commented on module/Finna/src/Finna/View/Helper/Root/RecordLink.php
> +        if ('identifier' === $link['type']) {
$escape-parametrin käsittely kuntoon. Kun se on päällä, pitäisi palauttaa escapeHtml:n kautta ajettu tulos, kuten parent::related tekee.

2021-04-30 12:56 UTC, EreMaijala commented on module/Finna/src/Finna/View/Helper/Root/RecordLink.php
>              ->getCurrentHiddenFilterParams($driver->getSourceIdentifier());
getCurrentHiddenFilterParams palauttaa oletuksena `&amp;` erottimena, pitää fiksata jotenkin niin, että saadaan sieltä pelkkää `&` -merkkiä. Muuten menee vaikeaksi tällä puolella hoitaa url kuntoon, koska yllämainittu htmlEscape sotkisi lisää.

2021-05-03 09:08 UTC, samuli commented on module/Finna/src/Finna/RecordDriver/SolrEad3.php
> +     * @return null|array
Ei, nyt palauttaa tyhjän arrayn.

2021-05-03 09:16 UTC, samuli commented on module/Finna/src/Finna/View/Helper/Root/RecordLink.php
>              ->getCurrentHiddenFilterParams($driver->getSourceIdentifier());
parent::related pyydetään ei-escapettuna ja escape-helper ajetaan yhden kerran aivan lopussa.

Upstreamiin voidaan korjata myöhemmin:
- Siirretään getCurrentHiddenFilterParamsin kutsu VuFindin RecordLinkiin 
- getCurrentHiddenFilterParams käyttämään & / &amp -erotinta myös parametrien välissä

2021-05-03 09:18 UTC, samuli commented on module/Finna/src/Finna/View/Helper/Root/RecordLink.php
> +        if ('identifier' === $link['type']) {
parent::related pyydetään ei-escapettuna ja escape-helper ajetaan yhden kerran aivan lopussa.

2021-05-03 10:25 UTC, EreMaijala approved these changes

2021-05-03 13:56 UTC, EreMaijala requested changes
Olin jo laittamassa sisään kun tajusin, että meillä on ainakin MARC-tietueissa getAllRecordLinks, joka on hyvin lähellä samaa. Voisiko sitä käyttää tässä ja sen palauttamaa rakennetta laajentaa tarpeen mukaan? Ei tunnu hyvältä tehdä toista hyvin samankaltaista metodia.

2021-05-04 07:48 UTC, samuli commented
@EreMaijala Joo, tämä on hieman hankala juttu.... Käytin ensin getAllRecordLinksiä kunnes huomasin että sen käyttämä template ei toimi ryhmitetyjen tietuekenttien kanssa, joita käytetään EAD3:ssa. Tämä sen vuoksi että data-allRecordLinks.phtml renderoi taulukon sarakkeita, mikä taas ei toimi jos template rendataan ryhmiteltynä, joka käyttää myös taulukoita (https://github.com/NatLibFi/NDL-VuFind2/blob/dev/themes/finna2/templates/RecordDriver/DefaultRecord/core-field-group-fields.phtml). Ongelma on siis laajempi ja ilmenee niin että kaikkia kenttiä ei voi rendata ryhmiteltynä. Nopeasti katsoen näitä ei onneksi ole paljon. Ryhmittelyn toteutusta pitää miettiä uudelleen tai vaihtoehtoisesti voi ehkä olla helpompi konvertoida ongelmalliset templatet yhteensopiviksi ryhmittelyn kanssa.

Mikäli halutaan hyödyntää EAD3:ssa getAllRecordLinksiä ilman suurempia muutoksia tulee mieleen nämä vaihtoehdot:
- Järkeillään data-allRecordLinks-templatessa milloin rendataan taulukkorakenne (esim. vain jos title-attribuutti on määritelty).
- tehdään Record Links -kentästä uusi versio RecordDataFormatterFactoryssä, joka käyttää eri templatea. Käytetään uutta kenttää vain EAD3:ssa. 

Näin ei tarvittaisi uutta metodia. Haittapuolena molemmissa on riippuvuus driverin palauttaman datan ja layoutin välillä.

2021-05-04 08:36 UTC, EreMaijala commented
@samuli En pidä driverin palauttaman datan vaikutusta layoutiin ongelmana. Se on ihan luonnollista, että esitystapa muokataan datan kannalta järkevimmäksi. Mutta jos nyt näyttää liian hankalalta, niin ehkä sama metodi mutta eri templaatti voisi toimia välimuotona?

2021-05-04 11:07 UTC, samuli commented
Muutin käyttämään getAllRecordLinksiä. Unohdin että otsikon pitää EADssa olla "Liittyvät aineistot", joten jouduin kuitenkin monistamaan uuden kentän. Template ja metodi ovat kuitenkin samoja.

Marcin toimivuuden voisi vielä varmistaa jos löytyy testitietue.

2021-05-05 12:40 UTC, EreMaijala approved these changes

2021-05-05 12:48 UTC, merged