Add CommonMark extension for processing custom elements
NatLibFi/NDL-VuFind2 pull request #1993
Opened 2021-04-28 13:44 UTC by aleksip

Depends on #1970

2021-04-28 13:51 UTC, aleksip commented
Travis-herja näyttäisi johtuvan puuttuvasta interfacesta joka lisätään toisessa PR:ssä.

2021-06-07 11:17 UTC, EreMaijala requested changes

2021-06-07 11:17 UTC, EreMaijala commented on module/Finna/src/Finna/View/CustomElement/CommonMark/CustomElementCloseBlock.php
> +        $this->finalStringContents = \implode("\n", $this->strings->toArray());
Ei tartte kenoviivaa implode.

2021-06-07 11:17 UTC, EreMaijala commented on module/Finna/src/Finna/View/Helper/Root/MarkdownFactory.php
> +            $cConfig['vufind']['plugin_managers']['view_customelement']['aliases']
Tähän null coalescing, tai muuten tämän pitää olla riippuvainen #1994:sta.

2021-06-08 11:35 UTC, EreMaijala approved these changes

2021-06-08 11:36 UTC, merged