Add finna-list, finna-panel and finna-truncate custom elements
NatLibFi/NDL-VuFind2 pull request #1994
Opened 2021-04-28 14:06 UTC by aleksip

Depends on #1970

2021-04-28 14:11 UTC, aleksip commented
Tässäkin Travis-herjat näyttäisivät johtuvan puuttuvasta luokasta joka lisätään toisessa PR:ssä.

2021-06-07 11:27 UTC, EreMaijala requested changes

2021-06-07 11:27 UTC, EreMaijala commented on module/Finna/config/module.config.php
> +                    \Finna\View\CustomElement\FinnaList::getName() => 'Finna\View\CustomElement\FinnaList',
`::getName()` => `::class` kuten muualla koodissa?

2021-06-07 11:27 UTC, EreMaijala commented on module/Finna/src/Finna/View/CustomElement/FinnaList.php
> +    public function __construct(?array $options = [])
Tällä on oletusarvona tyhjä array, enkä huomannut mitään selkeää syytä sallia null. Eli voisi olla ilman kysymysmerkkiä, vai? Sama muissakin.

2021-06-07 11:27 UTC, EreMaijala commented on themes/finna2/templates/CustomElement/finna-list.phtml
> +    'id' => $id,
Saisiko nämä [vars](https://docs.laminas.dev/laminas-view/php-renderer/#vars):lla? Jos ei, niin käytä compact-funktiota.

2021-06-08 11:37 UTC, EreMaijala approved these changes

2021-06-09 09:58 UTC, samuli approved these changes

2021-06-09 10:24 UTC, merged