[ALLI-6839] SolrForward: Video warning icons
NatLibFi/NDL-VuFind2 pull request #1995
Opened 2021-05-03 10:58 UTC by LuomaJuha

Tests: 
Record/kavi.elonet_elokuva_113528
Record/kavi.elonet_elokuva_1609672
Record/kavi.elonet_elokuva_117827

config.ini:

[Record]
embedVideo = true

also test with embedVideo = false
Warning icons should be displayed in the popup for a small amount of time

2021-05-03 13:34 UTC, EreMaijala requested changes
Refaktoroinnit mielellään erikseen...

2021-05-03 13:34 UTC, EreMaijala commented on local/languages/finna/fi.ini
> +video_warning_S = "Sallittu kaikenikäisille"
Olisiko parempi vain yhdistää S ja T ..._general_audiences -merkinnäksi ja näyttää se käyttöliittymän kielellä?

2021-05-03 13:34 UTC, EreMaijala commented on local/languages/finna/en-gb.ini
> +video_warning_violence = "Contains violence"
Jakaisin nämä kahteen osaan vähän virallisten luokitusten mukaan, esim. content_descriptor_violence...content_descriptor_drug_use ja age_rating_... 

Eikä ehkä tartte olla video-kohtaisia, jolloin voisi hyödyntää muussakin sisällössä tarvittaessa.

ks. esim. https://en.wikipedia.org/wiki/Motion_Picture_Association_film_rating_system ja https://fi.wikipedia.org/wiki/Kuvaohjelmien_ik%C3%A4rajat_Suomessa

2021-05-06 12:16 UTC, LuomaJuha commented on local/languages/finna/en-gb.ini
> +video_warning_violence = "Contains violence"
Kuulostaa hyvältä

2021-05-06 12:43 UTC, LuomaJuha commented on local/languages/finna/fi.ini
> +video_warning_S = "Sallittu kaikenikäisille"
Sitä mäki mietin, mut esim verkossa ruotsinkielisissä sarjoissa tulee esille T mikä on ruotsiksi kaite kirjoitettuna automaattisesti vaikka olis suomenkielinen sivu https://kavi.fi/ikarajat/yleistieto/symbolit/ . Joten vähän vaikea sanoa :S

2021-05-11 07:54 UTC, EreMaijala requested changes

2021-05-11 07:54 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrForward.php
> +        'S' => 'age_rating_for_all_ages_fi',
_fi pois?

2021-05-11 07:54 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrForward.php
> +        'T' => 'age_rating_for_all_ages_sv',
_sv pois?

2021-05-11 07:54 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/record-video-player.phtml
> +              <span class="video-warning-icon"><img title="<?=$this->transEsc($translation)?>" data-src="<?=$warningImageUrls[$warning]?>"/></span>
transEscAttr ja src:lle escapeHtmlAttr

2021-05-12 09:58 UTC, EreMaijala approved these changes

2021-05-12 09:59 UTC, merged