Alli 6802
NatLibFi/NDL-VuFind2 pull request #1997
Opened 2021-05-04 18:20 UTC by tmikkonen

2021-05-05 13:37 UTC, EreMaijala requested changes
Käytä attribuutteihin menevissä käännöksissä transEscAttr-metodia pelkän transEsc:n sijaan.

Sivut eivät mene HTML-validaattorista läpi, korjattava.

2021-05-05 13:37 UTC, EreMaijala commented on themes/finna2/templates/myresearch/checkedout.phtml
> +                      <span class="sr-only"><?=$this->transEsc('Sort')?></span>
Suurella todennäköisyydellä tulee paikallisten räätälöintien kanssa ongelmia, jos teksti siirretään sort.phtml:stä. Ja miksi pitäisi, kun sieltä se näytetään vain, jos on oikeasti vaihtoehtoja?

2021-05-05 13:37 UTC, EreMaijala commented on themes/finna2/templates/myresearch/checkedout.phtml
> +                <div class="text-right" colspan="2">
colspan?

2021-05-05 13:37 UTC, EreMaijala commented on local/languages/finna/fi.ini
> +Item = "Teos"
Tämä ei ole mitenkään yksiselitteinen käännös, joten jos se säilytetään tällaisena, niin avaimeksi jotain tilannekohtaista. "Teos" ei kuitenkaan ole hyvä käännös, jos kyseessä on niteen otsikko. Voisiko käyttää olemassaolevaa Title-käännöstä?

2021-05-05 13:37 UTC, EreMaijala commented on local/languages/finna/sv.ini
> +Request = "Beställning"
Tässä sama ongelma kuin Item-käännöksessä. Pitäisi olla tarkempi avain, esim. ill_request.

2021-05-05 13:37 UTC, EreMaijala commented on local/languages/finna/fi.ini
> +Request = "Varaus"
Tämä ei vastaa ruotsinkielistä, ja jos käytetään ILL-sivulla, niin kyseessä on kaukolainapyyntö eikä varaus.

2021-05-05 13:37 UTC, EreMaijala commented on themes/finna2/templates/myresearch/checkedout.phtml
> +              <th id="label-title-column" aria-colindex="2"><?=$this->transEsc('Item');?><span aria-hidden="true" class="hidden-xs"><?=$this->transEsc('Renewals and Due Date')?></span></th>
Tekstit menevät yhteen, eikö? Item ei tuossa ehkä oikein avaudu. Ongelmana myös se, ettei sarake välttämättä sisällä kaikkia tietoja, ainakaan uusimista, jos ei niitä saada kirjastojärjestelmästä.
Jos jälkimmäistä tekstiä ei edes näytetä, tarvitaanko sitä? Ehkä riittäisi, kun Teos-tekstin kohdalla olisi "Lainan tiedot".

2021-05-05 13:37 UTC, EreMaijala commented on themes/finna2/templates/myresearch/holds.phtml
> +              <th id="label-title-column" aria-colindex="2"><?=$this->transEsc('Item');?><span aria-hidden="true" class="hidden-xs"><?=$this->transEsc('Hold');?></span></th>
Samat kommentit kuin lainojen kohdalla.

2021-05-05 16:58 UTC, tmikkonen commented on local/languages/finna/fi.ini
> +Item = "Teos"
Titleä yritin ensin, mutta sille on käytössä "Otsikko".
Käännöksiä joutuu vielä miettimään, mutta luultavasti tilannekohtainen avain on järkevin ratkaisu kun noiden kanssa sai jo aiemmin raapia päätään.

2021-05-05 17:00 UTC, tmikkonen commented on themes/finna2/templates/myresearch/checkedout.phtml
> +                      <span class="sr-only"><?=$this->transEsc('Sort')?></span>
Tämä on poistamatta unohtunut turha jäänne ennen kuin tajusin muokata hieman sort.phtml:ää.

2021-05-05 17:01 UTC, tmikkonen commented on themes/finna2/templates/myresearch/checkedout.phtml
> +                <div class="text-right" colspan="2">
Rivit hyppineet ilmeisesti silmissä. Täysin turha.

2021-05-05 17:04 UTC, tmikkonen commented on themes/finna2/templates/myresearch/checkedout.phtml
> +              <th id="label-title-column" aria-colindex="2"><?=$this->transEsc('Item');?><span aria-hidden="true" class="hidden-xs"><?=$this->transEsc('Renewals and Due Date')?></span></th>
Kokeilin välissä aiemmin selventäviä "sr-only"-väliotsikoita, mutta meni aika sillisalaatiksi ja poistin ne kaikki.
Pasin alkuperäinen ehdotus oli tuo tiedot, joten luultavasti parempi tosiaan mennä sillä ja käyttää em. tilannekohtaisia avaimia.

2021-05-05 17:20 UTC, tmikkonen commented
Tuli hieman yllätyksenä, että aria-colindexillä ei voikaan numeroida sarakkeita uusiksi table-taulukossa. Toimii vain div role="table" -rakenteessa.
Oli siellä toki pari muutakin virhettä noiden lisäksi, mutta ne on ratkottu.
TransEscAttr:t lisätty.
Käännöstermit avaimineen täytyy tosiaan vielä pähkäillä ennen uutta pushia.

2021-05-07 14:50 UTC, tmikkonen commented
Vaihdoin käännösavaimia ja muutin otsikointia "Xxxxx:n tiedot"-tyyppisiksi kaikissa jättäen esim. eräpäivätiedoilta erillisen (väli)otsikoinnin pois. Lisäksi poistin otsikot näkyvistä, vaikka ne toki luetaan ruudunlukijalla (yhtenäisempää, kun otsikointia ei ole kaikissa oman tilin taulukoissa muutenkaan ja joskus aiemmin pyrittiin säästämään pystytilan käytössä - helppo vaihtaa haluttaessa näkyviin "sr-only"-luokka poistamalla.

2021-05-14 10:11 UTC, tmikkonen commented
Tein aiemmin Pasin muutostoiveet ja mergesin keskiviikkona Juhan tekemiin muutoksiin ja niiden aiheuttamiin konflikteihin.

2021-05-31 06:33 UTC, pasitiis approved these changes

2021-06-01 13:14 UTC, EreMaijala requested changes

2021-06-01 13:14 UTC, EreMaijala commented on themes/finna2/templates/myresearch/checkedout.phtml
> +                      <?=$this->partial('myresearch/helpers/record-author.phtml', ['record' => $resource]);?>
Tupla

2021-06-01 13:14 UTC, EreMaijala commented on themes/finna2/templates/myresearch/checkedout.phtml
> +                        <input type="submit" class="btn btn-primary renew-button" name="renewSelected" value="<?=$this->escapeHtmlAttr("renew_selected")?>" />
Ei käänny, pitäisi olla transEscAttr

2021-06-01 13:14 UTC, EreMaijala commented on themes/finna2/templates/myresearch/checkedout.phtml
> +                          <input type="submit" class="btn btn-primary renew-button" name="renewAll" value="<?=$this->escapeHtmlAttr('renew_all')?>" />
Ei käänny, pitäisi olla transEscAttr

2021-06-02 15:16 UTC, tmikkonen commented on themes/finna2/templates/myresearch/checkedout.phtml
> +                      <?=$this->partial('myresearch/helpers/record-author.phtml', ['record' => $resource]);?>
poistettu

2021-06-02 15:17 UTC, tmikkonen commented on themes/finna2/templates/myresearch/checkedout.phtml
> +                        <input type="submit" class="btn btn-primary renew-button" name="renewSelected" value="<?=$this->escapeHtmlAttr("renew_selected")?>" />
Vieläkö näitä jäi... vaihdettu.

2021-06-02 15:17 UTC, tmikkonen commented on themes/finna2/templates/myresearch/checkedout.phtml
> +                          <input type="submit" class="btn btn-primary renew-button" name="renewAll" value="<?=$this->escapeHtmlAttr('renew_all')?>" />
Vaihdettu.

2021-06-07 07:12 UTC, EreMaijala approved these changes

2021-06-07 07:13 UTC, merged