Remove duplicate description from authority links
NatLibFi/NDL-VuFind2 pull request #2009
Opened 2021-05-11 07:40 UTC by LuomaJuha

2021-05-11 07:52 UTC, samuli commented
@LuomaJuha description-kenttä siirtyy myös tässä: https://github.com/NatLibFi/NDL-VuFind2/pull/2000
Voitko tarkistaa korjaako tilanteen myös sun testi-casessa.

2021-05-11 09:28 UTC, LuomaJuha commented
Ah, itseasiassa tärkeintä olikin saada tuo yksi if blokki data-contributoreissa pois. @samuli

2021-05-12 09:04 UTC, samuli approved these changes

2021-05-12 09:06 UTC, samuli commented
Virhe esiintyy tässä esimerkissä (kun toimija-linkitys on käytössä), Muut tekijät > Kreditoimattomat
http://finna-dev-fe.csc.fi/edge2/Record/kavi.elonet_elokuva_122609

2021-05-12 09:57 UTC, EreMaijala requested changes

2021-05-12 09:57 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/authority-link-element.phtml
> +  </a><?= $additionalDataEl?><?php if (!empty($this->description)): ?> <span class="author-description"><?="({$this->escapeHtml($this->description)})"?></span><?php endif; ?>
authority-link-element:n pitäisi olla riippumaton auktoriteetin tyypistä, eikö? Silloin author-description on väärä luokka.

2021-05-12 11:17 UTC, merged