[ALLI-6956] EAD3: display all originations
NatLibFi/NDL-VuFind2 pull request #2015
Opened 2021-05-18 08:48 UTC by samuli

Listataan kaikki arkistonmuodostajat. 
AHAAn origination-elementit erotellaan localtype-attribuutin mukaan nimiin ja aikatietoihin. 

http://finna-dev-fe.csc.fi/edge2/Record/ahaa-ng.851133713?_=1621255999868&lng=fi

```
<origination>
      <name localtype="http://www.rdaregistry.info/Elements/u/#P60672" relator="Arkistonmuodostaja" identifier="EAC_592905922">
        <part localtype="Ensisijainen nimi" lang="fin">Tapanilat (suku)</part>
        <part localtype="suhteen ajallinen kattavuus">unknown - open</part>
      </name>
    </origination>
    <origination>
      <name localtype="http://www.rdaregistry.info/Elements/u/#P60672" relator="Arkistonmuodostaja" identifier="EAC_851133747">
        <part localtype="Ensisijainen nimi" lang="fin">Finnatestin organisaatio</part>
        <part localtype="suhteen ajallinen kattavuus">unknown - open</part>
        <part localtype="Varianttinimi" lang="swe">Finnatest organisation</part>
        <part localtype="suhteen ajallinen kattavuus">unknown - open</part>
        <part localtype="Aikaisempi nimi" lang="fin">Finnatestin testiorganisaatio</part>
        <part localtype="suhteen ajallinen kattavuus">unknown - open</part>
      </name>
    </origination>
  </did>
``'

2021-05-18 09:10 UTC, EreMaijala requested changes

2021-05-18 09:10 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrEad3.php
> +        return $originations[0] ?? null;;
puolipiste tuplana. Voisi palauttaa aina stringin, tässä vaihtoehtona tyhjän, kuten SolrEad:n getOrigination.

2021-05-18 09:10 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrEad3.php
> +        if ($originations = $this->getOriginationExtended()) {
Voisi palauttaa aina arrayn.

2021-05-18 09:10 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrEad3.php
> +     * @return array|null
Sama tässä, palautetaan aina array, vaikka sitten tyhjänä.

2021-05-18 09:10 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrEad3.php
> +        foreach ($record->did->origination as $origination) {
tähänkin `->origination ?? []`

2021-05-18 09:10 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrEad3.php
> +                            if ($nextEl = $names[$i+1] ?? null) {
Tämä tuntuu todella epävarmalta tavalta, mutta jos "suhteen ajallinen kattavuus" -tagiin ei saada kielikoodia mukaan, niin ei ilmeisesti muuta vaihtoehtoa.

2021-05-18 09:10 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/SolrEad/result-condensed.phtml
> +            <a href="<?=$this->url('search-results')?>?lookfor=%22<?=urlencode($origination)?>%22&amp;type=Author"><?=$this->escapeHtml($origination)?></a><?=$i + 1 < $originationCount ? ' ; ' : ''?>
Lisätään puolipiste ennen linkkiä muille paitsi ensimmäiselle, niin ei tarvitse count():ia.

2021-05-18 09:10 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/SolrEad/result-list.phtml
> +                <a href="<?=$this->url('search-results')?>?lookfor=%22<?=urlencode($origination)?>%22&amp;type=Author"><?=$this->escapeHtml($origination)?></a><?=$i + 1 < $originationCount ? ' ; ' :
Lisätään puolipiste ennen linkkiä muille paitsi ensimmäiselle, niin ei tarvitse count():ia.

2021-05-18 09:10 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/SolrEad/result-condensed.phtml
> +            <a href="<?=$this->url('search-results')?>?lookfor=%22<?=urlencode($origination)?>%22&amp;type=Author"><?=$this->escapeHtml($origination)?></a><?=$i + 1 < $originationCount ? ' ; ' : ''?>
Kun näitä nyt viilataan, niin olisi hyvä käyttää url-helperiä parametrien lisäämiseen ja ajaa tulos escapeHtmlAttr:n kautta. Ks. esim. https://github.com/NatLibFi/NDL-VuFind2/blob/dev/themes/finna2/templates/librarycards/home.phtml#L79

2021-05-18 09:10 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/SolrEad/result-list.phtml
> +                <a href="<?=$this->url('search-results')?>?lookfor=%22<?=urlencode($origination)?>%22&amp;type=Author"><?=$this->escapeHtml($origination)?></a><?=$i + 1 < $originationCount ? ' ; ' :
Kun näitä nyt viilataan, niin olisi hyvä käyttää url-helperiä parametrien lisäämiseen ja ajaa tulos escapeHtmlAttr:n kautta. Ks. esim. https://github.com/NatLibFi/NDL-VuFind2/blob/dev/themes/finna2/templates/librarycards/home.phtml#L79

2021-05-18 10:53 UTC, samuli commented on module/Finna/src/Finna/RecordDriver/SolrEad3.php
> +                            if ($nextEl = $names[$i+1] ?? null) {
Samaa mieltä, ratkaisu ei tosiaan ole kaunis...

2021-05-20 12:23 UTC, EreMaijala approved these changes

2021-05-20 12:23 UTC, merged