[ALLI-6971] Extend Subject search use ID's.
NatLibFi/NDL-VuFind2 pull request #2018
Opened 2021-05-21 07:28 UTC by samuli

2021-05-26 08:19 UTC, EreMaijala requested changes

2021-05-26 08:19 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrEad3.php
> +                    $data['authType'] = preg_match('/^https?:/', $id)
Pitäisikö meillä olla jokin "tuntematon" tyyppi vai riittääkö tämä?

2021-05-26 08:19 UTC, EreMaijala commented on local/config/finna/config.ini.sample
> +;   - search-subject performs an OR search by topic_id_str_mv and topic
Vastaavan pitäisi kai toimia tekijöiden/toimijoiden kanssa. Voisiko asetuksen nimetä yleisemmin tyyliin "search-mixed" vai onko parempi tehdä erillinen "search-author"?

2021-05-31 08:31 UTC, samuli commented on module/Finna/src/Finna/RecordDriver/SolrEad3.php
> +                    $data['authType'] = preg_match('/^https?:/', $id)
Tuntematon tyyppi voisi olla järkevä, mutta se vaatii linkin yhteyteen uuden ikonin. Mapataanko tuntemattomaksi tässä ja määritellään uusi ikoni `format-unknownname`, joka käyttää toistaiseksi Personal Namen ikonia?
https://github.com/NatLibFi/NDL-VuFind2/blob/dev/themes/finna2/less/global/finnaicons.less#L495

2021-05-31 08:44 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrEad3.php
> +                    $data['authType'] = preg_match('/^https?:/', $id)
Joo, se voisi olla järkevää.

2021-05-31 08:54 UTC, samuli commented on local/config/finna/config.ini.sample
> +;   - search-subject performs an OR search by topic_id_str_mv and topic
`search-subject` etsii toimijaindeksin tunnisteella topic_id_str_mv -kentästä. Kentässä voi olla toimijaindeksin tunnisteita tai muita ureja. Voidaan toki nimetä `search-mixed` jos on selkeämpi.

`search` taas hakee authority2_id_str_mv-kentästä, milloin se vastaisi search-authoria? (tätä ei ehkä kannata muuttaa koska asetus on jo käytössä) 

Molempia asetuksia käytetään vain Authority-helpperin kautta, milloin tunnisteen tyypin pitää olla Personal/Corporate/Family Name. Jos taas tunniste on uri (esim. Marcin asiasanat), tehdään samanlainen topic_id_str_mv -haku, mutta se pyydetään Record-helpperin getLinkiltä (joka käyttää samaa link-authority-search-subject -sivupohjaa) :
https://github.com/NatLibFi/NDL-VuFind2/pull/2018/files#diff-3d98f8b46686f3ee1f96fa907d8ce606254c2265f3fad308215b7d46c3cd52e2R26

2021-05-31 10:28 UTC, samuli commented on module/Finna/src/Finna/RecordDriver/SolrEad3.php
> +                    $data['authType'] = preg_match('/^https?:/', $id)
Muutettu.

2021-06-01 17:36 UTC, EreMaijala commented on local/config/finna/config.ini.sample
> +;   - search-subject performs an OR search by topic_id_str_mv and topic
Okei, on ihan ok noin.

2021-06-01 17:48 UTC, EreMaijala approved these changes

2021-06-01 17:48 UTC, merged