[ALLI-6971] Add optional detail to record link items
NatLibFi/NDL-VuFind2 pull request #2020
Opened 2021-05-21 11:56 UTC by samuli

Näytetään liittyvän tietueen lisätieto linkin yhteydessä:

EAD3 esimerkki:
http://finna-dev-fe.csc.fi/edge2/Record/ahaa-ng.851133713_2348188453
![image](https://user-images.githubusercontent.com/3889/119132786-cc69e800-ba43-11eb-9d53-eb553cd6ef34.png)

2021-05-26 08:08 UTC, EreMaijala requested changes

2021-05-26 08:08 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrEad3.php
> +                'detail' => isset($attr->arcrole) ? (string)$attr->arcrole : null,
Kannattaisiko käyttää !empty niin ei tule tyhjillä attribuuteilla tyhjiä sulkuja?

2021-05-31 09:00 UTC, samuli commented on module/Finna/src/Finna/RecordDriver/SolrEad3.php
> +                'detail' => isset($attr->arcrole) ? (string)$attr->arcrole : null,
Jep, parempi näin.

2021-06-02 11:49 UTC, EreMaijala requested changes
Laita samalla tyylillä kuin https://github.com/NatLibFi/NDL-VuFind2/pull/2017/files#diff-3d98f8b46686f3ee1f96fa907d8ce606254c2265f3fad308215b7d46c3cd52e2R30

2021-06-03 12:53 UTC, EreMaijala approved these changes

2021-06-03 12:53 UTC, merged