Add EasyMDE-based Markdown editable component
NatLibFi/NDL-VuFind2 pull request #2042
Opened 2021-06-14 12:12 UTC by aleksip

- Replace SimpleMDE with EasyMDE
- Add finna-md-editable, finna-editable, finna-btn and finna-truncate components
- Refactor finna-mylist.js to use finna-md-editable
- Add server-rendered Markdown as a return value to EditList and EditListResource Ajax handlers
- Remove old custom tag related code from finna-mylist.js
- Add replaceDeprecatedTags method to Markdown view helper
- Add custom elements whitelist support to CleanHtml view helper
- Clean HTML while in Markdown format in Markdown view helper
- Small improvements to custom elements

2021-06-15 06:46 UTC, aleksip commented
Kattaa myös ALLI-6982 ja ALLI-6602.

2021-06-15 09:45 UTC, LuomaJuha commented on themes/finna2/js/components/organisms/widgets/finna-md-editable/finna-md-editable.js
> +  var instance = this;
Voinee määrittää ekalla rivillä?
Aika monessa paikassa käytetään var _ = this; jolloin viitataan itse prototyyppiin ja merkkejä säästyy vähän. :D

2021-06-30 06:39 UTC, EreMaijala requested changes
Huomio varsinaisten muutosten ulkopuolelta: nyt kun finna-truncate tulee laajemmin käyttöön, niin sen pitäisi nähdäkseni olla itseriittoisempi. Nythän se käsittääkseni luottaa finna-layout:n initTruncate:n tekevän varsinaisen työn, mutta yläjuoksulla on tulossa https://github.com/vufind-org/vufind/pull/1791, joka voi vaikuttaa truncaten toimintaan, ja helposti jää kyllä finna-truncate silloin huomioimatta.

2021-06-30 06:39 UTC, EreMaijala commented on module/Finna/src/Finna/View/Helper/Root/CleanHtmlFactory.php
> +        foreach ($customElements as $elementName => $elementCass) {
Pitäisikö muuttujan nimen olla `$elementClass`?

2021-06-30 06:39 UTC, EreMaijala commented on module/Finna/src/Finna/View/Helper/Root/Markdown.php
> +        return '/<' . $tagName . $attributes . '\s*>([\S\s]*?)'
Mikä tuon `[\S\s]` idea on? Miksei vain `.`?

2021-06-30 06:39 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/list-entry.phtml
> +            <?php $markdown = ($hasNote && $notes) ? $this->markdown()->replaceDeprecatedTags($notes) : ''; ?>
Tätä voisi varmaan vähän viilata nyt samalla, kun ei ole kauhean kätevää, että on $hasNote ja $notes erikseen, eli en nyt keksinyt mitään syytä $hasNote-muuttujan olemassaololle. 
Samaa noissa list-entry -templaateissa.

2021-06-30 06:39 UTC, EreMaijala commented on themes/finna2/js/components/organisms/widgets/finna-md-editable/finna-md-editable.js
> +      $('.finna-md-editable').each(function initFinnaMdEditable() {
Tässä varmaan olisi hyvä huolehtia siitä, ettei tupla-init sotke mitään. Eihän sellaista pitäisi tehdä, mutta puolustautuisin sitä vastaan kuitenkin.

2021-06-30 06:39 UTC, EreMaijala commented on local/languages/finna/en-gb.ini
> +editor_other = "Other"
Käännösavaimista voisi tehdä ainakin tällä puolella vähän rajaavampia, vaikka sitten js:ssä jättäisi lyhyemmäksi. Ts. `editor_other`  => `editor_insert_other` jne.

2021-06-30 08:08 UTC, aleksip commented on module/Finna/src/Finna/View/Helper/Root/Markdown.php
> +        return '/<' . $tagName . $attributes . '\s*>([\S\s]*?)'
Ideana on matchata myös rivinvaihdot.

2021-07-06 06:25 UTC, EreMaijala commented on module/Finna/src/Finna/View/Helper/Root/Markdown.php
> +        return '/<' . $tagName . $attributes . '\s*>([\S\s]*?)'
Mä suosisin m-optiota viimeisen kauttaviivan jälkeen, mutta ok noin.

2021-07-06 09:39 UTC, EreMaijala commented on themes/finna2/js/components/organisms/widgets/finna-md-editable/finna-md-editable.js
> +      if (!initDone) {
Tämä on ok olettaen, ettei editableja koskaan ladata dynaamisesti esim. tabiin tms., mutta jos ladataan, niin ei ole mitään tapaa enää initialisoida niitä. Eli parempi olisi lisätä vaikka data-attribuutti niille, jotka on initialisoitu ja tarkistaa se luupissa.

2021-07-09 11:08 UTC, EreMaijala approved these changes

2021-07-09 11:10 UTC, merged