[ALLI-6903] EAD3: show arrangement info.
NatLibFi/NDL-VuFind2 pull request #2051
Opened 2021-06-16 10:13 UTC by samuli

"Aineiston järjestäminen" -tietuekentän lisäksi nämä:
- getDisplayLabel korjattu palauttamaan tyhjä lista nullin sijaan (kutsujat olettavat näin).
- Puuttuva Archive Relations -tietuekenttä lisätty Collection-sivulle.

2021-06-17 11:32 UTC, EreMaijala requested changes
"Arrangement" on liian geneerinen termi, ja ainakin minulle tulee siitä ensimmäisenä mieleen musiikin sovitus. Tarvitaan siis jokin kuvaavampi termi tiedon järjestämiselle. Material arrangement?

2021-06-17 12:26 UTC, piiajn commented
Hyvä huomio, ehdotus sopii

2021-06-17 12:31 UTC, EreMaijala commented
Parasta muuttaa myös getArrangement => getMaterialArrangement jne.

2021-06-29 12:13 UTC, EreMaijala approved these changes

2021-06-29 12:13 UTC, merged