[ALLI-7023] Clean up search and list control styles
NatLibFi/NDL-VuFind2 pull request #2061
Opened 2021-06-22 09:52 UTC by pasitiis

Eri näyttökokoja (desktop-tablet-mobile) pyritty optimoimaan. Flexiä käytetty enemmän elementtien aselmointiin.

Vaikutuksia näihin sivuihin (search-controls):
MyResearch/MyList/*
List/*
Search/*

2021-09-02 13:08 UTC, rajaro requested changes

2021-09-02 13:08 UTC, rajaro commented on themes/finna2/less/finna/public-favorites.less
> -
Tää vaikuttaa upotettuun listaan myös: jos on esim `<?=$this->userlistEmbed(['id' => 'x', 'allowCopy' => true])?>` niin nyt puuttuu margin listan ja kopiointinapin välistä

2021-09-02 13:08 UTC, rajaro commented on themes/finna2/less/finna/mylist.less
> +}
välilyöntejä pois

2021-09-02 13:09 UTC, LuomaJuha commented
Näyttää vähän nihkeältä omaan silmään tuo järjestyksen muokkauspainike. Oliskohan mahdollista saada vähän samanlaiseksi? (Firefox)
![Kuvakaappaus - 2021-09-02 16-07-29](https://user-images.githubusercontent.com/33253757/131848960-eea5457e-9163-4132-b5f2-6eefbf04bfda.png)

2021-09-03 06:17 UTC, pasitiis commented
> Näyttää vähän nihkeältä omaan silmään tuo järjestyksen muokkauspainike. Oliskohan mahdollista saada vähän samanlaiseksi? (Firefox)
> ![Kuvakaappaus - 2021-09-02 16-07-29](https://user-images.githubusercontent.com/33253757/131848960-eea5457e-9163-4132-b5f2-6eefbf04bfda.png)

Voi olla että on hyvä jättää "Muokkaa järjestystä" teksti painikeen yhteyteen. Nyt tuossa on tilan säätämiseksi näkyvillä vain toiminnon ikoni mobiilissa (jotta toiminnot mahtuisi yhdelle riville). Voi olla aika pieni käyttäjäryhmä, joka lähtee suosikkilistan järjestystä muuttamaan mobiilisti (nykyisellään painike tulee hyvin voimakkaasti esille puhelimella).

2021-09-03 11:49 UTC, LuomaJuha commented
Joo, eikun mietin josko se olis esim. saman paksunen ku muut siinä vieressä niin olis harmonisempi :)

2021-09-09 09:41 UTC, pasitiis commented
Ok. Tein nyt painikkeesta harmoonisemman ja korjasin muut ongelmat.

2021-09-20 11:29 UTC, rajaro approved these changes

2021-09-27 08:14 UTC, EreMaijala commented
@LuomaJuha Ok nyt?

2021-09-29 11:46 UTC, LuomaJuha approved these changes

2021-10-08 07:14 UTC, merged