[ALLI-7063] EAD3: add container info
NatLibFi/NDL-VuFind2 pull request #2062
Opened 2021-06-23 12:37 UTC by samuli

2021-06-29 12:40 UTC, EreMaijala requested changes

2021-06-29 12:40 UTC, EreMaijala commented on themes/finna2/templates/RecordTab/externaldata.phtml
> +            <?php if (!empty($format) || !empty($info)): ?><br /><?php endif; ?><span class="physical-location"><?=$this->escapeHtml($physicalLocation) ?></span>
Ei varmaan tartte olla tuon span:n samalla rivillä?

2021-06-29 12:40 UTC, EreMaijala commented on themes/finna2/templates/RecordTab/externaldata.phtml
> +          <?php $accressRestriction = $item['accessRestriction'] ?? ''; if (!empty($accessRestriction)): ?>
$accessRestriction-muuttujaa ei vissiin muualla käytetä, aika turha?

2021-07-05 07:28 UTC, samuli commented on themes/finna2/templates/RecordTab/externaldata.phtml
> +          <?php $accressRestriction = $item['accessRestriction'] ?? ''; if (!empty($accessRestriction)): ?>
Jep, poistin.

2021-07-05 07:32 UTC, EreMaijala approved these changes

2021-07-05 07:32 UTC, merged