[ALLI-6970] EAD3: show summary item with URL
NatLibFi/NDL-VuFind2 pull request #2068
Opened 2021-07-08 13:23 UTC by samuli

Näytetään scopecontent->p:n mahdollinen ref-elementti linkkinä:

<img src="https://user-images.githubusercontent.com/3889/124927383-44499d00-e007-11eb-9653-7aa0a9840f8d.png" width="500" />

Esim:
http://finna-dev-fe.csc.fi/edge2/Record/ahaa-ng.851133713_889200015

2021-07-08 18:41 UTC, EreMaijala requested changes

2021-07-08 18:41 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrEad3.php
> +    public function getSummary($withLinks = false)
Voisi olla siistimpi, jos olisi joku `protected getSummaryData($withLinks)`, jota tämä kutsuisi, niin ei varsinainen getSummary sisältäisi mitään parametria.

2021-07-08 18:41 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/SolrEad/core.phtml
> +                (<a target="_blank" href="<?=$this->escapeHtmlAttr($url)?>"><?=$this->escapeHtml($url)?></a>)
Pitäisikö url proxyttaa? Ja näytettävä osa ajaa truncateUrl:n kautta?

2021-07-09 06:41 UTC, samuli commented on themes/finna2/templates/RecordDriver/SolrEad/core.phtml
> +                (<a target="_blank" href="<?=$this->escapeHtmlAttr($url)?>"><?=$this->escapeHtml($url)?></a>)
En tiedä minkälaisia urlit tulevat olemaan, mutta molemmat voitaneen tehdä. Lisäsin mukaan.

2021-07-09 07:05 UTC, EreMaijala approved these changes

2021-07-09 07:05 UTC, merged