[ALLI-7086] RecordDriverRelated: show top-level title
NatLibFi/NDL-VuFind2 pull request #2075
Opened 2021-07-13 13:04 UTC by samuli

2021-08-18 05:35 UTC, EreMaijala requested changes

2021-08-18 05:35 UTC, EreMaijala commented on themes/finna2/templates/Related/RecordDriverRelatedRecordList.phtml
> +              <br/><?=$topTitles[0]?>
Escape puuttuu.

2021-09-02 12:10 UTC, EreMaijala requested changes

2021-09-02 12:10 UTC, EreMaijala commented on themes/finna2/templates/Related/RecordDriverRelatedRecordList.phtml
> +              <br/><?=$this->escapeHtml($topTitles[0])?>
Huomasin just, että leiskassa tämä on linkki. Eli pitäisi tehdä linkki samaan tapaan kuin tuolla: https://github.com/NatLibFi/NDL-VuFind2/blob/dev/themes/finna2/templates/RecordDriver/SolrEad/result-list.phtml#L64. Siellä on muutenkin aika paljon ehtoja sen suhteen, mitä missäkin tilanteessa näytetään. Tarvitaanko niistä mitään tässä?

2021-09-02 13:36 UTC, samuli commented on themes/finna2/templates/Related/RecordDriverRelatedRecordList.phtml
> +              <br/><?=$this->escapeHtml($topTitles[0])?>
Totta, linkki puuttui. Lisäsin sen ja erottelin samalla formaatin omalle rivilleen:

<img src="https://user-images.githubusercontent.com/3889/131853123-e45ba196-545e-4af7-ae80-f4a196cfd7ec.png" width="300" />

Käsittääkseni tässä on tarkoitus näyttää vain ylimmän tason otsikko, milloin yksinkertaisempi logiikka riittää.

2021-09-13 11:06 UTC, EreMaijala approved these changes

2021-09-13 11:07 UTC, merged