[ALLI-6957] EAD3: title statements with urls
NatLibFi/NDL-VuFind2 pull request #2078
Opened 2021-07-14 07:57 UTC by samuli

Näytetään kaikki lisätieto-elementit ja näihin liittyvät linkit:

<img src="https://user-images.githubusercontent.com/3889/125584520-147d1ebd-8d93-43ad-a283-0df0c909ae59.png" width="500" />

Esim: http://finna-dev-fe.csc.fi/edge2/Record/ahaa-ng.851133713_851133881

Mukana myös getTitleStatementin korjaus, joka palauttaa ensimmäisen lisätiedon kun kielikäännöstä ei ole saatavissa.

2021-08-18 05:47 UTC, EreMaijala requested changes

2021-08-18 05:47 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/data-addInfo.phtml
> +<?php $extendedData = $this->driver->tryMethod('getTitleStatementsExtended'); if (!empty($extendedData)): ?>
data-templaattien pitäisi toimia sillä datalla, mitä niille on annettu, eikä tehdä omia lisäjuttuja. Muuten hajoaa RecordDataFormatterin arkkitehtuuri.

2021-08-30 12:50 UTC, samuli commented on themes/finna2/templates/RecordDriver/DefaultRecord/data-addInfo.phtml
> +<?php $extendedData = $this->driver->tryMethod('getTitleStatementsExtended'); if (!empty($extendedData)): ?>
Totta. Refaktoroin käyttämään erillistä sivupohjaa.

2021-09-02 12:11 UTC, EreMaijala approved these changes

2021-09-02 12:11 UTC, merged