Custom elements implementation improvements
NatLibFi/NDL-VuFind2 pull request #2081
Opened 2021-07-16 10:23 UTC by aleksip

- Palautetaan yksityiskohtaisempaa tietoa elementeistä ja niiden tukemista lapsielementeistä HTML Purifierin sääntöjen asetusta varten
- Lisätty elementtien toteutusta helpottavia apumetodeja perusluokkaan
- Säädetty HTML-parseria toimimaan paremmin Markdownista tuotetun HTML:n kanssa
- Huomioitu elementtien toimivuus myös ilman parsittavaa HTML:ää
- Lisätty finna-panel:in tuki h-tagien käyttöön, muutettu oletustagiksi h3 ja oletusotsikkotasoksi 3
- Muutettu metodien ja muuttujien nimiä kuvaavammiksi
- Muutettu paquettg/php-html-parser -versiota uusimmassa versiossa olevan HTML-kommenttikäsittelybugin välttämiseksi

2021-09-02 12:23 UTC, EreMaijala requested changes

2021-09-02 12:23 UTC, EreMaijala commented on module/Finna/src/Finna/View/CustomElement/AbstractBase.php
> +    protected function getVariable(string $name, $default = null)
Minusta näiden metodien käyttäminen tekee tarkoituksesta aiempaa epäselvemmän. Voisiko nimetä metodit esim. get/setTemplateVariable?

2021-09-03 06:14 UTC, aleksip commented on module/Finna/src/Finna/View/CustomElement/AbstractBase.php
> +    protected function getVariable(string $name, $default = null)
Ajattelin että olisi sopinut joukkoon kun on jo

```php
protected function getDefaultVariables(): array
protected static function getAttributeToVariableMap(): array
protected static function getOptionToVariableMap(): array
```

mutta ymmärrän kyllä pointin... Jos lähdetään mahdollisimman selvää nimeä etsimään, niin käyttäisin ehkä mielummin `templateVariable`:n  sijaan `viewModelVariable` (lisäksi sitten `viewModelTemplate`), kun `ViewModel`:ia voi myös käyttää vaikkapa elementin JSON-version muodostamiseen (toki siinäkin voi käyttää templatea, mutta ei välttämättä).

Mutta pitäisikö sitten olla myös

```php
protected function getDefaultViewModelVariables(): array
protected static function getAttributeToViewModelVariableMap(): array
protected static function getOptionToViewModelVariableMap(): array
```

Ei noissa sinänsä kai mitään, mutta PEAR-koodausstandardin rajoitteet pistävät helposti ahdistamaan tosi pitkien nimien kanssa. Tuo oli pääsyynä noihin apumetodeihinkin, että saisi vähän lyhennettyä kutsua.

2021-09-03 06:39 UTC, EreMaijala commented on module/Finna/src/Finna/View/CustomElement/AbstractBase.php
> +    protected function getVariable(string $name, $default = null)
Ehkä toi nykyinen on sitten ihan ok, jos vaan muistaa ajatella tätä kokonaisuutena, jossa view model on vähän niin kuin container muuttujille.

2021-09-03 06:40 UTC, EreMaijala approved these changes

2021-09-03 07:20 UTC, merged