[ALLI-6738] Multiselect improvements
NatLibFi/NDL-VuFind2 pull request #2082
Opened 2021-07-23 10:03 UTC by LuomaJuha

Multiselect component without jQuery. Introducing jsHelper, which is supposed to go to vufind at some point. Accessibility improvements and should be faster at loading.

2021-07-27 11:31 UTC, LuomaJuha commented
Piti laittaa draftiks. Mut laitoin in progress labelin tohon nyt.

2021-08-18 06:38 UTC, EreMaijala commented
Sen voi konvertoida draftiksi siitä reviewers:n alapuolelta, jos tarttee.

2021-08-19 09:42 UTC, pasitiis commented
Multiselect näytti toimivan desktopissa. Testaan vielä mobiilipuolta.  jsHelper olisi hyvä laittaa erikseen yläjuokselle.

2021-09-06 07:29 UTC, pasitiis commented
Testasin iOS/Android 10, vaikutti toimivan hyvin.

2021-09-13 13:04 UTC, pasitiis approved these changes
Komponetti näytti toimivan desktopissa ja mobiilissa. Jshelperiä en varsinaisesti katselmoinut.

2021-09-17 11:45 UTC, EreMaijala requested changes
Kävin vähän läpi jsHelperiä, siitä muutama ehdotus.

2021-09-17 11:45 UTC, EreMaijala commented on themes/finna2/js/js-helper.js
> +   * Find next sibling with syntax
syntax? selector?

2021-09-17 11:45 UTC, EreMaijala commented on themes/finna2/js/js-helper.js
> +})();
rivinvaihto

2021-09-17 11:45 UTC, EreMaijala commented on themes/finna2/js/js-helper.js
> +   * Check if the element is same as selector.
"is same as" => "matches the"?

2021-09-17 11:45 UTC, EreMaijala commented on themes/finna2/js/js-helper.js
> +   * Find all parents of element until selector is satisfied.
Tätä voisi vähän tarkentaa: `Return all parents of an element up to and including the first one that matches the given selector.`

2021-09-17 11:45 UTC, EreMaijala commented on themes/finna2/js/js-helper.js
> +/* exported jsHelper */
Osassa funktioita käytetään while-luuppia ja osassa for-luuppia tekemään käytännössä sama asia. Voisi yhtenäistää käyttämään toista kattavammin.

2021-09-17 11:45 UTC, EreMaijala commented on themes/finna2/js/js-helper.js
> +   * Check if the element is same as selector.
ei kyllä osu nyt funktioon tämä kuvaus tai parametrit

2021-09-17 11:45 UTC, EreMaijala commented on themes/finna2/js/js-helper.js
> +   * If the DOMContent has been loaded, trigger immediatly.
*immediately

2021-09-17 11:45 UTC, EreMaijala commented on themes/finna2/js/js-helper.js
> +    if (document.readyState !== 'loading'){
välilyönti ennen {

2022-03-11 07:36 UTC, aleksip commented
Tämä olisi hyvä toteuttaa komponenttikirjastoon. Eli komponenttikohtaiset JS- ja Less-tiedostot, vaikkapa `finna2/js/components/molecules/navigation/finna-multiselect/finna-multiselect.js` ja `finna2/templates/components/molecules/navigation/finna-multiselect/finna-multiselect.less`. Jotka sitten kytketään `finna2/components.config.php`:ssa ja `finna2/less/components.less`:issä.

2022-07-22 07:22 UTC, LuomaJuha commented
Menossa components repoon.

2022-07-22 07:22 UTC, closed without merging