Start notification emails with a greeting + firstname
NatLibFi/NDL-VuFind2 pull request #2083
Opened 2021-07-23 17:11 UTC by tmikkonen

2021-07-23 18:09 UTC, tmikkonen commented
[ALLI-7060] unohtui commitista, pahoittelut.

2021-08-18 06:26 UTC, EreMaijala requested changes
Ei käytetä due_date_hello-viestiä muissa kuin due date reminderissa. Ainakin account_expiration_body sisältää jo tervehdyksen, näillä muutoksilla tulisi tuplana. Muutokset pitää testata (ks. https://www.kiwi.fi/pages/viewpage.action?pageId=77366277), ei voi tehdä sokkona.

2021-09-02 12:36 UTC, EreMaijala commented on themes/finna2/templates/Email/account-expiration-reminder.phtml
> +<?= $this->transEsc('due_date_hello', ['%%firstname%%' => $this->firstname])?>
transEsc => translate sähköpostissa, plain textia

2021-09-02 12:36 UTC, EreMaijala commented on themes/finna2/templates/Email/due-date-reminder.phtml
> +<?= $this->transEsc('due_date_hello', ['%%firstname%%' => $this->firstname])?>
transEsc => translate sähköpostissa, plain textia

2021-09-02 12:36 UTC, EreMaijala commented on themes/finna2/templates/Email/scheduled-alert.phtml
> +<?= $this->transEsc('due_date_hello', ['%%firstname%%' => $this->firstname])?>
transEsc => translate sähköpostissa, plain textia

2021-11-05 12:45 UTC, EreMaijala requested changes

2021-11-05 12:45 UTC, EreMaijala commented on module/FinnaConsole/src/FinnaConsole/Command/ScheduledSearch/NotifyCommand.php
> +    /**
Tee mieluummin yläjuoksulle muutospyyntö, että otetaan $user mukaan info-arrayyn. Tulee muuten ihan hirveästi duplikoitua koodia yhden etunimen takia.

2021-11-05 12:45 UTC, EreMaijala commented on module/FinnaConsole/src/FinnaConsole/Command/Util/DueDateReminders.php
> +        $firstName = $user->firstname;
Vähän tarpeeton muuttuja, kun otetaan tosta suoraan. Ehkä muutenkin tässäkin olisi parempi laittaa koko $user tonne info-arrayyn mukaan, niin templaatissa voi siitä ottaa mitä tarttee.

2021-11-05 12:45 UTC, EreMaijala commented on themes/finna2/templates/Email/scheduled-alert.phtml
> -
Onko näiden rivien poistamiselle jokin tarkoitus? Vaikuttaa viestin ulkoasuun eikä ainakaan kuulu JIRA-tikettiin.

2021-11-16 12:28 UTC, EreMaijala commented
@tmikkonen Muutin draftiksi, kun vaatii muutoksia yläjuoksulle yms. Muuta takaisin, kun on valmista.

2022-02-16 08:37 UTC, EreMaijala requested changes

2022-02-16 08:37 UTC, EreMaijala commented on module/FinnaConsole/src/FinnaConsole/Command/Util/DueDateReminders.php
> +        $firstName = $user->firstname;
Tämä vielä muuttamatta.

2022-02-16 14:14 UTC, EreMaijala requested changes

2022-02-16 14:14 UTC, EreMaijala commented on module/FinnaConsole/src/FinnaConsole/Command/Util/DueDateReminders.php
> +            'firstname' => $user->firstname
Vielä muutos kuten NotifyCommand:ssa, että otetaan koko $user mukaan, jolloin templaatissa voi siitä ottaa mitä tarvitsee.

2022-02-16 14:30 UTC, EreMaijala approved these changes

2022-02-16 14:31 UTC, merged