[ALLI-7061] Scheduled alert email subject translation string alterati…
NatLibFi/NDL-VuFind2 pull request #2084
Opened 2021-07-23 17:12 UTC by tmikkonen

…on + added greeting

2021-07-23 18:08 UTC, tmikkonen commented
[ALLI-7060] unohtui commitista, pahoittelut.

2021-11-05 12:47 UTC, EreMaijala requested changes

2021-11-05 12:47 UTC, EreMaijala commented on local/languages/finna/en-gb.ini
> +Scheduled Alert Results = "Results from your alert schedule"
Ei tässä käännöksessä ole järkeä. "Results from your scheduled alert" voisi toimia.

2021-11-16 13:10 UTC, EreMaijala commented
Poista changes requested -label, kun on valmista.

2022-05-10 11:09 UTC, EreMaijala approved these changes

2022-05-10 11:10 UTC, merged