[ALLI-7039] Add greeting to library card recovery email
NatLibFi/NDL-VuFind2 pull request #2085
Opened 2021-07-26 12:25 UTC by tmikkonen

2022-05-10 11:16 UTC, EreMaijala requested changes

2022-05-10 11:16 UTC, EreMaijala commented on module/Finna/src/Finna/Controller/LibraryCardsController.php
> +            $userdata = $this->getTable('User')->select(['email' => $email]);
Ei tätä oikein voi näin tehdä. Siihen voi tulla nimeksi vaikka lapsen nimi, jos pelkällä sähköpostiosoitteella haetaan. Lisäksi toiminto ei edellytä, että käyttäjän tietoja on Finnan kannassa, vaan tieto pitäisi saada ILS-ajurilta (tällä hetkellä ei saa, eikä varmaan kyllä ihan äkkiä tulekaan).

2022-05-10 11:16 UTC, EreMaijala commented on module/Finna/src/Finna/Controller/LibraryCardsController.php
> +            foreach ($userdata as $row) {
Jos käyttäjää ei löydy, jää $user määrittelemättä.. Ja turhaan luuppaa, jos on useampi.

2022-05-10 11:16 UTC, EreMaijala commented on themes/finna2/templates/Email/recover-library-card-password.phtml
> +<?= $this->translate('library_card_recovery_email_hello', ['%%firstname%%' => $this->user->firstname]) ?>
user ei välttämättä ole määritelty

2022-05-17 05:38 UTC, EreMaijala requested changes

2022-05-17 05:38 UTC, EreMaijala commented on module/Finna/src/Finna/Controller/LibraryCardsController.php
> +            $user = $this->getTable('User')->select(
Ei tätä oikein voi näinkään tehdä. Siihen voi tulla nimeksi vaikka huoltajan nimi, jos haetaan kortin numerolla ja se sattuu olemaan huoltajalla aktiivisena. Lisäksi toiminto ei edellytä, että käyttäjän tietoja on Finnan kannassa, vaan tieto pitäisi saada ILS-ajurilta (tällä hetkellä ei saa, eikä varmaan kyllä ihan äkkiä tulekaan).

2022-05-17 12:21 UTC, tmikkonen commented
Suljen PR:n, koska riittävän yksilöivää tietoa käyttäjästä oikean nimen liittämiseksi viestiin ei ole näillä näkymin saatavissa.

2022-05-17 12:21 UTC, closed without merging