[ALLI-7040] Due date remainder greeting personalizing + small changes…
NatLibFi/NDL-VuFind2 pull request #2086
Opened 2021-07-27 16:05 UTC by tmikkonen

… to message contents

2021-07-27 16:14 UTC, tmikkonen commented
En tiennyt miten testata lopputulosta. Muutokset eivät lopulta olleet isoja ja yritin olla huolellinen.

2021-09-02 12:35 UTC, EreMaijala requested changes

2021-09-02 12:35 UTC, EreMaijala commented on local/languages/finna/en-gb.ini
> +due_date_email_login_last = "If you no longer use this account, this message does not require any further actions. You last used this account on %%lastLogin%% by logging in with your %%loginMethod%%.
"your" ei toimi %%loginMethod%%:n kanssa. ks. due_date_login_method_*. Jälkimmäisiä käännöksiä ei voi muuttaa ilman ongelmia taaksepäin yhteensopivuuden kanssa.

2021-09-02 12:35 UTC, EreMaijala commented on local/languages/finna/en-gb.ini
> +due_date_email_login_error = "We were not able to find data on all your library cards. The due date reminders of these cards have now been deactivated. You can reactivate your due date reminders afte
Olisiko parempi "not able to *retrieve*"? Muuten tuo näyttää siltä, että kaikki on kunnossa, mutta ei vaan tällä kertaa oikein sujunut.

2021-09-02 12:35 UTC, EreMaijala commented on local/languages/finna/sv.ini
> +due_date_email_login_last = "Om du inte längre använder detta konto, förutsätter detta meddelande inga ytterligare åtgärder. Du använde kontot senast %%lastLogin%% genom att logga in med ditt %%login
"ditt":n kanssa sama ongelma kuin englanniksi.

2021-09-02 12:35 UTC, EreMaijala commented on themes/finna2/templates/Email/due-date-reminder.phtml
> +<?= $this->transEsc('due_date_hello', ['%%firstname%%' => $this->firstname])?>
Ei transEsc:iä sähköpostissa

2021-09-02 12:35 UTC, EreMaijala commented on themes/finna2/templates/Email/due-date-reminder.phtml
> +<?= $this->transEsc('due_date_email_login_error', ['%%serviceName%%' => $this->serviceName]) ?>
Ei transEsc:iä sähköpostissa. Ei poisteta olemassaolevia parametreja, ne voivat olla käytössä muokatuissa käännöksissä.

2021-09-02 12:35 UTC, EreMaijala commented on themes/finna2/templates/Email/due-date-reminder.phtml
> +<?= $this->transEsc('due_date_email_login_last', ['%%lastLogin%%' => $this->lastLogin, '%%loginMethod%%' => $this->transEsc('due_date_login_method_' . $this->loginMethod, null, '..')]) ?>
translate, ei transEsc

2021-09-13 13:29 UTC, EreMaijala requested changes

2021-09-13 13:29 UTC, EreMaijala commented on themes/finna2/templates/Email/due-date-reminder.phtml
> +<?= $this->translate('due_date_email_login_last', ['%%lastLogin%%' => $this->lastLogin, '%%loginMethod%%' => $this->translate('due_date_login_method_' . $this->loginMethod, null, '..')]) ?>
`'..'`?

2021-09-13 13:29 UTC, EreMaijala commented
Testaaminen: https://www.kiwi.fi/pages/viewpage.action?pageId=77366277.

2021-11-05 12:51 UTC, EreMaijala requested changes

2021-11-05 12:51 UTC, EreMaijala commented on local/languages/finna/en-gb.ini
> +due_date_email_login_last = "If you no longer use this account, this message does not require any further actions. You last used this account on %%lastLogin%% by logging in with %%loginMethod%%."
Mä sanoisin "action" eikä "actions".

2021-11-05 12:51 UTC, EreMaijala commented on themes/finna2/templates/Email/due-date-reminder.phtml
> +<?= $this->translate('due_date_email_login_last', ['%%lastLogin%%' => $this->lastLogin, '%%loginMethod%%' => $this->translate('due_date_login_method_' . $this->loginMethod, null, '..')]) ?>
Edelleen tämä, mikä on?

2021-11-05 12:51 UTC, EreMaijala commented on local/languages/finna/fi.ini
> +due_date_email_login_last = "Mikäli et enää käytä tätä tiliä, ei tämä viesti edellytä lisätoimia. Käytit tiliä viimeksi %%lastLogin%% kirjautumalla %%loginMethod%%."
Tämä voisi olla `due_date_email_login_error_footer` tms. koska ei käytetä kuin virhetilanteissa.

2021-11-16 13:11 UTC, EreMaijala commented
Poista changes requested -label, kun on valmista.

2022-05-10 11:38 UTC, EreMaijala approved these changes

2022-05-10 11:38 UTC, merged