[ALLI-7108] Add library types to organisationsList helper
NatLibFi/NDL-VuFind2 pull request #2091
Opened 2021-08-16 10:35 UTC by rajaro

2021-08-16 10:54 UTC, EreMaijala commented on module/Finna/src/Finna/View/Helper/Root/OrganisationsList.php
> +                        $params->addFilter('-merged_boolean:true');
Mikä tämän tarkoitus on?

2021-08-16 10:57 UTC, EreMaijala requested changes

2021-08-16 10:57 UTC, EreMaijala commented on module/Finna/src/Finna/View/Helper/Root/OrganisationsList.php
> +                        $sub = str_split($sector, 4);
Mieluummin jotain tällaista, ettei tarvitse luottaa stringin pituuteen:

```
$parts = explode('_', $sector, 2);
if ('lib' === $parts[0] && isset($parts[1])) {
```

2021-08-16 13:29 UTC, rajaro commented on module/Finna/src/Finna/View/Helper/Root/OrganisationsList.php
> +                        $params->addFilter('-merged_boolean:true');
Tarkoitus siis kerätä eri kirjastot (yleinen, yliopisto, jne) tuohon organisationsListiin, jotta saadaan Aineistojen tarjoajat -sivulla eriteltyä ne omiin kolumneihinsa.

2021-08-16 13:41 UTC, EreMaijala commented on module/Finna/src/Finna/View/Helper/Root/OrganisationsList.php
> +                        $params->addFilter('-merged_boolean:true');
Tarkoitin tuota uutta filtteriä `-merged_boolean:true`. Siitä ei ole mitään mainintaa missään, ja tuollainen suodatin on normaalisti DeduplicationListenerissä asetettava.

2021-08-17 08:21 UTC, rajaro commented on module/Finna/src/Finna/View/Helper/Root/OrganisationsList.php
> +                        $params->addFilter('-merged_boolean:true');
Ah. Pelkästään tota sector_str_mv filtteriä käyttämällä vastauksessa oli paljon muutakin kuin luulis, eli esim. /lib/pub/ -filtterillä tulee paljon muitakin kuin yleisiä kirjastoja. Oletus oli, että deduplikointiin liittyvä ongelma, ja tolla uudella filtterillä näytti toimivan ok.

2021-08-18 06:30 UTC, EreMaijala commented on module/Finna/src/Finna/View/Helper/Root/OrganisationsList.php
> +                        $params->addFilter('-merged_boolean:true');
Ei se ole ongelma, vaan deduplikointi toimii niin, kun deduplikoituna voi olla eri sektoreiden tietueet. Pitäisi varmaan kehittää ennemmin DeduplicationListener::fetchLocalRecords -metodia niin, että se ottaa mahdollisen sektorirajauksen huomioon ja palauttaa sen mukaan valikoidun tietueen oletuksena. Joka tapauksessa tuon rajauksen lisääminen aiheuttaa sen, että tietueita jää kokonaan pois tuloksesta, kun deduplikointi on käytössä.

2021-10-05 10:44 UTC, EreMaijala commented on module/Finna/src/Finna/View/Helper/Root/OrganisationsList.php
> +                        $params->addFilter('-merged_boolean:true');
Eihän yllä esitetty idea toimikaan, kun tuloksessa käytetään fasetteja. Pitää kytkeä ennemmin deduplikointi pois päältä tässä haussa finna.deduplication -suodattimella.

2021-10-05 10:45 UTC, EreMaijala commented
Kiireinen, otan toteutukseen muualla.

2021-10-05 10:45 UTC, closed without merging