[Alli-7117] EAD3: Fix displaying labels for non-nested accessrestrict elements in Collection view
NatLibFi/NDL-VuFind2 pull request #2100
Opened 2021-09-10 09:02 UTC by rajaro

esimerkkitietue: http://finna-dev-fe.csc.fi/edge2/Collection/sks.106445052
yksittäisen accessrestrict-elementin kohdalla Collection-sivupohjaan ei tule taulukkotietoihin otsikkoa. 
Muutos: käsitellään yksittäiset elementit samoin kuin monikerroksiset. Eli collection-pohjassa taulukon otsikko tulee encodinganalog-attribuutista, ja Recordissa pääotsikko on Pääsyoikeudet, jonka alla alaotsikkona encodinganalog:ista tuleva otsikko

2021-09-13 11:10 UTC, EreMaijala requested changes

2021-09-13 11:10 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrEad3.php
> +            // Case 2: nested accessrestrict elements grouped under subheadings
Miten Case 2 eroaa nyt Case 1:stä? Eikö sama koodi toimisi myös Case 1:ssä?

2021-09-13 11:39 UTC, rajaro commented on module/Finna/src/Finna/RecordDriver/SolrEad3.php
> +            // Case 2: nested accessrestrict elements grouped under subheadings
Joo toimishan se, ja turhahan noita oli tossa erotella. Otin ton erottelun poies

2021-09-14 05:54 UTC, EreMaijala approved these changes

2021-09-14 05:55 UTC, merged