[ALLI-6735] Search results: Add screen reader count descriptor to every facet badge for accessibility
NatLibFi/NDL-VuFind2 pull request #2113
Opened 2021-09-20 14:13 UTC by halanikkola

2021-09-21 12:56 UTC, EreMaijala requested changes
Tästä puuttuu tiketissä mainittu pilkku. En ole varma, miten paljon se vaikuttaa ymmärrettävyyteen, mutta voisin kuvitella, että pilkun kanssa jaksottuisi paremmin. Olisiko parempi piilottaa alkuperäinen luku ruudunlukijoilta ja tehdä käännöksestä placeholderilla varustettu, tyyliin:
`facet_aria_count = ", %%count%% results"` 

Jos on päädytty siihen, ettei pilkkua tarvita, niin se pitäisi merkitä tikettiin. Lisäksi käännösavain voisi olla vähän tilannekohtaisempi tyyliin facet_aria_count_label.

2021-09-22 09:47 UTC, pasitiis commented
> Tästä puuttuu tiketissä mainittu pilkku. En ole varma, miten paljon se vaikuttaa ymmärrettävyyteen, mutta voisin kuvitella, että pilkun kanssa jaksottuisi paremmin.

Osa ruudunlukijoista osaa jaksottaa puheen pilkun avulla (ja osa ohittaa pilkun tekemättä mitään puheen jaksotukselle).

2021-09-27 08:08 UTC, EreMaijala requested changes

2021-09-27 08:08 UTC, EreMaijala commented on themes/finna2/js/finna-layout.js
> +      tree.find('ul > li.jstree-node').each(function appendDescriptors() {
Toimii vain näkyvillä hierarkiatasoilla. Käytännössä siis näkyvä päätaso saa arvot, mutta sitten kun avaa jonkin alatason, ei niitä olekaan.

2021-09-27 12:21 UTC, halanikkola commented on themes/finna2/js/finna-layout.js
> +      tree.find('ul > li.jstree-node').each(function appendDescriptors() {
Hyvä pointti. Lisäsin kuuntelijan myös avattaville nodeille ja siirsin tuon muokkaustoiminnon omaan funktioonsa.

2021-10-01 11:52 UTC, EreMaijala requested changes

2021-10-01 11:52 UTC, EreMaijala commented on themes/finna2/js/finna-layout.js
> +      $(this).find('.facet-value').append('<span class="sr-only">, ' + VuFind.translate('result_count', {'%%count%%': badge.text()}) + '</span>');
Muuten hyvä, mutta aina kun avaa uuden päätason, monistuu edellisille tämä sisältö.

2021-10-12 11:47 UTC, EreMaijala approved these changes

2021-10-12 11:48 UTC, merged