LIDO: Use one loop to parse all representations into caches
NatLibFi/NDL-VuFind2 pull request #2114
Opened 2021-09-21 07:05 UTC by LuomaJuha

2021-09-22 07:43 UTC, EreMaijala requested changes

2021-09-22 07:43 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +            // Check if there is any links in given resourceSet so we can continue
Laita vaikka `// Skip the set if there are no links` tms. niin tarkoitus on selkeämpi.

2021-09-22 07:43 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +            // are multiple representations in the set (non-standard)
Tämä luuppi sopisi varmaan hyvin erotettavaksi erilliseksi apumetodiksi.

2021-09-22 07:43 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +                    // Is browser capable of showing this format?
Tässä olisi varmaan syytä selittää, miksi me halutaan image_original joka tapauksessa, muuten näyttää oudolta.

2021-09-22 07:43 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +                $representationAttributes = $representation->attributes();
Voisi jättää turhat muuttujat pois. Kun esim. `$representationAttributes` käytetään vain kerran, niin parempi ottaa suoraan `representationType = (string)$representation->attributes()->type;`

2021-09-22 07:43 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +                if (in_array($representationType, $imageTypeKeys)) {
Mä koittaisin jakaa tämän ja model-kohdan myös erillisiksi apumetodeiksi, jotka palauttavat taulukkoon lisättävän arrayn.

2021-09-22 07:43 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +                        $currentHiRes = [];
Tämän voisi kirjoittaa lyhyemmin tyyliin:

```
$currentHiRes = [
  'data' => $this->formatImageMeasurements(
      $representation->resourceMeasurementsSet
  ),
  'url' => $url
];
```

2021-09-22 07:43 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +        if (isset($this->cache['images'])) {
Tykkäisin enemmän siitä, että parseRepresentations hoitaisi kaiken cachettamiseen liittyvän itse, ja palauttaisi sitten cachen sisällön vaikka arrayna, jossa olisi avaimina images ja models. Tällä vältettäisiin sitä, että luotetaan tavallaan metodin sivuvaikutuksiin ja siihen, ettei sitä kutsuta turhaan. Silloin siis tässä olisi vain tyyliin:

```
$result = $this->parseRepresentations();
return $result['images'];
```
Vastaava getModels:ssa.

2021-09-22 07:43 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +        $this->cache['images'] = $imageResults;
Koska metodi saa language-parametrin, pitäisi cachettaa sen mukaisesti. Ts. jos ensin kutsutaan 'fi'-parametrilla ja sitten 'en'-parametrilla, ei saa palauttaa fi:llä cachetettua dataa.

2021-10-22 08:20 UTC, EreMaijala requested changes

2021-10-22 08:20 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +    protected function parseResourceRights($resourceSet, $language): array
Kaikille parametreille tyypit. Ja tarkemmin, object => \SimpleXMLElement tms.

2021-10-22 08:20 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +        return $this->getFromCache('images', $language);
Vielä tätä logiikkaa vähän viilaisin: muutetaan parseRepresentations => getRepresentations. Kutsutaan tässä tyyliin:

```
$representations = $this->getRepresentations($language);
return $representations['images'];
```
Sitten getRepresentations:ssa:

```
    protected function parseRepresentations(string $language): array
    {
        $cacheKey = __FUNCTION__ . "/$language";
        if (isset($this->cache[$cacheKey])) {
            return $this->cache[$cacheKey];
        }
        
        ...
        
        $result = [
            'images' => $imageResults,
            'models' => $modelResults
        ];
        $this->cache[$cacheKey] = $result;
        return $result;

```

2021-10-22 08:20 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +        $i = 0;
Turha?

2021-10-22 09:58 UTC, LuomaJuha commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +        $i = 0;
ylläpitää järjestystä $modelResults[$i] = $modelUrls;

2021-10-22 10:10 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +        $i = 0;
Onko sillä jotain eroa siihen, että laitat vain `$modelResults[] = $modelUrls;`?

2021-10-22 10:13 UTC, LuomaJuha commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +        $i = 0;
jos on sallittu kuvat malleissa ja malleja on keskellä kuvarimpsua niin silloin on

2021-10-22 10:19 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +        $i = 0;
Okei, nyt tajusin. Sitten meillä on rakenteellinen ongelma, ja tuloksena pitäisi olla results, jonka rakenne on jotain tällaista:
```
[
    [
        'images' => [...],
        'models' => [...]
    ],
    [
        'images' => [...],
        'models' => [...]
    ],
]
```
jotta ei tarvitse kahden arrayn keskinäisen järjestyksen perusteella toimia. Jos sitten halutaan vain toiset, niin sen saa tähän tapaan: `$images = array_column($results, 'images');`.

2021-10-22 10:30 UTC, LuomaJuha commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +        $i = 0;
Hmm, toihan kuulostaa järkevältä.

2021-10-22 11:09 UTC, LuomaJuha commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +        $i = 0;
Noni, koitin tollasen.

2021-10-29 12:28 UTC, EreMaijala requested changes

2021-10-29 12:28 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +     * Function to return model in formatted format
"formatted format"? Löytyisikö jotain vähän selkeämpää kuvausta niin, että siitä tajuaa, mitä tämä tekee?

2021-10-29 12:28 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +     * Function to return image in formatted format
Sama kuin yllä..

2021-11-01 09:20 UTC, LuomaJuha commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +     * Function to return model in formatted format
Eiköhän siihen löydy!

2021-11-11 08:01 UTC, EreMaijala approved these changes

2021-11-11 08:02 UTC, merged