[ALLI-7135] Display 567 field with links
NatLibFi/NDL-VuFind2 pull request #2115
Opened 2021-09-21 10:05 UTC by LuomaJuha

2021-10-01 11:48 UTC, EreMaijala requested changes

2021-10-01 11:48 UTC, EreMaijala commented on module/Finna/src/Finna/View/Helper/Root/RecordDataFormatterFactory.php
> +            'methodology-links.phtml',
Käytäntönä on ollut laittaa data-etuliite näille, jatketaan sitä.

2021-10-01 11:48 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/methodology-links.phtml
> +            <a title="<?=$this->escapeHtmlAttr($obj['term'] ?? $obj['description'])?>" target="_blank" href="<?=$this->escapeHtmlAttr($obj['url'])?>">
Nykytoteutuksessa `$obj['description']` ei välttämättä ole määritelty

2021-10-01 11:48 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrMarc.php
> +            foreach ($this->getAllSubfields($field) as $subfield) {
Nyt luuppi ottaa vain viimeisen esiintymän kustakin osakentästä. Ennemmin ensimmäinen, jolloin käytettäisiin MarcReader:n getSubfield-metodia. b ja 0 ovat kuitenkin toistettavia osakenttiä, joten pitäisi miettiä, miten niitä tuetaan. Yksi vaihtoehto olisi tehdä näin:

```
// $marcReader = $this->getMarcReader();
$description = $marcReader->getSubfield($field, 'a');
$terms = array_filter($marcReader->getSubfields($field, 'b'));
$urls = array_filter($marcReader->getSubfields($field, '0'));
$results[] = compact('description', 'terms', 'urls');

```
Jos ei haluta/tarvitse tukea toistuvia kenttiä, niin sitten vain getSubfield joka kohtaan ja muuttujien nimet $term ja $url.

Olettaisin, että tuossa on ajatuksena ollut, että jos on a-osakenttä, niin sitten voidaan siihen liittyviä b+0 toistaa, mutta ihan selvää tuon toistamisen käyttötapa ei kyllä ole, ja kun mikään ei takaa, että b ja 0 toistuvat niin, että ne vastaavat toisiaan, niin voi mennä vaikeaksi.

2021-10-07 08:25 UTC, LuomaJuha commented on module/Finna/src/Finna/RecordDriver/SolrMarc.php
> +            foreach ($this->getAllSubfields($field) as $subfield) {
jahaas, no sitten!

2021-10-22 09:47 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrMarc.php
> +            foreach ($this->getAllSubfields($field) as $subfield) {
Eli tarkoitin sitä, että otetaan vain eka b ja 0. Muuten toi menee tosi vaikeaksi, koska niiden järjestyksellä voi olla merkitystä jne.

2021-10-22 11:28 UTC, LuomaJuha commented on module/Finna/src/Finna/RecordDriver/SolrMarc.php
> +            foreach ($this->getAllSubfields($field) as $subfield) {
... noh, meni sit vähän ohi toi ohje

2021-10-22 11:48 UTC, LuomaJuha commented on module/Finna/src/Finna/RecordDriver/SolrMarc.php
> +            foreach ($this->getAllSubfields($field) as $subfield) {
Nyt pitäis olla niin, että ottaa vaan ekan? http://localhost/vufind/Record/3amk.211748#details

Jos oikein siis ymmärrän, että sama 567 kenttä voi sisältää seuraavanlaisen:



567 |  \|b kvalitatiivinen tutkimus  \|2 yso/fin  \|0 http://www.yso.fi/onto/yso/p11782 \|b uusi arvo \|0 jotain outoa

2021-11-05 12:57 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrMarc.php
> +            foreach ($this->getAllSubfields($field) as $subfield) {
Joo, tosin en löytänyt sellaista tapausta ihan heti...

2021-11-05 13:05 UTC, EreMaijala requested changes

2021-11-05 13:05 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/data-methodology-links.phtml
> +            $desc = $obj['description'] ?? '';
Voitais sopia, että toi getMethodology palauttaa aina nämä kentät, niin ei tartte täällä enää tarkistella.

2021-11-05 13:05 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/data-methodology-links.phtml
> +            <a title="<?=$this->escapeHtmlAttr($term ?: $desc)?>" target="_blank" href="<?=$this->escapeHtmlAttr($url)?>">
Näyttää vähän oudolta tämä rakenne, kun a-tagin sisään tulee div (ja eteen), mutta a itsessään ei ole missään.

2021-11-05 13:05 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/data-methodology-links.phtml
> +        <?php if ($url): ?>
Välttäisin rakenteita, joissa tagi avataan ja suljetaan kaukana toisistaan. Ennemmin kaksi tapausta, joista toisessa koko url ja toisessa urliton vaihtoehto. Tyyliin:

```
<?php if ($url): ?>
  <a title="<?=$this->escapeHtmlAttr($term ?: $desc)?>" target="_blank" href="<?=$this->escapeHtmlAttr($url)?>"><?=$this->escapeHtml($term ?: $this->truncateUrl($url))?></a>
<?php elseif ($term): ?>
  <?=$this->escapeHtml($term);?>
<?php endif; ?>
```

2021-11-08 08:13 UTC, LuomaJuha commented on themes/finna2/templates/RecordDriver/DefaultRecord/data-methodology-links.phtml
> +        <?php if ($url): ?>
Mukavampi noin, vaihdettu.

2021-11-16 13:41 UTC, EreMaijala approved these changes

2021-11-16 13:42 UTC, merged