[ALLI 6935] Add cart add/remove button to bottom mobile toolbar
NatLibFi/NDL-VuFind2 pull request #2125
Opened 2021-10-01 09:10 UTC by halanikkola

2021-10-08 07:51 UTC, EreMaijala requested changes
Toimii, mutta kaipaa visuaalista palautetta siitä, että korissa tapahtui jotain, kun kori on valikossa piilossa. Pasi lupasi lisätä taskiin ehdotuksen.

2021-11-16 12:20 UTC, EreMaijala requested changes
Sama voisi olla nyt hakutuloslistan "Lisää koriin" -linkeissä. Tartteeko poistossa olla? Ja riittäisikö yksi välähdys? @pasitiis ?

2021-11-17 07:20 UTC, pasitiis commented
Lisätään hakutuloksen välähdys. Otetaan poistosta pois ja vain yksi välähdys riittää.
![Screenshot 2021-11-17 at 9 14 51](https://user-images.githubusercontent.com/1954586/142154158-0116798f-10b8-4a41-a084-0952a3e499a6.png)

2021-11-30 14:25 UTC, EreMaijala approved these changes

2021-11-30 14:25 UTC, merged