[ALLI-6792] Add logic to #content anchor placement
NatLibFi/NDL-VuFind2 pull request #2132
Opened 2021-10-07 08:53 UTC by halanikkola

2021-10-08 08:25 UTC, EreMaijala requested changes
Tämä on niin laajavaikutteinen muutos, että hirvittää. Koen vähän ongelmallisena sen, että container:n toimintaa muutettaisiin niin, ettei se ole enää leveydestä riippuvainen ja padattu, vaan enemmän container-fluid:n kaltainen. Lisäksi näkyviä ongelmia ainakin tarkennetun haun otsikkopalkin kuvakkeessa, ja tabien marginaalit hakutulossivulla ovat muuttuneet (mutta ehkä parempaan). Olisiko parempi vaihtaa finna-main-tabs:n alainen container sitten container-fluid:ksi, niin ei karkaisi niin kauas bootstrap:n mallista?

2021-10-08 12:20 UTC, halanikkola commented
@EreMaijala Juttelin tästä jo etukäteen Pasin kanssa ja tää on kyllä vähän hurja muutos. Mietittiin nyt että jos me  tapauskohtaisesti siirreltäis tuota ankkuria olemassaolevan rakenteen eri elementeissä (Containerin, Headerin ja Tabien välillä). Periaatteessa vähän hölmön näköinen koodin puolesta varmasti mutta ainakin vähemmän invasiivinen. Mitä oisit mieltä?

2021-10-12 11:57 UTC, EreMaijala commented
@halanikkola Se olisi ainakin paljon vähemmän pelottava muutos. 👍

2021-10-22 08:44 UTC, EreMaijala requested changes
Alkaa mennä aika monimutkaiseksi nuo riippuvuudet if:ien sisällä, enkä oikein tykkää siitä, että #content osoittaa vaihtelevasti eri elementteihin.  Mitä jos kaikilla elementeillä olisi omat id:t, ja hyppylinkkiä säädettäisiin osoittamaan oikeaan tähän tyyliin:
```

<?php
  $contentJumpId = 'content';
  if (!empty($this->layout()->finnaMainHeader)) {
    $contentJumpId = 'finna-main-header';
  } elseif (!empty($this->layout()->finnaMainTabs)) {
    $contentJumpId = 'finna-main-tabs';
  }
?>
...
        <a class="sr-only sr-only-focusable" href="#<?=$contentJumpId?>"><?=$this->transEsc('Skip to content') // skip to content ?></a>

```

2021-10-22 08:44 UTC, EreMaijala commented on themes/finna2/templates/layout/layout.phtml
> +        <?php if (empty($this->layout()->finnaMainHeader)): ?>
Sisennykset kuntoon

2021-10-26 12:52 UTC, halanikkola commented
Hyvä idea. Juttelin asiasta Pasin kanssa ja päätettiin mennä tuolla sun ehdotuksella. Nimesin noita elementtejä vähän vähemmän huomiota herättävämmin, näyttävät urlissa hieman siistimmältä.

2021-10-29 11:21 UTC, EreMaijala approved these changes

2021-10-29 11:22 UTC, merged