[ALLI-6430] Videojs airplay, chrome and vod changes
NatLibFi/NDL-VuFind2 pull request #2138
Opened 2021-10-13 10:34 UTC by LuomaJuha

2021-10-13 12:51 UTC, LuomaJuha commented
Waiting for chromecast testing.

2021-11-16 13:49 UTC, pasitiis reviewed
AirPlay näytti toimivan (testattu Safari). Vodia ja Chromecastia en saanut toimimaan omassa kehitysympäristössä (luultavasti johtuu omista verkkoasetuksista)

2021-12-07 08:30 UTC, pasitiis commented on themes/finna2/templates/Helpers/videojs-translations.phtml
> +                'Open chromecast menu' => 'Open chromecast menu',
Chromecast isolla alkukirjaimella?

2022-01-05 08:57 UTC, EreMaijala commented
@pasitiis Jos tämä on ok puolestasi, niin laita approved review.

2022-01-10 12:10 UTC, pasitiis approved these changes

2022-01-19 13:16 UTC, EreMaijala requested changes
Asetukset pitää varmaan laittaa datasources.ini:in. Ei voida olettaa, että on vain yksi yhteinen VOD-palvelu kaikille.

2022-01-19 13:16 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrForward.php
> +        if (strpos($_SERVER['HTTP_HOST'], "finna-pre") !== false) {
Ei voi testata näin. Joku asetus tms. ennemmin, mutta miksi edes tarvitaan kaksi URLia, kun testauksessa voi käyttää finna-pre-fe:llä voi määritellä toisen ja tuotannossa toisen, jos tarvitsee?

2022-01-19 13:16 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrForward.php
> +    protected function getVODUrl($path): string
Tämä nyt olettaa, että VOD-url luodaan aina samalla tavalla. Lienee kuitenkin Vimeon mekanismi eikä mikään yleismaailmallinen, vai?

Näyttää minusta siltä, että tarvitaan jonkinlaiset VOD-providerit vähän samaan tyyliin kuin kansikuvissa tai verkkomaksamisessa, jotta provider-kohtainen toiminnallisuus saadaan eristettyä.

2022-01-19 13:16 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrForward.php
> +        $isChrome = stripos($_SERVER['HTTP_USER_AGENT'], 'Chrome') !== false;
Tässä sama juttu kuin yllä.

2022-01-19 13:17 UTC, EreMaijala commented
Ylläolevassa pohjalla siis ajatus siitä, että joku muukin voi haluta joskus striimata jotain, ja että SolrForward ei ole korvamerkitty Kaville.

2022-01-25 08:12 UTC, pasitiis commented
Mietin pitäisikö tässä yhteydessä päivittää myös video.js-kirjasto uusimpaan versioon (v7.17.0)? Ainakin streaming-kirjastoihin on tullut korjauksia/päivityksiä.

2022-01-27 12:26 UTC, LuomaJuha commented
Tuunailenpas vähän yleismallikkaamman luokan hoitelemaan noita.

2022-03-16 09:50 UTC, EreMaijala requested changes

2022-03-16 09:50 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/Feature/SolrCommonFinnaTrait.php
> + * Copyright (C) The National Library 2022.
2019-2022.

2022-03-16 09:50 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrForward.php
> +        if (!($handler = $this->videoHandler->getHandler($source))) {
Pitäisi tarkistaa, ettei videoHandler ole null

2022-03-16 09:50 UTC, EreMaijala commented on module/Finna/src/Finna/Video/Handler/AbstractBaseFactory.php
> +<?php
Tätä ei tarvita, kun konstruktorilla ei ole parametreja, vaan voi käyttää Laminas'n InvokableFactorya.

2022-03-16 09:50 UTC, EreMaijala commented on module/Finna/src/Finna/Video/Handler/AbstractBase.php
> +    public function init(array $config): void
Onko mitään syytä, ettei $source voisi olla myös init:n parametri? Ei tarvitsisi kahta kutsua.

2022-03-16 09:50 UTC, EreMaijala commented on module/Finna/src/Finna/Video/Video.php
> +    public function getHandler($source): ?Handler\AbstractBase
parametrille tyyppi kaikkiin metodeihin

2022-03-16 11:16 UTC, LuomaJuha commented on module/Finna/src/Finna/Video/Handler/AbstractBase.php
> +    public function init(array $config): void
Ei taida olla muuta syytä kuin omat aivot. Joten yhdistän!

2022-03-21 14:39 UTC, LuomaJuha commented
@EreMaijala Tuunattu!

2022-03-24 13:29 UTC, EreMaijala approved these changes

2022-03-24 13:32 UTC, merged