[ALLI-7073] Feedtabs improvement
NatLibFi/NDL-VuFind2 pull request #2145
Opened 2021-10-25 12:42 UTC by LuomaJuha

Lazy-load images, save tab to url fragment. Small style tuning, use proper anchors. Switch code from jquery to js.

Test with 2 feedtabs. Rss.ini can be fetched from vaski.

`

<? $this->headTitle(''); $this->content()->setHeading(''); ?>

<br><br>
<div class="row">
    <div class="col-xs-12">
<p>Voit selata tapahtumia eri aihepiirien mukaan. Oman kirjastosi tapahtumat näet toimipisteen sivulla. </P>
<?=$this->feedTabs(['title' => 'Tapahtumaotsikko_kaikki_tapahtumat', 'ids' => ['Valilehti_1_kaikki' => 'kaikki_tapahtumat_kirjallisuus', 'Valilehti_2_kaikki' => 'kaikki_tapahtumat_esitys', 'Valilehti_3_kaikki' => 'kaikki_tapahtumat_muu_tapahtuma', 'Valilehti_4_kaikki' => 'kaikki_tapahtumat_nayttely']])?>

</div>
</div>

<div class="row">
    <div class="col-xs-12">
<p>Voit selata tapahtumia eri aihepiirien mukaan. Oman kirjastosi tapahtumat näet toimipisteen sivulla. </P>
<?=$this->feedTabs(['title' => 'Juutestivaan', 'ids' => ['Valilehti_1_kaikki' => 'vinkit-nuoret', 'Valilehti_2_kaikki' => 'nuortenvinkkinosto_kirjat', 'Valilehti_3_kaikki' => 'nuortenvinkkinosto_elokuvat', 'Valilehti_4_kaikki' => 'nuortenvinkkinosto_pelit']])?>

</div>
</div>

`

2021-10-27 07:33 UTC, pasitiis approved these changes
Tarkastelin yleistä toimivuutta. Näytti toimivan ainakin etusivulle upotetussa välilehdessä. Ehkä olisin palastellut tyylimuutokset omaan PR:ään.

2021-10-29 11:43 UTC, EreMaijala requested changes

2021-10-29 11:43 UTC, EreMaijala commented on themes/finna2/js/finna-feed-tabs.js
> +    _.allowHashchange = false;
Laittaisin ton nimeksi `allowHashChange` isolla C:llä.

2021-10-29 11:43 UTC, EreMaijala commented on themes/finna2/js/finna-feed-tabs.js
> +  function getHashWithoutHashTag() {
Olisko esim. getTabFromLocationHash käyttötarkoitusta kuvaavampi?

2021-10-29 11:43 UTC, EreMaijala commented on themes/finna2/js/finna-feed-tabs.js
> +    // TODO: remove jquery version of the init
Mihin tämä viittaa ja miksi se on TODO?

2021-10-29 11:43 UTC, EreMaijala commented on themes/finna2/js/finna-feed.js
> +  function processLoadFeed(holder, params, callback) {
`callback` ei kerro mitään. Missä tilanteessa kutsutaan? Sen pitäisi määrittää nimi tyyliin onComplete..

2021-10-29 11:43 UTC, EreMaijala commented on themes/finna2/js/finna-feed.js
> +  function loadFeed(holder, callback) {
Sama kuin yllä, `callback` nimenä huono.

2021-10-29 11:43 UTC, EreMaijala commented on themes/finna2/js/finna-feed-tabs.js
> +    container.classList.add('inited');
Jostain syystä 'inited' häiritsee minua. Voisiko vaihtaa 'init-done':ksI tms?

2021-11-11 07:44 UTC, EreMaijala approved these changes

2021-11-11 07:47 UTC, merged