[ALLI-7195] Fix missing pdf links from result-online-urls
NatLibFi/NDL-VuFind2 pull request #2148
Opened 2021-10-26 09:48 UTC by LuomaJuha

Shouldn't they be still shown as they are not images but rather converted images.

test:

http://localhost/vufind/Search/Results?lookfor=id%3A%28etk.10024_129049+OR+etk.10024_129412+OR+etk.10024_129423+OR+etk.10024_131469%29&type=AllFields&dfApplied=1&limit=20

2021-10-29 12:48 UTC, EreMaijala requested changes

2021-10-29 12:48 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/result-online-urls.phtml
> +                && strcasecmp(pathinfo($url['url'], PATHINFO_EXTENSION), 'pdf') !== 0
Pitäisi tarkistaa, ettei `$images[$url['url']]]['pdf']` ole true. Voi olla vaikka minkä muotoisia PDF-linkkejä, jolloin päätteen tarkistaminen ei riitä.

2021-11-01 08:31 UTC, LuomaJuha commented
@EreMaijala Laitoin vertailun codeccia vastaan noihin result online urls juttuihin.

2021-11-05 12:36 UTC, EreMaijala requested changes

2021-11-05 12:36 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/result-online-urls.phtml
> +              if (isset($images[$url['url']]) && !empty($url['codec']) && $url['codec'] !== 'pdf') {
En ole ihan varma, oliko tuo tarkoituksellista, että codec on oltava määriteltynä, jotta linkin voi ohittaa. Jos ei, nin codec-tarkistusta voisi lyhentää molemmissa kohdissa jättämällä empty-tarkistuksen pois ja käyttämällä null coalescingia: `($url['codec'] ?? '') !== 'pdf'`

2021-11-05 12:36 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/result-online-urls.phtml
> +                if (!empty($url['codec']) && $url['codec'] !== 'pdf') {
Yksinkertaista kuten yllä ja laita samaan iffiin.

2021-11-08 08:04 UTC, LuomaJuha commented on themes/finna2/templates/RecordDriver/DefaultRecord/result-online-urls.phtml
> +              if (isset($images[$url['url']]) && !empty($url['codec']) && $url['codec'] !== 'pdf') {
Ne menee resolveurltype kautta, näköjään codeccia ei aina ole joten tuo on parempi. Muutettu

2021-11-10 15:04 UTC, EreMaijala approved these changes

2021-11-10 15:05 UTC, merged