[ALLI-7209] Change autocomplete.js to select2.js
NatLibFi/NDL-VuFind2 pull request #2153
Opened 2021-10-28 11:11 UTC by LuomaJuha

Testpage: http://localhost/vufind/OrganisationInfo/Home?id=Satakirjastot#85525

2021-10-28 12:17 UTC, pasitiis approved these changes

2021-10-29 11:52 UTC, EreMaijala commented
Muistuttaisiko joku minulle, miksei tässä käytetä select2:n tyylistä valintakomponenttia? Tuohan ei kuitenkaan ole mikään varsinainen hakukenttä, jossa voisi laittaa osia jostain ja se hakisi siitä, jolloin autocomplete on toiminnaltaan väärän tyyppinen kenttä.

2021-10-29 12:02 UTC, LuomaJuha commented
Se on toki vaihtoehto. Pitääpi olla tarkkana sen saavutettavuuden kanssa sitten. Ja näyttäisi olevan jopa ariat niissäkin

2021-10-29 12:03 UTC, EreMaijala commented
Joo, ja siis kyllähän tämä toimii paremmin kuin vanha, että sikäli voidaan mennä tällä nyt. Ihmettelin vaan (taas kerran).

2021-10-29 12:06 UTC, LuomaJuha commented
Kyl mie voin sen vaihtaa vielä! eipä siinä kauaa mene :)

2021-10-29 12:08 UTC, EreMaijala requested changes

2021-10-29 12:08 UTC, EreMaijala commented on themes/finna2/js/finna-organisation-info-page.js
> +          return a > b ? 1 : -1;
Tarviiko tätä callbackia ollenkaan?

2021-10-29 12:10 UTC, EreMaijala commented
@LuomaJuha Ookei, no kyllä se passaa. :)

2021-11-01 08:16 UTC, LuomaJuha commented
@EreMaijala nyt o laitettu select2 js palikka tuohon.

2021-11-01 11:38 UTC, pasitiis commented
Select2 toimii paremmin, joten vaihdetaan vaan.

2021-11-05 12:21 UTC, EreMaijala requested changes
Mulla ei ainakaan toimi valinta näppäimistöllä (Firefox). Enterin painaminen taas lataa sivun uudelleen.

2021-11-05 12:21 UTC, EreMaijala commented on themes/finna2/js/finna-organisation-info-page.js
> +        option.innerHTML = el.name;
Jos vaikka tekisi näistä tekstinodet, ettei tule escapeamatonta..

2021-11-05 12:21 UTC, EreMaijala commented on themes/finna2/templates/organisationinfo/map-information.phtml
> +          <select id="office-search">
sisennykset

2021-11-05 16:01 UTC, pasitiis commented
Mulla  myös ongelmia valita toimipiste näppämistöllä ja myös häikkää focuksen kanssa (Firefox/Mac).

2021-11-08 07:48 UTC, LuomaJuha commented on themes/finna2/js/finna-organisation-info-page.js
> +        option.innerHTML = el.name;
tehty ja encodattu hash vielä kaupan päälle.

2021-11-08 14:58 UTC, EreMaijala approved these changes

2021-11-08 14:58 UTC, pasitiis approved these changes

2021-11-08 14:59 UTC, merged