[ALLI-7173] AWS: allow excluding of pick up location depending on the hold type
NatLibFi/NDL-VuFind2 pull request #2155
Opened 2021-10-29 10:06 UTC by LuomaJuha

Allows to block individual units or organisations depending on the hold type. Bc for old setting.

2021-10-29 12:44 UTC, EreMaijala requested changes

2021-10-29 12:44 UTC, EreMaijala commented on module/Finna/src/Finna/ILS/Driver/AxiellWebServices.php
> +    protected function isUnitPickUpBlocked($compare, $holdType, $unitType): bool
Parametreille tyypit.

2021-10-29 12:44 UTC, EreMaijala commented on module/Finna/src/Finna/ILS/Driver/AxiellWebServices.php
> +                    if (count($exploded) > 0) {
Eikö tämä ole aina true?

2021-10-29 12:44 UTC, EreMaijala commented on local/config/finna/AxiellWebServices.ini.sample
> +;pickUpLocationBlockList['regional'] = 'id=1:1.001:7.115:12.160'
Ei varmaan ole mitenkään välttämätöntä tulla toimeen yhdellä asetuksella? Voisi tehdä selkeämmäksi, jos olisi (olemassaolevaa asetusta mukaillen esim.

```
; Normal holds:
excludeOrganisationsFromNormalHoldPickUp = "1:3"
excludeLocationsFromNormalHoldPickUp = "1.001:7.115"
; Regional holds:
excludeOrganisationsFromRegionalHoldPickUp = "1:3"
excludeLocationsFromRegionalHoldPickUp = "1.001:7.115"

```

2021-10-29 12:44 UTC, EreMaijala commented on module/Finna/src/Finna/ILS/Driver/AxiellWebServices.php
> +        // Bc for older setting
Parempi muokata vanha asetus sitten täyttämään uudet member-muuttujat.

2021-10-29 12:44 UTC, EreMaijala commented on module/Finna/src/Finna/ILS/Driver/AxiellWebServices.php
> +    protected function isUnitPickUpBlocked($compare, $holdType, $unitType): bool
.. jos on ylipäänsä tarpeellinen metodi, jos asetukset jaetaan useampaan erilliseen. Vähän ehkä sekava, kun tekee useita eri asioita.

2021-11-01 08:33 UTC, LuomaJuha commented on local/config/finna/AxiellWebServices.ini.sample
> +;pickUpLocationBlockList['regional'] = 'id=1:1.001:7.115:12.160'
Jooh, yritin tiivistää mut onhan tuo "vähän" selkeämpää. Muuttelen >.

2021-11-01 10:52 UTC, LuomaJuha commented on module/Finna/src/Finna/ILS/Driver/AxiellWebServices.php
> +        // Bc for older setting
Se on kyllä huomioitu!

2021-11-05 12:09 UTC, EreMaijala approved these changes

2021-11-05 12:09 UTC, merged