[ALLI-6947] Add descriptive label for collection search form
NatLibFi/NDL-VuFind2 pull request #2158
Opened 2021-10-29 12:38 UTC by halanikkola

2021-11-05 13:33 UTC, EreMaijala requested changes

2021-11-05 13:33 UTC, EreMaijala commented on themes/finna2/templates/RecordTab/collectionlist.phtml
> +          <label for="keywordFilter_lookfor"" class="sr-only" hidden=""><?=$this->transEsc("Find")?></label>
Tupla `""`, `hidden` mieluummin ilman arvoa. Onko jokin syy olla käyttämättä aria-label -attribuuttia input-kentässä (muu kuin että tätä on käytetty muualla)?

2021-11-10 12:59 UTC, halanikkola commented on themes/finna2/templates/RecordTab/collectionlist.phtml
> +          <label for="keywordFilter_lookfor"" class="sr-only" hidden=""><?=$this->transEsc("Find")?></label>
Mennään aria-labelilla, se on hyvä tähän.

2021-11-16 14:04 UTC, EreMaijala requested changes

2021-11-16 14:04 UTC, EreMaijala commented on themes/finna2/templates/RecordTab/collectionlist.phtml
> +          <input id="keywordFilter_lookfor" type="text" name="lookfor" aria-label="<?=$this->transEsc('Search from collection')?>" placeholder="<?=$this->transEsc('Search from collection')?>" value="
Attribuuteille pitäisi käyttää transEscAttr-metodia (voisi korjata tuon placeholder-attribuutin samalla).

2021-11-18 14:01 UTC, EreMaijala approved these changes

2021-11-18 14:01 UTC, merged