[ALLI-7205] QDC remove image links from online links section
NatLibFi/NDL-VuFind2 pull request #2178
Opened 2021-11-17 09:39 UTC by LuomaJuha

2021-11-17 11:45 UTC, EreMaijala requested changes

2021-11-17 11:45 UTC, EreMaijala commented on module/Finna/src/Finna/View/Helper/Root/Record.php
> +    public function filterImageURLs($urls)
Tälle parempi paikka olisi varmaan record-helpperi.

2021-11-19 11:35 UTC, EreMaijala requested changes
`$otherUrls`:n voisi suodattaa heti siinä kun se on tehty vaikka $displayUrls-taulukkoon, jonka saa sitten suoraan foreach:iin, kun näytetään.

2021-11-19 11:35 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/SolrQdc/core.phtml
> +  $hasOnlineURLs = count($this->record($this->driver)->filterImageURLs(
Mieluummin `!empty` kuin `count`, jos tarvitaan vain tieto, onko jotain.

2022-01-31 13:51 UTC, LuomaJuha commented
Teen tän eri tavalla.

2022-01-31 13:51 UTC, closed without merging