[ALLI-7232] LIDO add documents as downloadable representations
NatLibFi/NDL-VuFind2 pull request #2183
Opened 2021-11-18 14:26 UTC by LuomaJuha

Clean up the code. Parse words have been removed as it sounds pretty harsh.

2021-11-24 07:45 UTC, pasitiis commented
Lisää lataus-ikoneihin aria-hidden="true".

<i class="fa fa-download"  aria-hidden="true"></i>

Mua hieman hämää että suluissa tiedostotyypiksi ilmoitetaan docx tai xlsx, vaikka ainakin testiaineisto on doc/xls-muodossa (tämä on metadatan ongelma). Melkein jättäisin pois suluissa olevan tiedostotyypin näyttämisen.

2021-11-24 09:10 UTC, LuomaJuha commented
Jeh, tässä pitää vähän myöskin keskustella tuosta palvelimen läpi viemisestä teknisellä puolella tarkemmin.

2021-11-24 09:24 UTC, pasitiis commented
Ehkä vain luotetaan siihen että formatResourcessa tulee oikea tiedostopääte.

2021-11-25 12:47 UTC, pasitiis commented
Onko jossain testitietuetta jossa olisi <resourceDescription type="displayLink"> -kentään laitettu kuvaus?

2021-12-28 08:55 UTC, LuomaJuha commented
Erottelen vielä vähän tästä

2022-01-19 08:34 UTC, pasitiis approved these changes

2022-01-19 12:36 UTC, EreMaijala requested changes

2022-01-19 12:36 UTC, EreMaijala commented on local/languages/finna/en-gb.ini
> +download_file_with_type = "Download %%type%%-file"
Englanninkielisessä ei väliviivaa.

2022-01-19 12:36 UTC, EreMaijala commented on local/languages/finna/en-gb.ini
> +download_file_with_type = "Download %%type%%-file"
Tykkäisin ehkä muutenkin enemmän siitä, että tyyppi olisi suluissa perässä tms.

2022-01-19 12:36 UTC, EreMaijala commented on module/Finna/src/Finna/File/Loader.php
> +    protected function getMimeType(string $format): string
Kokeilitko tai kokeilisitko toimisiko `mime_content_type("foo.$format")`? Tylsä pitää itse yllä mappaustaulukkoa.

2022-01-19 12:36 UTC, EreMaijala commented on module/Finna/src/Finna/File/Loader.php
> +        $client = $this->httpService->createClient(
Tässä pitäisi varmaan tyhjätä output bufferi ja laittaa bufferointi pois päältä.

2022-01-19 12:36 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +    protected $supportedDocumentFormats = [
Onko hyvä, että on vain suppea lista vaihtoehtoja? Mietin, että pitäisikö kaikki se, mikä ei kuulu kuviin, videoihin tms. tarjota ladattavaksi?

2022-01-19 13:42 UTC, LuomaJuha commented on module/Finna/src/Finna/File/Loader.php
> +        $client = $this->httpService->createClient(
Lisätty

2022-01-19 13:43 UTC, LuomaJuha commented on module/Finna/src/Finna/File/Loader.php
> +    protected function getMimeType(string $format): string
Lisätty league plugari

2022-01-19 13:43 UTC, LuomaJuha commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +    protected $supportedDocumentFormats = [
Tehty muutos ja poistettu.

2022-01-19 13:44 UTC, LuomaJuha commented on local/languages/finna/en-gb.ini
> +download_file_with_type = "Download %%type%%-file"
Laitettu käyttämään Download the file käännösavainta ja suluissa sitten ext

2022-01-19 14:10 UTC, EreMaijala approved these changes

2022-01-19 14:10 UTC, merged