[ALLI-7281] Sort organisation list in organisation info page
NatLibFi/NDL-VuFind2 pull request #2190
Opened 2021-11-30 10:06 UTC by rajaro

2021-11-30 14:36 UTC, EreMaijala requested changes

2021-11-30 14:36 UTC, EreMaijala commented on themes/finna2/js/finna-organisation-info-page.js
> +            return a.text > b.text ? 1 : -1;
Tässä olisi varmaan parempi käyttää String:n localeCompare-metodia.

2021-11-30 14:37 UTC, EreMaijala commented on themes/finna2/js/finna-organisation-info-page.js
> +            return a.text > b.text ? 1 : -1;
Vai olisiko? Joka tapauksessa case-insensitiivinen vertailu olisi järkevä.

2021-12-01 07:54 UTC, EreMaijala commented on themes/finna2/js/finna-organisation-info-page.js
> +            return a.text > b.text ? 1 : -1;
Nyt kun mietin tätä vielä, niin sorttauksen voisi tehdä palvelinpuolella Collator:lla (ks. esim. about_finna_sites.phtml).

2021-12-01 14:02 UTC, rajaro commented on themes/finna2/js/finna-organisation-info-page.js
> +            return a.text > b.text ? 1 : -1;
Hm, taitaakin sorttaus olla palvelimella, mutta ton JS objektin organisationList järkkä sitte vähä omansa

2021-12-08 13:36 UTC, EreMaijala commented on themes/finna2/js/finna-organisation-info-page.js
> +            return a.text > b.text ? 1 : -1;
Tarviiko se sortterin, joka vain säilyttää olemassaolevan järjestyksen?

2021-12-08 16:04 UTC, rajaro commented on themes/finna2/js/finna-organisation-info-page.js
> +            return a.text > b.text ? 1 : -1;
Laitoinki nyt niin, että annetaan initSearch:ille suoraan toi palvelimelta tuleva lista (sama tapahtuu organisation info widgetissä olevassa toimipistelistassa) niin ei tartte sorttausta.

2021-12-17 11:19 UTC, EreMaijala commented on themes/finna2/js/finna-organisation-info-page.js
>      var count = Object.keys(organisationList).length;
Tässä pitäisi varmaan myös olla `list`?

2021-12-17 11:52 UTC, EreMaijala commented on themes/finna2/js/finna-organisation-info-page.js
>      var count = Object.keys(organisationList).length;
Siis rivillä 146.

2021-12-20 10:48 UTC, rajaro commented on themes/finna2/js/finna-organisation-info-page.js
>      var count = Object.keys(organisationList).length;
Jep. Muutin

2021-12-20 10:50 UTC, EreMaijala approved these changes

2021-12-20 10:52 UTC, merged