[ALLI-6824] Add extended version of music composition display.
NatLibFi/NDL-VuFind2 pull request #2206
Opened 2021-12-22 14:28 UTC by EreMaijala

Currently used only with MARC records that provide granular data.

2021-12-22 14:29 UTC, EreMaijala commented
Note: Looks like there's a mistake in the specs, and subfield e should be in () while t gets a prefix (as shown in examples).

2021-12-27 12:09 UTC, LuomaJuha requested changes
Snadi tiivistys, mut muuten toimii.

2021-12-27 12:09 UTC, LuomaJuha commented on module/Finna/src/Finna/RecordDriver/SolrMarc.php
> +                $code = $subfield['code'];
```
            foreach ($allSubfields as $subfield) {
                if (($type = $typeMap[$subfield['code']] ?? false) &&
                    ($contents = trim($subfield['data']))
                ) {
                    $items[] = compact('type', 'contents');
                }
            }
```
Tää mahtuis myös näinkin päin

2021-12-28 07:49 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrMarc.php
> +                $code = $subfield['code'];
Muutettu. Laitoin `||`, varmaan ihan ok? :)

2021-12-28 07:50 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrMarc.php
> +                $code = $subfield['code'];
Rävelsin ensin, mutta nyt pitäisi olla kunnossa.

2021-12-28 07:51 UTC, EreMaijala commented
Korjasin ylimääräisen kaksoispisteen ja puuttuvan sv-käännöksen myös. Nyt pitäisi olla kunnossa.

2021-12-28 08:51 UTC, merged