[ALLI-7218] Model viewer improvements
NatLibFi/NDL-VuFind2 pull request #2207
Opened 2021-12-28 14:19 UTC by LuomaJuha

Update dependencies to be in par. Allow exporting of glb files from the viewer. (Saves the settings).

2022-01-20 08:03 UTC, pasitiis reviewed
Testasin tällä aineistoilla. Record/museovirasto_testi.9EF05A3B3ADE8202D669D3EAC25460E8?imgid=3

- Vaihtaisin tähti-ikonin hammasrata-ikoniin (https://fontawesome.com/v4.7/icon/cog)
- "Settings"-painikkeen siirtäisin info-painikkeen jälkeen
- Piilottaisin "Settings"-painikkeen oletuksena, koska toiminoille on pieni käyttäjäryhmä (tekisin ini-asetuksen, jolla toiminnon saa näkyviin tarvittaessa jossain testinäkymässä)
- Dokumentaatio File/Material/Lights-toiminnoille (itselleni ei kaikki toiminnot avaudu)

2022-01-20 09:25 UTC, pasitiis commented
Laittaisin  Info-kohtaan tiedon, jos mallin mukana tulee valaistus ja jota katseluohjelma käyttää oletuksena. Samassa yhteydessä voisi olla yksinkertainen valinta, jolla Finnan oletusvalaituksen saa päälle.

2022-02-02 19:02 UTC, EreMaijala commented
Poista changes requested -labeli, kun valmista.

2022-02-22 13:38 UTC, pasitiis commented
Pitäisikö themes/finna2/images/p...png -tiedostot laittaa models-kansioon?

2022-03-16 10:43 UTC, LuomaJuha commented
testataan integraatiota!

2022-03-16 10:52 UTC, LuomaJuha commented
edellinen close ja open oli siis vaan kadonneen slackintegraation testausta.

2022-04-21 08:20 UTC, pasitiis approved these changes

2022-04-21 10:22 UTC, EreMaijala requested changes

2022-04-21 10:22 UTC, EreMaijala commented on local/config/finna/contentsecuritypolicy.ini.sample
> +;connect-src[] = "blob:"
Rivinvaihto puuttuu.

2022-04-21 10:22 UTC, EreMaijala commented on local/languages/finna/en-gb.ini
> +model_add light = "Add light"
Muotoon `model_add_light`

2022-04-21 10:22 UTC, EreMaijala commented on local/languages/finna/en-gb.ini
> +model_desktop help = "<b>Rotating</b><br/>You can rotate the model by dragging the mouse in the desired direction while holding the primary mouse button.<br/><b>Zooming in and out</b><br/>You can zoo
Sama tässä ja muissakin, koodimuotoisiin ei välilyöntejä vaan alaviivat.

HTML:ää sisältävissä teksteissä käytettävä _html -päätettä.

2022-04-21 10:22 UTC, EreMaijala commented on local/languages/finna/en-gb.ini
> +model_export .glb = "Export glb-file"
Englanniksi ei väliviivaa.

2022-04-21 10:22 UTC, EreMaijala commented on local/languages/finna/en-gb.ini
> +model_directionallight = "Directional light"
`model_directional_light`?

2022-04-21 10:22 UTC, EreMaijala commented on local/languages/finna/en-gb.ini
> +model_envmapintensity = "Light from environment"
`model_env_map_intensity`?

2022-04-21 10:22 UTC, EreMaijala commented on themes/finna2/js/finna-model-viewer.js
> +                console.log(this);
Pois

2022-04-21 10:22 UTC, EreMaijala commented on themes/finna2/js/finna-model-viewer.js
> +    const ref = this;
Voisiko käyttää `ref`:n sijaan `self`, joka on yleinen käytäntö, vai onko siihen erityinen syy?

2022-04-21 10:22 UTC, EreMaijala commented on themes/finna2/js/finna-object-helper.js
> +}
Rivinvaihto puuttuu

2022-04-21 10:22 UTC, EreMaijala commented on themes/finna2/js/finna-object-helper.js
> +    return this.translate(this.escape(s));
Eikö tässä ole kutsut väärin päin?

2022-04-21 10:22 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/record-image-paginator.phtml
>          $tmp = [
`$tmp` on hirveän huono nimi, kuulostaa niin väliaikaiselta. Voisi jotain parempaa laittaa.

2022-04-21 10:22 UTC, EreMaijala commented on themes/finna2/js/finna-object-helper.js
> +/* exported ObjectHelper */
Mulla on pieni ongelma tän kanssa, kun toisaalta ObjectHelper kuulostaa hyvin geneeriseltä, ja tässä on toimintoja, joista voisi olla yleisestikin hyötyä, mutta toisaalta tämä on ihan tiettyä tarkoitusta varten. Ainakin nimen pitäisi olla tarkempi, tai sitten koko homma pitäisi olla pilkottu geneeriseen ja yhden tarkoituksen osiin.

2022-04-22 07:41 UTC, LuomaJuha commented on themes/finna2/js/finna-model-viewer.js
> +    const ref = this;
ei oo erityistä syytä. Aivot vaan ajatteli ekana asiana ref:iä.

2022-05-02 08:58 UTC, EreMaijala requested changes

2022-05-02 08:58 UTC, EreMaijala commented on themes/finna2/js/finna-model-viewer.js
> +            self.scene.children.forEach((child) => {
this ja self, sekakäyttöä? Voisiko tässä metodissa käyttää vain this? Tuossa alempana on ainakin myös `            self.scene.add(cameraSave);`.

2022-05-04 06:44 UTC, EreMaijala requested changes

2022-05-04 06:44 UTC, EreMaijala commented on themes/finna2/templates/Helpers/modeljs-translations.phtml
> +echo json_encode($translations);
Sisennys kummasti?

2022-05-04 06:55 UTC, LuomaJuha commented on themes/finna2/templates/Helpers/modeljs-translations.phtml
> +echo json_encode($translations);
joo, taitaa olla!

2022-05-04 06:55 UTC, LuomaJuha commented on themes/finna2/templates/Helpers/modeljs-translations.phtml
> +echo json_encode($translations);
joo, taitaa olla!

2022-05-04 11:37 UTC, EreMaijala approved these changes

2022-05-04 11:38 UTC, merged