[ALLI-7183] Fix displaying record author in holds/loans
NatLibFi/NDL-VuFind2 pull request #2213
Opened 2022-01-07 14:41 UTC by rajaro

2022-01-19 14:54 UTC, EreMaijala requested changes

2022-01-19 14:54 UTC, EreMaijala commented on themes/finna2/templates/myresearch/helpers/record-author.phtml
> +<?php elseif (empty($authors)):?>
false-tarkistus on Missing-tietueita varten, jolloin getNonPresenterAuthors-metodia ei ole. Jos se on tyhjä taulukko, niin metodi on olemassa, mutta ei palauttanut mitään, jolloin tuo on väärä haara. Oikea ratkaisu olisi kutsua getPresenters, jos getNonPresenterAuthors palauttaa tyhjää, esim. jotenkin tähän tapaan:

```
<!-- START of: finna - myresearch/helpers/record-author.phtml -->
<?php
  $author = null;
  $authors = $record->tryMethod('getNonPresenterAuthors', [], false);
  if (!empty($authors[0])) {
    $author = $authors[0];
  } else {
    $presenters = $record->tryMethod('getPresenters', [], false);
    if (!empty($presenters['presenters'][0])) {
      $author = $presenters['presenters'][0];
    }
  }
  if (null !== $author):
?>
  <?=$this->record($record)->getAuthorityLinkElement('author', $author['name'], $author, ['authorityType' => $author['type'] ?? null])?><br/>
<?php elseif (false === $authors):?>
  <?php
    // Fallback for missing records that don't support getNonPresenterAuthors/getPresenters
    $listAuthor = $record->tryMethod('getPrimaryAuthor');
    if (!empty($listAuthor)):
  ?>
    <a href="<?=$this->record($record)->getLink('author', $listAuthor)?>"><?=$this->escapeHtml($listAuthor)?></a><br/>
  <?php endif; ?>
<?php endif; ?>
<!-- END of: finna - myresearch/helpers/record-author.phtml -->

```

2022-01-20 10:53 UTC, rajaro commented on themes/finna2/templates/myresearch/helpers/record-author.phtml
> +<?php elseif (empty($authors)):?>
jeps toimihan tuo, muutettu

2022-02-02 19:03 UTC, EreMaijala approved these changes

2022-02-02 19:03 UTC, merged