[ALLI-7278] Fix QR code display on print styles
NatLibFi/NDL-VuFind2 pull request #2215
Opened 2022-01-12 14:28 UTC by halanikkola

2022-01-20 09:16 UTC, EreMaijala requested changes
Ei mun nähdäkseni Bootstrapissa ole mitään tähän vaikuttavaa, vaan ongelma tulee siitä, että jos ei ole kuvaa, lisätään media-left:lle finna-image-paginator:ssa hidden-xs. Se piilottaa myös Finna-arvion yms. näkyvistä kapealla näytöllä, jos kuvaa ei ole. Minusta tämä vaikuttaa virhetoiminnolta, mutta @pasitiis ja @LuomaJuha voivat varmaan valottaa asiaa.

2022-01-20 11:58 UTC, pasitiis commented
On virhetoiminto että piilottaa muutakin kuin kuvan. Olisi parempi korjata kokonaisuutena tuo.

2022-01-20 12:58 UTC, pasitiis commented
Eikös tuo korjaanut sillä että poistetaan kokonaan finna-image-paginatorin asettama asetus hidden-xs media-leftille (en nopeasti keksi syytä sen käytölle)? Joka tapauksessa finna-image-paginatoria pitäisi tarkastella tässä kohtaa.

2022-01-20 14:22 UTC, EreMaijala commented
@pasitiis Kyllä.

2022-01-20 14:40 UTC, LuomaJuha commented
Finna-image-paginator.js rivi 565 voinee poistaa.

2022-01-21 09:09 UTC, EreMaijala approved these changes

2022-01-21 09:11 UTC, merged