[ALLI-7327] Fix adding DOI to OpenURL
NatLibFi/NDL-VuFind2 pull request #2234
Opened 2022-02-02 10:34 UTC by rajaro

Lisätään DOI oikeassa formaatissa eli `rft_id=info:doi/xxx`.
Tietueessa saattaa olla jo rft_id:n arvona pmid, jota ei haluta yliajaa.
SFX:ssä muotoa ` rft_id[0]=x&rft_id[1]=y ` ei tueta, joten url muutetaan muotoon ` rft_id=x&rft_id=y `

2022-02-02 19:57 UTC, EreMaijala requested changes

2022-02-02 19:57 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/Feature/FinnaRecordTrait.php
> +            $doi = 'info:doi/' . $doi;
Pitäisikö tässä tarkistaa, ettei $doi:ssa ole ennestään tuota `info:doi/` -prefiksiä tai `doi:`-prefiksiä?

2022-02-02 19:57 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/Feature/FinnaRecordTrait.php
> +                $params['rft_id'] = [$params['rft_id'], $doi];
Tässä pitäisi varautua siihen, että `$params['rft_id']` on jo array. Koko homman voisi tehdä tähän tyyliin:

```
$params['rft_id'] = (array)($params['rft_id'] ?? []);
$params['rft_id'][] = $doi;
```

2022-02-02 19:57 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/Primo.php
> +        $url = preg_replace('/%5B([0-9]?)%5D=/', '=', $url);
Tämä pitäisi tehdä muillakin kuin Primolla. Mutta koska OpenURL:ssa ei tuota PHP:n array-syntaksia käytetä koskaan, niin muutos pitäisi tehdä yläjuoksulle DefaultRecord:n getOpenUrl-metodiin. Mieluummin ehkä myös kokoaisin url:n ilman http_build_query-metodia, jotta sitä ei tarvitse jälkikäteen korjata.

2022-10-12 10:57 UTC, rajaro commented on module/Finna/src/Finna/RecordDriver/Primo.php
> +        $url = preg_replace('/%5B([0-9]?)%5D=/', '=', $url);
[yläjuoksun muutokset](https://github.com/vufind-org/vufind/commit/9aff1152e113ab6e26dafceb6d74beac12e3d040)

2022-10-12 12:37 UTC, EreMaijala approved these changes

2022-10-12 12:37 UTC, merged