[ALLI-7360] Adjust image popup descriptions and indentations
NatLibFi/NDL-VuFind2 pull request #2239
Opened 2022-02-04 14:08 UTC by LuomaJuha

2022-02-08 11:17 UTC, EreMaijala requested changes

2022-02-08 11:17 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/record-image-popup-information.phtml
> +      <?php if ($recordType == 'marc'): ?>
Laita tähänkin vertailun muutos, joka on tossa ylempänä lido:n kohdalla.

2022-02-08 12:28 UTC, LuomaJuha commented
@EreMaijala done

2022-02-16 08:34 UTC, EreMaijala approved these changes

2022-02-16 08:35 UTC, merged