[ALLI-7274] Adjust highresolution image download steps
NatLibFi/NDL-VuFind2 pull request #2240
Opened 2022-02-07 11:49 UTC by LuomaJuha

Offer original images from QDC records as a downloadable objects. Small change.

2022-02-08 11:24 UTC, EreMaijala requested changes

2022-02-08 11:24 UTC, EreMaijala commented on module/Finna/config/module.config.php
> -    'Cover/Download',
Jättäisin tämän routen siltä varalta, että sitä käytetään jossain paikallisesti muokatussa templatessa. Action voi sitten forward:ata suoraan Record-controllerin DownloadFile:en.

Vaihtoehtoisesti pitäisi tarkistaa kaikki näkymät, ettei tuota ole käytetty.

2022-02-08 11:24 UTC, EreMaijala commented on module/Finna/src/Finna/Controller/RecordController.php
> +            case 'highresolution':
Tämä voisi olla vaikka highresimg tms. niin erottaa vaikka videosta tarvittaessa.

2022-02-08 11:24 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/image-download.phtml
> +                            <li><a download="<?=$downloadName?>" href="<?=$this->escapeHtmlAttr($this->url('record-downloadfile', [], ['query' => $info['params']]))?>" rel="nofollow"> <?=$this->trans
Escapet puuttuu: `$dimensions` ja `$info['format']`

2022-02-08 12:08 UTC, LuomaJuha commented on module/Finna/config/module.config.php
> -    'Cover/Download',
voin ajaa läpi grepin

2022-02-08 12:28 UTC, LuomaJuha commented
@EreMaijala done

2022-02-08 13:46 UTC, LuomaJuha commented on module/Finna/config/module.config.php
> -    'Cover/Download',
Mie otin sen pois nytkun tein tuon paremman routen siihen.

2022-02-14 12:28 UTC, EreMaijala approved these changes

2022-02-14 12:28 UTC, merged