[ALLI-7355] AWS: allow startDate setting in extraHoldFields
NatLibFi/NDL-VuFind2 pull request #2241
Opened 2022-02-07 12:38 UTC by LuomaJuha

2022-02-07 12:52 UTC, LuomaJuha commented
Small question about date vs. gmdate. Trying to find out the answer

2022-02-08 11:14 UTC, EreMaijala requested changes

2022-02-08 11:14 UTC, EreMaijala commented on module/Finna/src/Finna/ILS/Driver/AxiellWebServices.php
> +            $validFromDate = !empty($holdDetails['startDate'])
Käytä startDateTS:ää, niin menee yksinkertaisemmin, kuten requiredByTS updateHolds:ssa. Voisi saman tien vaihtaa requiredBy:n myös tosta alta.

2022-02-08 11:45 UTC, LuomaJuha commented on module/Finna/src/Finna/ILS/Driver/AxiellWebServices.php
> +            $validFromDate = !empty($holdDetails['startDate'])
Jepulis!

2022-02-08 11:51 UTC, LuomaJuha commented
@EreMaijala timestampit otettu käyttöön

2022-02-08 11:55 UTC, LuomaJuha commented
Meinas jäädä pari oleellista asiaa uupumaan...

2022-02-08 12:00 UTC, EreMaijala approved these changes

2022-02-08 12:53 UTC, merged