Submit search on new tab with middle mouse button
NatLibFi/NDL-VuFind2 pull request #2244
Opened 2022-02-10 13:55 UTC by LuomaJuha

Just a small thing

2022-02-10 14:06 UTC, LuomaJuha commented
@pasitiis Jos sulla herää tähän jotain käytettävyyden takia tai muuta niin merkkaan sut tarkastajaks.

2022-02-10 14:29 UTC, EreMaijala requested changes

2022-02-10 14:29 UTC, EreMaijala commented on themes/finna2/js/finna-layout.js
> +    var submitButton = searchForm.querySelector('button[type="submit"]');
searchForm:lle tarvitaan null-tarkistus

2022-02-10 14:29 UTC, pasitiis commented
Kaiketi ominaisuus on ihan hyödyllinen, tosin mulla ei nyt ole hiirtä, jossa olisi toimiva keskipainike. Mä oon tottunut avaamaan linkin Macillä uuteen välilehteen Cmd + hiiren ykköspainike.

2022-02-10 14:40 UTC, pasitiis commented
Testasin vanhalla Microsoftin hiirellä. Macissa Chromella ja Safarilla toimii mutta ei Firefoxilla (Firefoxilla kyllä toimii linkit muuten keskipainikkeesta, mutta ei tuosta hakupainikkeesta)

2022-02-16 08:46 UTC, LuomaJuha commented
@pasitiis nyt on vähän muokattu tätä.

2022-02-16 14:27 UTC, pasitiis commented
Nyt näytti toimivan Firefox/Mac.

2022-02-16 14:28 UTC, pasitiis approved these changes

2022-02-16 14:30 UTC, EreMaijala approved these changes

2022-02-16 14:31 UTC, merged