Layout.phtml cleaning
NatLibFi/NDL-VuFind2 pull request #2247
Opened 2022-02-17 07:36 UTC by LuomaJuha

2022-02-17 07:43 UTC, EreMaijala requested changes
Ei kosketa niihin kohtiin, jotka eivät ole Finnassa muokattuja. Vaikeuttaa vertailua yläjuoksun versioon. Sinne voi toki tarjota siivousta. Tai vielä parempaa, sinne voisi tarjota layout.phtml:n pilkkomista kivoihin palasiin. Jos saisi sen peräti sellaiseksi, että siellä includataan sopivissa kohdissa juttuja, jotka voisi sitten meidän teemassa lisätä niin, ettei tartte koskea koko layout.phtml:ään, niin se se vasta olisikin hienoa, mutta voi mennä vähän hankalaksi.

2022-02-17 08:54 UTC, LuomaJuha commented
@EreMaijala Laitoin kanssa yläjuoksulle noita samoja kohtia siivoutumaan.

2022-03-04 07:58 UTC, EreMaijala commented
Ok. Laitan holdiin kunnes saadaan muutokset yläjuoksulta.

2022-06-07 12:07 UTC, EreMaijala approved these changes

2022-06-07 12:07 UTC, merged