[ALLI-7369] EAD3 Image adjustments
NatLibFi/NDL-VuFind2 pull request #2254
Opened 2022-02-23 11:32 UTC by LuomaJuha

Alter the check for undisplayable format. Unify Lido and EAD3 to use the same check.
Checked that lidoFileFormatBl* was not in use any view with find + grep.

2022-02-28 11:51 UTC, EreMaijala requested changes

2022-02-28 11:51 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrEad3.php
> +     * Return an associated array with all the presentetion types.
present**a**tion

2022-02-28 11:51 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrEad3.php
> +                    $type = (string)(
Menee yhdelle riville, eikö?

2022-02-28 11:51 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrEad3.php
> +                        && false === strpos($title, 'Kuva/Aukeama')
Tämän 'Kuva/Aukeama' sijaan voisi olla joku member-array tms. jossa tällaiset määritellään.

2022-02-28 11:51 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrEad3.php
> +                    if (empty($displayImage)
Tee tämä tarkistus ensin:

```
                    // Image might be original, can not be displayed in browser.
                    if ($this->isUndisplayableFormat($format)) {

```

Kun siinä on lopussa continue, niin ei tarvitse enää tuota tarkistella enempää, vaan voit jatkaa yksinkertaisemmin, tyyliin:

```
                    // Image might be original, can not be displayed in browser.
                    if ($this->isUndisplayableFormat($format)) {
                        ...
                    }
                    
                    if (empty($displayImage) {
                        ...
                    }
```

2022-02-28 11:51 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrEad3.php
> +                        $displayImage['pdf'][$size]
Mahtunee yhdelle riville?

2022-02-28 11:51 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrEad3.php
> +                        $size = (false === $size)
Ei ketjuteta `?:` -operaattoreita.

2022-02-28 11:51 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +        if ($this->isUndisplayableFormat($format) && $type !== 'image_original') {
type-tarkistus ekaksi, se on nopeampi.

2022-03-03 09:45 UTC, LuomaJuha commented
@EreMaijala Tää on nyt tuunattu ja Piian kans käytiin tätä vähän läpi.

2022-03-04 08:52 UTC, LuomaJuha commented
@EreMaijala Apufunktion nimi vaihdettu.

2022-03-04 09:18 UTC, EreMaijala approved these changes

2022-03-04 09:19 UTC, merged