[ALLI-7345] Paytrail Payment API support and refactor online payment.
NatLibFi/NDL-VuFind2 pull request #2255
Opened 2022-02-23 14:08 UTC by EreMaijala

- Simplifies and unifies the processing of payments.
- Handles payment responses directly to simplify the AJAX handler for payment processing.
- Transactions are updated through the row object.
- Canceled or failed payment doesn't block a new attempt.
- Etc.

2022-03-01 13:34 UTC, LuomaJuha requested changes
Laitoin nyt pari mitä tosta näin. Eniten ehkä häiritsee tuolla Cpu puolella nuo kaikki muuttujat ja muut ku ne alkaa isolla kirjaimella. Pitäisköhän ne yhtenäistää muun koodin kanssa?

2022-03-01 13:34 UTC, LuomaJuha commented on module/Finna/config/module.config.php
> +            'onlinepayment_handler' => [],
Tartteisko kommentin miksi on jätetty tyhjä avain + taulu?

2022-03-01 13:34 UTC, LuomaJuha commented on module/Finna/src/Finna/OnlinePayment/Handler/Connector/Cpu/Product.php
>  // @codingStandardsIgnoreStart
Pitäisköhän näistä hankkiutua eroon?

2022-03-01 13:34 UTC, LuomaJuha commented on module/Finna/src/Finna/OnlinePayment/Handler/Connector/Cpu/Client.php
>  // @codingStandardsIgnoreStart
Pitäisköhän näistä hankkiutua eroon?

2022-03-01 13:34 UTC, LuomaJuha commented on module/Finna/src/Finna/OnlinePayment/Handler/Connector/Cpu/Payment.php
>  // @codingStandardsIgnoreStart
Pitäisköhän näistä hankkiutua eroon?

2022-03-01 13:34 UTC, LuomaJuha commented on module/Finna/src/Finna/AjaxHandler/AbstractOnlinePaymentAction.php
> +            if ($card->cat_username == $t->cat_username) {
=== ?

2022-03-01 14:07 UTC, LuomaJuha requested changes
Saakohan täs jotenkin lisättyä vanhaan tutkailuun

2022-03-01 14:07 UTC, LuomaJuha commented on module/Finna/src/Finna/Controller/FinnaOnlinePaymentControllerTrait.php
> +                    ->addErrorMessage('online_payment_in_progress');
Tää avain on poistettu ylempänä?

2022-03-01 14:07 UTC, LuomaJuha commented on module/Finna/src/Finna/OnlinePayment/Handler/Connector/TurkuPayment/TurkuPaytrailE2.php
> +    ) {
Palautustyyppi + parametrien tyypit?

2022-03-01 18:37 UTC, EreMaijala commented on module/Finna/config/module.config.php
> +            'onlinepayment_handler' => [],
Joo, kopasin VuFindin module.config.php:sta vastaavan.

2022-03-01 18:38 UTC, EreMaijala commented on module/Finna/src/Finna/OnlinePayment/Handler/Connector/Cpu/Product.php
>  // @codingStandardsIgnoreStart
Ehkä, mutta jätin nyt toistaiseksi, koska noi luokat on saatu CPU:lta enkä ole halunnut koskea niihin enempää kuin pakko, jotta on tarvittaessa helppo vertailla, jos CPU joskus tarjoaa uudempia.

2022-03-01 18:38 UTC, EreMaijala commented on module/Finna/src/Finna/AjaxHandler/AbstractOnlinePaymentAction.php
> +            if ($card->cat_username == $t->cat_username) {
Done.

2022-03-01 18:38 UTC, EreMaijala commented on module/Finna/src/Finna/Controller/FinnaOnlinePaymentControllerTrait.php
> +                    ->addErrorMessage('online_payment_in_progress');
Oli väärä avain, korjattu.

2022-03-01 18:38 UTC, EreMaijala commented on module/Finna/src/Finna/OnlinePayment/Handler/Connector/TurkuPayment/TurkuPaytrailE2.php
> +    ) {
Lisätty, myös ylempään metodiin.

2022-03-01 18:47 UTC, EreMaijala commented
Tosiaan Cpu-luokat on saatu CPU:lta, niin olen koittanut minimoida niihin tehdyt muutokset, jotta on tarvittaessa mahdollisimman helppo verrata alkuperäisiin. Toki olisi parempi, jos ne saisi asennettua Paytrailin tapaan composer:lla niin, ettei tyyliseikoilla olisi niin väliä, mutta tämä on tällaista tasapainottelua.

2022-03-02 07:13 UTC, EreMaijala commented
Ja nyt on oikeasti puskettu muutokset tänne.

2022-03-07 09:44 UTC, LuomaJuha requested changes
Kommenteista tuli pari huomiota!

2022-03-07 09:44 UTC, LuomaJuha commented on module/Finna/src/Finna/OnlinePayment/OnlinePayment.php
>   */
Voi päivittää tämänkin vuosiluvun?

2022-03-07 09:44 UTC, LuomaJuha commented on module/Finna/src/Finna/OnlinePayment/OnlinePaymentFactory.php
>              throw new \Exception('Unexpected options passed to factory.');
Kommentin vuosi.

2022-03-07 09:44 UTC, LuomaJuha commented on module/Finna/src/Finna/OnlinePayment/OnlinePaymentPostRequestTrait.php
>  <?php
Kommentin vuosi.

2022-03-07 09:44 UTC, LuomaJuha commented on module/Finna/src/Finna/OnlinePayment/OnlinePaymentPostRequestTrait.php
>   * @author   Samuli Sillanpää <samuli.sillanpaa@helsinki.fi>
Saa kreditoida!

2022-03-07 09:44 UTC, LuomaJuha commented on module/Finna/src/Finna/OnlinePayment/Handler/Paytrail.php
>   * @link     http://vufind.org/wiki/vufind2:developer_manual Wiki
Krediitti!

2022-03-07 09:44 UTC, LuomaJuha commented on module/Finna/src/Finna/OnlinePayment/Handler/TurkuPayment.php
>   * @license  http://opensource.org/licenses/gpl-2.0.php GNU General Public License
Krediitti!

2022-03-07 09:44 UTC, LuomaJuha commented on module/Finna/src/Finna/OnlinePayment/Handler/Connector/TurkuPayment/TurkuPaytrailE2.php
>   * @license  http://opensource.org/licenses/gpl-2.0.php GNU General Public License
Vuosi + krediitti!

2022-03-07 09:44 UTC, LuomaJuha commented on module/Finna/src/Finna/OnlinePayment/Handler/Connector/Paytrail/PaytrailE2.php
>   * @link     http://vufind.org/wiki/vufind2:developer_manual Wiki
Vuosi!

2022-03-07 09:44 UTC, LuomaJuha commented on module/Finna/src/Finna/ILS/Driver/Demo.php
>      public function getConfig($function, $params = null)
Vuosi?

2022-03-07 09:44 UTC, LuomaJuha commented on module/Finna/src/Finna/Db/Table/Transaction.php
>      public const STATUS_PROGRESS              = 0;
Vuosi!

2022-03-07 09:44 UTC, LuomaJuha commented on module/Finna/src/Finna/Controller/FinnaOnlinePaymentControllerTrait.php
>   * it under the terms of the GNU General Public License version 2,
Krediitti!

2022-03-07 10:49 UTC, LuomaJuha approved these changes

2022-03-07 10:52 UTC, merged