[ALLI-7386] Use result-online-urls in popup
NatLibFi/NDL-VuFind2 pull request #2257
Opened 2022-02-25 09:20 UTC by LuomaJuha

2022-02-28 11:58 UTC, EreMaijala requested changes

2022-02-28 11:58 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/result-online-urls.phtml
> +      <?php if (!in_array($context, ['popup'])): ?>
Miksei vain `if ('popup' !== $context)`?

2022-02-28 11:58 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/result-online-urls.phtml
> +        <?php if ('popup' === $context && count($renderedURLs) >= $maxLinksCount): ?>
Onko tämä tarkistus oikein? Jos maksimi on 4 ja tietueessa on 4, niin pum?

2022-03-08 11:08 UTC, pasitiis approved these changes

2022-03-08 12:01 UTC, EreMaijala requested changes

2022-03-08 12:01 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/result-online-urls.phtml
> +          $amountOfLinks = 0;
`$amountOfLinks` => `$linkCount`

2022-03-08 14:49 UTC, LuomaJuha commented on themes/finna2/templates/RecordDriver/DefaultRecord/result-online-urls.phtml
> +          $amountOfLinks = 0;
Päivitin linkcount ja maxlinkscount = maxlinkcount yhtenäisyyden vuoksi.

2022-03-09 10:32 UTC, EreMaijala approved these changes

2022-03-09 10:32 UTC, merged