[ALLI-7357] EAD3: Remove 'not digitized' text in external data tab for collection…
NatLibFi/NDL-VuFind2 pull request #2259
Opened 2022-02-25 14:41 UTC by rajaro

… and series level records

2022-03-04 07:57 UTC, EreMaijala requested changes
Ymmärsin issuesta, ettei tätä tekstiä haluta näyttää ikinä. Eli series-tarkistus on turha, eikö?

2022-03-04 07:57 UTC, EreMaijala commented on themes/finna2/templates/RecordTab/externaldata.phtml
> +<?php if (!$digitized && !($collectionOrSeries)): ?>
turhat sulut `$collectionOrSeries` ympärillä

2022-03-04 07:57 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrEad3.php
> +    }
Tämän voisi lyhentää: 

`return in_array((string)($xml->attributes()->level ?? ''), self::SERIES_LEVELS);`

2022-03-08 13:49 UTC, rajaro commented
Ymmärsin, että otetaan teksti pois sillon kun on kokoelma/sarjatason tietue, muutoin näytetään

2022-03-16 09:54 UTC, EreMaijala commented
@rajaro Joo, mutta silloin kun sisältöä ei ole, niin piti jättää koko välilehti näyttämättä. Tyhjä välilehti ei ole hyödyllinen.

2022-03-24 13:20 UTC, EreMaijala requested changes
Eikös tämä nyt edelleen näytä tyhjän tabin, jos `$data['items']` on tyhjä ja `$data['digitized']` on false eikä ole kokoelma? `$data['digitized']` ei edes voi olla true, ellei `$data['items']` sisällä jotain, jolloin tuo testi on turha. Ei tuo aiempikaan versio kyllä ole toiminut, koska `(empty($data['items']) && $data['digitized'])` ei koskaan ole true.

Eli mun nähdäkseni isActive-metodissa riittäisi tarkistus:

```
if (empty($data['items'])) {
    $this->enabled = false;
}
```

Vai enkö vain tajua jotain tilannetta?

2022-03-29 13:16 UTC, rajaro commented
joo kyllähän tuo tarkistus `empty($data['items'])` riittää. Muutettu

2022-04-01 08:11 UTC, EreMaijala approved these changes

2022-04-01 08:14 UTC, merged