[ALLI-7398] Add initial tests to SolrForward record driver
NatLibFi/NDL-VuFind2 pull request #2266
Opened 2022-03-02 15:05 UTC by LuomaJuha

Adds tests for checking presenters and production events.

2022-03-04 07:39 UTC, EreMaijala requested changes

2022-03-04 07:39 UTC, EreMaijala commented on module/Finna/tests/unit-tests/src/FinnaTest/RecordDriver/SolrForwardTest.php
> +        $record->setLazyRecordXml($fixture);
Ei tätä pitäisi tarvita mihinkään. XML luodaan raw datasta, kun kutsutaan getAllRecordsXML-metodia.

2022-03-04 07:39 UTC, EreMaijala commented on module/Finna/tests/unit-tests/src/FinnaTest/RecordDriver/SolrForwardTest.php
> +     * Test nonpresenter secondaryauthors.
nope

2022-03-04 07:39 UTC, EreMaijala commented on module/Finna/tests/unit-tests/src/FinnaTest/RecordDriver/SolrForwardTest.php
> +     * Test nonpresenter secondaryauthors.
nope

2022-03-04 08:19 UTC, LuomaJuha commented on module/Finna/tests/unit-tests/src/FinnaTest/RecordDriver/SolrForwardTest.php
> +        $record->setLazyRecordXml($fixture);
Ahaa, pitää sit koittaa et teinkö vaan asiat väärin.

2022-03-04 08:25 UTC, EreMaijala commented on module/Finna/tests/unit-tests/src/FinnaTest/RecordDriver/SolrForwardTest.php
> +        $record->setLazyRecordXml($fixture);
Jos ei se toimi, niin jossain muualla on vikaa.

2022-03-04 08:28 UTC, LuomaJuha commented on module/Finna/tests/unit-tests/src/FinnaTest/RecordDriver/SolrForwardTest.php
> +        $record->setLazyRecordXml($fixture);
ah, asetin vaan siihen avaimeks fullrecord niin lähti pelittämään.

2022-03-04 08:40 UTC, LuomaJuha commented
@EreMaijala korjailtu.

2022-03-09 10:35 UTC, EreMaijala approved these changes

2022-03-09 10:35 UTC, merged