Add support for expanding component template names
NatLibFi/NDL-VuFind2 pull request #2270
Opened 2022-03-09 12:11 UTC by aleksip

2022-03-10 18:59 UTC, EreMaijala requested changes

2022-03-10 18:59 UTC, EreMaijala commented on module/Finna/config/module.config.php
> +            'ViewResolver' => 'Finna\View\Resolver\AggregateResolverFactory',
Tässä pitäisi olla `'Finna\View\Resolver\AggregateResolver' => 'Finna\View\Resolver\AggregateResolverFactory'` ja aliases-kohdassa alempana sitten mappaus, että `'ViewResolver' => 'Finna\View\Resolver\AggregateResolver'`. Tämän jälkeen factoryssa voidaan luoda `$requestedName`. Muuten factory voi luoda jotain muuta kuin mitä pyydettiin. laminas-mvc:n factory on nähdäkseni siis pielessä..

2022-03-11 07:44 UTC, aleksip commented on module/Finna/config/module.config.php
> +            'ViewResolver' => 'Finna\View\Resolver\AggregateResolverFactory',
Totta!

2022-03-11 12:57 UTC, EreMaijala requested changes

2022-03-11 12:57 UTC, EreMaijala commented on module/Finna/src/Finna/View/Resolver/AggregateResolverFactory.php
> +        $resolver = new AggregateResolver();
Tähän vielä käyttöön `$requestedName`.

2022-03-14 07:46 UTC, EreMaijala approved these changes

2022-03-14 07:49 UTC, merged