[ALLI-6596] Relocate narrow search mobile button.
NatLibFi/NDL-VuFind2 pull request #2273
Opened 2022-03-16 09:31 UTC by pasitiis

Muutos koskee haun rajausta sekä kokoelmasivun rajauspainketta (esim. Collection/sls.%25C3%2596TA+112).

2022-03-16 10:57 UTC, EreMaijala requested changes

2022-03-16 10:57 UTC, EreMaijala commented on themes/finna2/js/finna-layout.js
> +      if ($(e.target).attr('class') !== 'fa fa-times' || 'fa fa-info-big') {
Vertailun loppuosa on pielessä, tarkistaa vain, että `'fa fa-info-big'` on "truey". Parempi olisi esim.:
`if (e.target.classList.contains('fa-times') || e.target.classList.contains('fa-info-big'))`

2022-03-16 10:57 UTC, EreMaijala commented on themes/finna2/templates/search/results.phtml
> +<?php if (($recordTotal = $this->results->getResultTotal()) > 0): ?>
$recordTotal haetaan nyt kahteen kertaan (toinen alempana). Voisi hakea ihan alussa kerran.

2022-03-16 12:12 UTC, LuomaJuha commented on themes/finna2/js/finna-layout.js
> +      if ($(e.target).attr('class') !== 'fa fa-times' || 'fa fa-info-big') {
Aijuu, on myös olemassa seuraavanlainen mahdollisuus nyt es6 avulla = 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/some
if (['fa-times', 'fa-info-big'].some(c => e.target.classList.contains(c)) {

2022-03-16 13:16 UTC, pasitiis commented on themes/finna2/js/finna-layout.js
> +      if ($(e.target).attr('class') !== 'fa fa-times' || 'fa fa-info-big') {
Tarkemmin kun ajattelee niin ei tuo tarvitse mitään verailuja jos käytetään on/off:ia.

2022-03-17 12:40 UTC, EreMaijala approved these changes

2022-03-17 12:41 UTC, merged