[ALLi-7096] Add contained in field for QDC
NatLibFi/NDL-VuFind2 pull request #2274
Opened 2022-03-18 10:18 UTC by LuomaJuha

2022-04-01 08:08 UTC, EreMaijala requested changes
Meillä on jo getHostRecords ja siihen liittyvä toiminnallisuus. Halutaanko varmasti rinnakkainen?

2022-04-01 08:08 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrQdc.php
> +        foreach ($xml->isPartOf ?? [] as $isPartOF) {
Pienellä f:llä.

2022-04-01 13:28 UTC, EreMaijala commented
Jos ei host recordit osu, niin getAllRecordLinks tarjoaa laajat mahdollisuudet tehdä linkkejä.

2022-04-19 07:42 UTC, LuomaJuha commented
Jees, pitääpi koitella tuota!

2022-04-25 09:06 UTC, EreMaijala approved these changes

2022-04-25 09:06 UTC, merged