[ALLI-7295] Decide which title to display with checkedout items
NatLibFi/NDL-VuFind2 pull request #2275
Opened 2022-03-18 13:58 UTC by LuomaJuha

Display the longer title.

2022-03-24 12:59 UTC, EreMaijala requested changes

2022-03-24 12:59 UTC, EreMaijala commented on themes/finna2/templates/myresearch/helpers/record-title.phtml
> +    $title = strlen($ilsTitle) > strlen($indexTitle) ? $ilsTitle : $indexTitle;
Vähän huolestuttaa tämä vertailu. Mitä jos indeksissä on pidempi mutta epätarkempi nimi? Esim. lehdillä voi olla olennaista, että saadaan nimen mukana numero, jota taas indeksissä ei ole.

2022-03-24 12:59 UTC, EreMaijala commented on themes/finna2/templates/myresearch/helpers/record-title.phtml
> +    $indexTitle = $this->escapeHtml($record->getTitle());
Tämä on liian aikaisin. Ei voi verrata escapettua index-titleä escapeattomaan ils-titleen. Parempi olisi jättää kaikki escapet pois tästä ja tehdä se vasta kun title näytetään.

2022-03-24 13:16 UTC, LuomaJuha commented on themes/finna2/templates/myresearch/helpers/record-title.phtml
> +    $title = strlen($ilsTitle) > strlen($indexTitle) ? $ilsTitle : $indexTitle;
Hmm, toisena vaihtoehtona mietin kanssa, että jättää vanhan olemaan, mutta lisätään subtitle esim alle käyttämällä

driver->getSubtitle?

2022-04-01 08:10 UTC, EreMaijala commented on themes/finna2/templates/myresearch/helpers/record-title.phtml
> +    $title = strlen($ilsTitle) > strlen($indexTitle) ? $ilsTitle : $indexTitle;
Sitä tietoa ei saa driverista, kun yhteen tietueeseen liittyy läjä numeroita. Vain lainan tiedoissa on tieto niteestä eli lainatusta kappaleesta.

Vaihtoehto tässä olisi se, että lainan numerointitiedot tulisivat omana kenttänään, mutta silloinkaan tietojen yhdistäminen kahden lähteen välillä ei välttämättä onnistu mitenkään järkevästi, kun näissä on erilaisia kombinaatioita.

2022-04-01 10:52 UTC, closed without merging