[ALLI-7403] SolrForward: Display thanks
NatLibFi/NDL-VuFind2 pull request #2279
Opened 2022-03-21 14:38 UTC by LuomaJuha

New information.

2022-03-24 12:54 UTC, EreMaijala requested changes

2022-03-24 12:54 UTC, EreMaijala commented on local/languages/finna/en-gb.ini
> +Thanks = "Thanks"
Tämä pitäisi ehkä laittaa vähän tarkemmalla käännösavaimella, ettei sekoitu ihan perus-kiitokseen, jos sellaista joskus tarvitaan. movie_thanks tms.?

2022-03-24 13:15 UTC, LuomaJuha commented on local/languages/finna/en-gb.ini
> +Thanks = "Thanks"
käy kyllä hyvin

2022-03-24 13:31 UTC, LuomaJuha commented
@EreMaijala vaihdettu.

2022-03-25 07:58 UTC, EreMaijala commented on local/languages/finna/en-gb.ini
> +Thanks = "Thanks"
Ja sitten kun se ei ole suoraan näytettävä teksti, niin käännösavaimeksi movie_thanks.

2022-03-30 06:54 UTC, LuomaJuha commented on local/languages/finna/en-gb.ini
> +Thanks = "Thanks"
Niinjoo, voin laittaa sen tuosta kontekstin titlekentästä sitten.

2022-04-01 08:24 UTC, EreMaijala commented
@LuomaJuha Edelleen koska "Movie Thanks" ei ole teksti, joka näytettäisiin englanniksi sellaisenaan, pitää se laittaa käännösavaimeen, jonka muoto on `movie_thanks`.

2022-04-01 09:31 UTC, LuomaJuha commented
@EreMaijala joo, en ollut vielä kerennyt muokata sitä!

2022-04-04 16:16 UTC, EreMaijala approved these changes

2022-04-04 16:16 UTC, merged