Alli 7399
NatLibFi/NDL-VuFind2 pull request #2292
Opened 2022-04-07 15:24 UTC by tmikkonen

2022-04-11 08:22 UTC, EreMaijala requested changes
Tuo "display" kentän nimessä tarkoittaa vain sitä, että se on käyttäjälle näytettävässä muodossa. Ts. kentän sisältö on "edition" Meillä on jo Edition-kenttä (`getEdition`) käytössä, käytetään sitä tässäkin.

2022-04-11 10:39 UTC, tmikkonen commented
Tulisiko siis käyttää getEdition-funktiota, joka palauttaa stringin ja scheman mukaan ymmärsin tarvittavan array:ta, kun palautettavia voi olla kai useampia (xsd:element name="displayEdition" type="lido:textComplexType" minOccurs="0" maxOccurs="unbounded")?

Vaiko näytetään kentän nimenä "Edition"?
Se on käännetty suomeksi "Painos", mikä esim. valokuvan kohdalla omaan korvaan vähän särähtää (mutta voi tietty olla ihan ok).

2022-04-11 14:48 UTC, EreMaijala commented
Voi lisätä `getEditions`-metodin rinnakkaiseksi. Jos on tosiaan tarpeen olla erillinen otsikko LIDOn kanssa (miksiköhän? tätä on LIDOssa tarkoitus käyttää nimenomaan painetulle aineistolla), niin sitten pidetään se erillisenä, mutta laitetaan käännösavaimeksi jotain tyyliin `lido_editions`.

2022-04-12 11:58 UTC, tmikkonen commented
Draftiksi ennenkuin museolta kuultu kelpaako "Edition" otsikoksi.

2022-04-20 07:00 UTC, EreMaijala approved these changes

2022-04-20 07:00 UTC, merged