[ALLI-7094] QDC: Display alternative titles below main title.
NatLibFi/NDL-VuFind2 pull request #2294
Opened 2022-04-11 17:16 UTC by EreMaijala

2022-04-12 12:53 UTC, LuomaJuha requested changes
Pari tyylijuttua.

2022-04-12 12:53 UTC, LuomaJuha commented on themes/finna2/templates/RecordDriver/SolrQdc/result-condensed.phtml
> +      <?php if ($otherTitles = $this->driver->tryMethod('getAlternativeTitles')): ?>
tryMethod vähän turha tässä tapauksessa?

2022-04-12 12:53 UTC, LuomaJuha commented on themes/finna2/templates/RecordDriver/SolrQdc/result-list.phtml
> +          <?php if ($uniformTitles = $this->driver->tryMethod('getUniformTitles')): ?>
SolrQDC::getUniformTitles ei ole toteutettu.

2022-04-12 12:53 UTC, LuomaJuha commented on themes/finna2/templates/RecordDriver/SolrQdc/result-list.phtml
> +          <?php if ($results = $this->driver->tryMethod('getOtherLinks')): ?>
getOtherLinks ei ole toteutettu?

2022-04-12 12:53 UTC, LuomaJuha commented on themes/finna2/templates/RecordDriver/SolrQdc/result-list.phtml
> +            <?php $authors = $this->driver->tryMethod('getAuthorsWithRoles'); if (!empty($authors)): ?>
if ($authors = $this->driver->tryMethod('getAuthorsWithRoles')) ?

2022-04-12 12:53 UTC, LuomaJuha commented on themes/finna2/templates/RecordDriver/SolrQdc/result-list.phtml
> +              <?php foreach ($summInCollection as $collId => $collText): ?>
foreach ($this->driver->getContainingCollections() ?

2022-04-12 12:53 UTC, LuomaJuha commented on themes/finna2/templates/RecordDriver/SolrQdc/result-list.phtml
> +        <?php $recordHelper = $this->record($this->driver); ?>
Alkuun ja kaikki kutsut this->record($this->driver) >> $recordHelper->?

2022-04-12 12:53 UTC, LuomaJuha commented on themes/finna2/templates/RecordDriver/SolrQdc/result-list.phtml
> +                ?>
sisennykset.

2022-04-12 12:53 UTC, LuomaJuha commented on themes/finna2/templates/RecordDriver/SolrQdc/result-list.phtml
> +            <?php /* Saved lists */ ?>
sisennykset.

2022-04-12 12:53 UTC, LuomaJuha commented on themes/finna2/templates/RecordDriver/SolrQdc/result-list.phtml
> +            <?=$thumbnail ?>
sisennykset.

2022-04-12 12:53 UTC, LuomaJuha commented on themes/finna2/templates/RecordDriver/SolrQdc/result-list.phtml
> +                <?php /* Add to favorites */ ?>
Sisennykset.

2022-04-12 12:53 UTC, LuomaJuha commented on themes/finna2/templates/RecordDriver/SolrQdc/result-list.phtml
> +                <?=$this->render('record/cart-buttons.phtml', ['id' => $this->driver->getUniqueId(), 'source' => $this->driver->getSourceIdentifier()]); ?><br/>
Sisennykset.

2022-04-19 08:06 UTC, EreMaijala commented
@LuomaJuha Hyviä kommentteja, mutta.. Taitaa noi kaikki olla DefaultRecord:n templaateista kopioituja ongelmia. Pitäisin ne mielelläni samana, koska toiveena olisi jossain vaiheessa saada vähän yhtenäistettyä templaatteja, ja kaikki erot sitten vaikeuttavat vertailua. Siksi siis on myös noita toteuttamattomia metodeja.

2022-04-19 09:11 UTC, LuomaJuha commented
@EreMaijala se on ihan hyvä pointti.

2022-04-19 09:11 UTC, LuomaJuha approved these changes

2022-04-19 09:12 UTC, merged