Remove jquery from searchTabsRecommendations.js
NatLibFi/NDL-VuFind2 pull request #2299
Opened 2022-04-21 09:27 UTC by LuomaJuha

Small cleaning.

2022-04-21 10:33 UTC, EreMaijala requested changes

2022-04-21 10:33 UTC, EreMaijala commented on themes/finna2/js/finna-search-tabs-recommendations.js
> +      .then((data) => {
Olisi selkeämpi, jos tämän nimi olisi jotain muuta kuin `data`. Esim. `json` jos `responseJson` on turhan pitkä, niin ei tulisi data dataa.

2022-04-21 10:59 UTC, LuomaJuha commented on themes/finna2/js/finna-search-tabs-recommendations.js
> +      .then((data) => {
Eipä tuo turhan pitkä ollu jsonResponse.

2022-04-25 09:02 UTC, EreMaijala approved these changes

2022-04-25 09:02 UTC, merged