[ALLI-7425] EAD: Display origination date in record details
NatLibFi/NDL-VuFind2 pull request #2312
Opened 2022-05-05 07:52 UTC by rajaro

2022-05-10 09:16 UTC, EreMaijala requested changes

2022-05-10 09:16 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrEad.php
> +        if (!empty($name = $this->getOrigination())) {
Voisitko selventää vähän tätä logiikkaa `dateOnly`-hommelin osalta? En oikein ymmärrä koko systeemin tarkoitusta, ts. miksei vain palauteta juuri niitä tietoja, jotka halutaan näyttää? Johtuuko siitä, että meillä on getOrigination ja getOriginationExtended? Nähdäkseni olisi syytä muuttaa koko systeemi käyttämään pelkkää getOriginationExtended:iä niin, ettei templaatissa kutsuta getOriginationExtended:ia, vaan se tulee RecordDataFormatter:ilta.

2022-05-11 12:49 UTC, rajaro commented on module/Finna/src/Finna/RecordDriver/SolrEad.php
> +        if (!empty($name = $this->getOrigination())) {
Syy tolle oli se, että tällä hetkellä getOriginationExtended näytetään käytännössä muodossa (EAD3):
Tekijä Nimi (tietoa, vuosi-vuosi)
Mutta tähän haluttiin muodossa
Tekijä Nimi, vuosi-vuosi

Varmaan ois joo hyvä käyttää pelkkää getOriginationExtended:iä ja yhtenäisellä esitystavalla. Suluissa siis?

2022-05-11 13:08 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrEad.php
> +        if (!empty($name = $this->getOrigination())) {
Se olisi varmaan UX:n päätettävä, mutta joka tapauksessa pitäisi olla jotenkin yhtenäinen.

2022-05-18 12:34 UTC, rajaro commented on module/Finna/src/Finna/RecordDriver/SolrEad.php
> +        if (!empty($name = $this->getOrigination())) {
Muutettu. Nyt siis käytössä tuo ead3 muoto myös ead:ssa

2022-05-18 12:52 UTC, EreMaijala requested changes

2022-05-18 12:52 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrEad.php
> +    public function getOriginationExtended()
Eikö tämän pitäisi hakea tiedot kaikista origination-elementeistä? Nyt palauttaa vain ensimmäisen.

2022-05-18 12:52 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrEad.php
> +            $date = isset($record->did->origination->ref->date)
Tällaisen voi lyhentää `$date = (string)($record->did->origination->ref->date ?? '');`

2022-05-18 13:19 UTC, rajaro commented on module/Finna/src/Finna/RecordDriver/SolrEad.php
> +    public function getOriginationExtended()
Eikös tähän asti EADssa oo näytetty vain ensimmäinen? En tiedä, onko tarvetta näyttää enempää. Eikä ainakaan taskissa mainittu siitä, ja pitäskö sen olla jokatapauksessa eri taski? Voin sen kyllä tähänkin laittaa, jos tarve on.

2022-05-19 09:59 UTC, EreMaijala requested changes

2022-05-19 09:59 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrEad.php
> +    public function getOriginationExtended()
Aiemmin on näytetty ehkä vain yksi, mutta kun tämä nyt on toteutettu, niin sen pitäisi toimia oikein.

2022-05-20 06:44 UTC, EreMaijala approved these changes

2022-05-20 06:45 UTC, merged