[ALLI-7491] LIDO: Do not add empty collections
NatLibFi/NDL-VuFind2 pull request #2316
Opened 2022-05-06 11:35 UTC by mshroom

2022-05-10 11:12 UTC, EreMaijala requested changes

2022-05-10 11:12 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +            $collection = (string)$node->relatedWork->displayObject ?? '';
Pitäisikö varmuuden vuoksi tehdä myös `trim()` molemmissa kohdissa? Joissain tietueissa on ainakin näkynyt sellaisia, joissa on vain välilyöntejä, rivinvaihtoja ja kommentteja..

2022-05-11 10:25 UTC, mshroom commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +            $collection = (string)$node->relatedWork->displayObject ?? '';
Lisäsin. Laitoin vielä vastaavan tarkistuksen getRelatedPublications() kohtaan, varmaan ok korjata se tässä samassa.

2022-05-11 10:32 UTC, EreMaijala approved these changes

2022-05-11 10:33 UTC, merged