[ALLI-7495] Hide available online if no links are set
NatLibFi/NDL-VuFind2 pull request #2320
Opened 2022-05-12 13:46 UTC by LuomaJuha

test: Search/Results?filter%5B%5D=~building%3A%220%2Fporintaidemuseo%2F%22&dfApplied=1&type=AllFields

2022-05-16 10:36 UTC, EreMaijala requested changes
Minusta tuntuu, että meidän pitäisi muuttaa kaikki tietueajurit niin, että jättävät palauttamatta urleina kuvat. Vai tarvitaanko me jossain tilanteessa niitä urlien kanssa? Tuntuu hullulta, että pitää muistaa suodattaa ne jälkikäteen, mikä helposti unohtuukin.

2022-05-16 10:36 UTC, EreMaijala commented on module/Finna/src/Finna/View/Helper/Root/Record.php
> +        $cacheKey = __FUNCTION__ . "/{$this->driver->getUniqueID()}";
Cache on tietuekohtainen, ei siihen tarvitse id:tä..

2022-05-16 10:36 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/result-online-urls.phtml
> +    $combined = $recordHelper->filterImageURLs([...$urls, ...$onlineURLs, ...(!empty($mergedData['urls']) ? $mergedData['urls'] : [])]);
Tuon ternaryn voisi korvata `$mergedData['urls'] ?: []`.

2022-05-16 10:37 UTC, LuomaJuha commented
@EreMaijala Kuulostaa kyllä ihan järkevältä, että ne poistuis jo etukäteen. Koitanpas sellasta vaihtoehtoa.

2022-05-16 10:37 UTC, LuomaJuha commented
@EreMaijala Kuulostaa kyllä ihan järkevältä, että ne poistuis jo etukäteen. Koitanpas sellasta vaihtoehtoa.

2022-05-17 05:36 UTC, EreMaijala commented
Laita katselmointiin sit uudelleen...

2022-05-18 12:26 UTC, EreMaijala approved these changes

2022-05-18 12:27 UTC, merged