Translations for School library department [FINNAPOSTI-17623]
NatLibFi/NDL-VuFind2 pull request #2321
Opened 2022-05-16 16:28 UTC by jlehmus

2022-05-17 05:35 UTC, EreMaijala requested changes

2022-05-17 05:35 UTC, EreMaijala commented on local/languages/finna/en-gb.ini
> +3/*/10/ = "School libraries"
Onko siihen joku syy, että tässä on monikossa ja department/en-gb.ini:ssä yksikössä?

2022-06-14 05:56 UTC, EreMaijala commented on local/languages/finna/en-gb.ini
> +3/*/10/ = "School libraries"
@jlehmus ?

2022-06-22 08:34 UTC, jlehmus commented on local/languages/finna/en-gb.ini
> +3/*/10/ = "School libraries"
Vahinko, pitäisi olla nyt kunnossa

2022-10-12 10:43 UTC, EreMaijala approved these changes

2022-10-12 10:44 UTC, merged