[ALLI-7499] Display all actors in eventSet
NatLibFi/NDL-VuFind2 pull request #2345
Opened 2022-06-21 12:18 UTC by LuomaJuha

Also remove xPath from getNonPresenterAuthors.

test: Record/lappeenrannanmuseot.872D25E7-D075-46E7-B38D-BF56369D4FE7

2022-06-22 08:08 UTC, EreMaijala requested changes

2022-06-22 08:08 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +                if (trim($name)) {
Pitäisikö ottaa lopputulokseen tuo trimmattu nimi?

2022-06-22 08:09 UTC, LuomaJuha commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +                if (trim($name)) {
Kyllähän se pitäisi... Laitetaas se

2022-06-23 11:24 UTC, EreMaijala approved these changes

2022-06-23 11:24 UTC, merged

2022-08-12 07:43 UTC, EreMaijala commented
Tämän olisi pitänyt olla ALLI-7501.