[ALLI-7602] Fix type check in Params::initSpatialDateRangeFilter
NatLibFi/NDL-VuFind2 pull request #2350
Opened 2022-07-06 07:03 UTC by LuomaJuha

2022-08-24 09:30 UTC, LuomaJuha commented
Tää oli pieni bugi ettei daterangen tyyppi fasetissa säilyny kun sivu latautu.

2022-08-24 09:52 UTC, EreMaijala requested changes
Tämän pitäisi tapahtua jo serveripuolella, mutta jotain on nyt pahasti pielessä. Eli FinnaParams:n `parseDateRangeFilter` väittää osaavansa kertoa tyypin, mutta ei osaa. Ja pieleen menee. En ole ihan varma, missä vaiheessa tämä on räjähtänyt käsiin, mutta voi olla, että aikoinaan kun aikavälit vaihdettiin spatial-tyyppisestä hausta normaaliksi date range:ksi, meni jotain pieleen. Joka tapauksessa korjaus pitäisi tehdä serveripuolella esim. siinä, kun nykymuotoinen date range parsitaan parseDateRangeFilter:llä.

2022-08-24 10:35 UTC, LuomaJuha commented
Ah, se onkin isompi näköjään joten sitten tutkitaan sitä.

2022-09-01 06:24 UTC, EreMaijala approved these changes

2022-09-01 06:25 UTC, merged