[ALLI-6203] Use patrons source as primary selection for dedup-selects
NatLibFi/NDL-VuFind2 pull request #2364
Opened 2022-08-24 10:38 UTC by LuomaJuha

Otherwise user must select a library before seeing holdings information.

2022-08-26 12:52 UTC, LuomaJuha commented
Didn't feel comfortable when adding lots of stuff to the template so decided to split logic a littlebit into two seperate templates and using record helper to check for conditions.

2022-09-06 09:41 UTC, EreMaijala requested changes
Jos valitsee jonkin kirjaston, niin sen pitäisi näkyä sitten kaikille hakutuloksille saman tien. Muuten pitää ladata sivu uudelleen, jotta preferredRecordSource tulee voimaan. Ehkä tässä yhteydessä voisi myös miettiä, voisiko preferredRecordSource sisältää listan viimeisistä valinnoista, jotta olisi myös toissijainen lähde, jos oletuslähteestä ei ole saatavuustietoja.

2022-09-06 09:41 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/holdings.phtml
> +      <select id="<?=$this->escapeHtmlAttr($attrID)?>" class="dedup-select form-control" role="listbox" aria-haspopup="true" title="<?=$this->transEsc('select_dedup_organisation');?>" aria-label="<?=
Attribuuteille `transEscAttr`

2022-09-06 09:41 UTC, EreMaijala commented on local/config/finna/config.ini.sample
> +; Will display choose library placeholder in the deduplicated select elements.
Laita `...display a "Choose library" placeholder in the record source select elements.`

2022-09-06 09:41 UTC, EreMaijala commented on module/Finna/src/Finna/View/Helper/Root/Record.php
> +            if ($this->driver->getDedupData()) {
Tämän voisi yhdistää ylemmän if:n kanssa.

2022-09-06 09:41 UTC, EreMaijala commented on module/Finna/src/Finna/View/Helper/Root/Record.php
> +     * If deduplication selections are allowed to fetch holdings
`Whether to load holdings for the default source on page load for deduplicated records.`

2022-09-06 09:41 UTC, EreMaijala commented on module/Finna/src/Finna/View/Helper/Root/Record.php
> +            if ($this->driver->getDedupData()) {
Muistaakseni tietueella voi olla dedup data, vaikkei näkyisikään duplikaatteja. Ts. jos deduplikointi on käytössä source-rajauksen kanssa, voi olla deduplikoitu tietue vain yhdestä lähteestä, jolloin saatavuus pitäisi näyttää heti. Vanhassa holdings.phtml:ssä tarkistetaan lukumäärä, pitäisikö tässäkin?

2022-09-06 09:41 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/holdings-deduplicated.phtml
> +  $selectID = "{$this->driver->getUniqueID()}-dedup-select";
ID voi sisältää merkkejä, jotka eivät ole valideja elementin id:ssä. safeId:itä luodaan eri paikoissa poistamalla ei-alfanumeeriset merkit, mikä voi kyllä olla vähän riskikin. Ehkä kuin base64 tuosta voisi olla turvallinen, mutta jos tietueen id:tä ei varsinaisesti tarvitse kaivaa elementin id:stä (johon data-attribuutti olisi parempi), niin ehkä joku `static $counter = 0; ++$counter; $selectID = "dedup-select-$counter";`

2022-09-06 09:41 UTC, EreMaijala commented on local/config/finna/config.ini.sample
> +;select_dedup_holdings_library = true
Asetus kuuluu sektioon `Item_Status`.

2022-09-14 09:59 UTC, LuomaJuha commented on local/config/finna/config.ini.sample
> +;select_dedup_holdings_library = true
Hyvä huomio, oli lipsahtanut liian pitkälle.

2022-09-14 10:00 UTC, LuomaJuha commented on module/Finna/src/Finna/View/Helper/Root/Record.php
> +            if ($this->driver->getDedupData()) {
Laitetaan varmuuden vuoksi.

2022-09-20 08:06 UTC, pasitiis approved these changes
Toiminnallisesti näytti toimivan.

2022-09-29 07:39 UTC, EreMaijala requested changes

2022-09-29 07:39 UTC, EreMaijala commented on module/Finna/src/Finna/Search/Solr/DeduplicationListener.php
> +            $preferred = $cookieManager->get('preferredRecordSourceArray');
Tämä voisi myös olla edelleen `preferredRecordSource`, kunhan tsekkaa, näyttääkö json:lta vai stringiltä, jolloin olisi taaksepäin yhteensopiva. En kylläkään ole varma, tarviiko olla. Muuten suosisin `preferredRecordSources` vaikka vain koska se on vähän lyhyempi.

2022-09-29 07:39 UTC, EreMaijala commented on module/Finna/src/Finna/Search/Solr/DeduplicationListener.php
> +            foreach (array_reverse($preferred ?? []) as $source) {
json_decode palauttaa false, jos epäonnistuu, joten tän pitäisi olla varmaan `$preferred ?: []`.

2022-09-29 07:39 UTC, EreMaijala commented on local/languages/finna/en-gb.ini
> +Choose Library = "Choose library"
Tässä taitaa olla termiongelma, kun deduplikoitavaa aineistoa voi tulla muualtakin kuin kirjastoista.

2022-09-29 07:39 UTC, EreMaijala commented on module/Finna/src/Finna/Search/Solr/DeduplicationListener.php
> +            foreach (array_reverse($preferred ?? []) as $source) {
Tämä edelleen.

2022-09-29 07:39 UTC, EreMaijala commented on themes/finna2/js/finna-item-status.js
> +        cookie.pop();
slice olisi varmempi, jos jostain syystä array olisi päässyt kasvamaan liian isoksi

2022-09-29 07:39 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/holdings.phtml
> +  $selectID = "dedup-select-" . Finna\View\Helper\Root\Record::$dedupCounter++;
Tämä on vähän häkkyrä. Ennemmin vaikka helpperi tms., jolta saa juoksevan numeron tyyliin `$selectID = 'dedup-select-' . $this->counter()->increment()`. Silloin ei tarvitse edes mitään static:ia, kun helpperi on aina sama instanssi.

2022-09-29 07:39 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/holdings.phtml
> +          <option value="<?=$this->escapeHtmlAttr($current['id']) ?>" class="dedup-data-id" data-source="<?=$this->escapeHtmlAttr($source) ?>" <?php if ($recordSource === $source): ?> selected="selec
Turha välilyönti lisätty.

2022-09-29 07:39 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/list-entry.phtml
> +<div class="result record-container<?php if($this->record($this->driver)->getPreferredSource() && $this->driver->supportsAjaxStatus()): ?> ajaxItem<?php endif ?> myresearch-row">
??? Kyllä voi olla deduplikoimatonkin tietue olla ajaxItem, ei voida rajoittaa niihin, joille saadaan preferred source.

2022-09-29 07:39 UTC, EreMaijala commented on module/Finna/src/Finna/View/Helper/Root/Record.php
> +        if (!$this->driver->supportsAjaxStatus()) {
Olisi parempi olla sekoittamatta preferred sourcea ja sitä, tukeeko tietue ajax statusta.

2022-09-29 07:40 UTC, LuomaJuha commented on module/Finna/src/Finna/Search/Solr/DeduplicationListener.php
> +            $preferred = $cookieManager->get('preferredRecordSourceArray');
Sekin passaa.

2022-09-29 07:46 UTC, LuomaJuha commented on local/languages/finna/en-gb.ini
> +Choose Library = "Choose library"
Hmm, se on totta. Olisikohan valitse lähde parempi. @pasitiis

2022-09-29 07:59 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/holdings.phtml
> +      <select id="<?=$this->escapeHtmlAttr($selectID)?>" class="dedup-select form-control" role="listbox" aria-haspopup="true" title="<?=$this->escapeHtmlAttr($this->translate('select_dedup_organisat
aria-label transEscAttr

2022-11-18 08:42 UTC, pasitiis commented on local/languages/finna/en-gb.ini
> +Choose Library = "Choose library"
"Valitse lähde" voi olla vähän vaikeasti ymmärettävä. Täytyy vielä pohtia termikysymystä.

2023-01-09 10:41 UTC, EreMaijala requested changes

2023-01-09 10:41 UTC, EreMaijala commented on module/Finna/src/Finna/View/Helper/Root/Record.php
> +            $preferredRecordSource = json_decode($preferredRecordSource);
Tästä puuttuu taaksepäin yhteensopivuustuki. Pitäisi tsekata, onko eka merkki `{` ennen kuin yrittää json_decode:a. Muuten jos sisältö on vaikka `abo`, palauttaa json_decode null:n. Ja vaikka kutsuttaisiin json_decode:a, pitää tarkistaa, että saadaan tuloksena array.

2023-01-09 10:41 UTC, EreMaijala commented on module/Finna/src/Finna/View/Helper/Root/Record.php
> +            $preferredRecordSource[] = $patron['source'];
Lopullinen muuttuja voisi olla `$preferredSources`

2023-01-09 10:41 UTC, EreMaijala commented on module/Finna/src/Finna/Search/Solr/DeduplicationListener.php
> +                $preferred = json_decode($preferred);
Tästä puuttuu taaksepäin yhteensopivuustuki. Pitäisi tsekata, onko eka merkki { ennen kuin yrittää json_decode:a. Muuten jos sisältö on vaikka abo, palauttaa json_decode null:n.

2023-01-09 10:41 UTC, EreMaijala commented on module/Finna/src/Finna/View/Helper/Root/Record.php
> +        $classes = '';
Tee tästä array ja palauta lopussa implode:lla tulos, niin ei tartte välilyöntejä lisäillä.

2023-01-09 10:41 UTC, EreMaijala commented on themes/finna2/js/finna-item-status.js
> +      var cookie = finna.common.getCookie('preferredRecordSource');
Tässäkin ongelma taaksepäin yhteensopivuuden ja virheenkäsittelyn kanssa: JSON.parse heittää virheen, jos sisältö ei ole validia. Pitäisi joka tapauksessa catchata poikkeus.

2023-01-09 10:41 UTC, EreMaijala commented on themes/finna2/js/finna-item-status.js
> +      cookie.unshift(source);
Pitäisikö tässä tsekata, ettei `cookie` jo sisällä `source`:a?

2023-01-09 10:41 UTC, EreMaijala commented on themes/finna2/js/finna-vufind-overrides.js
> +/*global VuFind*/
Voisiko tämän välttää, jos lisäisi `js-sourceless`:n sijaan `js-item-done`-luokan container:lle? Silloin VuFindin init ei tekisi hakua, kun se olisi ikäänkuin valmiiksi tehty.

2023-01-09 10:41 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/holdings.phtml
> +  $recordSource = $this->record($this->driver)->getPreferredSource();
Nimeä tämä vaikka `$preferredSource`, niin ei vaikuta siltä kuin olisi alkuperäisen tietueen source.

2023-01-09 10:41 UTC, EreMaijala commented on module/Finna/src/Finna/View/Helper/Root/Record.php
> +    public function getContainerClasses(): string
Kävisikö `getContainerJsClasses`, kun tämä palauttaa vain tietyt js-toimintoja ohjaavat luokat?

2023-01-11 14:03 UTC, LuomaJuha commented on themes/finna2/js/finna-vufind-overrides.js
> +/*global VuFind*/
Testaan tätä, koska tää vois olla paljon parempi ratkasu.

2023-01-11 14:04 UTC, LuomaJuha commented on module/Finna/src/Finna/View/Helper/Root/Record.php
> +            $preferredRecordSource = json_decode($preferredRecordSource);
Jeespoks, lisätään bc

2023-01-12 09:24 UTC, LuomaJuha commented on themes/finna2/js/finna-item-status.js
> +      cookie.unshift(source);
Lisätty filtteröinti.

2023-01-12 10:34 UTC, LuomaJuha commented on module/Finna/src/Finna/Search/Solr/DeduplicationListener.php
> +                $preferred = json_decode($preferred);
Lisätty [ tarkastus kun js tallentaa sen tauluna

2023-01-12 10:35 UTC, LuomaJuha commented on themes/finna2/js/finna-item-status.js
> +      var cookie = finna.common.getCookie('preferredRecordSource');
laitettu parse try catchiin.

2023-01-13 08:23 UTC, LuomaJuha commented
Käännökset jäikin unohtumaan, lisäilen. Edit: lisätty.

2023-01-18 13:14 UTC, EreMaijala approved these changes

2023-01-18 13:58 UTC, merged