[ALLI-7533] Add individual rights check for allowRecordImageDownload function
NatLibFi/NDL-VuFind2 pull request #2386
Opened 2022-09-26 10:02 UTC by LuomaJuha

2022-10-04 07:37 UTC, EreMaijala requested changes

2022-10-04 07:37 UTC, EreMaijala commented on module/Finna/src/Finna/View/Helper/Root/Record.php
> +                if (mb_strtoupper($copyright) === $restriction) {
mb_strtoupper:lle toiseksi parametriksi `'UTF-8'`, niin ei tartte luottaa siihen, että PHP:ssa oletus-locale on se.

2022-10-04 07:37 UTC, EreMaijala commented on local/config/finna/config.ini.sample
> +[RestrictedFileDownload]
Jos sektion nimi olisi vaikka `[FileDownload]`, niin sinne voisi tarvittaessa lisätä muitakin asetuksia. Ja asetus vaikka `excludeRights`.

2022-10-04 07:37 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/image-download.phtml
> +    if (!$this->record($this->driver)->allowRecordImageDownload($image['rights']['copyright'] ?? '')) {
Voisi olla suoraan image-taulukossakin `'downloadable'`, jolloin tarvittaessa voisi olla vaikka tietueessa itsessään se tieto. Tarttee toki muutoksia useampaan paikkaan, mutta tarjoaa sitten joustavuutta. Mitä mieltä?

2022-10-04 07:42 UTC, LuomaJuha commented on themes/finna2/templates/RecordDriver/DefaultRecord/image-download.phtml
> +    if (!$this->record($this->driver)->allowRecordImageDownload($image['rights']['copyright'] ?? '')) {
Kuulostaa kyllä ihan passelilta idealta.

2022-10-06 14:06 UTC, LuomaJuha commented on module/Finna/src/Finna/RecordDriver/Feature/FinnaRecordTrait.php
> +        $indexRights = $this->tryMethod('getUsageRights', [], []);
Tätä mietin vaan että halutaanko enää kattoa edes indeksistä tulleita arvoja.

2022-10-07 11:46 UTC, EreMaijala approved these changes

2022-10-07 11:47 UTC, merged