[ALLI-7608] EAD3: Add finding aid and bibliography to collection view
NatLibFi/NDL-VuFind2 pull request #2398
Opened 2022-10-06 10:48 UTC by rajaro

2022-10-07 11:41 UTC, EreMaijala requested changes
Tämä aiheuttaa sen, että EAD-tietueilta katoaa `Additional Information`, eivätkä ne tue `Additional Information Extended`:iä. Eli pitää tsekata `$type` tai lisätä em. tuki SolrEad:hen.

2022-10-07 11:56 UTC, rajaro commented
Kyllähän siellä edelleen on Additional Information, nyt vaan lisäksi Extended. Ja lopussa kutsutaan filterEadFields/filterEad3Fields joissa sitten Extended on vain ead3:ssa

2022-10-10 06:08 UTC, EreMaijala commented
@rajaro Ai sori, luin väärin.

2022-10-10 06:08 UTC, EreMaijala approved these changes

2022-10-10 06:09 UTC, merged