[ALLI-7664] Add option to include icon for feeds from instagram, twitter etc...
NatLibFi/NDL-VuFind2 pull request #2406
Opened 2022-10-07 12:36 UTC by LuomaJuha

2022-10-18 11:23 UTC, EreMaijala requested changes
Mä vaihtaisin "social" => "feed" eli esim. feed_icon. Ei kaikki kohteet ole välttämättä somea..

2022-10-18 11:23 UTC, EreMaijala commented on local/config/finna/config.ini.sample
> +; Array of hosts and their name values, seperated by a semicolon
*separated*

2022-10-18 11:23 UTC, EreMaijala commented on local/languages/finna/fi.ini
> +social_icon = "%%platform%% ikoni"
`"%%platform%%-ikoni"` ?

2022-10-18 11:23 UTC, EreMaijala commented on local/config/finna/config.ini.sample
> +; Array of hosts and their name values, seperated by a semicolon
Kaksoispiste on useammin käytetty, sopisi minusta tähänkin

2022-10-18 11:23 UTC, EreMaijala commented on themes/finna2/templates/Helpers/social-icon.phtml
> +      <i class="social-icon fa <?="fa-{$this->escapeHtmlAttr($icon['name'])}"?>" aria-label="<?=$this->transEscAttr('social_icon', ['%%platform%%' => $icon['name']])?>"></i>
Uusi ikoni, käytetään icon-helperiä (kaikissa kohdissa)

2022-10-18 11:23 UTC, EreMaijala commented on themes/finna2/templates/Helpers/social-icon.phtml
> +    <div class="social-icon-wrapper <?=$this->class?>">
escapeHtmlAttr class:lle.

2022-10-18 11:23 UTC, EreMaijala commented on module/Finna/src/Finna/Feed/Feed.php
> +            if ($showIcons
Tämä mappauspätkä erilliseen metodiin, niin saadaan tästä vähän siistimpi.

2022-10-18 11:23 UTC, EreMaijala commented on local/languages/finna/en-gb.ini
> +social_icon = "%%platform%% icon"
`social_icon_label` olisi parempi (tai `feed_icon_label` toisen kommentin mukaan)

2022-10-19 12:40 UTC, LuomaJuha commented on themes/finna2/templates/Helpers/social-icon.phtml
> +      <i class="social-icon fa <?="fa-{$this->escapeHtmlAttr($icon['name'])}"?>" aria-label="<?=$this->transEscAttr('social_icon', ['%%platform%%' => $icon['name']])?>"></i>
Aijoo, unohin sen kokonaan.

2022-10-20 11:52 UTC, LuomaJuha commented
@EreMaijala nyt pitäis olla muokattu, jos oikein ymmärsin asiat

2022-10-20 12:05 UTC, EreMaijala approved these changes

2022-10-20 12:06 UTC, merged