[ALLI-7688] Fix displaying organisation info if there are multiple sectors
NatLibFi/NDL-VuFind2 pull request #2424
Opened 2022-10-25 12:52 UTC by LuomaJuha

Some organisations have multiple different sectors and the check doesn't always work if the first one is only checked. This one is a bugfix but there is alot to be improved in this code.

2022-11-03 10:54 UTC, EreMaijala requested changes
Tämä kaipaisi pilkkomista. Toi metodi alkaa olla niin pitkä ja monipolvinen, että sitä on vaikea seurata. Voisiko sektorien selvittämisen tms. laittaa erilliseen metodiin?

2022-11-09 13:23 UTC, EreMaijala requested changes

2022-11-09 13:23 UTC, EreMaijala commented on module/Finna/src/Finna/AjaxHandler/GetOrganisationInfo.php
> +     * Get informations for the organisation.
"Get information for..." ja metodin nimeksi `getOrganisationInfo`.

2022-11-09 13:23 UTC, EreMaijala commented on module/Finna/src/Finna/AjaxHandler/GetOrganisationInfo.php
> +     * @param array  $parents   Parents data
Tarttisi vähän parempaa kuvausta siitä, mitä `$parents` tarkoittaa ja sisältää. Toimisiko nimenä `$organisations`? Samoin `$action` ainakin kaipaa tietoa siitä, mitä se voi olla.

2022-11-09 13:23 UTC, EreMaijala commented on module/Finna/src/Finna/AjaxHandler/GetOrganisationInfo.php
> +     * @param array  $parent    Parent data
Sama juttu tässä, vähän tarkempaa kuvausta siitä, mitä `$parent` meinaa. Toimisiko nimenä `$organisation`? Samoin `$action` ainakin kaipaa tietoa siitä, mitä se voi olla.

2022-11-09 13:23 UTC, EreMaijala commented on module/Finna/src/Finna/AjaxHandler/GetOrganisationInfo.php
> +     * @param string $action    Action type
$action kaipaa tietoa siitä, mitä se voi olla.

2022-11-09 13:23 UTC, EreMaijala commented on module/Finna/src/Finna/AjaxHandler/GetOrganisationInfo.php
> +     * @param array $parent Information for fetch
`string $institutionId`? Ei tartte muuta, eikö?

2022-11-10 08:21 UTC, LuomaJuha commented on module/Finna/src/Finna/AjaxHandler/GetOrganisationInfo.php
> +     * @param array  $parents   Parents data
Jees, miepä lisäilen

2022-11-10 08:22 UTC, LuomaJuha commented on module/Finna/src/Finna/AjaxHandler/GetOrganisationInfo.php
> +     * @param array $parent Information for fetch
jeps

2022-11-10 15:09 UTC, LuomaJuha commented on module/Finna/src/Finna/AjaxHandler/GetOrganisationInfo.php
> +     * @param string $action    Action type
lisätty alle lista.

2022-11-11 09:22 UTC, EreMaijala approved these changes

2022-11-11 09:24 UTC, merged