RecordDataFormatter: removed all the entries with no function in the driver
NatLibFi/NDL-VuFind2 pull request #2425
Opened 2022-10-26 13:59 UTC by LuomaJuha

The simple function used:

`       var_dump(count($include));
        echo "<pre>";
        $intersected = array_intersect_key($coreFields, array_flip($include));
        $ind = 0;
        $realFunctions = [];
        foreach ($intersected as $key => $value) {
            if (is_callable([$driver, $value['dataMethod']], true, $callable_name)) {
                if (method_exists($driver, $value['dataMethod'])) {
                    $realFunctions[] = $key;
                }
            } else {
                // Sometimes the dataMethod is not a function name, so save it in case
                $realFunctions[] = $key;
            }
        }
        sort($realFunctions);
        $j = 0;
        for ($i = 0; $i < count($realFunctions); $i++) {
            echo "'{$realFunctions[$i]}', ";
            if (++$j === 3) {
                echo PHP_EOL;
                $j = 0;
            } 
        }
        echo "</pre>";
        var_dump($ind);`

2022-10-26 14:00 UTC, LuomaJuha commented
Huoh, se funktio meni vaan yheks pötköks...

2022-11-04 07:58 UTC, EreMaijala requested changes
Let's just make it so that there's one field per line. It's longer, but it'll make making and diffing changes so much easier later on.

2022-11-04 14:49 UTC, LuomaJuha commented
Added also an entry for lido in the function filterCollectionFields

2022-11-09 07:57 UTC, EreMaijala requested changes
Sorry, one more thing: I think it would be better to use case-insensitive sort. I find it confusing that e.g. `child_records` is at the bottom of the list.

2022-11-09 12:42 UTC, LuomaJuha commented
Noticed that I didn't create a ticket for this one. Will do so the history is recorded somewhere.

2022-11-10 09:53 UTC, EreMaijala requested changes

2022-11-10 09:53 UTC, EreMaijala commented on module/Finna/src/Finna/View/Helper/Root/RecordDataFormatter.php
> +        case 'ead':
Laitetaan EAD3 `case 'ead3':`:lle eikä tehdä defaultina mitään tai viskataan poikkeus tai jotain.

2022-11-10 15:06 UTC, LuomaJuha commented on module/Finna/src/Finna/View/Helper/Root/RecordDataFormatter.php
> +        case 'ead':
jepulis!

2022-11-10 15:21 UTC, LuomaJuha commented on module/Finna/src/Finna/View/Helper/Root/RecordDataFormatter.php
> +        case 'ead':
Laitoin pienen poikkeuksen tulemaan jos yrittää tietuetyypillä, mil ei oo tukea collectionille.

2022-11-10 18:54 UTC, EreMaijala approved these changes

2022-11-10 18:54 UTC, merged