[ALLI-7636] EAC-CPF: Display alternative title dates
NatLibFi/NDL-VuFind2 pull request #2433
Opened 2022-11-03 13:36 UTC by rajaro

2022-11-04 08:33 UTC, EreMaijala requested changes

2022-11-04 08:33 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrAuthEaccpf.php
> +            $dates = $fromDate && $toDate ? "{$fromDate}-{$toDate}" : '';
Pitäisikö muotoilla samalla tavalla kuin esim. module/Finna/src/Finna/Search/Solr/Params.php:653? Eli ndash ja välit ympärille?

2022-11-09 08:07 UTC, EreMaijala requested changes
I checked the [EAC-CPF specs](https://eac.staatsbibliothek-berlin.de/schema/taglibrary/cpfTagLibrary2019_EN.html#elem-useDates), and it seems that `useDates` may also contain a `date` or a `dateSet` (that in turn can contain multiple `date` and/or `dateRange` elements. I think that we need a method that parses all of these and returns a string presentation such as a comma-separated list of dates and date ranges.

2022-11-16 07:52 UTC, EreMaijala requested changes
While the code looks ok now, I think we need tests to exercise the different possibilities including recursive ones.

2022-11-16 07:52 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrAuthEaccpf.php
> +            if (preg_match('/^(\d{4})-([a-z]{2})-([a-z]{2})$/', $date, $matches)) {
Add a comment for what this case handles.

2022-11-21 10:56 UTC, rajaro commented
Muutokset ja testit tehty. Lisäksi dokumentoinnin perusteella päivämäärä tulee koneluettavasti attribuutissa standardDate, joten muutin koodia niin, että luetaan standardDate sisältö ensin ja jos tyhjä, niin vasta sitten elementin tekstisisältö

2022-11-22 08:20 UTC, EreMaijala approved these changes

2022-11-22 08:20 UTC, merged