[ALLI-7524] Add Bazaar API support
NatLibFi/NDL-VuFind2 pull request #2436
Opened 2022-11-07 09:26 UTC by aleksip

Continuing work from #2337

2023-03-03 13:17 UTC, EreMaijala requested changes

2023-03-03 13:17 UTC, EreMaijala commented on local/config/finna/config.ini.sample
> +;client['client_id'] = secret
Ei tuossa hakasulkujen sisällä yleensä hipsuja käytetä. Lukeeko parseri ne oikein?

2023-03-03 13:17 UTC, EreMaijala commented on local/languages/finna/en-gb.ini
> +bazaar_browse_title = ""
"Browse and Select"?

2023-03-03 13:17 UTC, EreMaijala commented on local/languages/finna/sv.ini
> +bazaar_browse_cancel = ""
"Avbryta"?

2023-03-03 13:17 UTC, EreMaijala commented on local/languages/finna/sv.ini
> +bazaar_browse_title = ""
"Bläddring"?

2023-03-03 13:17 UTC, EreMaijala commented on module/Finna/src/Finna/Controller/SearchController.php
> +            throw new AuthException('authentication_error_expired');
Kai se voisi olla virheellinenkin? Olisiko parempi 'authentication_error_invalid'?

2023-03-03 13:17 UTC, EreMaijala commented on module/Finna/src/Finna/Controller/SearchController.php
> +        $row = $authHash->getByHashAndType($hash, 'bazaar', false);
Pitäisikö ottaa hash talteen sessioon ja ohittaa nämä tarkistukset ym. jos hash on jo sessiossa, jotta ei tulisi virhettä, vaikka menisi selaimella liikaa taaksepäin?

2023-03-03 13:17 UTC, EreMaijala commented on module/Finna/src/Finna/View/Helper/Root/BazaarSession.php
> +        $this->container = $this->session->getStorage()->offsetGet(self::NAMESPACE);
Tuntuisi paremmalta, jos olisi getContainer()-metodi, jolta container pyydetään aina tarvittaessa, ettei sitä aseteta isActive:n sivuvaikutuksena. Vaihtoehtoisesti $this->container:n voisi asettaa constructorissa.

2023-03-03 13:17 UTC, EreMaijala commented on module/FinnaApi/src/FinnaApi/Controller/BazaarApiController.php
> +        $authHash = $this->serviceLocator
getTable-metodi löytyisi valmiina

2023-03-03 13:17 UTC, EreMaijala commented on module/FinnaApi/src/FinnaApi/Controller/BazaarApiController.php
> +        $baseUrl = $this->getServerUrl('home');
module config:ssa on määritelty reitti search-bazaar (tehdään $staticRoutes-lisäyksen perusteella), niin käytetään sitä suoraan home:n sijaan.

2023-03-03 13:17 UTC, EreMaijala commented on module/FinnaApi/src/FinnaApi/Controller/BazaarApiController.php
> +        $browseUrl = $baseUrl . 'Search/Bazaar?hash=';
Tuntuisi luontevammalta lykätä hash tuohon perään heti eikä vasta alempana.

2023-03-03 13:17 UTC, EreMaijala commented on module/FinnaApi/src/FinnaApi/Controller/BazaarApiController.php
> +        if (!$value = $payload[$name] ?? null) {
Sulut lisää, niin on selkeämpi:
`if (!($value = $payload[$name] ?? null)) {`

2023-03-06 08:00 UTC, aleksip commented on module/Finna/src/Finna/View/Helper/Root/BazaarSession.php
> +        $this->container = $this->session->getStorage()->offsetGet(self::NAMESPACE);
Tässä tarkoituksena nimenomaan estää tuo, eli container ei asetu tämän seurauksena?

2023-03-06 08:03 UTC, EreMaijala commented on module/Finna/src/Finna/View/Helper/Root/BazaarSession.php
> +        $this->container = $this->session->getStorage()->offsetGet(self::NAMESPACE);
Nyt en ymmärtänyt, voitko tarkentaa?

2023-03-06 08:20 UTC, aleksip commented on local/config/finna/config.ini.sample
> +;client['client_id'] = secret
Lukee, mutta otetaan toki pois jos ei käytetä!

2023-03-08 13:44 UTC, EreMaijala requested changes

2023-03-08 13:44 UTC, EreMaijala commented on module/Finna/src/Finna/AjaxHandler/BazaarAddResource.php
> +<?php
Tämän nimi voisi olla BazaarEndSession tms. jotta se vastaisi sitä, mitä se oikeasti tekee.

2023-03-09 07:11 UTC, EreMaijala approved these changes

2023-03-09 07:14 UTC, merged