[ALLI-7186] Add sort for holds list
NatLibFi/NDL-VuFind2 pull request #2439
Opened 2022-11-08 13:48 UTC by rajaro

2022-11-09 08:17 UTC, EreMaijala requested changes

2022-11-09 08:17 UTC, EreMaijala commented on module/Finna/src/Finna/Controller/HoldsController.php
> +            $aDate = $aDetail
Nämä mahtuvat yhdelle riville, eikö?

2022-11-09 08:17 UTC, EreMaijala commented on module/Finna/src/Finna/Controller/HoldsController.php
> +                    'desc' =>  'hold_available',
Tälle oma käännös, ja kuvauksena olisi parempi esim. "Noudettavissa olevat ensin".

2022-11-09 08:17 UTC, EreMaijala commented on module/Finna/src/Finna/Controller/HoldsController.php
> +            return $order === 'asc' ? $aDate - $bDate : $bDate - $aDate;
Jos päiväys on sama, sortataan toissijaisesti noudettavissa olevat ensin ja vielä sen jälkeen vaikka titlen mukaan, jotta saadaan järkevä pysyvä järjestys.

2022-11-30 18:53 UTC, EreMaijala requested changes

2022-11-30 18:53 UTC, EreMaijala commented on local/languages/finna/en-gb.ini
> +hold_sort_available = "Available for Pickup first"
pienellä p:llä

2022-11-30 18:53 UTC, EreMaijala commented on local/languages/finna/sv.ini
> +hold_sort_available = "Kan avhämtas först"
"Avhämtningbara först"

2022-11-30 18:53 UTC, EreMaijala commented on module/Finna/src/Finna/Controller/HoldsController.php
> +            return strcmp(
Käytetään titlen vertailuun [Sorter](module/VuFind/src/VuFind/I18n/Sorter.php)-luokkaa, muuten ei mene ääkköset ym oikein.

2022-12-02 07:57 UTC, EreMaijala commented
@rajaro Mergeäisitkö uusimman dev:n, niin pääsee tarkistamaan asemoinnin?

2022-12-02 07:58 UTC, EreMaijala requested changes
Issuessa mainitaan, että aiemmin on ollut nimekkeen mukaisessa järjestyksessä, mutta nyt sitä ei enää ole. Pitäisi pystyä sorttaamaan myös nimekkeen mukaan, eikä varauksen luontipäiväkään olisi huono.

2022-12-02 09:03 UTC, rajaro commented
Asemointi korjattu ja lisäsin sortit nimekkeelle ja luontipäivälle (nouseva ja laskeva)

2022-12-08 11:53 UTC, EreMaijala requested changes
Ei mene vieläkään nätisti, jos on varausten muokkaus käytössä (Demo-ajurilla esim. Holds-sektiossa `updateFields = frozen:frozenThrough:pickUpLocation`).

2022-12-15 13:34 UTC, EreMaijala requested changes
Ei mene vieläkään nätisti. dev:ssä on viilattu nappuloiden välit ja "Valitse sivu" -tekstin asemointi kohdalleen, nyt tässä menee vähän vinoon. Kahden ensimmäisen nappulan pystyväli on eri kuin kolmannen.

Lopputulos on nyt muutenkin sekava, kun nappulat rivittyvät leveälläkin näytöllä. Pasin kanssa pohdittiin, että voisi järjestämisen nostaa omalle rivilleen nappuloiden yläpuolelle. Silloin nappuloihin ei tarvitsisi koskea ollenkaan.

2023-01-18 19:37 UTC, EreMaijala requested changes

2023-01-18 19:37 UTC, EreMaijala commented on themes/finna2/templates/holds/list.phtml
> +                  <div class="holds-sort"><?=$this->context($this)->renderInContext("myresearch/controls/sort.phtml", ['sortList' => $this->sortList])?></div>
Ei voi laittaa diviä tr:n sisään.

2023-01-18 19:37 UTC, EreMaijala commented on themes/finna2/templates/holds/list.phtml
> +                <td class="holds-sort"><?=$this->context($this)->renderInContext("myresearch/controls/sort.phtml", ['sortList' => $this->sortList])?></td>
Olisi varmaan yhtenäisempää käyttää samaa asettelua (järjestäminen omalla rivillään) vaikka yhtään nappulaa ei olisi.

2023-01-20 13:49 UTC, rajaro commented on themes/finna2/templates/holds/list.phtml
> +                  <div class="holds-sort"><?=$this->context($this)->renderInContext("myresearch/controls/sort.phtml", ['sortList' => $this->sortList])?></div>
Aivan. Otin koko elementin pois koko tablesta kun samassa paikassa omalla rivillään jokatapauksessa

2023-01-23 12:14 UTC, EreMaijala commented
Mitä @pasitiis sanot lopputuloksesta? Pitäisiköhän nyt tuon "Järjestä" -labelin näkyä kapeammillakin näytöillä ja onko muuten ok?

2023-01-23 15:13 UTC, pasitiis commented
Labelin näkyminen selkeyttäisi toimintoa mobiilissa, mutta kun se on piilotettu esim. lainat-osiossa, niin ehkä pitäisin yhtenäisyyden. 

Menisin nyt tällä ratkaisulla. Pitää erikseen miettiä, miten mobiilia saisi parannettua oma tili -osioiden välillä.

2023-01-24 09:41 UTC, EreMaijala approved these changes

2023-01-24 09:43 UTC, pasitiis approved these changes

2023-01-24 11:27 UTC, merged