Changed tooltip links to buttons
NatLibFi/NDL-VuFind2 pull request #2447
Opened 2022-11-14 11:49 UTC by siiriylonen

2022-11-15 08:30 UTC, EreMaijala requested changes

2022-11-15 08:30 UTC, EreMaijala commented on themes/finna2/less/finna/organisation-page.less
>                          &:hover {
Tätä hover-sääntöä ei varmaan enää tarvita, vai?

2022-11-15 08:30 UTC, EreMaijala commented on themes/finna2/less/finna/organisation-page.less
> +                        color: #007c90;
Tässä pitäisi olla `color: @link-color;`

2022-11-15 08:30 UTC, EreMaijala commented on themes/finna2/less/finna/organisation-page.less
> +                        padding: inherit;
Olisiko turvallisempaa laittaa  `border: none;` ja `padding: 0;`, niin ei mahdolliset ylemmän tason elementin tee kummia?

2022-11-16 08:24 UTC, EreMaijala approved these changes
Minusta näyttää nyt hyvältä. Odotetaan vielä @pasitiis hyväksyntää.

2022-11-16 11:56 UTC, pasitiis approved these changes

2022-11-22 08:43 UTC, merged