ALLI-7728 loans-page buttons alligned
NatLibFi/NDL-VuFind2 pull request #2455
Opened 2022-11-17 13:51 UTC by siiriylonen

2022-11-17 14:01 UTC, EreMaijala requested changes
Muuten hyvä, mutta kapealla näytöllä (esim. iPhone SE, 380px) ei rivity oikein.
Ennen:
![Näyttökuva 2022-11-17 kello 15 59 28](https://user-images.githubusercontent.com/1327659/202466297-a7df61a3-f77c-4513-8d7d-7e6c85204df7.png)

Nyt:
![Näyttökuva 2022-11-17 kello 15 59 50](https://user-images.githubusercontent.com/1327659/202466331-f8f0be2b-8d1f-4631-a7c1-4eaef38098a3.png)

2022-11-18 13:44 UTC, pasitiis commented on themes/finna2/templates/myresearch/checkedout.phtml
> +                        <input type="submit" class="btn-primary btn-sm" id="renewSelected" name="renewSelected" value="<?=$this->transEscAttr('renew_selected')?>" class="btn btn-default dropdown-togg
Vaihtaisin luokaksi "btn btn-primary dropdown-toggle" -> vastaava mitä oma tilin varaukset sivulla (/Holds/List) on jo käytetty. Toiminnon pitäisi näyttää samalta.

2022-11-18 13:44 UTC, pasitiis commented on themes/finna2/templates/myresearch/checkedout.phtml
> +                          <input type="submit" class="btn-primary btn-sm" id="renewAll" name="renewAll" value="<?=$this->transEscAttr('renew_all')?>" class="btn btn-default dropdown-toggle" data-togg
Tähän sama muutos kuin ylempänä.

2022-11-23 09:18 UTC, EreMaijala requested changes
@siiriylonen Nyt toimii hyvin. Huomasin kuitenkin, että varastotilauksissa ja kaukolainapyynnöissä on vastaavia ongelmia, joihin auttaisi, jos tuo nappuloiden tyyli koskisi niitäkin. Ne ovat myresearch-table -luokan sijaan myresearch-grid-list -luokan alla. Voisiko vielä ympätä samaan?

2022-11-23 12:58 UTC, pasitiis commented
@siiriylonen Aavistuksen myös yhtenäistäisin eri näyttökokoja. Paikkeiden marginaali harmaaseen linjaan poikkeaa eri näyttökoissa (xs, sm, md ja lg). Lisäksi mobiilissa käyttäisin toimintojen välillä samaa pystyväliä. 
<img width="631" alt="Näyttökuva 2022-11-23 kello 14 44 57" src="https://user-images.githubusercontent.com/1954586/203552286-0d491219-4510-41db-8ecb-218309752247.png">
<img width="776" alt="Näyttökuva 2022-11-23 kello 14 46 03" src="https://user-images.githubusercontent.com/1954586/203552451-a0dc86e2-715c-4247-ad19-b4a21200eb03.png">
<img width="434" alt="Näyttökuva 2022-11-23 kello 14 42 35" src="https://user-images.githubusercontent.com/1954586/203552497-51e27b07-59cf-4873-8475-b5125e34192b.png">

2022-11-29 10:27 UTC, EreMaijala requested changes
Sopivalla leveydellä menevät nappulat nyt kiinni toisiinsa:
![Näyttökuva 2022-11-29 kello 12 26 34](https://user-images.githubusercontent.com/1327659/204505029-6389eb0c-7142-41f5-b8a8-9fea0ac72b94.png)
![Näyttökuva 2022-11-29 kello 12 26 15](https://user-images.githubusercontent.com/1327659/204505034-3c4c9f4e-0c23-4ece-9817-a1753e269e2d.png)

2022-11-30 14:03 UTC, siiriylonen commented
Varaukset-sivusta en osaa sanoa, koska en näe tuota Muokkaus-nappulaa, mutta muuttelin marginaaleja ja se on nyt ok? Ongelmana tässä on nyt ollut, että nappulat eivät mobiilissa ole yhtä lähellä alaviivaa kuin muualla. En nyt ainakaan itse näytä saavan niitä kohdalleen, koska muotoilut tulevat muutamasta eri paikasta.

2022-11-30 18:39 UTC, EreMaijala approved these changes

2022-12-01 14:05 UTC, pasitiis approved these changes

2022-12-01 14:20 UTC, merged