[ALLI-7736] Add support for container record formats and curated records
NatLibFi/NDL-VuFind2 pull request #2460
Opened 2022-11-24 13:27 UTC by aleksip

2022-11-29 07:59 UTC, EreMaijala requested changes

2022-11-29 07:59 UTC, EreMaijala commented on module/Finna/src/Finna/Record/Loader.php
> +                $result = parent::load($parts[0]);
En laittaisi parenttia `$result`-muuttujaan, ettei hämmennä. Ehkä ennemmin `$parentRecord` tms.

Pieni kommentti siitä, että koitetaan ensin ladata parent ja siitä encapsuloitu tietue, auttaisi ymmärtämään, mitä tapahtuu.

Pieni huoli siitä, että tämä tekee turhaa työtä ID:illä, joissa on alaviiva (aika yleinen), mutta ehkä yritys ladata olematon tietue on sen verran harvinainen, ettei se haittaa.

2022-11-29 07:59 UTC, EreMaijala commented on module/Finna/src/Finna/AjaxHandler/GetEncapsulatedRecords.php
> +        $html = $this->helper->loadMoreEncapsulatedRecords(
"More" ainakin pois metodin nimestä, kun ei se kai vaadi mitään alkulatausta ensin, vai kuinka? Olisiko parempi `renderEncapsulatedRecords` kun se tuottaa html:ää?

2022-11-29 07:59 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/Feature/ContainerFormatTrait.php
> +    protected PluginManager $driverManager;
Nimeäisin `$recordDriverManager` ettei sekoitu esim. ILS-drivereihin.

2022-11-29 07:59 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/Feature/ContainerFormatTrait.php
> +    public function attachDriverManager(PluginManager $driverManager): void
`attachRecordDriverManager`?

2022-11-29 07:59 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/Feature/ContainerFormatTrait.php
> +     * Names of specific encapsulated record XML elements.
Kaikki ei välttämättä ole XML:ää. Pitäisin mahdollisena myös sen, että olisi vaikka JSON-muotoisia tietueita (kuten MARC-tietueet ovat jatkossa). Näin ollen ainakin pitäisi tietuetta kaivelevat kohdat tehdä niin, että ne voi yliajaa ilman muuta kopiointia. Ehkä tätä taulukkomappausta selkeämpää olisi, että olisi getterit tyyliin `getEncapsulatedRecordFormat($record)`, ja oletustoteutus XML-tietueelle, jossa format-elementti.

2022-11-29 07:59 UTC, EreMaijala commented on module/Finna/src/Finna/View/Helper/Root/Record.php
> +        int $indexStart = null
Miksi välillä on `startIndex` ja välillä `indexStart`?

2022-11-29 07:59 UTC, EreMaijala commented on module/Finna/src/Finna/View/Helper/Root/Record.php
> +        $this->driver = $this->loader->load($id);
Record-helpperi pitäisi invoke:ta driver:lla, jota halutaan käyttää. Tämä rikkoo nyt rakennetta.

2022-12-13 08:06 UTC, aleksip commented on module/Finna/src/Finna/Record/Loader.php
> +                $result = parent::load($parts[0]);
Erotinmerkin voisi tietysti muuttaa harvinaisemmaksi? Itse mietin alun perin risuaitaa.

2022-12-15 07:08 UTC, EreMaijala requested changes

2022-12-15 07:08 UTC, EreMaijala commented on module/Finna/src/Finna/View/Helper/Root/Record.php
> +        $loadMore = $offset !== null;
Pitäisikö myös `$offset === 0` huomioida?

2022-12-15 07:08 UTC, EreMaijala commented on module/Finna/src/Finna/View/Helper/Root/Record.php
> +                'indexStart' => $idStart,
Lisätään tähän aina jotain, esim. 1000, niin ei mene koskaan sekaisin, vaikka samalla sivulla olisi muita tietuelistoja. Oikeastaan haluaisin näille id:ille oman prefiksin, mutta nykyinen systeemi ei sitä tue.

2022-12-19 08:12 UTC, EreMaijala commented on module/Finna/src/Finna/Record/Loader.php
> +                $result = parent::load($parts[0]);
Risuaita voi sekoittua hämmentävästi url:n hashiin. Ehkä putki `|`?

2022-12-19 08:26 UTC, EreMaijala requested changes

2022-12-19 08:26 UTC, EreMaijala commented on module/Finna/src/Finna/View/Helper/Root/Record.php
> +        $resultsCopy = clone $this->encapsulatedResults;
Voisiko tämän tehkä callback-metodilla, joka annetaan constructorissa? Silloin ei tarvitsisi luoda encapsulatedResults:ia etukäteen eikä muistaa `clone`:a. Tyyliin: `$resultsCopy = $this->getEncapsulatedResults(new Parameters($opt))`

Ja factoryn constructor-kutsussa:

```
            [...],
            $container->get(\VuFind\Form\Form::class),
            function ($params) {
                $result = clone $container->get(\VuFind\Search\Results\PluginManager::class)
                    ->get('EncapsulatedRecords');
                $result->initFromRequest($params);
                return $result;
            }
        );
```

2022-12-21 08:16 UTC, EreMaijala requested changes

2022-12-21 08:16 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/encapsulated-records.phtml
> +          <button class="btn btn-outline-primary load-more" aria-label="<?= $this->transEsc('See all')?>" data-id="<?= $this->escapeHtmlAttr($this->id)?>" data-start-index="<?= $this->escapeHtmlAttr(
transEscAttr attribuuteille

2022-12-21 08:33 UTC, EreMaijala approved these changes

2022-12-21 08:33 UTC, merged