[ALLI-7161] textarea for reporting comments
NatLibFi/NDL-VuFind2 pull request #2462
Opened 2022-11-29 11:31 UTC by siiriylonen

2022-11-29 13:03 UTC, siiriylonen commented
Luo sarakkeen:
ALTER TABLE finna_comments_inappropriate ADD elaborate_reason VARCHAR(1000) DEFAULT NULL;

2022-12-01 08:09 UTC, EreMaijala requested changes

2022-12-01 08:09 UTC, EreMaijala commented on module/Finna/src/Finna/Controller/CommentsController.php
> +            $elaborateReason = $this->params()->fromPost('elaborateReason');
Oletusarvoksi (toinen parametri) `''`.

2022-12-01 08:09 UTC, EreMaijala commented on module/Finna/sql/mysql.sql
> +  `elaborate_reason` varchar(1000) DEFAULT NULL,
Voisikohan tämän nimetä vaikka `message`? Olisi vähän lyhyempi ja erottuisi reason-kentästä paremmin.

2022-12-01 09:38 UTC, EreMaijala commented on themes/finna2/templates/comments/inappropriate.phtml
> +  <p>Tarkennus miksi on asiaton:</p>
Tämä kielitiedostoihin ja transEsc:llä näytölle (kuten muissakin kohdissa). Tekstiksi esim. 'Tarkempi kuvaus (vapaaehtoinen)'.

2022-12-01 13:02 UTC, EreMaijala requested changes
Vielä tarvitaan käännökset. Tässä ehdotus yksinkertaisista käännöksistä:
sv: "Beskrivning (valfritt)"
en-gb: "Description (optional)"

2022-12-01 13:02 UTC, EreMaijala commented on themes/finna2/templates/comments/inappropriate.phtml
> +  <p><?=$this->transEsc('report_inappropriate_info') ?></p>
Kaksoispiste vielä perään, kun edellisessäkin on.

2022-12-01 13:23 UTC, EreMaijala approved these changes

2022-12-01 13:29 UTC, merged