[ALLI-7726] Video player cookie consent
NatLibFi/NDL-VuFind2 pull request #2463
Opened 2022-12-01 13:47 UTC by LuomaJuha

Adds 2 custom elements:
- finna-video
- finna-consent

All the logic of displaying videos are moved into the finna-video element. The element loads required js files, when they are needed. This applies also to the finna.videoPopup module, it is now loaded only when a videoplayer is being added to the dom.
Finna-consent is also loaded when it is needed.

The old style of moving the video player with javascript after the searchbox is now removed and the player is appended when the dom is created in php.

Added alots of comments also, thats why there is so much added lines.

2022-12-08 12:43 UTC, EreMaijala commented
@LuomaJuha Irrotetaan script loader ja siihen liittyvät muutokset tästä ja tehdään ne ensin.

2022-12-09 07:59 UTC, EreMaijala requested changes
ks. aiempi kommentti

2022-12-09 11:29 UTC, LuomaJuha commented
@EreMaijala uusi pr tuosta scriptLoaderista tehty.

2022-12-14 19:11 UTC, EreMaijala requested changes

2022-12-14 19:11 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/core.phtml
> +    <?php if (!empty($videoUrls) && !$this->config()->inlineVideoEnabled()): ?>
Tämä tarkistus olisi ehkä turvallisempi tehdä record-video-player.phtml:n alussa. Silloin ei tarvitsisi tehdä joka paikassa, ja core.phtml:iä saattaa hyvin olla yliajettu näkymissä.

2022-12-14 19:11 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/record-video-player.phtml
> +      $hasConsent = !$cookieConsent->isEnabled() || $cookieConsent->isCategoryAccepted('video');
Vaadittava kategoria pitäisi pystyä määrittelemään asetuksissa. 'video' on hyvä oletus, mutta pitää pystyä laittamaan jokin muukin.

2022-12-14 19:11 UTC, EreMaijala commented on themes/finna2/js/finna-cookie-consent-element.js
> +    divDescription.append(divActions);
divActions ei pidä olla divDescriptionin alla vaan samalla tasolla eri divInfo:n alla. Nyt ei tyylit mene oikein ja nappulat on ihan kiinni descriptionissa.

2022-12-14 19:11 UTC, EreMaijala commented on themes/finna2/js/finna-cookie-consent-element.js
> +    aOuterLink.append(linkIcon);
linkIcon:n eteen tarvitaan whitespace. Nyt menee kiinni tekstiin.

2022-12-14 19:11 UTC, EreMaijala commented on themes/finna2/js/finna-video-element.js
> +        {'js-cookie-consent': 'finna-cookie-consent-element.js'},
key voisi olla vain 'cookie-consent', muuten tulee toistoa.

2022-12-16 13:41 UTC, pasitiis commented on themes/finna2/templates/Helpers/organisation-info.phtml
> -          'Open in a new window' => 'Open in a new window',
Tämä ei kuulu tähän PR:ään?

2022-12-19 08:17 UTC, LuomaJuha commented on themes/finna2/templates/Helpers/organisation-info.phtml
> -          'Open in a new window' => 'Open in a new window',
Kyllä se kuuluu, tarvitsin tuota translaatioavainta niin siirsin sen paikkaa.

2022-12-19 09:25 UTC, pasitiis approved these changes

2022-12-19 18:12 UTC, EreMaijala requested changes

2022-12-19 18:12 UTC, EreMaijala commented on local/config/vufind/CookieConsent.yaml.sample
> +    RecordVideoPlayer:
Justiinsa hokasin, että meillähän on jo Matomo esimerkkinä siitä, miten kategoria ohjaa toimintoa, eli kategorian asetuksissa voi olla `ControlVuFindServices`. Käytetään sitä tähänkin. Eli kategoria kertoo, että se ohjaa RecordVideoPlayeria eikä toisin päin.

2022-12-20 07:51 UTC, LuomaJuha commented on local/config/vufind/CookieConsent.yaml.sample
> +    RecordVideoPlayer:
Ah, laitetaas sit niin

2022-12-20 09:21 UTC, EreMaijala requested changes

2022-12-20 09:21 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/record-video-player.phtml
> +      $consentSettings = $cookieConsent->getConsentSettingsForService('video');
cookieConsent-helpperillä on `isServiceAllowed`-metodi, jota voi käyttää suoraan, eli ei tartte hakea asetuksia erikseen ja tarkistaa kategoriaa. Vastaava löytyy myös js:stä. Ks. https://vufind.org/wiki/configuration:cookie_consent#information_for_developers)

2022-12-20 10:36 UTC, LuomaJuha commented on themes/finna2/templates/RecordDriver/DefaultRecord/record-video-player.phtml
> +      $consentSettings = $cookieConsent->getConsentSettingsForService('video');
No toihan on näppärä. Pitääkin muokata tuohon.

2022-12-20 12:35 UTC, LuomaJuha commented
Noni, jäi pari hommaa puskematta. Piti jättää tohon funktio, et sain ton categoryn titlen ees jotenkin haettavaksi ku sitä ei näköjään mitenkään saanu sieltä ulos.

2022-12-21 09:11 UTC, EreMaijala commented
@LuomaJuha Mergeäisitkö dev:n tänne?

2022-12-21 09:14 UTC, EreMaijala requested changes

2022-12-21 09:14 UTC, EreMaijala commented on module/Finna/src/Finna/View/Helper/Root/CookieConsent.php
> +     * Get cookie consent title for service.
"Get title of required category for a service"

2022-12-21 09:14 UTC, EreMaijala commented on module/Finna/src/Finna/View/Helper/Root/CookieConsent.php
> +    public function getServiceTitle(string $service): string
getCategoryTitleForService

2022-12-21 11:51 UTC, EreMaijala approved these changes

2022-12-21 11:54 UTC, merged