[ALLI-6601] Username display when logged in
NatLibFi/NDL-VuFind2 pull request #2465
Opened 2022-12-02 08:20 UTC by siiriylonen

2022-12-08 12:29 UTC, EreMaijala requested changes

2022-12-08 12:29 UTC, EreMaijala commented on themes/finna2/templates/myresearch/profile.phtml
> +
Ylimääräinen muutos

2022-12-08 12:29 UTC, EreMaijala commented on themes/finna2/templates/navibar.phtml
> +            <a href="#" role="menuitem" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i id="account-icon" class="fa fa-user fa-lg" aria-hidden="true"></i><span class="username lo
Tuo span selitystekstillä "logged_in_as" ei nyt enää kuulu tuohon. Sen sijaan se voisi olla hyvä profile-sivulla.

2022-12-08 13:59 UTC, pasitiis approved these changes

2022-12-09 07:33 UTC, pasitiis commented on themes/finna2/templates/myresearch/profile.phtml
> +          <i id="account-icon" class="fa fa-user"></i><span class="sr-only"><?=$this->transEsc('logged_in_as')?>: </span><?=$this->escapeHtml($user->getDisplayName(), 20) ?>
Tässä taitaa olla vielä tekstin katko (20 merkkiä), jota ei tarvita omat tiedot sivulla.

2022-12-09 08:00 UTC, EreMaijala approved these changes

2022-12-09 08:01 UTC, merged