[ALLI-7717] Text about fetching info to organisation page
NatLibFi/NDL-VuFind2 pull request #2468
Opened 2022-12-07 08:54 UTC by siiriylonen

2022-12-07 15:15 UTC, pasitiis commented
Käännökset tuntuvat pitkiltä. Tein Jiraan ehdotuksen tekstien tiivistämiseksi.

2022-12-08 12:26 UTC, EreMaijala requested changes
Laittaisin käännösavaimeksi `organisation_data_source_desc` ja luokaksi `organisation-data-source-desc` tai `source-desc`.

2022-12-08 12:26 UTC, EreMaijala commented on local/languages/finna/en-gb.ini
> +organisation_fetched_from ="The data is retrieved from Kirkanta and from the museum database of the Finnish Museums Association. The data is maintained by libraries, archives and museums."
Välilyönti yhtäsuuruusmerkin perään.

2022-12-08 13:36 UTC, pasitiis approved these changes

2022-12-09 07:15 UTC, EreMaijala requested changes

2022-12-09 07:15 UTC, EreMaijala commented on themes/finna2/less/finna/organisation-page.less
> +        .source_desc {
Luokkien nimet väliviivalla: `source-desc`.

2022-12-09 07:15 UTC, EreMaijala commented on themes/finna2/less/finna/organisation-page.less
> +            margin-top: 30px;
Tsekkaa sisennys.

2022-12-09 08:19 UTC, EreMaijala approved these changes

2022-12-09 08:20 UTC, merged