[ALLI-7756] Add finna.scriptLoader
NatLibFi/NDL-VuFind2 pull request #2473
Opened 2022-12-09 11:16 UTC by LuomaJuha

2022-12-09 12:29 UTC, EreMaijala requested changes

2022-12-09 12:29 UTC, EreMaijala commented on themes/finna2/js/finna-script-loader.js
> +      const found = document.getElementById(key);
key:llä voisi olla jokin prefiksi tyyliin `async-js-`, ettei se vahingossakaan sekoitu muihin id:ihin sivulla. Sitten kutsussa voisi tiputtaa `js-` -prefiksin pois.

2022-12-09 13:44 UTC, LuomaJuha commented on themes/finna2/js/finna-script-loader.js
> +      const found = document.getElementById(key);
jepulis!

2022-12-09 14:57 UTC, LuomaJuha commented on themes/finna2/js/finna-script-loader.js
> +      const found = document.getElementById(key);
Laitoin tuohon vielä vähän dokumentoivamman nimen eteen.

2022-12-14 12:48 UTC, EreMaijala approved these changes

2022-12-14 12:48 UTC, merged