[ALLI-7241] Fix services-icons screen reader issue
NatLibFi/NDL-VuFind2 pull request #2476
Opened 2022-12-15 09:19 UTC by siiriylonen

2022-12-15 11:28 UTC, pasitiis commented on themes/finna2/templates/Helpers/organisation-info.phtml
> +          <span class="sr_only"><?=$this->transEsc('organisation_info_service_wifi')?></span>
vaihda luokan nimeksi sr-only.

2022-12-15 11:28 UTC, pasitiis commented on themes/finna2/templates/Helpers/organisation-info.phtml
> +          <span class="sr_only"><?=$this->transEsc('organisation_info_service_print')?></span>
vaihda luokan nimeksi sr-only.

2022-12-16 07:05 UTC, pasitiis approved these changes

2022-12-20 09:22 UTC, EreMaijala requested changes
Käytä attribuuteille `transEscAttr`.

2022-12-21 09:28 UTC, EreMaijala approved these changes

2022-12-21 09:30 UTC, merged