[ALLI-7760] Replace lazyloading with VuFind.observerManager
NatLibFi/NDL-VuFind2 pull request #2478
Opened 2022-12-15 13:55 UTC by LuomaJuha

Removed jquery inview script and changed finna.common.observeimages to use vufind.observerManager.

2022-12-19 11:54 UTC, siiriylonen approved these changes

2022-12-21 08:02 UTC, EreMaijala requested changes

2022-12-21 08:02 UTC, EreMaijala commented on themes/finna2/theme.config.php
> -        'vendor/hunt.min.js',
Hunt:ia ei voi poistaa vielä, kun sitä käytetään yläjuoksun koodissa. Sotkee esim. OpenURL:ien ja versioiden latauksen.

2022-12-21 08:19 UTC, EreMaijala approved these changes

2022-12-21 08:32 UTC, merged