[ALLI-7801] Add core-fields.phtml templates
NatLibFi/NDL-VuFind2 pull request #2495
Opened 2023-01-17 13:15 UTC by LuomaJuha

2023-01-23 11:18 UTC, EreMaijala requested changes

2023-01-23 11:18 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/core-fields.phtml
> +      $formatter->filterMarcFields($formatter->getDefaults($this->defaults))
Voisi varmaan fiksata vähän tässä yhteydessä, kun ei ole järkeä siinä, että DefaultRecord:ssa on MARC-spesifinen filtteröinti. Kun RecordDataFormatter tietää tietueen, voisi siitä kaivaa formaatin ja sen pohjalta tehdä vaikka `filterCoreFields`-metodin, joka sitten tekee oikean suodatuksen formaatin perusteella.

2023-01-23 12:22 UTC, LuomaJuha commented on themes/finna2/templates/RecordDriver/DefaultRecord/core-fields.phtml
> +      $formatter->filterMarcFields($formatter->getDefaults($this->defaults))
Jes, kuulostaa passelilta.

2023-01-25 08:33 UTC, EreMaijala requested changes

2023-01-25 08:33 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/core-fields.phtml
> +    <?php if (!empty($this->openUrlActive)): ?>
Käytetään samaa muotoa kaikkialla; joko `$openUrlActive` tai `$this->openUrlActive`.

2023-01-25 08:33 UTC, EreMaijala commented on module/Finna/src/Finna/View/Helper/Root/RecordDataFormatter.php
> +            throw new Exception("Core fields for record type $type not found.");
`"Unhandled record type $type"` ?

2023-01-25 09:16 UTC, EreMaijala approved these changes

2023-01-25 09:19 UTC, merged