[ALLI-7451] Add MARC field 341 (a, b) to core details
NatLibFi/NDL-VuFind2 pull request #2505
Opened 2023-01-24 16:22 UTC by tmikkonen

2023-01-25 09:43 UTC, EreMaijala requested changes
Meillä on jo getAccessibilityFeatures (SolrLrmi) otsikolla "Saavutettavuuden ominaisuudet". Voisiko nämä yhdistää? Ei vaikuta järkevältä, että on monta melkein samanlaista.

2023-01-25 09:43 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrMarc.php
> +        if ($fields = $this->getFieldArray('341', ['a', 'b'], true, ' : ')) {
Kaksoispisteen vasemmalla puolella ei ainakaan issuen mukaan pidä olla välilyöntiä.

2023-01-25 09:43 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrMarc.php
> +        $results = [];
Tämä on turha muuttuja. getFieldArray:n paluuarvon voi aina palauttaa suoraan.

2023-01-25 09:43 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrMarc.php
> +    public function getAccessibility()
Lisää paluuarvon tyyppi: `public function getAccessibility(): array`

2023-01-25 12:59 UTC, EreMaijala requested changes
Onko nykyisten käännösten sopivuus tarkistettu?

2023-01-25 12:59 UTC, EreMaijala commented on module/Finna/src/Finna/View/Helper/Root/RecordDataFormatterFactory.php
> +            'Accessibility Feature',
Tälle on jo templaattirivi getAccessibilityFeatures-metodia varten.

2023-01-25 14:53 UTC, tmikkonen commented on module/Finna/src/Finna/View/Helper/Root/RecordDataFormatterFactory.php
> +            'Accessibility Feature',
Selvitän käännöksen sopivuutta.

getAccessibilityFeatures-metodille on olemassa 'Accessibility Features', niin käytin tässä erotuksena 'Accessibility Feature'. Tuleeko käyttää samaa vai erottaa selvemmin toisistaan? Sama metodi tuskin toimii molempiin.

2023-03-13 09:24 UTC, EreMaijala requested changes

2023-03-13 09:24 UTC, EreMaijala commented on module/Finna/src/Finna/View/Helper/Root/RecordDataFormatterFactory.php
> +            'Accessibility Feature',
Miksei sama metodi toimisi? getAccessibilityFeatures olisi silläkin hyvä, että kun MARC-kenttä 532 tulee mukaan, sen saa samaan yhteyteen silloin kun sen 1. indikaattori on 0 tai 1 (ja vastaavasti getAccessibilityHazards, kun 532:n 1. indikaattori on 2).

2023-03-16 17:28 UTC, tmikkonen commented on module/Finna/src/Finna/View/Helper/Root/RecordDataFormatterFactory.php
> +            'Accessibility Feature',
Jostain syystä kuvittelin, ettei MARC:lla voi olla samannimistä metodia, joka on käytössä jo LRMI:llä :)

2023-03-17 07:36 UTC, EreMaijala commented on module/Finna/src/Finna/View/Helper/Root/RecordDataFormatterFactory.php
> +            'Accessibility Feature',
Nimenomaan käytetään samannimisiä tekemään sama asia, niin pysyy jotenkin hallussa tämä. Ehkä. :)

2023-03-17 07:38 UTC, EreMaijala requested changes

2023-03-17 07:38 UTC, EreMaijala commented on module/Finna/src/Finna/View/Helper/Root/RecordDataFormatterFactory.php
> +        $setTemplateLine(
Tämä on nyt tupla, poistettava.

2023-03-17 14:02 UTC, EreMaijala approved these changes

2023-03-17 14:10 UTC, merged