[ALLI-6724] Add accessibility information about accordion status
NatLibFi/NDL-VuFind2 pull request #2508
Opened 2023-01-26 13:21 UTC by siiriylonen

2023-01-26 14:12 UTC, EreMaijala requested changes

2023-01-26 14:12 UTC, EreMaijala commented on themes/finna2/js/finna-record.js
> +      var itemChildren = item.querySelector('fa-arrow-down');
Tämä ei toimi, pitäisi olla `.fa-arrow-down`, mutta on vähän vaarallista luottaa ikonin luokkaan. Jos ei muuta löydy, niin pitää lisätä. Mutta ei näytä muutenkaan olevan oikein laittaa lisää-nappulalle aria-expanded:ia.

2023-01-26 14:12 UTC, EreMaijala commented on themes/finna2/js/finna-record.js
> +      item.setAttribute('tabindex', '0');
Jos jotain tehdään kaikille aina, niin se pitäisi tehdä templaatissa valmiiksi.

2023-01-26 14:12 UTC, EreMaijala commented on themes/finna2/js/finna-record.js
> +      if ($(e.target).parent().attr('aria-expanded') === 'false') {
Saako aria-expanded jossain alkuarvon ennen ekaa klikkausta?

2023-01-31 12:44 UTC, siiriylonen commented on themes/finna2/js/finna-record.js
> +      if ($(e.target).parent().attr('aria-expanded') === 'false') {
setUpHoldingsTab():issä saa alkuarvon

2023-02-08 12:33 UTC, pasitiis commented
Jännä juttu että space-näppäimellä avattessa sivu skrollaa mutta ei enterillä (Firefox). Sivun ei pitäisi skrollata kun elementin avaa.

2023-02-09 09:26 UTC, EreMaijala requested changes

2023-02-09 09:26 UTC, EreMaijala commented on themes/finna2/js/finna-record.js
> +      }
Tyylikorjaus:
```
if  {
  ...
} else {
  ... 
}
```

2023-02-09 09:26 UTC, EreMaijala commented on themes/finna2/js/finna-record.js
> +      } else { item.setAttribute('aria-expanded', 'false'); }
Tyylikorjaus:
```
if  {
  ...
} else {
  ... 
}
```

2023-02-09 09:26 UTC, EreMaijala commented on themes/finna2/js/finna-record.js
> +    var accordionActivation = document.querySelectorAll('.location');
Eikö aria-expanded:n alkuarvot voisi laittaa paikalleen templaateissa?

2023-02-09 09:35 UTC, siiriylonen commented on themes/finna2/js/finna-record.js
> +    var accordionActivation = document.querySelectorAll('.location');
Voi laittaa, mutta koska yksi(?) on aina valmiiksi auki, täytyisi ne kuitenkin tarkastaa tässäkin kohtaa?

2023-02-09 10:05 UTC, EreMaijala commented on themes/finna2/js/finna-record.js
> +    var accordionActivation = document.querySelectorAll('.location');
Se riippuu asetuksista, mitä on auki, mutta kyllähän templaatti sen tietää, kun se laittaa collapsed-luokankin sen mukaan.

2023-02-13 09:29 UTC, pasitiis commented
Nyt näyttäisi toimivan oikein näppämistöllä käytettäessä.

2023-02-14 07:56 UTC, pasitiis approved these changes

2023-02-15 11:58 UTC, EreMaijala requested changes

2023-02-15 11:58 UTC, EreMaijala commented on themes/finna2/js/finna-record.js
> +      if ($('.location', this).parent().attr('aria-expanded') === 'false') {
Eikö `$('.location', this).parent()` ole käytännössä sama kuin `$(this)`? Eli turha etsiä mitään, kun voisi tehdä vaikka näin:
`$(this).attr('aria-expanded', function (i, attr) { return attr === 'true' ? 'false' : 'true'; });`

2023-02-17 07:13 UTC, EreMaijala approved these changes

2023-02-17 07:15 UTC, merged