[ALLI-7701] Add copyright information next to pdf-download link
NatLibFi/NDL-VuFind2 pull request #2519
Opened 2023-02-08 12:27 UTC by siiriylonen

2023-02-14 11:00 UTC, EreMaijala requested changes
Ei toimi esimerkkitietueilla: `Undefined array key "link"` SolrLido/core.phtml:124.

2023-02-14 11:00 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/SolrLido/core.phtml
> +                  $rightsDescription = array_unique($this->driver->getAccessRestrictions($language));
Korjataan ennemmin getAccessRestrictions niin, ettei se palauta tuplia.

2023-02-15 12:26 UTC, EreMaijala requested changes
Leiskan mukaan sulut pitäisi olla vain tiedoston tyypin ympärillä. Lisäksi nuolet pitäisi asemoida pystysuunnassa linjaan tekstin kanssa.

Tarvitaanko aria-attribuutteja kertomaan, että tämä on dropdown-tyyppinen kenttä? Voisiko käyttää bootstrap:n dropdown-elementtiä oman JS:n sijaan?

2023-02-15 12:26 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/SolrLido/core.phtml
>                <?php foreach ($documents as $i => $document): ?>
Voisin kuvitella, että tätä saatetaan tarvita muissakin formaateissa. Voisi siis laittaa erilliseen templaattiin DefaultRecord:n alle, ja näyttää tässä samaan tapaan kuin esim. versions-link.phtml vähän ylempänä.

2023-02-15 12:26 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/SolrLido/core.phtml
> +                        <a class="copyright-meaning" href="<?=$this->escapeHtmlAttr($rights['link'])?>" target="_blank"><?=$this->escapeHtmlAttr($rights['copyright']);?></a>
Luokka voisi olla `copyright-description`. Jätä puolipiste pois ennen sulkevaa `?>`.

2023-02-15 12:26 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/SolrLido/core.phtml
> +                        <?=$this->transEsc('Additional Information')?> <i class="fa fa-arrow-down"></i>)
Käytetään uudessa koodissa icon helperiä, esim. `<?=$this->icon('truncate-more')?>` ja `<?=$this->icon('truncate-less')?>`

2023-02-15 12:26 UTC, EreMaijala commented on themes/finna2/js/finna-record.js
> +    $('.show-info.more-link').button().on('click', function handleClick() {
Selektoreina paremmat voisi olla esim.  '.fulltextField .show-info' ja '.fulltextField .hide-info'. Silloin eivät osu muuhun sisältöön mutta eivät myöskään toista tavallaan samaa sisältöä.

2023-02-21 07:32 UTC, siiriylonen commented
Tässä vielä sama bootstrap kautta, ei ihan suoraan toiminut, joten en tiedä kumpi olisi optimaalisempi tapa.

2023-02-21 11:11 UTC, EreMaijala requested changes

2023-02-21 11:11 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/document-rights.phtml
> +    $i = 1;
Laita `$i` static:ksi, niin toimii, vaikka tätä templatea kutsuttaisiin useita kertoja.

2023-02-21 11:11 UTC, EreMaijala commented on themes/finna2/js/finna-record.js
> +    var more = VuFind.translate('Additional Information') + ' ' + VuFind.icon("truncate-more") + ')';
more-tekstihän on jo elementissä valmiiksi. Laita less-teksti vaikka data-attribuuttiin tai ota se hide-info -nappulasta, niin voit vain vaihdella niitä tarpeen mukaan, eikä tartte skriptissä alkaa kokoamaan tekstejä.

2023-02-21 11:11 UTC, EreMaijala commented on themes/finna2/js/finna-record.js
>      };
Turha muutos

2023-02-24 09:37 UTC, EreMaijala requested changes

2023-02-24 09:37 UTC, EreMaijala commented on local/languages/finna/en-gb.ini
> +more_info_hide = "Hide more info"
Tämä käännös ei muuten oikein toimi. "Hide information"?

2023-02-24 09:37 UTC, EreMaijala commented on local/languages/finna/sv.ini
> +more_info_hide = "Dölj mer information"
Tämäkään ei taida toimia. Ehkä vain "Dölj information"?

2023-02-24 09:37 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/document-rights.phtml
> +                <?=$this->transEsc('more_info_hide')?> <?=$this->icon('truncate-less')?>)
Tässä ei pitäisi olla sulkua perässä.

2023-02-24 09:37 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/document-rights.phtml
> +                    <?=$this->transEsc('Additional Information')?> <?=$this->icon('truncate-more')?>)
Tälle vielä oma käännösavain copyright_info_show, ja piilotuksen käännösavaimeksi vastaavasti copyright_info_hide. Muuten voi tulla myöhemmin sotkua, kun "Additional Information" on käytössä muuallakin.

2023-02-24 11:43 UTC, EreMaijala requested changes
Nyt ylälaidan Sulje lisätiedot -linkin oikealta puolelta hävisi sulku.

Jos klikkaa nuolta, vaihtuu teksti ja kuvake, mutta muuten ei tapahdu mitään.

2023-02-24 11:43 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/document-rights.phtml
> +    foreach ($documents as $i => $document):
Ei muuten toi `$i` varmaan toimi oikein, kun se on tässä indeksin muuttujana. Jätä pois tästä ja kasvata sitä joka iteraatiolla itse.

2023-02-24 11:43 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/document-rights.phtml
> +            <p class="access-rights"><?=$this->escapeHtmlAttr(implode("<br/>", $rightsDescription));?></p>
Pitäisi olla escapeHtml. Ja ensin escapet, sitten vasta implode, muuten escapettaa tuon br-tagin.

2023-02-24 11:43 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/document-rights.phtml
> +                    <a class="copyright-description" href="<?=$this->escapeHtmlAttr($rights['link'])?>" target="_blank"><?=$this->escapeHtmlAttr($rights['copyright'])?></a>
Väärä escape sisällössä, pitäisi olla escapeHtml

2023-02-24 11:43 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/document-rights.phtml
> +                    <?=$this->escapeHtmlAttr($rights['copyright']);?>
Väärä escape sisällössä, pitäisi olla escapeHtml

2023-02-24 13:29 UTC, siiriylonen commented
Huomasinkin virheen, joten ei kannata katsoa vielä

2023-02-27 15:03 UTC, pasitiis commented
Näppämistön fokus hukkuu kun suljen lisätiedot, lisäksi fokuksen sininen linja ei näy vasemalla. 
![Näyttökuva 2023-2-27 kello 16 53 25](https://user-images.githubusercontent.com/1954586/221597474-b9726f8f-58ea-43fc-ba1d-5b6f6ae82f62.png).

Ylhäällä näppäimistö fokukseen tulee sulkumerkki mukaan, pitäisi olla siten että sulkumerkki on näppäimistö fokuksen ulkopuolella.

2023-03-01 12:43 UTC, EreMaijala requested changes

2023-03-01 12:43 UTC, EreMaijala commented on themes/finna2/js/finna-record.js
> +    var buttonText = document.querySelectorAll('.show-hide-button');
Tälle parempi nimi (esim. showHideButton...), tai sitten vaan suoraan `document.querySelectorAll('.show-hide-button').forEach...`.

2023-03-01 12:43 UTC, EreMaijala commented on themes/finna2/js/finna-record.js
> +    var more = $('.show-hide-button').html();
Nämä kaikki voisivat olla const:eja.

2023-03-01 12:43 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/document-rights.phtml
> +                <span id='bracket'>)</span>
Ehkä tällä voisi olla vain luokka. Tuntuu kummalta antaa id yksittäiselle sululle. Tai ehkä vielä parempi olisi laittaa heti `</button>`:n perään ilman väliä, niin ei tarvitsisi virittää negatiivista marginaalia.

2023-03-01 12:43 UTC, EreMaijala commented on themes/finna2/js/finna-record.js
> +      var element = $(this).parents('.fulltextField');
hide-nappulaa painettaessa ei koskaan voi olla tapahtumassa näyttäminen, tämän voi yksinkertaistaa niin, että poistaa vain active-luokan ja asettaa more-tekstin.

2023-03-01 12:43 UTC, EreMaijala commented on themes/finna2/js/finna-record.js
> +      $(this).toggleClass('active');
Ei toimi vieläkään, jos vaikka tuplaklikkaa. Nappulan vaihto pitäisi varmaan tehdä collapsen eventtien perusteella, jotta toimisi aina.

2023-03-01 13:56 UTC, siiriylonen commented on themes/finna2/js/finna-record.js
> +      $(this).toggleClass('active');
En tiedä aiheuttaako tässä ongelmia se, kun collapsella on välivaihe, jolloin luokkana on 'collapsing'. Ja se siis näyttäisi tekevän saman, vaikka käyttäisin collapsed luokan katsomista.

2023-03-02 06:17 UTC, EreMaijala commented on themes/finna2/js/finna-record.js
> +      $(this).toggleClass('active');
Tarkoitin sitä, että nappulan tilan vaihtaisi sen perusteella, että tulee collapsen eventti: https://getbootstrap.com/docs/3.4/javascript/#collapse-events
Eli nappulan toiminto vaihdetaan, kun tulee shown.bs.collapse tai hidden.bs.collapse. Esim. embedded_record.js:ssä on selkeä esimerkki.

2023-03-03 08:21 UTC, EreMaijala requested changes
Nyt toimii. Vielä pienet viilaukset ja @pasitiis katselmointi.

2023-03-03 08:21 UTC, EreMaijala commented on themes/finna2/js/finna-record.js
> +      item.innerHTML = more;
Tarvitaanko tätä johonkin? Eikö käytössä ole vain yksi show-hide-button, jolla on oletuksena oikea teksti?

2023-03-03 08:21 UTC, EreMaijala commented on themes/finna2/less/finna-other.less
> -
Tässä tyhjä rivi hävinnyt. Ihan hyvä se on olla, niin helpompi lukea.

2023-03-03 08:21 UTC, EreMaijala commented on themes/finna2/less/finna-other.less
> +}
Tähän samoin tyhjä rivi perään.

2023-03-03 08:21 UTC, EreMaijala commented on themes/finna2/less/finna-other.less
> +.record-links {
Tämä sisältö sopisi paremmin record.less:iin, eikö?

2023-03-03 08:21 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/SolrLido/core.phtml
> +              <?=$this->record($this->driver)->renderTemplate('document-rights.phtml')?>
Välitä `$documents` templaatille parametrina, niin ei tarvitse hakea uudelleen siellä.

2023-03-03 08:21 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/document-rights.phtml
> +<?php
Tälle parempi nimi olisi vaikka `document-links.phtml`. Muuten tulee helposti käsitys, että sisältää vain käyttöoikeudet.

2023-03-03 09:33 UTC, EreMaijala requested changes

2023-03-03 09:33 UTC, EreMaijala commented on themes/finna2/js/finna-record.js
> +      $(this).parents('.fulltextField').find('.show-hide-button').html(less);
Ota vielä show-hide-button talteen muuttujaan ylempänä, niin ei tarvitse hakea uudelleen tässä alemmassa event-handlerissa (ja on käytössä vain yksi selektori sitä varten).

2023-03-03 09:33 UTC, EreMaijala commented on themes/finna2/less/finna-other.less
> +.copyright-wrapper {
Eikö tämäkin mene record.less:iin?

2023-03-03 10:52 UTC, EreMaijala requested changes

2023-03-03 10:52 UTC, EreMaijala commented on themes/finna2/js/finna-record.js
> +      $(this).parents('.fulltextField').find(button).html(less);
Sori, tuli virheellinen ohje, kun en huomioinut, että näitä voi olla monta. Perutaan tämä viimeisin js-muutos.

2023-03-03 10:53 UTC, EreMaijala commented on themes/finna2/js/finna-record.js
> +      $(this).parents('.fulltextField').find('.show-hide-button').html(less);
Olipa huono idea minulta. Ei toimisi, jos kenttiä on useita.

2023-03-03 11:31 UTC, EreMaijala approved these changes

2023-03-06 10:55 UTC, pasitiis approved these changes

2023-03-13 13:23 UTC, merged