[ALLI-7861] Feed overhaul
NatLibFi/NDL-VuFind2 pull request #2533
Opened 2023-02-14 14:33 UTC by LuomaJuha

2023-02-17 07:07 UTC, EreMaijala requested changes

2023-02-17 07:07 UTC, EreMaijala commented on themes/finna2/js/finna-feed-element.js
> +  afterGetFeed(jsonResponse) {
Tämän voisi nimetä vaikka `buildFeedDom`.

2023-02-17 07:07 UTC, EreMaijala commented on themes/finna2/js/finna-feed-element.js
> +      let carousel = ['carousel', 'carousel-vertical'].includes(settings.type);
käytä pelkkää `type` includes:n parametrissa

2023-02-17 07:07 UTC, EreMaijala commented on themes/finna2/js/finna-feed-element.js
> +        carousel = true;
Eikös tämä jo ylempänä tsekattu?

2023-02-17 07:07 UTC, EreMaijala commented on themes/finna2/js/finna-feed-element.js
> +        carousel = true;
Eikös tämä jo ylempänä tsekattu?

2023-02-17 07:07 UTC, EreMaijala commented on themes/finna2/js/finna-feed-element.js
> +        vertical = true;
jos `vertical` käytetään vain carousellissa, niin voisi jättää tämän asettamatta ennen kuin ollaan tuolla `if (carousel)` -blokin sisällä.

2023-02-17 07:07 UTC, EreMaijala commented on themes/finna2/js/finna-feed-element.js
> +    switch (name) {
Kun on vain yksi tapaus, `if` olisi simppelimpi.

2023-02-17 07:07 UTC, EreMaijala commented on themes/finna2/templates/Helpers/feed.phtml
> +<finna-feed class="feed-container" feed-id="<?= $this->id; ?>"></finna-feed>
Pitäisikö id escapeta?

2023-02-17 07:07 UTC, EreMaijala commented on themes/finna2/templates/ajax/feed-carousel-vertical-item.phtml
> +    <?php if (isset($item['title']) || isset($item['dateFull'])): ?>
Sisennys muuttuu tässä kahdesta neljään

2023-02-17 07:07 UTC, EreMaijala commented on themes/finna2/templates/ajax/feed-carousel-vertical-item.phtml
> +    <?php if (isset($item['title']) || isset($item['dateFull'])): ?>
Pitäisikö isset:n sijaan käyttää !empty vai onko tarkoituksella niin, että voisi tulla elementti tyhjänäkin?

2023-02-17 07:07 UTC, EreMaijala commented on themes/finna2/templates/ajax/feed-carousel-vertical-item.phtml
> +            <p><?=$this->escapeHtml($item['text'])?></p>
Tänne tullaan, jos `$clickableLink` on true, vaikka `$item['text']` olisi määrittelemättä..

2023-02-17 07:07 UTC, EreMaijala commented on themes/finna2/templates/ajax/feed-carousel-vertical-item.phtml
> +            <span class="carousel-description"><?= $linkTextEsc ?></span>
Mistä tulee `$linkTextEsc`?

2023-02-17 07:07 UTC, EreMaijala commented on themes/finna2/templates/ajax/feed-carousel.phtml
> +            <?=$this->partial("ajax/feed-$this->type-item.phtml", compact('item', 'linkDescEsc'))?>
Pitäisikö compact:eissa olla linkTextEsc?

2023-02-23 08:04 UTC, LuomaJuha commented on themes/finna2/templates/Helpers/feed.phtml
> +<finna-feed class="feed-container" feed-id="<?= $this->id; ?>"></finna-feed>
hyvä huomio muuten

2023-02-24 11:27 UTC, EreMaijala approved these changes

2023-02-24 11:28 UTC, merged