[ALLI-7371] Replace slick.js with splide.js
NatLibFi/NDL-VuFind2 pull request #2543
Opened 2023-02-28 14:23 UTC by LuomaJuha

2023-03-08 14:20 UTC, pasitiis commented
Splidessä titlePosition = "bottom" -asetuksella "title-bottom"-alue näkyy eri tavalla kuin slickissä. Aiemmin height-arvolla määriteltiin kuvan korkeus, uuudessa totetuksessa korkeus näyttäisi sisältävän myös title-alueen, jolloin kuva voi helposti hukkua title-alueen alle.

Käytin oheisia asetuksia testauksessa:

`[carousel-small]
type = "carousel"
active = 1
url[*]= "https://musasto.wordpress.com/feed/"
title = 'rss'
height = 150
titlePosition = "bottom"`

Splide:
<img width="1244" alt="splide-carousel" src="https://user-images.githubusercontent.com/1954586/223737028-0a6f7374-f5ec-41f3-a1a3-27be54da41e7.png">

Slick:
<img width="1216" alt="slick-carousel" src="https://user-images.githubusercontent.com/1954586/223737039-814bcf96-9a3b-4f86-b9d7-ab49d98d063a.png">

2023-03-10 07:55 UTC, EreMaijala requested changes

2023-03-10 07:55 UTC, EreMaijala commented on local/languages/Carousel/en-gb.ini
> +@parent_ini = "finna/category/en-gb.ini"
väärä polku

2023-03-10 07:55 UTC, EreMaijala commented on local/languages/Carousel/sv.ini
> +@parent_ini = "finna/category/sv.ini"
väärä polku

2023-03-10 07:55 UTC, EreMaijala commented on local/languages/Carousel/fi.ini
> +@parent_ini = "finna/category/fi.ini"
väärä polku

2023-03-10 07:55 UTC, EreMaijala commented on themes/finna2/js/finna-carousel-manager.js
> +  function create(elements, settings) {
Olisko `createCarousel` hyvä nimi, niin olisi selkeämpää, mitä `finna.carouselManager.createCarousel([this], settings);` tekee?

2023-03-10 08:00 UTC, EreMaijala commented
Paginaattori ei taida oikein toimia. Näyttää vain yhden mustan pallukan:
![Uploading Näyttökuva 2023-3-10 kello 10.00.14.png…]()

2023-03-10 08:07 UTC, EreMaijala commented
Teksti ei myöskään laajene hover:lla, vaan kuva menee vain tummaksi.

2023-03-13 07:38 UTC, LuomaJuha commented
@EreMaijala Paginointi toimii kyllä. Tuo on vain ainoa sivu mitä suuremmalla näytöllä on nähtävillä. (3 ns. itemiä). Tekstiä ei näy kun sit ei tule ollenkaan tuossa mukana, joten pitääkin siihen säätää et hover ei olis olemassa jos tekstiä ei löydy.

2023-03-13 08:29 UTC, EreMaijala commented
@LuomaJuha En tajua. Itemeitä on kuitenkin monta sivua, kun voi skrollata nuolilla vaikka kuinka pitkälle. Mitä tuo sivutus sitten edustaa?

2023-03-13 08:41 UTC, LuomaJuha commented
@EreMaijala Se oli Loop tyyppinen karuselli näköjään. Siellä oli myös toinen vaihtoehto Slide ja sille piti vielä erikseen laittaa rewind niin katos noi pallukat.

2023-03-13 14:30 UTC, LuomaJuha commented
Noni, oon testannu nyt ainakin carousel, carousel-vertical, title-bottom, muuttujat customista toimivat myös. Piilotin kanssa että tekstiä ei näy jos sitä ei ole. @EreMaijala Onkohan tää semmonen muutos et venytetään tämän julkaisun yli seuraavaan julkaisuun. Jotta saadaan testailtua rauhassa staging alueella ja kerättyä vähän tietoa.

2023-03-13 14:58 UTC, EreMaijala commented
@LuomaJuha Mä sanoisin, että voidaan vielä loppuun asti tässä releasessa, koska muuten on ihan mahdollista, että jotain hajoaa nyt niiden alustavien refaktorointien jälkeen, ja olisikin ollut lopullisessa ihan ok. Mitä mieltä?

2023-03-14 07:16 UTC, LuomaJuha commented
@EreMaijala Onhan toikin hyvä pointti. Eiköhän yritetä saada julkasuun.

2023-03-14 07:34 UTC, pasitiis commented
Julkaisu teksti ei näy kokonaan (asetus content[date] = 1).
<img width="1272" alt="Näyttökuva 2023-3-14 kello 9 31 37" src="https://user-images.githubusercontent.com/1954586/224927586-f42c0832-23e0-495b-84c6-e5ee393f9d8c.png">

2023-03-14 07:37 UTC, pasitiis commented
Autoplay-asetus ei näyttäisi toimivan.

2023-03-14 09:22 UTC, LuomaJuha commented
@pasitiis Noni, nyt toimii autoplay ja tekstit ei title-bottomissa pitäis kadota.

2023-03-14 11:05 UTC, EreMaijala approved these changes

2023-03-14 11:29 UTC, pasitiis commented
Jos feedin ei ole asetettu autoplayta niin nyt taitaa laittaa oletuksena päälle. Oletus pitäisi olla false.

2023-03-14 11:53 UTC, pasitiis approved these changes

2023-03-14 12:19 UTC, merged