[ALLI-7784] Change the language select menu's appearance v2
NatLibFi/NDL-VuFind2 pull request #2546
Opened 2023-03-01 08:30 UTC by siiriylonen

2023-03-01 09:33 UTC, siiriylonen commented
Oman tunnuksen ilmoituspampula huitelee tällä hetkellä väärässä paikassa, mutta onko muuten oikean näköinen? Tabletissa yleisen valikon pitäisi sulkeutua kun avaa kielivalikon?

2023-03-02 12:37 UTC, EreMaijala requested changes
Muutama pikainen kommentti. Isompana ehkä ulkoasu. Joo, menee leiskan mukaan, mutta minusta varsinkin mobiilin korkea harmaa alue inset:llä näyttää oudolta meidän teemassa. @pasitiis, meillä ei ole tuollaisia oikein missään muualla, pitääkö tässä olla?

2023-03-02 12:37 UTC, EreMaijala commented on themes/finna2/less/finna/navigation.less
> +.finna-navbar .navbar-nav .logoutOptions {
.logoutOptions:n voisi laittaa ylläolevan blokin sisään.

2023-03-02 12:37 UTC, EreMaijala commented on themes/finna2/less/finna/navigation.less
>  // fix navbar for logoutoptions
Kommentti väärässä kohdassa

2023-03-02 12:37 UTC, EreMaijala commented on themes/finna2/less/global/navbar-bootstrap.less
> +  box-shadow: inset 0 0 10px #d1d1d1;
Tämä ja border pitäisi varmaan tuottaa background-color:sta?

2023-03-02 12:37 UTC, EreMaijala commented on themes/finna2/less/global/navbar-bootstrap.less
> +  background-color: @btn-primary-bg !important;
Huolettaa `!important`, jota pitäisi välttää aina kuin vain suinkin mahdollista. Olisiko poistettavissa?

2023-03-02 12:37 UTC, EreMaijala commented on themes/finna2/less/global/navbar-bootstrap.less
> +    color: @btn-primary-color !important;
Huolettaa !important, jota pitäisi välttää aina kuin vain suinkin mahdollista. Olisiko poistettavissa?

2023-03-07 08:17 UTC, pasitiis commented
> Muutama pikainen kommentti. Isompana ehkä ulkoasu. Joo, menee leiskan mukaan, mutta minusta varsinkin mobiilin korkea harmaa alue inset:llä näyttää oudolta meidän teemassa. @pasitiis, meillä ei ole tuollaisia oikein missään muualla, pitääkö tässä olla?

Inset pois, ei toimi. Ylä- ja alalinjan paksuus 1px.

![Screenshot 2023-03-07 at 10-13-55 (ei hakusanaa) Hakutulokset Finna](https://user-images.githubusercontent.com/1954586/223363672-61f9820f-5c60-4b6b-b359-076a024eb09f.png)

2023-03-08 14:41 UTC, pasitiis commented
Mobiilivalikossa näyttäisi olevan tuplalinja. Poista toinen linja. 

<img width="609" alt="Näyttökuva 2023-3-8 kello 16 39 26" src="https://user-images.githubusercontent.com/1954586/223742651-821cbe8d-0d4b-420f-bec9-d21451a077c9.png">

2023-03-10 07:05 UTC, pasitiis commented
Kielivalikon ja oma tilin väkänen pitäisi olla tyyliltään sama.

<img width="316" alt="Näyttökuva 2023-3-10 kello 9 01 21" src="https://user-images.githubusercontent.com/1954586/224246822-f51b39c5-06e1-4171-af66-53ff4ab87f20.png">

2023-03-10 13:10 UTC, pasitiis commented
Oma tili -valikkossa linja katkeaa kesken. Joku tyylimuutos vaikuttaa kyseiseen kohtaan. 
<img width="351" alt="Näyttökuva 2023-3-10 kello 15 05 31" src="https://user-images.githubusercontent.com/1954586/224324317-6eaf66df-fd54-4ed8-86df-330ea6c84761.png">

2023-03-13 10:50 UTC, EreMaijala commented
@siiriylonen Onko kaikki Pasin raportoimat korjattu?

2023-03-13 11:18 UTC, EreMaijala requested changes
Miksi kielivalikko on ihan erilainen kuin muut valikot? 

Mobiilivalikossa harmaa reuna vasemmalla ja oikealla näyttää minusta edelleen vähän kummalta.

2023-03-13 11:18 UTC, EreMaijala commented on themes/finna2/js/finna-layout.js
> +      $('#dropdownMenuButton').children('.fa-chevron-down').removeClass('fa-chevron-down').addClass('fa-chevron-up');
Olisi parempi, että html:ssä lisätään kaksi kuvaketta joita vaihdetaan. Vaihdon voisi tehdä css-luokan perusteella, eli tässä vain togglettaisi `#language_menu`: lle esim. open-luokan.

2023-03-13 11:18 UTC, EreMaijala commented on themes/finna2/templates/navibar.phtml
> +          <li id="logout" class="logoutOptions">
Miksi tälle tuli id?

2023-03-13 11:18 UTC, EreMaijala commented on themes/finna2/templates/navibar.phtml
> +        </div>
Sisennys korjattava.

2023-03-13 11:18 UTC, EreMaijala commented on themes/finna2/templates/navibar.phtml
> +      <div class="lang-login-buttons">
div ei saa olla suoraan ul:n alla.

2023-03-13 12:32 UTC, siiriylonen commented
> @siiriylonen Onko kaikki Pasin raportoimat korjattu?

On korjattu

2023-03-13 12:55 UTC, EreMaijala commented on themes/finna2/js/finna-layout.js
> +      $('#dropdownMenuButton').children('.fa-chevron-down').removeClass('fa-chevron-down').addClass('fa-chevron-up');
Ks. esim. https://github.com/vufind-org/vufind/blob/dev/themes/bootstrap3/templates/Recommend/SideFacets.phtml#L61

2023-03-14 08:17 UTC, pasitiis commented
Säätäisin vielä mobiilivalikkon avauspainikeeta siten että linkin väri ja fontin koko sekä paksuus on vastaava desktop-version kanssa. Mobiilista border-left ja border-right pois.
<img width="452" alt="Näyttökuva 2023-3-14 kello 10 13 45" src="https://user-images.githubusercontent.com/1954586/224938310-52c873e8-7a76-4084-9df1-fca0864f990a.png">

2023-03-15 07:45 UTC, EreMaijala requested changes
Edelleen suurin kysymys on, miksi kielivalikko on ihan erinäköinen kuin muut valikot. Minusta se hyökkää päälle tosi kummallisena, kun ei ole tyyliltään ollenkaan vastaava. @pasitiis?

2023-03-15 07:45 UTC, EreMaijala commented on themes/finna2/js/finna-layout.js
> +    $('#language_menu').find(open).addClass(hidden);
Oikea aloitustila tällä ja `#collapseMenuButton` pitäisi olla templaatissa.

2023-03-15 07:45 UTC, EreMaijala commented on themes/finna2/less/global/navbar-bootstrap.less
> +    padding-right: 10px !important;
Onko `!important` välttämätön, vai saisiko riittävän tarkalla selectorilla tehtyä?

2023-03-15 07:45 UTC, EreMaijala commented on themes/finna2/less/global/navbar-bootstrap.less
> +    margin-right: 1em !important;
Onko `!important` välttämätön, vai saisiko riittävän tarkalla selectorilla tehtyä?

2023-03-15 07:45 UTC, EreMaijala commented on themes/finna2/templates/navibar.phtml
> +          <button class="btn collapse-mobile" aria-label="<?=$this->transEscAttr('select_language')?>" type="button" id="collapseMenuButton" data-toggle="collapse" data-target="#language_menu_mobile"
Mitä hyötyä tästä tekstistä on? Jos käyttäjä ei ymmärrä nykyistä kieltä, ei myöskään ymmärrä tekstiä.

2023-03-15 08:09 UTC, pasitiis commented on themes/finna2/templates/navibar.phtml
> +          <button class="btn collapse-mobile" aria-label="<?=$this->transEscAttr('select_language')?>" type="button" id="collapseMenuButton" data-toggle="collapse" data-target="#language_menu_mobile"
Olen vähän kahden vaiheella. Mun puolesta valikkoa voisi muuttaa vähemmän hyökkääväksi, mutta osa käyttäjistä on toivonut että kielivalikko saisi tulla paremmin esille mobiilivalikossa (nykyinen kielivalinta on hukkunut muiden valikko elementtien sekaan).

2023-03-15 08:12 UTC, EreMaijala commented on themes/finna2/templates/navibar.phtml
> +          <button class="btn collapse-mobile" aria-label="<?=$this->transEscAttr('select_language')?>" type="button" id="collapseMenuButton" data-toggle="collapse" data-target="#language_menu_mobile"
Mobiilissa se voi olla uuden mallinen, enempi mua häiritsee tuo leveän version erilaisuus.

2023-03-16 10:59 UTC, siiriylonen commented
(Desktop valikosta tehdään vielä kapeampi, kuten mobiilissa.)

2023-03-16 11:17 UTC, pasitiis commented
Pohdiskelen vielä ul-elementin lang-login-buttons-luokan tarpeellisuutta. Poistaisin koko lista rakenteen. Kielivalinnan ei tarvistse olla liitoksissa kirjautumistoimintojen kanssa. Rakenne luultavasti vaikuttaa oudolta ruudunlukijalla.

2023-03-16 11:33 UTC, pasitiis commented on themes/finna2/templates/navibar.phtml
> +        <li id="language_menu" class="dropdown" role="navigation" aria-label="<?=$this->transEscAttr('select_language')?>">
select_language  ->  Language (nykyinen käännös ei oikein toimi valikon kanssa)

2023-03-16 11:36 UTC, pasitiis commented on themes/finna2/templates/navibar.phtml
> +        <li id="language_menu" class="dropdown" role="navigation" aria-label="<?=$this->transEscAttr('select_language')?>">
select_language  ->  Language (nykyinen käännös ei oikein toimi valikon kanssa)

2023-03-16 14:01 UTC, pasitiis commented
Muutetaan vielä headerin rakennetta siten että kielivalikko ja kirjautuminen/oma tili-valikko ei ole päävalikon sisällä. Lisäksi poistetaan lang-login-buttons-luokan ympäriltä div-elementti johon asetettu role="menubar".

2023-03-17 07:35 UTC, EreMaijala requested changes
Katselmoidaan uudelleen pyydettyjen muutosten jälkeen.

2023-03-17 14:44 UTC, pasitiis commented
Finna-navbarissa on role-määritykset osittain pielessä. Axe-tarkastustyökalu herjaa virheistä. @siiriylonen laitoin korjaus ohjeet slackiin (korjattu rakenne perustuu [tähän](https://www.w3.org/WAI/ARIA/apg/patterns/menubar/examples/menubar-navigation/)).

2023-03-17 14:55 UTC, pasitiis commented
Kielivalikkossa Wave-tarkastustyökalu herjaa virheestä. Luultavasti dropdown-menun dropdown-item sisällä olevalle linkille pitää lisätä role="menuitem", koska dropdown-menulla on rooli menu.

2023-03-21 07:46 UTC, pasitiis commented
Poista boostrap3 -teemaan tehdyt muutokset. Ei oikein toimi että kielivalikko ja oma tili-valikko on erillään. Nyt oma tili-valikko on vaikeasti löydettävä. Palaisin vanhaan navbar-rakenteeseen (jätä aria-roleihin tehdyt muutokset).

2023-03-21 12:56 UTC, siiriylonen commented
Nyt pitäisi molempien taas olla osa päävalikkoa ja Firefoxilla pitäisi nyt näkyä focus outline myös dropdown-toggle elementeillä.

2023-03-22 06:17 UTC, pasitiis commented
AXE-tarkistustyökalu antaa virheen kielivalikosta (role=navigation elementti menubarissa ei mene validaattorista läpi). En käyttäisi menubar roolia kielivalikossa. Jos menubar roolin poistaa pitää myös menuitemit poistaa. Kannattaa asentaa koneelle [AXE-tarkastustyökalu](https://www.deque.com/axe/devtools/firefox-browser-extension/), muuten aria-virheitä on hankala huomata.

2023-03-22 07:52 UTC, siiriylonen commented
Nyt kielivalikko ei ole "menubar", mutta on silti "menu", kuten myös Oma tili-valikko ja näiden parent divillä on rooli "navigation" (kuten alkuperäisessä versiossa näytti olevan).

2023-03-24 13:14 UTC, pasitiis commented
Firefoxilla kielivalikon sulkeminen ei näytä toimivan oikein (esc-näppäimen painamisen jälkeen valikko tulee uudelleen näkyviin). Chromella toimii ok. Sama vika näyttää olevan myös päävalikossa.

Mua vielä häiritsee että kielivalikossa valikon väkänen käänty, mutta muissa header-osion valikoissa ei. Ehkä väkäsen kääntyminen kannattaa ottaa pois tai lisätä muihin header valikoihin.

2023-03-24 13:35 UTC, siiriylonen commented
Uudelleen aukeaminen näyttäisi tapahtuvan kun on mennyt listalla valinnoissa eteenpäin (tab), mutta sulkee esc:illä ilman valintaa -> aukeaa uudelleen ilman valintaa? (Tai ainakin saan noin toistettua myös muilla selaimilla sekä muissa navigaation dropdown-menuissa saman.)

2023-03-24 14:01 UTC, siiriylonen commented
Otin ikonin muuttumisen avatessa kokonaan pois.

2023-03-28 07:24 UTC, siiriylonen commented
Nyt valikon pitäisi sulkeutua myös ensimmäisellä esc painalluksella.

2023-04-06 11:56 UTC, pasitiis approved these changes

2023-04-11 17:41 UTC, EreMaijala requested changes

2023-04-11 17:41 UTC, EreMaijala commented on themes/finna2/less/finna/navigation.less
> +  span.fa-chevron {
Tarvitaanko tätä enää? Jos tarvitaan, niin pitäisi kohdistaa joko span.icon:iin tai sitten antaa ikonille erityinen luokka. Muuten kuvakkeen vaihtaminen sotkee tämän.

2023-04-11 17:41 UTC, EreMaijala commented on themes/finna2/less/global/navbar-bootstrap.less
> +  .fa.fa-globe {
Tähän `.icon` tms. joka ei riipu kuvakkeen nimestä.

2023-04-11 17:41 UTC, EreMaijala commented on themes/finna2/templates/navibar.phtml
>                      <div><?= $this->transEsc($label) ?></div>
Tältä div:ltä puuttuu sisennys, eikö?

2023-04-11 17:41 UTC, EreMaijala commented on themes/finna2/templates/navibar.phtml
> +      <a href="#" id="dropdownMenuButton" class="btn dropdown-toggle" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
Ei voi antaa tällaista id:tä yksittäiselle dropdown-nappulalle, kun sivulla voi olla joukko vastaavia ihan samanarvoisia nappuloita. id:t kokonaan pienellä ja alaviivalla. Kelvollinen voisi olla esim. `language_menu_dropdown_button`.

2023-04-13 12:17 UTC, EreMaijala requested changes
Pientä hienosäätöä vielä language-ikonille.

2023-04-13 12:17 UTC, EreMaijala commented on themes/finna2/less/global/navbar-bootstrap.less
> +  .fa.lang-icon {
`fa` on edelleen ikonikohtainen luokka, pitää ottaa pois.

2023-04-13 12:17 UTC, EreMaijala commented on themes/finna2/templates/navibar.phtml
> +        <i class='fa fa-globe lang-icon'></i>
Käytetään uusille ikoneille icon-helperiä kuten collapse alempana. Ikonin nimeksi vaikka `language`.

2023-04-13 16:46 UTC, EreMaijala approved these changes

2023-04-13 17:19 UTC, merged