[ALLI-7722] Marc: Display subfield 3 from field 546
NatLibFi/NDL-VuFind2 pull request #2547
Opened 2023-03-01 10:48 UTC by rajaro

2023-03-01 12:54 UTC, EreMaijala requested changes

2023-03-01 12:54 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/data-languageNotes.phtml
> +        <?=$this->escapeHtml($detail)?><br/>
Eikö tämä mene aika rumasti, jos on useampi detail-kenttä? Aiemmin näytettiin yhdellä rivillä, onko mitään syytä laittaa noita rivinvaihtoja?

2023-03-01 13:25 UTC, rajaro commented on themes/finna2/templates/RecordDriver/DefaultRecord/data-languageNotes.phtml
> +        <?=$this->escapeHtml($detail)?><br/>
Aattelin että luettavampi jos erityyppiset kentät omal rivillään, a kun on huomautus kielistä ja b kirjaimisto. Mutta tosiaan aiemminkin ollu samalla rivillä ja ehkä se menee hassun näköseks. Voin ottaa pois

2023-03-02 06:11 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/data-languageNotes.phtml
> +        <?=$this->escapeHtml($detail)?><br/>
Se osakenttä 3 (part) tulee ensimmäisen rivin eteen, niin ei ole enää mitenkään selvää, että koskee myös toista riviä. Siksi olisi selkeämpää pitää yhdellä rivillä.

2023-03-02 06:12 UTC, EreMaijala approved these changes

2023-03-02 06:13 UTC, merged