[ALLI-7835] Update Finnish Public Libraries Classification System translations
NatLibFi/NDL-VuFind2 pull request #2549
Opened 2023-03-07 13:17 UTC by aleksip

2023-03-09 13:56 UTC, EreMaijala requested changes
Ymmärrän, että ainakin osa virheistä on jo lähtödatassa, mutta tehdään korjaukset ja jos rahkeet riittävät, niin lähetetään korjauspyynnöt myös lähtödatan ylläpitäjille. 

Kommenteissa "isolla" ja "pienellä" viittaa toki vain alkukirjaimeen.

2023-03-09 13:56 UTC, EreMaijala commented on local/languages/finna/classification/fi.ini
> +ykl 34.5 = "Yhdyskuntasuunnittelu. Kaupunkisuunnittelu ympäristönsuunnittelu"
Luulen, että tämän pitäisi olla `Yhdyskuntasuunnittelu. Kaupunkisuunnittelu. Ympäristönsuunnittelu`. Laitoin kysymyksen Finton suuntaan, mutta korjaisin sen tähän. Muilla kielillä onkin niin.

2023-03-09 13:56 UTC, EreMaijala commented on local/languages/finna/classification/fi.ini
> +ykl 78.48142 = "Kazakstan. Kirgisia. Tadzikistan. Turkmenistan uzbekistan"
Tässä pitäisi nähdäkseni myös Uzbekistan olla isolla ja piste ennen sitä.

2023-03-09 13:56 UTC, EreMaijala commented on local/languages/finna/classification/fi.ini
> +ykl 78.94 = "Keski-euroopan maiden musiikin historia"
Euroopan isolla alkukirjaimella.

2023-03-09 13:56 UTC, EreMaijala commented on local/languages/finna/classification/fi.ini
> +ykl 78.96 = "Espanjan, italian, portugalin ja ranskan musiikin historia"
Isot alkukirjaimet.

2023-03-09 13:56 UTC, EreMaijala commented on local/languages/finna/classification/fi.ini
> +ykl 78.97 = "Muiden euroopan maiden musiikin historia"
Euroopan isolla.

2023-03-09 13:56 UTC, EreMaijala commented on local/languages/finna/classification/fi.ini
> +ykl 86.54 = "Australian ja uuden-seelannin englanninkielisen kirjallisuuden historia ja tutkimus"
Isot alkukirjaimet.

2023-03-09 13:56 UTC, EreMaijala commented on local/languages/finna/classification/fi.ini
> +ykl 86.56 = "Etelä-afrikan englanninkielisen kirjallisuuden historia ja tutkimus"
Isot alkukirjaimet.

2023-03-09 13:56 UTC, EreMaijala commented on local/languages/finna/classification/fi.ini
> +ykl 94 = "Keski-euroopan historia"
Iso alkukirjain

2023-03-09 13:56 UTC, EreMaijala commented on local/languages/finna/classification/fi.ini
> +ykl 96 = "Etelä-euroopan historia"
Iso alkukirjain

2023-03-09 13:56 UTC, EreMaijala commented on local/languages/finna/classification/fi.ini
> +ykl 97 = "Itä-euroopan historia"
Iso alkukirjain

2023-03-09 13:56 UTC, EreMaijala commented on local/languages/finna/classification/fi.ini
> +udkf 24 = "Kristillinen etiikka. Kristillinen taide. Hymnologia. Hartaus. Mystiikka. Askeesi uskonnolliset kokemukset"
Pitäisiköhän tässäkin olla `Askeesi. Uskonnolliset..`?

2023-03-09 13:56 UTC, EreMaijala commented on local/languages/finna/classification/fi.ini
> +udkf 535 = "Valo-oppi optiikka"
Piste ja isolla?

2023-03-09 13:56 UTC, EreMaijala commented on local/languages/finna/classification/fi.ini
> +udkf 615 = "Farmakologia farmasia"
Piste ja isolla?

2023-03-09 13:56 UTC, EreMaijala commented on local/languages/finna/classification/fi.ini
> +udkf 616-053.2 = "Pediatria lastentaudit"
Piste ja isolla?

2023-03-09 13:56 UTC, EreMaijala commented on local/languages/finna/classification/fi.ini
> +udkf 616.379-008.64 = "Diabetes sokeritauti"
Piste ja isolla?

2023-03-09 13:56 UTC, EreMaijala commented on local/languages/finna/classification/fi.ini
> +udkf 621 = "Konetekniikka mekaaninen teknologia"
Piste ja isolla?

2023-03-09 13:56 UTC, EreMaijala commented on local/languages/finna/classification/fi.ini
> +udkf 621.38 = "Röntgentekniikka bioelektroniikka"
Piste ja isolla?

2023-03-09 13:56 UTC, EreMaijala commented on local/languages/finna/classification/fi.ini
> +udkf 658.3 = "Henkilöstöhallinto henkilöstölehdet & ala"
Piste ja isolla?

2023-03-09 13:56 UTC, EreMaijala commented on local/languages/finna/classification/fi.ini
> +udkf 666.9 = "Sementtiteollisuus betoniteollisuus. Kipsiteollisuus. Kalkkiteollisuus"
Piste ja isolla?

2023-03-09 13:56 UTC, EreMaijala commented on local/languages/finna/classification/fi.ini
> +udkf jaottelu = "Käyttämällä luokkaa 78 ja sopivaa muuta luokkaa:"
Tämä taitaa olla höpörivi, jonka voisi jättää pois.

2023-03-09 13:56 UTC, EreMaijala commented on local/languages/finna/classification/fi.ini
> +udkf 801.4 = "Äänneoppi fonetiikka. Fonologia"
Piste ja isolla?

2023-03-09 13:56 UTC, EreMaijala commented on local/languages/finna/classification/fi.ini
> +udk2 524.6 = "Galaksi (linnunrata)"
Linnunrata isolla

2023-03-09 13:56 UTC, EreMaijala commented on local/languages/finna/classification/fi.ini
> +udk2 550.93 = "Absoluuttisen geologisen Iän määrittäminen. Iän määritysmenetelmät"
Ensimmäinen Iän pitäisi olla pienellä.

2023-03-09 13:56 UTC, EreMaijala commented on local/languages/finna/classification/fi.ini
> +udk2 57.05 = "Säätelyprosessien periaatteet eri tasoilla, esim. Molekyyli- ja solutasolla, jne."
molekyyli pienellä.

2023-03-09 13:56 UTC, EreMaijala commented on local/languages/finna/classification/fi.ini
> +udk2 599.82 = "Platyrrhini (leveänenäapinat )"
Ylimääräinen välilyönti ennen loppusulkua

2023-03-09 13:56 UTC, EreMaijala commented on local/languages/finna/classification/fi.ini
> +udk2 596.2 = "Tunicata /urochordata (vaippaeläimet)"
Lisättävä välilyönti kauttaviivan perään.

2023-03-09 13:56 UTC, EreMaijala commented on local/languages/finna/classification/fi.ini
> +udk2 616-05 = "Sairaan persoonallisuus. (yksilölliset ja ympäristötekijät)"
Olisi varmaan parempi ilman pistettä

2023-03-09 13:56 UTC, EreMaijala commented on local/languages/finna/classification/fi.ini
> +udk2 685.2 = "Erilaiset nahka- ja kangasvarusteet, esim. Vyöt, nahkapuserot jne."
vyöt pienellä

2023-03-09 13:56 UTC, EreMaijala commented on local/languages/finna/classification/fi.ini
> +udk2 693 = "Muuraus. Betonivalu ym. Rakennustyöt"
rakennustyöt pienellä

2023-03-09 13:56 UTC, EreMaijala commented on local/languages/finna/classification/fi.ini
> +udk2 696 = "Lvi-asennukset. Sähköasennukset"
LVI isolla

2023-03-09 13:56 UTC, EreMaijala commented on local/languages/finna/classification/fi.ini
> +udk2 7.04 = "Taideteoksen aihe. Lkonografia. Ikonologia"
Pitäisikö olla Ikonografia, iillä?

2023-03-09 13:56 UTC, EreMaijala commented on local/languages/finna/classification/fi.ini
> +udk2 798.9 = "Muiden eläinten kilpailut, esim. Linnut"
linnut pienellä

2023-03-09 13:56 UTC, EreMaijala commented on local/languages/finna/classification/fi.ini
> +udk2 9 = "Arkeologilinen kirjallisuus. Esihistoria. Kotiseutuoppi. Maantiede. Historia. Elämäkerrat"
Pitäisiköhän tämän olla Arkeologinen?

2023-03-09 13:56 UTC, EreMaijala commented on local/languages/finna/classification/sv.ini
> +ykl 1 = "Filosofi. Psykologi paranormala fenomen. Vetenskapsteori"
Piste ennen ja `Paranormala` isolla alkukirjaimella.

2023-03-09 13:56 UTC, EreMaijala commented on local/languages/finna/classification/sv.ini
> +ykl 66.34 = "Vvs-arbeten. Elarbeten"
VVS isolla

2023-03-09 13:56 UTC, EreMaijala commented on local/languages/finna/classification/sv.ini
> +ykl 78.611 = "Musik är avsedd som studiematerial i pianospel (t.Ex. Etyder)"
Ex ja Etyder pienellä

2023-03-09 13:56 UTC, EreMaijala commented on local/languages/finna/classification/fi.ini
> +ykl 78.611 = "Pianonsoiton opintoaineistoksi tarkoitettu musiikki (esim. Etydit)"
etydit pienellä

2023-03-09 13:56 UTC, EreMaijala commented on local/languages/finna/classification/en-gb.ini
> +ykl 78.611 = "Music intended as study material for piano playing (e.g. Études)"
Études pienellä

2023-03-09 13:56 UTC, EreMaijala commented on local/languages/finna/classification/sv.ini
> +ykl 86.62 = "Litteraturhistoria och -forskning som rör litteratur på italienska"
Italienska isolla

2023-03-09 13:56 UTC, EreMaijala commented on local/languages/finna/classification/fi.ini
> +ykl 45 = "Brittein saaret"
Britteinsaaret yhdyssana.

2023-03-09 13:56 UTC, EreMaijala commented on local/languages/finna/classification/sv.ini
> +udk2 004.27 = "Avancerade arkitekturer. Icke-von neumann arkitekturer"
`Von Neumann` isolla?

2023-03-09 13:56 UTC, EreMaijala commented on local/languages/finna/classification/sv.ini
> +udk2 252 = "Religioner i mesopotamien"
mesopotamien isolla

2023-03-09 13:56 UTC, EreMaijala commented on local/languages/finna/classification/sv.ini
> +udk2 258 = "Religioner i syd- och centralamerica. Förkolombianska indianska religioner"
Syd ja centralamerica isolla

2023-03-09 13:56 UTC, EreMaijala commented on local/languages/finna/classification/sv.ini
> +udk2 37.01/.09 = "Speciella tillägg för teori, principer.Metoder och organisation av utbildningen"
Pisteen jälkeen väli

2023-03-09 13:56 UTC, EreMaijala commented on local/languages/finna/classification/sv.ini
> +udk2 524.6 = "Galaxen (vintergatan)"
vintergatan isolla

2023-03-09 13:56 UTC, EreMaijala commented on local/languages/finna/classification/sv.ini
> +udk2 582.095 = "Undervegetation (t.Ex. Björnbär - rosoideae)"
Ex. Björnbär pienillä

2023-03-09 13:56 UTC, EreMaijala commented on local/languages/finna/classification/sv.ini
> +udk2 582.097 = "Trädklättrare (t.Ex. Murgröna - araliaceae)"
t.Ex. Murgröna pienillä

2023-03-09 13:56 UTC, EreMaijala commented on local/languages/finna/classification/sv.ini
> +udk2 582.099 = "Örtartade eller icke-vedartade växter (ofta kallade "Plantor" eller "Blommor")"
plantor ja blommor pienellä

2023-03-09 13:56 UTC, EreMaijala commented on local/languages/finna/classification/sv.ini
> +udk2 62-94 = "Processernas riktning, hastighet, takt, längd, o.A.V."
o.a.v. pienellä

2023-03-09 13:56 UTC, EreMaijala commented on local/languages/finna/classification/sv.ini
> +udk2 683 = "Järnvaror. Hårdvaror. Låssmide. Förslutningar för flaskor o.Dyj. Lamptillverkning. Uppvärmningsanordningar"
Dyj pienellä

2023-03-09 13:56 UTC, EreMaijala commented on local/languages/finna/classification/sv.ini
> +udk2 7.08 = "Karaktäristiska kännetecken, former, kombinationer (I konst, underhållning och sport)"
I pienellä

2023-03-09 13:56 UTC, EreMaijala commented on local/languages/finna/classification/sv.ini
> +udk2 794 = "Bräd- och bordsspel (I form av tanke-, skicklighets- och turspel)"
I pienellä

2023-03-09 13:56 UTC, EreMaijala commented on local/languages/finna/classification/sv.ini
> +udk2 811.34 = "Döda språk av okänd tillhörighet, som talades omkring medelhavet och mellanöstern (utom semitiska språk)"
medelhavet ja mellanöstern isolla

2023-03-09 13:56 UTC, EreMaijala commented on local/languages/finna/classification/sv.ini
> +udk2 821.353 = "Litteratur från det sydliga (kartvelska) kaukasus"
Kaukasus isolla

2023-03-09 13:56 UTC, EreMaijala commented on local/languages/finna/classification/sv.ini
> +udk2 821.4 = "Afroasiatisk, nilosahirska, kongo-kordofaniansk, khoisan litteratur"
Kongo isolla?

2023-03-10 08:13 UTC, karisera commented on local/languages/finna/classification/sv.ini
> +ykl 86.62 = "Litteraturhistoria och -forskning som rör litteratur på italienska"
mä veikkaan että tossa on joku fiba koska ei muutkaan kielet tule ruotsiksi isolla?

2023-03-10 08:17 UTC, EreMaijala commented on local/languages/finna/classification/sv.ini
> +ykl 86.62 = "Litteraturhistoria och -forskning som rör litteratur på italienska"
hups, joo, väärin väitin

2023-03-10 08:27 UTC, karisera commented on local/languages/finna/classification/fi.ini
> +ykl 45 = "Brittein saaret"
Siitä pitää sit ehkä laittaa palautetta YKL-ylläpitoon, mutta korjaan nyt tuon

2023-03-14 13:48 UTC, EreMaijala commented on local/languages/finna/classification/fi.ini
> +ykl 45 = "Brittein saaret"
Ei korjattu, pitikö?

2023-03-14 13:50 UTC, EreMaijala requested changes

2023-03-14 13:50 UTC, EreMaijala commented on local/languages/finna/classification/sv.ini
> +udk2 62-94 = "Processernas riktning, hastighet, takt, längd, o.A.V."
vielä korjaamatta

2023-03-14 13:59 UTC, EreMaijala commented on local/languages/finna/classification/fi.ini
> +ykl 45 = "Brittein saaret"
Ei pitänyt.

2023-03-14 14:00 UTC, EreMaijala approved these changes

2023-03-14 14:15 UTC, merged