[ALLI-7940] Fix checkout history date handling and Mikromarc function…
NatLibFi/NDL-VuFind2 pull request #2551
Opened 2023-03-08 13:31 UTC by EreMaijala

…ality.

historicloans template was using all-lowercase keys, while upstream template and drivers returned camelCaps. Mikromarc retrieval mechanism was broken. Fixed and added sorting since we always fetch everything from the server.

2023-03-09 12:10 UTC, LuomaJuha requested changes

2023-03-09 12:10 UTC, LuomaJuha commented on module/Finna/src/Finna/ILS/Driver/Mikromarc.php
> +        $sort = $parts[0] ?? 'checkoutDate';
Pitäisi defaultata checkout eikä checkoutDate?

2023-03-09 12:10 UTC, LuomaJuha commented on module/Finna/src/Finna/ILS/Driver/Mikromarc.php
> +            $transactions[$id]['_' . $serviceCodeMap[$code]] = $actionTimestamp;
Vois olla kivempi, jos servicecodemap[code] olis jossain muuttujassa.

2023-03-10 06:36 UTC, EreMaijala commented on module/Finna/src/Finna/ILS/Driver/Mikromarc.php
> +        $sort = $parts[0] ?? 'checkoutDate';
Juu, korjattu.

2023-03-10 06:37 UTC, EreMaijala commented on module/Finna/src/Finna/ILS/Driver/Mikromarc.php
> +            $transactions[$id]['_' . $serviceCodeMap[$code]] = $actionTimestamp;
Siistitty.

2023-03-10 07:40 UTC, LuomaJuha approved these changes

2023-03-10 07:41 UTC, merged