[ALLI-7950] Fix location service to work with Axiell holdings. Fix QR code.
NatLibFi/NDL-VuFind2 pull request #2563
Opened 2023-03-16 13:02 UTC by EreMaijala

Location service is still a bit messy, but now all item information is available so that branch and department can be used in the links. QR code handling in location service was totally broken. Now uses similar mechanism to record link QR codes. A bit of JS is used to avoid the QR code dropdown from being clipped due to being in a truncated div.

Requires #2562.

2023-03-17 10:47 UTC, LuomaJuha requested changes

2023-03-17 10:47 UTC, LuomaJuha commented on module/Finna/src/Finna/View/Helper/Root/Callnumber.php
> +            $section = $basePage == 'results' ? 'qrCodeResults' : 'qrCodeRecord';
===

2023-03-17 10:47 UTC, LuomaJuha commented on themes/finna2/templates/Helpers/holding-callnumber.phtml
>    <?php else: ?>
Tähän olisi hyvä laittaa tarkastus, ettei callnumber ole tyhjä. Jos kolmas parametri on tyhjä, funktiossa callnumber() niin sit tulee ikävästi ilman locationserviceä seuraava: Lainattavissa: 1 (Hylly: )

2023-03-17 12:27 UTC, EreMaijala commented on module/Finna/src/Finna/View/Helper/Root/Callnumber.php
> +            $section = $basePage == 'results' ? 'qrCodeResults' : 'qrCodeRecord';
Korjattu.

2023-03-17 12:28 UTC, EreMaijala commented on themes/finna2/templates/Helpers/holding-callnumber.phtml
>    <?php else: ?>
Lisätty. Samalla huomattu, että jäi callno-kenttä location service -url:sta tyhjäksi tässä tapauksessa ja vaihdettu se käyttämään fields:iä.

2023-03-20 08:07 UTC, LuomaJuha requested changes
Nyt LocationService.php rivi 77 parametri $callnumber on käyttämätön. Sitä ei taida tarvita enää?

2023-03-20 11:26 UTC, EreMaijala commented
Ei, mutta en halua muuttaa metodin signaturea, ettei tule senkään osalta yhteensopivuusongelmia.

2023-03-20 18:10 UTC, LuomaJuha approved these changes

2023-03-20 18:11 UTC, merged