[ALLI-7898] Sierra: Add support for profile update.
NatLibFi/NDL-VuFind2 pull request #2566
Opened 2023-03-17 11:48 UTC by EreMaijala

Includes centralized support for field validation and patterns for textual fields.

Note that SierraRest uses the updateProfile section name like Alma to better convey the fact that the function can do more than just update the address.

2023-03-23 14:16 UTC, LuomaJuha requested changes

2023-03-23 14:16 UTC, LuomaJuha commented on local/config/finna/SierraRest.ini.sample
> +; Choose a method on how to update the address information (driver, email or url).
Miten mul o sellanen fiilis ettei tuota email enää tueta?

2023-03-23 14:16 UTC, LuomaJuha commented on themes/finna2/templates/myresearch/change-address-settings.phtml
> +              if ($data['required']) {
!empty, muuten kaatuu jos ei ole määritelty mitään fields taulua [updateProfile]

2023-03-23 14:16 UTC, LuomaJuha commented on themes/finna2/templates/myresearch/change-address-settings.phtml
> +              if ($data['pattern']) {
!empty?

2023-03-23 14:16 UTC, LuomaJuha commented on themes/finna2/templates/myresearch/change-address-settings.phtml
> +          <?php if ($data['hint']): ?>
ja tässä vielä !empty?

2023-03-27 08:28 UTC, EreMaijala commented on local/config/finna/SierraRest.ini.sample
> +; Choose a method on how to update the address information (driver, email or url).
Joo, database on oikea vaihtoehto. Korjattu.

2023-03-27 08:29 UTC, EreMaijala commented
@LuomaJuha Korvasin empty-tarkistukset sillä, että controlleri huolehtii, että kaikissa kentissä on aina kaikki tiedot. Ei tartte templaatissa tehdä niin paljon hommia sitten.

2023-03-29 06:59 UTC, LuomaJuha approved these changes

2023-03-29 07:00 UTC, merged