[ALLI-7937] LIDO: Normalize huge image sizes
NatLibFi/NDL-VuFind2 pull request #2587
Opened 2023-04-18 08:19 UTC by LuomaJuha

Cleaned the SolrLido::formatImageMeasurements.

Test: Record/museovirasto.6d9c0022-9c45-4090-a9b6-ed30d8433a5a

2023-04-19 07:44 UTC, EreMaijala requested changes

2023-04-19 07:44 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +        $termToTypeMappings = [
Nää mappaukset voisi olla luokan alussa niin kuin muutkin mappaus-arrayt (ja nimenä ehkä `$measurementTypeMappings` ja `$measurementUnitMappings`).

2023-04-19 07:44 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +            'pikseli' => 'pixel'
Jos on bytes monikossa, niin voisi olla myös `pixels`?

2023-04-20 08:20 UTC, LuomaJuha commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +            'pikseli' => 'pixel'
Itseasiassa vaihdoin sen niin et bytes on byte.

2023-04-20 09:48 UTC, EreMaijala approved these changes

2023-04-20 09:48 UTC, merged