[FINNA-492] Refactor display of opening times in organisation info.
NatLibFi/NDL-VuFind2 pull request #2597
Opened 2023-05-02 12:26 UTC by EreMaijala

- Uses flexbox for improved layout.
- Fixes issues with rendering opening times with gaps during the day.
- Fixes a bug where a period marked closed (status = 0) was displayed as open.
- Ensures that previous open times in the summary line are removed when switching location.

2023-05-02 13:37 UTC, EreMaijala commented
Huom! organisation-info-schedule.phtml olisi ilmeisesti pitänyt poistaa [PR 548](https://github.com/NatLibFi/NDL-VuFind2/pull/548):n yhteydessä. En löytänyt enää mitään paikkaa, jossa se olisi ollut käytössä.

2023-05-05 11:24 UTC, LuomaJuha requested changes

2023-05-05 11:24 UTC, LuomaJuha commented on local/config/finna/rss-organisation-page.ini.sample
> +[organisation-info-schedule]
Hmm, en löytänyt tälle mitään tarvetta?

2023-05-05 11:24 UTC, LuomaJuha commented on module/Finna/src/Finna/OrganisationInfo/OrganisationInfo.php
> +            $today = $currentDate == $date;
===?

2023-05-08 13:22 UTC, EreMaijala commented on module/Finna/src/Finna/OrganisationInfo/OrganisationInfo.php
> +            $today = $currentDate == $date;
Ei. :)

2023-05-08 13:23 UTC, EreMaijala commented on local/config/finna/rss-organisation-page.ini.sample
> +[organisation-info-schedule]
En minäkään, poistettu. :)

2023-05-09 06:18 UTC, pasitiis approved these changes

2023-05-09 13:53 UTC, LuomaJuha approved these changes

2023-05-09 13:53 UTC, merged