[FINNA-412] LIDO: Display physical location
NatLibFi/NDL-VuFind2 pull request #2610
Opened 2023-05-19 13:35 UTC by mshroom

Odottaa kunnes testiaineiston data on korjattu

2023-05-26 08:10 UTC, mshroom commented
Testiaineiston data on nyt korjattu

2023-05-29 07:40 UTC, EreMaijala requested changes
Tiketistä ymmärsin, että tässä pitäisi olla myös kieliversioiden käsittely, vai onko se tarpeen?

2023-05-29 07:40 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +            if ($type != 'Current location') {
Vertailuoperaattoriksi `!==`

2023-05-29 11:06 UTC, mshroom commented
Totta, lisäsin kieliversiot displayRepositorylle. Sen sijaan repositoryLocationin alla tulevilla paikkatasoilla ei ainakaan toistaiseksi ole LIDO-pohjassa kieliversioita

2023-05-29 16:50 UTC, EreMaijala approved these changes

2023-05-29 16:50 UTC, merged