[FINNA-455] Improve feed's mobile accessibility
NatLibFi/NDL-VuFind2 pull request #2612
Opened 2023-05-22 06:27 UTC by siiriylonen

2023-05-23 07:47 UTC, siiriylonen commented
(Ongelmana .title-bottom:in sisältävä feed-elementti ja vaihtuva korkeus, jolla scrollaukseen liittyvän varjon tulisi näkyä.)

2023-06-01 13:14 UTC, LuomaJuha requested changes
Laitan vielä vähän kommenttia slackin kautta!

2023-06-01 13:14 UTC, LuomaJuha commented on themes/finna2/js/finna-feed-element.js
> +          $(holder).find('.feed-link a, .feed-link').on('click', function onClickSlideLink() {
Toi vanha funktio lähtis varmaan toimimaan, jos return falsen tilalle vaihtais e.preventDefault();
Ja sit vaihtais onSlideClick(e) joilloin eventti kulkeutuis mukana.
Alkuun sitten vois laittaa turvallisuuden vuoks e.stopImmediatePropagation() ettei painallus kuljeudu muihin elementteihin.

2023-06-01 13:14 UTC, LuomaJuha commented on themes/finna2/js/finna-feed-element.js
> +          $(holder).find('.feed-link').on('focusout', function removeClicked(event){
Tän vois toteuttaa paremmin silleen, et tos vanhassa funktiossa ennen slide.classlist.add('clicked') haettais kaikki feed-item-holder mil o .clicked luokka ja poistetaan se niistä.

2023-06-01 13:14 UTC, LuomaJuha commented on themes/finna2/js/finna-feed-element.js
> +          if (navigator.userAgent.match()) {
Onkos tän if blockin sisältö turha?

2023-06-01 13:14 UTC, LuomaJuha commented on themes/finna2/js/finna-feed-element.js
> +          el.classList.add('scrollable');
Scrollablen vois melkein yhdistää clicked kanssa, molemmat tarkoitettu toimimaan mobiililla. Eli voi poistaa tämän.

2023-06-01 13:14 UTC, LuomaJuha commented on themes/finna2/templates/ajax/feed-carousel-item.phtml
>    <?php if (isset($item['title'])): ?>
Uskon, että päästään lopputulokseen ilman suurempia templaattimuutoksia. :)

2023-06-05 13:03 UTC, LuomaJuha requested changes
Noni, näyttää hyvältä, pari homma löysin tuosta vielä jotka voisi tuunata.

2023-06-05 13:03 UTC, LuomaJuha commented on themes/finna2/templates/ajax/feed-carousel-item.phtml
> +      <p>
Sisennys

2023-06-05 13:03 UTC, LuomaJuha commented on themes/finna2/templates/ajax/feed-carousel-item.phtml
> +    <p><?=$this->escapeHtml($this->truncate($item['title'], 70))?></p>
Sisennys

2023-06-05 13:03 UTC, LuomaJuha commented on themes/finna2/less/finna/feed.less
> +                    margin: 30px -10px -30px -10px;
Onkos tämä margin sääntö tarpeellinen?

2023-06-05 13:03 UTC, LuomaJuha commented on themes/finna2/templates/ajax/feed-carousel-item.phtml
> +  <div class="shadow"></div>
Mietin luokkaa shadow, mikä on aika yleinen niin voisiko tämä olla enemmänkin feed-text-shadow?

2023-06-05 13:11 UTC, siiriylonen commented on themes/finna2/less/finna/feed.less
> +                    margin: 30px -10px -30px -10px;
Varmaan top ja bottom arvot eivät ole, mutta -10px on koska muuten varjo jää carousel-text sisäpuolelle ja sillä padding -> ei mene reunaan asti.

2023-06-05 13:18 UTC, LuomaJuha commented on themes/finna2/less/finna/feed.less
> +                    margin: 30px -10px -30px -10px;
jees, silloin voi kirjoittaa margin: 0 -10px;

2023-06-05 13:28 UTC, LuomaJuha approved these changes

2023-06-06 07:41 UTC, pasitiis commented on themes/finna2/templates/ajax/feed-carousel-item.phtml
> +      <p class="carousel-more"><?=$this->icon('export')?></p>
Export-kuvake ei oikein toimi tässä yhteydessä. Meillä on sama ikoni käytössä tietuesivulla, ja siellä sen funktio on eri (vie viite). Ehkä olisi parempi käyttää nuoli oikealle ja ikonin nimi voisi olla carousel-more.

2023-06-06 10:19 UTC, pasitiis commented on themes/finna2/templates/ajax/feed-carousel-item.phtml
> +      <p class="carousel-more"><?=$this->icon('export')?></p>
Ehkä tässä yhteydessä voisi toimia myös https://fontawesome.com/v4/icon/external-link (poikkeaa hiukan vie viite -ikonista) tai sitten fa-link.

2023-06-06 13:53 UTC, pasitiis commented
Täytyy vielä viilata esitystapaa yleisesti.

2023-06-09 09:00 UTC, EreMaijala commented
@siiriylonen Pyydä multa katselmointia uudelleen, kun viilaus on valmis.

2023-06-19 10:13 UTC, pasitiis commented
Totetutuksesta pitää ainakin korjata swipe. Elementin teksti välähtää näkyville kun vaihtaa swipellä elementistä toiseen.

2023-06-22 04:27 UTC, siiriylonen commented
Tässä nyt asetettu ajastin painallukselle, mutta sen toiminta on aika epäluotettavaa. Välillä toimii oikein ja välillä ei (siis linkin ja descriptionin näyttämisen suhteen).

2023-06-28 08:32 UTC, siiriylonen commented
Vielä pitää hieman muokata, mutta onko itse swaippauksen toiminta nyt halutunlaista?

2023-06-28 13:35 UTC, pasitiis commented
Mulla ei toimi sulkeminen (iphone). Mietin lisäksi pitäisikö "Avaa linkki" sijoittaa kuvan alakulmaan aina.

2023-06-29 04:36 UTC, siiriylonen commented
Eli että "Avaa linkki" ei olisi sticky vaan aina tekstin lopussa? (Title-bottom tapauksessa oli tarkoitus ottaa se sticky pois muutenkin.) Ja swaippausta pitää siis vielä katsoa, se nyt ottaa aina siitä otsikosta sen sulkemis swaippauksen, koska en tiedä sotkisiko muuten sisältötekstin skrollaamista.

2023-06-29 05:35 UTC, pasitiis commented
Varmaankin sticky tekstin pituudesta huolimatta. Pitää myös varautua siihen että feedissä ei ole description-tekstiä olleenkaan, mutta sisältää linkin ja titlen.

2023-07-03 11:09 UTC, siiriylonen commented
:hoverin ja .clicked samat less-säännöt erillään, koska mobiilissa :hover sekoitti swipe-toiminnon. Tai ainakin vaikutti että se oli syy sen toimimattomuudelle...

2023-07-05 06:39 UTC, siiriylonen commented
Ilman descriptioneja en ainakaan huomannut mitään erityistä ongelmaa.

2023-07-14 11:12 UTC, LuomaJuha requested changes
Näyttää muuten kivalta, mutta toi swipe tuntuu vähän ihmeelliseltä noissa descriptionin näyttämisissä.

2023-07-14 11:12 UTC, LuomaJuha commented on local/languages/finna/en-gb.ini
> +open_carousel_link_no_char = "Open link"
tulipa mieleen et pitäisköhän uudet käännösavaimet liittyen karuselleihin laittaa local/languages/finna/Carousel/fi.ini polkuun. Pitäis varmaan jossain välissä noi vanhatkin siirtää tuonne jos se on mahdollista.

2023-07-14 11:29 UTC, siiriylonen commented on themes/finna2/js/finna-feed-element.js
> +            if (el.classList.contains('show-link')) {
Mutta toinen näyttää ikonin ja toinen ei -> mistä se tietää kumpi? (Tai kun togglella ne molemmat ilmestyvät)

2023-07-18 07:37 UTC, siiriylonen commented
Tähän nyt lisätty mobiiliin swipe ylös ja alas toiminto, joka avaa/sulkee selitystekstin. Ongelmana vielä ehkä se, että näyttääkö kyseinen kenttä pyyhkäistävältä. Tila on kuitenkin aika rajallinen esim. suuremman nuolen lisäämiseksi tms, mutta tässä nyt kokeiltu kerran 3s viivellä ylös-nuoleen tehtävää animaatiota.

2023-08-01 08:42 UTC, pasitiis commented
Swipe ylös / alas ei toimi kunnolla iphonella (sotkentuu sivun skrolliin). En usko että saa toimimaan luotettavasti. @MillaKPE vielä leiskaa tähän liittyen.

2023-08-16 06:37 UTC, pasitiis commented
Nyt toimii selkeämmin kuin swipe. Muutamia kommetteja. 

Mobiilissa avaa linkki on eri kuin desktopissa.  Voisi olla sama molemissa (nuoli-ikoni). Mobiilissa sulje väkänen ei toimi (Iphone).

2023-08-17 05:22 UTC, siiriylonen commented
Kokeilin nyt vain simulatorilla, mutta siinä näyttäisi toimivan ok. (En tiedä onko normaalikäytössä napin "osumisalue" tarpeeksi iso?)

(Myös "Avaa linkki"-kohdan nuolesta tuli pienempi kuin desktop-version, pitäisikö sen olla samankokoinen vai onko ok?)

2023-08-17 06:11 UTC, pasitiis commented
Nyt toimii paremmin, mutta osumisalue on vähän pieni. Lisäksi teksti voi mennä lähelle väkästä. Voisi olla hyvä kasvattaa osumisaluetta. <img width="459" alt="Näyttökuva 2023-8-17 kello 9 08 33" src="https://github.com/NatLibFi/NDL-VuFind2/assets/1954586/0ed8dbb3-30bc-4dbe-92e0-339a308a5d82">

2023-08-21 05:36 UTC, pasitiis commented
Mietittiin vielä vähän selkeämpää totetusta. Väkäsen tilalle "..." -ikoni ja siitä aukeaa feedin kuvaskenttä. @MillaKPE päivittää vielä leiskaa.

2023-08-21 07:31 UTC, MillaKPE commented
Päivitetty leiska lisätty myös jiraan, " ... " väkäsen tilalle avatessa ja description auetessa ruksista sulkeminen. " ... " sulkemiseksi ei sopinut tyyliin. 
<img width="496" alt="Screenshot 2023-08-21 at 10 30 45" src="https://github.com/NatLibFi/NDL-VuFind2/assets/130566695/44707f7c-815d-4538-bcec-048b0d8b8e06">

2023-08-22 08:10 UTC, pasitiis commented
Ota vielä "Avaa linkki" mobiilista pois. Se on vähän turha.

2023-08-23 10:11 UTC, siiriylonen commented
Nyt siis vaihdettu (mobiiliin):
- Vain painettaessa X-ikonia sulkee avatun descriptionin.
- X-ikoni on sticky ja aina näkyvissä.
- Linkki ei avaudu painalluksella kun description on avattuna.

2023-08-25 06:11 UTC, pasitiis commented
Lisää vielä että karusellin kuvaa painamalla aukeaa linkki.

2023-08-25 12:34 UTC, pasitiis approved these changes

2023-08-31 07:12 UTC, EreMaijala approved these changes

2023-09-01 09:46 UTC, LuomaJuha requested changes

2023-09-01 09:46 UTC, LuomaJuha commented on themes/finna2/js/finna-feed-element.js
> +            if (el.querySelector('p')) {
voinee tallentaa muuttujaan ja katsoa sitä kautta että onko löytynyt ettei tarvitse tuplahakua tehdä.

2023-09-01 09:46 UTC, LuomaJuha commented on themes/finna2/js/finna-feed-element.js
> +            if (el.querySelector('p')) {
Pieni huomio vaan mutta ei muuta

2023-09-05 08:36 UTC, LuomaJuha approved these changes

2023-09-05 08:39 UTC, merged