[FINNA-544] Fix organisation map showing empty coordinates and route
NatLibFi/NDL-VuFind2 pull request #2616
Opened 2023-05-24 07:21 UTC by siiriylonen

2023-05-24 07:29 UTC, siiriylonen commented
Ok, tässä nyt vielä ajatusvirhe tullut if-kohdassa...

2023-05-29 06:59 UTC, EreMaijala requested changes

2023-05-29 06:59 UTC, EreMaijala commented on themes/finna2/js/finna-organisation-info-page.js
> +          // Map not shown when museum's information has no coordinates
Eikö tämän tarkistuksen voisi laittaa initMap:n sisään ja tehdä riippumatta siitä, onko kyseessä museo?

2023-05-29 06:59 UTC, EreMaijala commented on themes/finna2/js/finna-organisation-info-page.js
> +    if ('routeUrl' in data && data.address !== '') {
Miksi tässä tarkistetaan address eikä routeUrl?

2023-05-29 07:04 UTC, siiriylonen commented on themes/finna2/js/finna-organisation-info-page.js
> +    if ('routeUrl' in data && data.address !== '') {
Koska se tieto on laitettu/muodostettu taulukkoon joka tapauksessa, mutta ilman koordinaatteja. Tarkistaisinko siis mielummin jotenkin, että routeUrl osoitteessa löytyy koordinaatit?

2023-05-29 07:14 UTC, EreMaijala commented on themes/finna2/js/finna-organisation-info-page.js
> +    if ('routeUrl' in data && data.address !== '') {
Jos routeUrl muodostuu silloinkin, kun ei ole tarvittavia lähtötietoja, niin pitäisi korjata sen muodostaminen.

2023-05-31 08:05 UTC, siiriylonen commented on themes/finna2/js/finna-organisation-info-page.js
> +          // Map not shown when museum's information has no coordinates
Jos nyt olen katsonut asiaa oikein, niin initMap() kautta ei ole mahdollista, koska se kyllä tekee ne kartan markereiden infot, mutta se ei poistaisi sitä ongelmaa että karttapalikka näkyisi sivulla joka tapauksessa?

2023-05-31 08:06 UTC, siiriylonen commented on themes/finna2/js/finna-organisation-info-page.js
> +          // Map not shown when museum's information has no coordinates
Kartan muodostamisvaiheessa kyllä tarkistetaan esim. null arvoja koordinaateissa, mutta en tiedä onko tässä ongelmana nyt se, että museoiden tiedot muodostetaan eri tavalla kuin kirjastojen ja niihin ei tule ikinä null vaan on käytetty defaultina "" (niiden vaihtaminen null tai poistaminen kokonaan ei asiaan auttanut).

2023-05-31 08:22 UTC, EreMaijala commented on themes/finna2/js/finna-organisation-info-page.js
> +          // Map not shown when museum's information has no coordinates
Tarkoitin sitä, että initMap:n pitäisi tarkistaa, onko kartta näytettävissä, ja jättää se näyttämättä (tai jopa piilottaa), jos ei ole. Ja initMap:lla tarkoitin siis finna-organisation-info-page.js:stä löytyvää.

2023-05-31 08:34 UTC, siiriylonen commented on themes/finna2/js/finna-organisation-info-page.js
> +          // Map not shown when museum's information has no coordinates
Niin sitä siellä olevaa tarkoitinkin, mutta tarkoititkin että se siis piilotettaisiin myös sitä kautta, ihan kuten tässäkin olen tehnyt .hide() tavalla ja se olisi ok? (..ajattelin, että sen pitäisi jotenkin automaattisesti ymmärtää piilottaa se ilman tietoja.)

2023-06-01 07:37 UTC, EreMaijala requested changes

2023-06-01 07:37 UTC, EreMaijala commented on themes/finna2/js/finna-organisation-info-page.js
> +    var empty = [];
Miksi empty on array? Eikö true/false riittäisi?

2023-06-01 07:52 UTC, siiriylonen commented on themes/finna2/js/finna-organisation-info-page.js
> +    var empty = [];
Tässä taisi olla se, että kaikkien obj koordinaattien pitäisi olla tyhjiä, että karttaa ei tarvitse näyttää ja sen takia pitäisi sitten katsoa että kaikki tyhjät olisivat true -> kuitenkin array. Voin vielä tätä miettiä jos sen saisi järkevämmin tai jos en vain hoksannut yksinkertaisempaa tapaa.

2023-06-01 07:55 UTC, EreMaijala commented on themes/finna2/js/finna-organisation-info-page.js
> +    var empty = [];
Eli:
```
    var coordinatesExist = false;
    $.each(organisationList, function checkEmptyCoordinates(i, obj) {
      if (obj.address && obj.address.coordinates) {
        var coordinates = obj.address.coordinates;
        var isEmpty = Object.values(coordinates).some(value => (value === '' || value === null));
        if (!isEmpty) {
          coordinatesExist = true;
        }
      }
    });
    if (!coordinatesExist) {
      holder.find('.map-ui').hide();
      return;
    }
```

2023-06-05 08:42 UTC, EreMaijala approved these changes

2023-06-05 08:45 UTC, EreMaijala requested changes
Hetkonen, muualla on selektorina `.office.map-ui`, varmaan olisi hyvä käyttää tässä samaa.

2023-06-05 09:06 UTC, siiriylonen commented
Tässä elementissä ei ole vain luokkaa .office, mutta on .office-search, käytänkö sitä sen sijaan? (..muutin nyt näin ja ilmeisesti tämä siis on se kartta-palkki, josta se .office.map-ui tulisi näkyviin, jos kartan avaa.)
(.office-search .navi-section .map-ui ovat siinä piilotettavassa elementissä olevat luokat)

2023-06-05 09:16 UTC, EreMaijala commented
> Tässä sivun kohdassa ei ole vain luokkaa .office, mutta on .office-search, käytänkö sitä sen sijaan? (..muutin nyt näin) (.office-search .navi-section .map-ui ovat siinä piilotettavassa olevat luokat)

Ehkä pitäisi piilottaa sekä `.map-control-buttons` että `.office.map-ui`. Tässä on pieni ongelma, kun luokat ovat niin epäselviä. Nähdäkseni tuo `#consortium-service-point-section` div pitää jättää näkyviin, vaikka kartta piilotettaisiin, koska siinä on palvelupisteiden haku. Ja niitä voisi olla, vaikka ei olisi koordinaatteja.

2023-06-06 15:06 UTC, EreMaijala approved these changes

2023-06-06 15:06 UTC, merged