[FINNA-436] QDC: display copyrights as descriptions if suited
NatLibFi/NDL-VuFind2 pull request #2626
Opened 2023-05-31 13:02 UTC by LuomaJuha

* Try to match the language from the topmost copyright

2023-06-01 07:41 UTC, EreMaijala requested changes

2023-06-01 07:41 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrQdc.php
> +    protected function getRights(string $language): array
En oikein tajua, mitä tässä metodissa tapahtuu tai pitäisi tapahtua. Näyttäisi siltä, ettei `$language`-parametria käytetä ollenkaan, eikö pitäisi?

2023-06-01 07:41 UTC, EreMaijala commented on module/Finna/tests/fixtures/qdc/qdc_ir_test.xml
> +  <rights type="copyright" lang="fi">This is a copyright which is should not be displayed</rights>
`is` pois tästä ja seuraavasta :)

2023-06-01 07:52 UTC, LuomaJuha commented on module/Finna/src/Finna/RecordDriver/SolrQdc.php
> +    protected function getRights(string $language): array
Hmm, totta joo, jäi jotenkin ajattelematta tuo pointti. Sitä käytetään täl hetkel linkkien muodostukseen mut kaipa sil vois kattoa josko siel löytyis oikean kielinen copyright myöskin

2023-06-01 07:52 UTC, LuomaJuha commented on module/Finna/tests/fixtures/qdc/qdc_ir_test.xml
> +  <rights type="copyright" lang="fi">This is a copyright which is should not be displayed</rights>
hupsista

2023-06-05 09:06 UTC, EreMaijala requested changes

2023-06-05 09:06 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/Feature/SolrCommonFinnaTrait.php
> +            ...explode(
LocaleSettings:ltä saisi suoraan `getFallbackLocales`. Saisikohan sen ympättyä tänne? Se ei ole ihan sama kuin tuo asetus suoraan, mutta olisikin siinä mielessä parempi, että siinä on se järjestys, jota käännöksiin käytetään.

2023-06-05 09:06 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/Feature/SolrCommonFinnaTrait.php
> +        if ($shortCode) {
`SolrLido::getLanguageSpecificItem`:ssa tehdään niin, että koitetaan ensin koko language+region -yhdistelmällä ja sitten pelkällä languagella. Eli jos kielikoodina en-gb, niin taulukkoon tulisi
```
[
    'en-gb',
    'en',
]
```
Ehkä tässä voisi tehdä niin, tai sitten yhtenäistää jotenkin muuten?

2023-06-05 09:06 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/Feature/SolrCommonFinnaTrait.php
> +    protected function getLanguagePriority(
Tän nimi voisi olla esim. `getPrioritizedLanguages`, muuten kuulostaa siltä, että pyydetään annetun kielen prioriteettia.

2023-06-05 09:06 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrQdc.php
> +            // Add all extra copyrights as description
Tässä siis otetaan kaikkien muiden kielienkin tekstit? Miksi? Vähän tarkempi kommentti ainakin olisi paikallaan.

2023-06-06 15:51 UTC, EreMaijala approved these changes

2023-06-06 15:52 UTC, merged