[FINNA-639] QDC: allow displaying of images if media type is set.
NatLibFi/NDL-VuFind2 pull request #2633
Opened 2023-06-22 09:56 UTC by LuomaJuha

2023-08-01 09:54 UTC, EreMaijala requested changes

2023-08-01 09:54 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrQdc.php
> +                    ($type && !in_array($attributes->type, $mediaTypes))
Kun PDF:llä on vain yksi mediatyyppi, niin voisiko tässä vain verrata `$type !== 'application/pdf'`?

2023-08-01 09:54 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrQdc.php
> +                    || (!$type && !preg_match('/\.(pdf)$/i', $url))
Turhat sulut regexp:ssä

2023-08-28 06:50 UTC, LuomaJuha commented on module/Finna/src/Finna/RecordDriver/SolrQdc.php
> +                    ($type && !in_array($attributes->type, $mediaTypes))
Eiköhän se olis passelein tapa.

2023-08-31 07:04 UTC, EreMaijala requested changes

2023-08-31 07:04 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/Feature/SolrCommonFinnaTrait.php
> +                    || (!empty($images[$index]['pdf']) && $images[$index]['pdf'] === true)
Tän voisi vielä yksinkertaistaa `true === $images[$index]['pdf'] ?? false`

2023-08-31 07:22 UTC, LuomaJuha commented on module/Finna/src/Finna/RecordDriver/Feature/SolrCommonFinnaTrait.php
> +                    || (!empty($images[$index]['pdf']) && $images[$index]['pdf'] === true)
Typistin vielä vähän lisääkin

2023-08-31 07:55 UTC, EreMaijala approved these changes

2023-08-31 07:56 UTC, merged