[FINNA-774] Make advanced search facets collapsible
NatLibFi/NDL-VuFind2 pull request #2637
Opened 2023-07-06 11:16 UTC by siiriylonen

2023-07-17 14:52 UTC, siiriylonen commented
Täällä oli pienoinen ongelma liittyen Vuosivalinta- ja Kartta-fasettiin. Kun ne olivat alussa collapsed tilassa, niin niiden asetuksiin liittyviä margin arvoja yms. ei laskettu oikein (aina 0), jonka takia ne näkyivät väärin.
-> Nyt ne ovat aluksi kiinni, mutta vasta kun collapse on avattu niin ne lasketaan.

En osaa sanoa kumpi on parempi ratkaisu, että ne vain olisivat aluksi auki (koska sen jälkeen ei ongelmaa sulkemisen ja avaamisen kanssa) vai kuin ovat nyt (esim. mitä jos fasetin lataamisessa kestää).
(Tässä myös piti käyttää 'shown.bs.collapse', koska show oli ilmeisesti liian aikainen ja sama ongelma arvojen laskemisessa tuli vastaan...)

2023-08-01 10:57 UTC, EreMaijala requested changes
Ohessa pari pientä kommenttia nykyisestä toteutuksesta, mutta tässä pari isompaa juttua:

1. Olisi parempi käyttää finna-panel -komponenttia eikä toteuttaa uutta collapse-systeemiä.
2. Oletuksena collapsoidutkin rajaukset pitäisi näyttää avattuina ainakin silloin, kun muokataan hakua, jossa on tehty ko. rajauksia.
3. Myös EDS:n tarkennetussa haussa on rajaimia, pitäisi olla yhtenäinen.
4. Huolettaa, että esim. usein tiettyä rajainta käyttävää käyttäjää alkaa ärsyttää, jos avauksia ei muisteta ja aina pitää klikata rajain auki ensin.
5. Huolettaa, että nyt ei enää näe nopealla silmäyksellä, millaisia vaihtoehtoja on tarjolla.
6. Huolettaa, että tästä tulee aika iso muutos hyötyyn nähden.

2023-08-01 10:57 UTC, EreMaijala commented on themes/finna2/templates/search/advanced/ranges.phtml
> +      <button class="list-group-item title collapsed" type="button" data-toggle="collapse" data-target="#<?=$current['field']?>" controls="#<?=$current['field']?>" aria-expanded="false">
controls-attribuutilla ei kuulu olla risuaitaa

2023-08-01 10:57 UTC, EreMaijala commented on themes/finna2/templates/search/advanced/multiselect.phtml
> +  <button class="list-group-item title collapsed" type="button" data-toggle="collapse" data-target="#<?=$this->escapeHtmlAttr(str_replace(' ', '', $this->field))?>" controls="<?=$this->escapeHtmlAttr
Ota siistitty field talteen ensin, niin ei tarvitse tehdä samaa str_replace:a moneen kertaan.

2023-08-04 10:05 UTC, pasitiis commented
Olen kyllä samaa mieltä Eren kanssa että valinnat aiheuttaa lisäpainalluksia. Auttaisi jos käyttäjän avaamaat rajaimet muistettaisiin. 

Collapsointi on katsottu hyödylliseksi jos tarkennettuun hakuun tuodaan lisää rajaimia (mediatyppi, käyttöoikeudet jne.). Jos rajaimia on käytössä muutama, niin collapsointiin ei mielestäni ole tarvetta.

<img width="901" alt="Näyttökuva 2023-8-4 kello 9 57 32" src="https://github.com/NatLibFi/NDL-VuFind2/assets/1954586/0288d40a-3a07-4e38-bd8e-2e44355be872">

Tekstityyli saisi olla yhtenevä (nyt ylhäällä on pieniellä kirjoitettu ja alhaalla isolla)

2023-08-23 06:17 UTC, closed without merging