[FINNA-506] Make my account more compact on mobile (v2)
NatLibFi/NDL-VuFind2 pull request #2640
Opened 2023-07-10 07:15 UTC by siiriylonen

2023-07-10 09:12 UTC, siiriylonen commented
Muutama huomio:

- Lainaushistorian sivun rakenne oli erilainen, jolloin sticky-toolbar ei toiminut. Siirsin olemassaolevat elementit samaan järjestykseen kuin muilla taulukkosivuilla, joten toivottavasti se nyt on vielä ok. Sticky-toolbar ainakin toimii nyt.

- Suosikit-sivulla oli joku omanlainen sticky-toolbar systeemi ja napit tietynlaiset, niille en nyt ole tehnyt mitään (paitsi poistin "Valise sivu/kaikki"-tekstin.

- Kun toolbar on "stickymoodissa" eli kiinni navigaatiossa, sen alla pitäisi näkyä navigaation varjo (ja itse navigaation alla olevan ei pitäisi näkyä). Sain sen toteutettua IntersectionObserverillä, mutta se ei toimi muutamalla selaimella (kuten firefox ja safari), joten en ollenkaan ole sitä nyt lisännyt mukaan...

2023-07-12 13:35 UTC, siiriylonen commented
Tähän nyt lisätty se navigaation varjo, samalla tavalla kuin Suosikit-sivulla.

Lainaushistoria sivun "Kopioi suosikkeihin"-nappi on myös ollut mietinnässä. Se on nyt otettu pois, mutta jos se halutaan pitää siellä niin voisiko sille olla jokin parempi ratkaisu. Tietuelistauksissa sille on ikoni ja sitä kutsutaan nimellä "Lisää suosikkeihin" (Ja itse Suosikit-sivulla se toiminnon "Lisää listaan" alla.)

2023-07-17 11:28 UTC, siiriylonen commented
Lisähuomioiden lisähuomioita:

Varastotilaukset- ja Kaukolainatilaukset-sivuilla oli käytetty erilaista rakennetta toolbarin luomisessa (toolbarilla ei ollut ylätason table-elementtiä), oliko se näin jostain tietystä syystä, koska nyt sillä pitäisi olla sama kuin muualla -> mobiilissa samanlevyinen toolbar.
Näihin molempiin myös lisättiin "Valitse kaikki"-ruutu kuten muuallakin on.

Sticky toolbarin varjo nyt näkyy vain kun toolbar koko sivun levyinen (puhelin) koska muuten se ei tällä toteutuksella toiminut. (Eli otanko koko puhelimen lisävarjon pois vai annetaanko olla kuten muualla?)

2023-07-31 11:15 UTC, pasitiis commented
Täytyy vielä vähän miettiä yhtenäisyyttä.

- Lainat / Varaukset toiminnoissa toisessa on käytetty btn-groupia ja toisessa ei. Termejä on myös käytetty vähän eri tavalla.  
- Varaukset osiossa on käytössä disabled jos mitään ei ole valittu, pitäisi olla myös Lainoissa. 

Suosikkien valita tuntuu nyt selkeämmältä kuin Lainat ja Varaukset kohdissa. Olisi varmaan käyttäjälle selkeämpää että esitystapa olisi yhtenäinen. 

Nopea kokeilu lainat osioon vastaavalla tyylillä kuin suosikit.

<img width="1214" alt="Näyttökuva 2023-7-31 kello 13 34 07" src="https://github.com/NatLibFi/NDL-VuFind2/assets/1954586/eaec3063-654d-4fb5-bd9f-91dcf1d5b51c">

2023-07-31 13:43 UTC, siiriylonen commented
Mielestäni tähän jo push niitä muutoksia, mutta eivät vielä näy? Niin sitä vaan, että jos nyt tekee kuten Varastotilaukset-sivulla (ei yksisanaisia nappeja, niin sitten "Muokkaa" muuttuisi myös "Muokkaa valittuja" -> taas aika paljon tekstiä -> näyttäisi rivittyvän pienemmällä näytöllä

2023-08-01 06:33 UTC, pasitiis commented
Katsottiin @MillaKPE leiskoja ja kaiketi oli tarkoitus tehdä Suosikki-tyyliset toimintopainikkeet, jotta toimisi paremmin mobiilissa. @MillaKPE tekee vielä tarkennuksia leiskoihin (mm. desktop-versiossa oli tarkoitus käyttää samaa painiketyyliä kuin mobiilissa).

2023-08-02 13:48 UTC, MillaKPE commented
Leiskat on fiksailtu Figmassa, suosikit välilehti saattaa aiheuttaa ongelmaa, koska siinä vie tilaa custom listat, joilla on toinen nimi + mahdollisesti kuvaus + järjestelypainike. Lisään päivitettyjen leiskojen kuvat Jiraan ja poistan vanhat- jottei ne mene sekaisin.

2023-08-03 06:01 UTC, siiriylonen commented
Olen nyt muokannut näitä vastaamaan niitä uusia suunnitelmia ja:

- Lainaushistoria-sivu edelleen hieman ongelmallinen pienellä näytöllä, vaikka marginaaleja/reunoja pienentäisi napit rivittyisivät siitä huolimatta.

- Kaikilla sivuilla Järjestä-nappi ei mene samalle riville vaikka mahtuisi, koska pyrin myös eri kielillä saamaan sen oikeaan kohtaan -> menee leveämmän mukaan (ja yritin käyttää niitä olemassa olevia breakpointeja)

- Suosikit-sivulla en nyt ole vieläkään erityisemmin muokannut nappeja muuten kuin lisäsin yhden id:n reunojen pyöristämisen takia.

2023-08-03 07:15 UTC, EreMaijala commented
> (Ja kommentoin nyt vielä tähänkin siitä Lainaushistoria-sivun eng käännöksistä. Voisiko siellä käyttää termiä "Clear History" ja "Delete" nykyisen "Purge" ja "Purge History" sijaan?) -> muutos tehty

"Purge" on ihan tietoinen valinta ja luottaisin siinä natiivi-englanninkieliseen näkemykseen.

2023-08-03 09:25 UTC, siiriylonen commented
Nyt Järjestä-nappi myös suunnitelmaa vastaavasti aseteltu. (Niihin tuli nyt myös pikseli-laskelmia, koska muuten olisi ollut turhaa muutaman pikselin ajaksi siirtää napin paikkaa.)

2023-08-11 06:59 UTC, pasitiis commented
Desktopissa järjestä toiminto voisi olla edelleen lähempänä listaa. Mobiilissa on ok että on kahdella rivillä. 
![Näyttökuva 2023-8-11 kello 9 55 52](https://github.com/NatLibFi/NDL-VuFind2/assets/1954586/573a7c92-eeec-476a-95e4-f7570c6417c9)

2023-08-14 05:59 UTC, siiriylonen commented
Meniköhän tämä merge nyt ihan oikein? (history.phtml tiedostosta se valitti konfliktia ja jos oikein katsoin niin ainut muutos oli että osa sisällöstä tulee nyt template, joten sen pitäisi olla ok.) Mutta enemmän ihmettelen, että With_selected käännös on kadonnut kaikkialta?

2023-08-14 12:19 UTC, pasitiis commented
Jäin vielä miettimään, onko käyttäjälle tarpeeksi selkeää, että "oma tili" valikossa ei näy "oma tili"-teksti pienemmissä mobiilin näyttökoossa (esim iPhone mini). Leiskassa "oma tili" teksti on näkyvillä, mutta sen sijoittaminen tekee yläosasta ahtaan (jos kielivalikko on esillä).

2023-08-15 06:08 UTC, siiriylonen commented
Suomen kielen kanssa valikko ja täysi Oma tili -teksti toimii ihan hyvin, mutta englanniksi on vähän täysi:
<img width="467" alt="Screenshot 2023-08-15 at 9 01 11" src="https://github.com/NatLibFi/NDL-VuFind2/assets/117457514/36aa6b24-76ad-4ebd-ad0e-eff48b37fb94">

2023-08-15 06:49 UTC, pasitiis commented
Ehkä ei kannata laittaa näkyviin. Testasin myös pienemmällä tekstikoolla, näytti ahtaalta. 

<img width="444" alt="Näyttökuva 2023-8-15 kello 9 45 16" src="https://github.com/NatLibFi/NDL-VuFind2/assets/1954586/48e7aee2-ed11-40cd-81a3-fa3c51eb8627">


Ruudunlukijoille voisi tekstin kuitenkin laitttaa luettavaksi sr-only kentän avulla (jos joku käyttää ruudunlukijaa puhelimella).

2023-08-16 07:44 UTC, siiriylonen commented
Kai ymmärsin oikein ja sr-only siis pitäisi olla vain kun tekstiä ei muutenkaan näkyisi? (Koska se luokkahan piilottaisi sen muuten -> eli ei tehtäisi siitä aina sr-only luokan omaavaa, mutta niin että näkyisi kuten nyt..)

2023-08-25 06:24 UTC, pasitiis commented
Sr-only -kenttä vain siinä tapauksessa kun teksti ei muuten näy ja sisältö halutaan luettavan ruudunlukijalla.

2023-08-28 09:57 UTC, pasitiis commented
Flash-message sijaintia voisi säätää siten ettei tule hakupalkkiin kiinni.

<img width="470" alt="Näyttökuva 2023-8-28 kello 12 52 55" src="https://github.com/NatLibFi/NDL-VuFind2/assets/1954586/7c7fdfd5-5afd-4757-9153-5e37e86df0a4">

Korjattu ehdotus (ylä- ja alamarginaali 12px).
<img width="439" alt="Näyttökuva 2023-8-28 kello 12 54 05" src="https://github.com/NatLibFi/NDL-VuFind2/assets/1954586/e83386cd-ace9-47b5-808f-febfa1a201ca">

2023-08-28 11:51 UTC, pasitiis commented
Tekisin oma tili -valikon hieman siistimmäksi mobiilissa. Nykyinen totetus käyttää floatia, mutta flexillä rivityksen saisi hieman selkeämmäksi, mikäli teksti rivittyy kahdelle riville (esim. en-versio).

Nykyinen 
<img width="306" alt="Näyttökuva 2023-8-28 kello 14 46 41" src="https://github.com/NatLibFi/NDL-VuFind2/assets/1954586/5dfc9fa4-7dff-4fe0-9708-d0df79db5b58">

Kokonaan flexillä: 
<img width="354" alt="Näyttökuva 2023-8-28 kello 14 46 28" src="https://github.com/NatLibFi/NDL-VuFind2/assets/1954586/f7af267e-f224-4e90-8c72-f6b621333b03">

2023-08-28 13:12 UTC, siiriylonen commented
Tuolla on vielä eroavaisuuksia liittyen niihin nappien dropdown-varmistuksiin niin katson ne läpi..
Lainaushistoria-sivulla ne menevät ok (ja dropdown-teksti on 'span') kun taas esim. Varaukset-sivulla menee yli (dropdown-teksti on 'a' -> siksi ei rivity?):
<img width="410" alt="Screenshot 2023-08-28 at 15 49 09" src="https://github.com/NatLibFi/NDL-VuFind2/assets/117457514/6eecd5b2-d3e9-4358-99c7-c72da86da864">

2023-08-29 06:18 UTC, pasitiis commented
Kirjastokortti valintaan varmaankin pitää lisätä   justify-content: left;

```
#my-info-dropdown-menu .card-selection > a {
  justify-content: left;
}
```

<img width="390" alt="Näyttökuva 2023-8-29 kello 9 13 31" src="https://github.com/NatLibFi/NDL-VuFind2/assets/1954586/420e9b96-3047-4438-a238-5ccbadb63931">

2023-08-30 13:46 UTC, pasitiis commented
Suosikeissa on jotain häikkää checkbox-valinnan kanssa. Lisäksi Lisää listaan... -painikeessa on ylimääräistä tyhjää tilaa painikkeessa.
<img width="477" alt="Näyttökuva 2023-8-30 kello 16 41 31" src="https://github.com/NatLibFi/NDL-VuFind2/assets/1954586/8a3e9e26-e9f9-453c-9455-ac3489ae5775">

2023-09-06 07:12 UTC, pasitiis commented
Pohdin vielä pitäsikö painkkeiden tyylin nimeämisellä tehdä jotain. Aavistuksen sekavaa että templatessa painke määritellään btn-primaryksi joka sitten yliajetaan. voisiko painikkeen tyylinä olla btn btn-finna-toolbar tms. ?

2023-09-06 09:45 UTC, pasitiis commented
Sort-toiminnon voisi koittaa saada sivulle siten ettei mobiiliin tarvisi laittaa erikseen (esim. käyttämällä flexin reverse sääntöjä). Nyt sort-toiminnon sijoittelu on mielestäni tehty liian monimutkaisesti tyylitiedostoihin ja sivupohjaan.

2023-09-08 10:03 UTC, pasitiis approved these changes

2023-09-08 10:43 UTC, EreMaijala requested changes
Olen vähän huolissani siitä, miten paljon JS-koodia tässä tulee lisää.

2023-09-08 10:43 UTC, EreMaijala commented on local/languages/finna/en-gb.ini
> +with_selected = "with selected"
Miksi tämä on ilmestynyt takaisin?

2023-09-08 10:43 UTC, EreMaijala commented on themes/finna2/js/finna-mylist.js
> +    const stickyElement = $('.toolbar-sticky');
Uudessa js-koodissa olisi parempi välttää jQuerya.

2023-09-08 10:43 UTC, EreMaijala commented on themes/finna2/js/finna-mylist.js
> +    var checkCheckboxes = function CheckCheckboxes() {
Tämä on kopioitu muualta, mutta kuitenkin: tuolla var:lla ei tee mitään, funktion nimi pienellä, ja jotain muuta kuin "check", kun sen voi käsittää tarkoittamaan rastittamista, eikä oikeastaan kerro, mitä tehdään. Esim. `toggleButtonsForSelected`.

Lisäksi tämä on väärässä paikassa. mylist on suosikkilistojen js:lle.

2023-09-08 10:43 UTC, EreMaijala commented on themes/finna2/js/finna-mylist.js
> +      $('form[name="renewals"] .result .checkbox input[type=checkbox]').on('change', checkCheckboxes);
Nämä ovat väärässä paikassa. Pitäisi olla funktion ulkopuolella.

2023-09-08 10:43 UTC, EreMaijala commented on themes/finna2/js/finna-layout.js
> +  window.addEventListener('resize', () => {
Miksei `window.addEventListener('resize', srOnlyToNav);`?

2023-09-08 10:43 UTC, EreMaijala commented on themes/finna2/js/finna-mylist.js
> +      $(window).on('scroll', function onScrollWindow() {
Tämä ei ole hyvä juttu. scroll-eventti tapahtuu todella usein, ja stickyToolbar:ia kutsuttaisiin ihan hurjan usein. Koittaisin mieluummin esim. [tätä strategiaa](https://developer.chrome.com/blog/sticky-headers/). Jos se ei jostain syystä onnistu, pitäisi tuo scroll-eventti [debouncettaa ta throttlettaa](https://www.javascript.christmas/2020/19).

2023-09-08 10:57 UTC, siiriylonen commented on local/languages/finna/en-gb.ini
> +with_selected = "with selected"
Tämän käännöksen käyttö taisi liittyä siihen että nappien tekstejä lyhennettiin ja Suosikit-sivulla taisi muutenkin jo olla se käytössä, niin yhtenäisempi. Onko se nyt väärässä paikassa tiedostossa, jos käyttää sitä oma tilissä? Vai laitan jonkin muun käännöksen?

2023-09-08 11:51 UTC, siiriylonen commented on themes/finna2/js/finna-mylist.js
> +      $(window).on('scroll', function onScrollWindow() {
Ok, IntersectionObserver:iä kokeilin, mutta se varjomuutos ei toiminut oikein ainakaan Firefox ja Safari niin otin pois. Tässä myös oli Suosikit-sivulla oleville bulkActionButtoneille heti ylempänä oma funkio, joka tekee samaa, niin pitäisikö sillekin tehdä jotain? Pitäisikö molempien käyttää samaa funktiota?

2023-09-08 11:59 UTC, EreMaijala commented on local/languages/finna/en-gb.ini
> +with_selected = "with selected"
Se poistettiin kokonaan, kaikkialta. Kontekstista selviää toimintojen tarkoitus muutenkin.

2023-09-11 09:53 UTC, pasitiis commented on themes/finna2/js/finna-mylist.js
> +      $(window).on('scroll', function onScrollWindow() {
Kannattaa varmaan kaikki pyrkiä tekemään IntersectionObserverillä.

2023-09-11 12:14 UTC, siiriylonen commented on themes/finna2/js/finna-mylist.js
> +      $(window).on('scroll', function onScrollWindow() {
Okei, voin sitä vielä yrittää mutta siinä oli silloin se ongelma, jota en saanut ratkaistua ja se saattoi liittyä siihen miten ne selaimet itsessään toimivat.

2023-09-14 06:52 UTC, LuomaJuha commented on themes/finna2/js/finna-layout.js
> +  window.addEventListener('resize', () => {
Katsoin vain tämän ja mietin olisiko tässä mahdollista käyttää less tyyliä media < 400px ja silloin se kopioisi .sr-only luokan?

2023-09-14 11:44 UTC, siiriylonen commented
Ne Suosikit-sivun napit vielä...

2023-09-22 06:53 UTC, pasitiis commented on themes/finna2/js/finna-layout.js
> +  function setStickyNavObserver() {
Pitäsikö tälle olla paremmin kuvaava nimi, joka viittaa missä funktiota käytetään?  setStickyMyaccountHeader tms.

Itse ehkä optimoisin funktion koodia vähän selkeämmäksi ja käyttäisin togglea. 

`function setStickyNavObserver() {
  const toolbar = document.querySelector('.toolbar-sticky');
  const finnaNavbar = document.querySelector('.finna-navbar');
  const observedElement = document.querySelector('.myaccount-sticky-header');

  if (toolbar && finnaNavbar && observedElement) {
    const observer = new IntersectionObserver(entries => {
      const intersecting = entries[0].isIntersecting;
      toolbar.classList.toggle('isSticky', !intersecting);
    }, {
      rootMargin: `-${finnaNavbar.offsetHeight}px`,
    });

    observer.observe(observedElement);
  }
}`

2023-09-22 07:05 UTC, pasitiis commented on themes/finna2/js/finna-mylist.js
> +      $('#add-to-list').css('border-radius', '0 4px 4px 0');
Mietin voisiko border-radius olla määriteltynä less-tiedostossa?

2023-09-25 08:06 UTC, EreMaijala commented on themes/finna2/js/finna-mylist.js
> +      $('#add-to-list').css('border-radius', '0 4px 4px 0');
Tätä koko viritystä ei tarvita, jos spinneri siirretään pois tuosta btn-group:sta sotkemasta.

2023-09-25 11:29 UTC, LuomaJuha requested changes

2023-09-25 11:29 UTC, LuomaJuha commented on themes/finna2/js/finna-layout.js
> +    else if (element.closest('form').id === 'purge_history') {
Rivitys oudosti.

2023-09-25 11:29 UTC, LuomaJuha commented on themes/finna2/js/finna-layout.js
> +      document.getElementById('renewSelected').toggleAttribute('disabled', checkedRenewals === null);
Näissä varmaan kannattaa ottaa huomioon se, että document.getElementById||.querySelector saattaa palauttaa null jolloin suoraan sen kutsuminen ei onnistu vaan voi aiheuttaa virheen. Turvallisempi tapa on asettaa muuttujaan ja katsoa onko olemassa. Tämä siis sen takia, koska jossain näkymässä voi olla muutettu jotain templaattia tai jotain.

2023-09-25 11:29 UTC, LuomaJuha commented on themes/finna2/js/finna-layout.js
> +    if (renewalForm) {
querySelectorAll taas palauttaa tyhjän nodelistin, jolloin voi putkittaa suoraan querySelectorAll.forEach(...

2023-10-04 11:18 UTC, LuomaJuha approved these changes
Toimii, vaikka onkin paljon muokkauksia. Ei paistanut mitään silmään.

2023-10-05 11:26 UTC, EreMaijala requested changes
Vielä katselmointi kesken, mutta tässä pari juttua.

2023-10-05 11:26 UTC, EreMaijala commented on local/languages/finna/fi.ini
> +hold_cancel_selected = "Peru"
Koska "Valituille:" -tekstiä ei enää ole, niin säilyttäisin näissä "valitut". Eli "Peru valitut", "Uusi valitut" jne.

2023-10-05 11:26 UTC, EreMaijala commented on themes/finna2/less/finna/myresearch.less
> +  @media(min-width: calc(@screen-xs - 139px)) {
Kiinteä leveys ei toimi kaikissa tilanteissa. Riippuu ihan siitä, mitä vaihtoehtoja on käytettävissä. Pitää tehdä jotenkin toisella tavalla, esim. määrittelemällä dropdownille maksimileveys kapeilla näytöillä.

2023-10-05 11:27 UTC, EreMaijala commented on local/languages/finna/fi.ini
> +renew_selected = "Uusi"
Tämä suomenkielinen on erityisen huono yksinään, kun siitä voi saada hassusti idean uudesta lainasta..

2023-10-05 11:33 UTC, EreMaijala commented on themes/finna2/less/finna/myresearch.less
> +    @media(max-width: @screen-md) {
Onko siihen jokin syy, ettei stickyä käytetä kuin kapeilla näytöillä?

2023-10-06 07:42 UTC, siiriylonen commented
Vaihdoin käännökset, Järjestä-nappi vain -sm isommilla näytöillä toolbarissa ja se nyt sticky myös desktopilla, (mutta en laittanut varjoa, koska se tulee reunoilta yli leveämmillä näytöillä, ellei sitä vielä haluta siihenkin).

2023-10-09 10:07 UTC, EreMaijala requested changes
- "Järjestä"-teksti ennen järjestys-dropdownia voisi nyt varmaan näkyä aina.
- lainaushistoria-sivu ei validoitu
- kapealla näytöllä ruksi asemoituu hassusti suhteessa valittujen käsittelynappuloihin (aiemmin osui paremmin samalle riville, vaikkei muuten ollut niin hyvä):
![kuva](https://github.com/NatLibFi/NDL-VuFind2/assets/1327659/564b5b2e-4c6d-4bba-bcb4-522fda995b31)

2023-10-09 10:07 UTC, EreMaijala commented on local/languages/finna/sv.ini
> +hold_edit_selected = "Ändra utvalda"
Tähän sama "valda" kuin muissakin käännöksissä.

2023-10-09 10:07 UTC, EreMaijala commented on themes/finna2/less/finna/myresearch.less
> +.myresearch-body .form .mylist-functions #button_email {
Yhdistä nämä `.myresearch-body .form .mylist-functions` alle, niin ei tule toistoa.

2023-10-09 10:07 UTC, EreMaijala commented on themes/finna2/templates/checkouts/history.phtml
> +              <?=$paginator ? $this->paginationControl($paginator, 'Sliding', 'Helpers/pagination-simple.phtml', ['params' => $params]) : ''?>
Tuossa on jo `$paginator` -tarkistus yläpuolella, miksi lisätty?

2023-10-09 10:07 UTC, EreMaijala commented on themes/finna2/templates/checkouts/history.phtml
> +                  <div class="renew-button-col">
Ei historiassa voi olla uusintanappulaa.

2023-10-10 10:11 UTC, siiriylonen commented
Suoraan sanottuna, en ole ihan varma korjaantuiko se validointiongelma nyt, mutta yksi /div ainakin näytti puuttuvan.

2023-10-17 11:11 UTC, EreMaijala requested changes
- Kuten muutamista kommenteista käy ilmi, niin kun nyt pureuduin tähän vähän syvällisemmin, kaipaisin selkeyttä css-selektoreiden käyttöön. Tässä setissä on aika paljon "täsmäiskuja" tiettyä tarkoitusta varten, ja esim. `sort-col` -elementtiin kohdistuvia sääntöjä on nyt ainakin kolmessa eri kohdassa myresearch.less:ssä ja jälkimmäisenä tuplasetti `.loans-sort, .holds-sort, .history-sort` vs. `#renewals, #update_holds, #loan_history`. Menee tosi hankalaksi ylläpitää, ja siksi hakisin mahdollisimman paljon oleamssaolevien luokkien hyödyntämistä ja välttäisin yksittäisten toimintojen listaamista.
- Kaikkien `$this->noSupport` -kohtien sijainti pitäisi tarkistaa. Turha on esim. sorttaus-elementtiä laittaa sen yläpuolelle, jos ei tukea ole. Ehkä siistimpää olisi tarkistaa `$this->noSupport` alussa ja tehdä aikainen return, jos ei ole tukea ole.

2023-10-17 11:11 UTC, EreMaijala commented on themes/finna2/less/finna/myresearch.less
> +    @media (max-width: @screen-sm) {
Eikö tämä voisi olla kaikilla `.useraccount-confirm` -kentillä eli yhteisissä säännöissä tällä hetkellä riviltä 968 alkaen?

2023-10-17 11:11 UTC, EreMaijala commented on themes/finna2/templates/checkouts/history.phtml
> +                    <tr id="loan_history" class="toolbar">
Tämä ei ansaitse tätä id:tä. Eikä tarvitsekaan, jos ei käytetä sitä less:ssä.

2023-10-17 11:11 UTC, EreMaijala commented on themes/finna2/less/finna/myresearch.less
> +#renewals .toolbar, #update_holds .toolbar, #cancelStorageRetrievalRequest .toolbar, #cancelILLRequest .toolbar, #loan_history.toolbar {
Löytyisikö yhteistä sääntöä, esim. `.myresearch-grid-list .toolbar`?

2023-10-17 11:11 UTC, EreMaijala commented on themes/finna2/templates/checkouts/history.phtml
> +    <div class="myresearch-grid-list">
Ellei jäänyt jotain huomaamatta, en näe mitään muuta syytä vaihtaa tähän muotoon, jossa on kaksi sisäkkäistä div:iä, kuin sen, että sitä on käytetty muualla. Parempi olisi kuitenkin vähemmän elementtejä, eli vaihdetaan mieluummin muut yksinkertaisemmiksi.

2023-10-17 11:11 UTC, EreMaijala commented on themes/finna2/templates/myresearch/mylist.phtml
> +          <h2 class="list-title no-edit"><span><?=$this->transEsc('Favorites')?></span></h2>
Tässä on nyt kaksi h2:ta peräkkäin??? Ja tämä ei ole list-title.

2023-10-17 11:11 UTC, EreMaijala commented on themes/finna2/templates/myresearch/mylist.phtml
> +      </div>
Sisennys pielessä.

2023-10-17 11:12 UTC, EreMaijala commented
> Suoraan sanottuna, en ole ihan varma korjaantuiko se validointiongelma nyt, mutta yksi /div ainakin näytti puuttuvan.

Ei korjaantunut. Kannattaa testata itse. Esim. Web Developer Toolbar -laajennos tarjoaa näppärän "Validate local HTML" -toiminnon.

2023-10-24 08:03 UTC, siiriylonen commented on themes/finna2/less/finna/myresearch.less
> +    @media (max-width: @screen-sm) {
Tässä taisi olla se, että vain ne oikeammanpuoleiset vahvistusnapit menevät mobiilissa oikean reunan yli, jos laittaisi kaikkiin niin ne toiset menevät vasemmalta yli. Olisiko parempi esim. tehdä vielä erillinen luokka napille, joka tekisi näin?

2023-10-26 17:57 UTC, EreMaijala requested changes
Lainat:
- Uusi valitut -nappula ei aktivoidu
- Ei mene HTML-validaattorista läpi, jos lainoja ei ole
 
Lainaushistoria:
- Ei näy checkboxit, jos purgeSelected ei ole sallittu, eikä silloin voi lisätä valittuja suosikkeihin

Varaukset:
- Ei validoidu HTML, jos on varauksia, mutta yhtäkään ei voi muokata

Kaukolainatilaukset:
- Ei validoidu, jos on tilauksia

Suosikeissakin voisi "Järjestä" ja "Tuloksia sivulla" näkyä kaikilla leveyksillä

2023-10-26 17:57 UTC, EreMaijala commented on themes/finna2/templates/holds/list.phtml
> +      <?php if(!empty($this->recordList)): ?>
Väliyönti if:n jälkeen

2023-10-26 17:57 UTC, EreMaijala commented on themes/finna2/templates/myresearch/mylist.phtml
> +      </div>
Sisennys edelleen pielessä.

2023-10-26 17:57 UTC, EreMaijala commented on themes/finna2/templates/navibar.phtml
> +              <?php if($this->ils()->checkFunction('ILLRequests', $capabilityParams)): ?>
if perään väli

2023-10-26 17:57 UTC, EreMaijala commented on themes/finna2/less/finna/myresearch.less
> +  .mylist-controls .sort-button .dropdown-menu {
Tämä ei toimi oikein (mutta ongelmasta ehkä päästäisiin, jos tekstit näkyisivät koko ajan):
![kuva](https://github.com/NatLibFi/NDL-VuFind2/assets/1327659/56af4aef-39be-4876-9106-5e183ddba468)

2023-11-15 07:33 UTC, EreMaijala requested changes

2023-11-15 07:33 UTC, EreMaijala commented on themes/finna2/templates/myresearch/mylist.phtml
> +          <h2><?=$this->transEsc('Favorites')?></h2>
Tässä on nyt edelleen kaksi h2:ta peräkkäin.

2023-11-15 07:33 UTC, EreMaijala commented on themes/finna2/templates/navibar.phtml
> +                  <?=$this->transEsc('Interlibrary Loan Requests')?>
sisennys pielessä

2023-11-15 07:33 UTC, EreMaijala commented on themes/finna2/templates/navibar.phtml
> +                  <?=$this->transEsc('Storage Retrieval Requests')?>
sisennys pielessä

2023-11-16 08:39 UTC, EreMaijala approved these changes

2023-11-16 08:39 UTC, merged