[FINNA-646] Add place popover to LIDO event fields
NatLibFi/NDL-VuFind2 pull request #2649
Opened 2023-07-20 11:30 UTC by siiriylonen

2023-08-11 11:49 UTC, EreMaijala requested changes

2023-08-11 11:49 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +                        $place,
Menee sekavaksi, jos stringistä tehdäänkin array. Jokin toinen nimi arraylle, ja $place sinne järkevällä avaimella?

2023-08-11 11:49 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +                $placeId = $placenode->place->placeID ?? '';
Laita `?? []` ennemmin.

2023-08-11 11:49 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +                        $typeDesc = $this->translate('place_id_type_' . $idType, [], '');
Miksi oletuksena tyhjä?

2023-08-11 11:49 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +                        $place['type'] = $idType;
Nyt place:lle tulee vain viimeinen id ja tyyppi, vaikka ensimmäinen kuulostaisi loogisemmalta.

2023-08-11 11:49 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +                        $place['details'] = implode(', ', $details);
Nyt id:t ja niiden kuvaukset ovat irrallaan toisistaan, ja lopputuloksena on sotkua. Niiden pitäisi kulkea käsi kädessä. Ja mieluummin niin, että templaatissa määritellään, miten ne näytetään, eli ei käännöksiä tai implodea koodissa.

2023-08-14 11:43 UTC, siiriylonen commented
Saatoin nyt vähän mennä sekaisin mitä pitää loop ja mitä ei. Eli jos asetetaan vain ensimmäinen id ja idType, niin oliko nyt aivan väärin ottaa koko placeId:n foreach-loop pois? Vai pitäisi loopata, mutta otetaan kuitenkin vain ensimmäinen?

2023-08-16 09:23 UTC, EreMaijala requested changes

2023-08-16 09:23 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +                    if (isset($displayPlace['type'])) {
`$displayPlace` juuri määriteltiin ylempänä niin, ettei siinä voi olla type-elementtiä.

2023-08-16 09:23 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +                    $displayPlace['ids'][] = $id;
Tähän pitäisi ottaa mukaan kaikki id:t $placeId:stä.

2023-08-16 10:12 UTC, siiriylonen commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +                    $displayPlace['ids'][] = $id;
Eli loopataan placeId (koska on repeatable), mutta type ja id pitäisi käyttää vain ensimmäistä tulevaa arvoa ja ids:een menevät kaikki id:t

2023-08-24 12:10 UTC, EreMaijala approved these changes

2023-08-24 12:10 UTC, merged