[FINNA-788] Fix text break appearance on organisation info page
NatLibFi/NDL-VuFind2 pull request #2651
Opened 2023-07-25 04:24 UTC by siiriylonen

2023-08-01 11:01 UTC, EreMaijala requested changes
Tarkoitus on päästä eroon finna.layout.initTruncate:sta ja käyttää VuFind.truncate:a kaikkialla, joten pitäisi ennemmin saada se toimimaan oikein.

2023-08-01 11:42 UTC, siiriylonen commented
Onko sitä siis mahdollista muokata suoraan /themes/bootstrap3/js/truncate.js vai pyritään tekemään jollain muulla tavalla? (Se kun nyt laittaa ikonin eri puolelle ja käyttää eri käännöstä jne.)

2023-08-01 11:44 UTC, EreMaijala commented
Ei ole. Pitää säätää käännökset kohdalleen ja muut tyylit tarpeen mukaan. Jos tarvitaan muutoksia truncate.js:ään, niin yläjuoksulle niitä voi ehdottaa.

2023-08-02 13:40 UTC, pasitiis commented
Jotenkin tuntuu että jos ikoni on toisella puolella, niin toiminto saisi olla olemman painikeen tyylinen. Ehkä tyyli voisi olla jotakin tämänkaltaista. 
<img width="386" alt="Näyttökuva 2023-8-2 kello 16 32 41" src="https://github.com/NatLibFi/NDL-VuFind2/assets/1954586/7099f62d-11a8-4bfd-8abf-0910e43efc66">

2023-08-03 10:57 UTC, siiriylonen commented
(Pitäisi nyt olla alemman kuvan mukainen.)

2023-08-04 06:11 UTC, pasitiis commented
Yläjuoksun uudessa trucate-toteuksessa pitäisi olla parametri jossa ikoni voi sijoittaa oikealle. Yhtenäisyyden vuoksi olisi hyvä olla sijainti sama.

2023-08-04 06:23 UTC, EreMaijala commented
#2661 liittyy myös tähän.

2023-08-08 13:32 UTC, siiriylonen commented
Tämä käyttää nyt sitä finna-truncate komponenttia, mutta tekstistä jää hieman seuraavan rivin yläosaa näkyviin. Onko se mitä kautta korjattava asia? (Siis css teen jotain vai laskeeko tämä vaan jotain oudosti..)
-> Johtui margin-top, vaikka se kyllä "fonttikooltaan" sama. (Vaihdoin nyt vain sen kokoa, koska truncate tehdään myöhemmin niin siihen ei voi kohdistaa css-sääntöä ja se ei myöskään aina ole olemassa.)

2023-08-11 05:44 UTC, pasitiis commented on themes/finna2/less/finna/organisation-page.less
> +                    margin-top: 1.1em;
Onkohan tämä tarpeellinen muutos? En nyt näe isoa eroa vanhan ja uuden arvon välillä.

2023-08-11 05:55 UTC, pasitiis commented on themes/finna2/less/finna/organisation-page.less
> +                    margin-top: 1.1em;
Muutos näyttääkin olevan ok. 1em arvolla viimeinen rivi ei näytä peittyvän oikein

2023-08-16 09:24 UTC, EreMaijala commented
@pasitiis Mikä tämän tilanne, onko ok sinun puolestasi?

2023-08-16 13:15 UTC, pasitiis approved these changes

2023-08-16 13:17 UTC, EreMaijala approved these changes

2023-08-16 13:17 UTC, merged