[FINNA-452] Fix aria expanded on search facets
NatLibFi/NDL-VuFind2 pull request #2657
Opened 2023-07-26 13:00 UTC by siiriylonen

2023-07-26 13:01 UTC, siiriylonen commented
(En tiedä olisiko esim. 450, 451 ja 452 pr voinut yhdistää, mutta nyt meni näin.)

2023-08-01 11:58 UTC, EreMaijala requested changes
Bootstrapin (accessible?) asettaa joka tapauksessa aria-expanded:n, kun avaa tai sulkee, joten tämä korjaus ei auta. Jos vika on Bootstrapissa, niin ei voi mitään, mutta ehkä auttaisi, jos div:llä olisi `role="listbox"`?

2023-08-02 08:16 UTC, pasitiis commented
Vaikuttaa jotenkin bootstrap-accessibility ongelmalta. Heidän esimerkeissä aria-expandedia ei aseta html:ää, tällöin menee myös axe:n validatorista läpi. https://paypal.github.io/bootstrap-accessibility-plugin/demo.html#collapse-examples .

Bootstrap ilman bootstrap-accesibilityä menee validorista läpi vaikka aria-expanded on asetettu.. https://getbootstrap.com/docs/3.3/javascript/#collapse

2023-08-02 09:38 UTC, EreMaijala approved these changes
Pasin kanssa keskustelun jälkeen todettiin, ettei tätä nyt saada kokonaan kuntoon, kun vika on bootstrap-accessibility -moduulissa, mutta tämä korjaus auttaa hiukan lähtötilanteeseen, joten mennään tällä nyt toistaiseksi.

2023-08-02 09:39 UTC, merged