[FINNA-820] Fix subjects not showing on certain EAD3 items
NatLibFi/NDL-VuFind2 pull request #2660
Opened 2023-08-01 09:39 UTC by siiriylonen

2023-08-01 09:58 UTC, siiriylonen commented
Ai jaha, no huomasinkin että paikatkin vielä pitäisi saada näkyviin.. Eli kesken tämä nyt vielä

2023-08-02 11:23 UTC, EreMaijala requested changes

2023-08-02 11:23 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrEad3.php
> +            if (isset($controlaccess->geogname)) {
isset-tarkistus on turha. Vaikka yhtään geogname:a ei olisi, voi ne silti iteroida ilman tarkistuksia, kun SimpleXML ei palauta nullia tms. (tarkistus tarvitaan vain, jos yritetään päästä suoraan useamman elementin yli kuten aiemmin oli).

2023-08-02 11:23 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrEad3.php
> +            if (isset($controlaccess->subject)) {
isset-tarkistus on turha. Vaikka yhtään geogname:a ei olisi, voi ne silti iteroida ilman tarkistuksia, kun SimpleXML ei palauta nullia tms. (tarkistus tarvitaan vain, jos yritetään päästä suoraan useamman elementin yli kuten aiemmin oli).

2023-08-02 12:00 UTC, siiriylonen commented on module/Finna/src/Finna/RecordDriver/SolrEad3.php
> +            if (isset($controlaccess->geogname)) {
Eli ei tarvitse alempana (esim. $controlaccess->subject kohtaan) ?? [], koska ylempänä controlaccess joko arvo tai tyhjä taulukko?

2023-08-03 06:29 UTC, EreMaijala requested changes

2023-08-03 06:29 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrEad3.php
> +        foreach ($record->controlaccess ?? [] as $controlaccess) {
Tässäkään ei tarvita `?? []`.

2023-08-03 06:29 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrEad3.php
> +        foreach ($record->controlaccess ?? [] as $controlaccess) {
Eikä tässä.

2023-08-04 07:55 UTC, EreMaijala approved these changes

2023-08-04 07:56 UTC, merged