[FINNA-437] Display Dewey classification for MARC records
NatLibFi/NDL-VuFind2 pull request #2663
Opened 2023-08-08 18:34 UTC by jlehmus

2023-09-15 06:37 UTC, EreMaijala requested changes

2023-09-15 06:37 UTC, EreMaijala commented on local/languages/finna/en-gb.ini
> +Dewey = "Dewey Classification"
Myös käännösavaimeksi voisi laittaa `Dewey Classification`.

2023-09-15 06:37 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrMarc.php
> +    public function getDeweys()
Kävisikö `getDeweyClassifications`?

2023-09-15 06:37 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrMarc.php
> +            $result = [];
Tätä riviä ei tarvita.

2023-09-15 06:37 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrMarc.php
> +                break;
Miksi break? Eikö tarkoitus ole palauttaa kaikkia?

2023-09-18 09:39 UTC, jlehmus commented on module/Finna/src/Finna/RecordDriver/SolrMarc.php
> +    public function getDeweys()
okei

2023-09-18 09:44 UTC, jlehmus commented on module/Finna/src/Finna/RecordDriver/SolrMarc.php
> +                break;
oli vahingossa jäänyt, funktio palautti aluksi vain ekan arvon

2023-09-19 07:33 UTC, EreMaijala approved these changes

2023-09-19 07:33 UTC, merged