[FINNA-292] Use upstream icon helper.
NatLibFi/NDL-VuFind2 pull request #2665
Opened 2023-08-15 12:30 UTC by pasitiis

Pääosa Finnan  ikoneista muutettu yläjuoksun icon helpperiin. 

Puuttuvat
- hierarchyTree
- mylist
- finna-model-viewer

2023-08-29 07:52 UTC, EreMaijala requested changes

2023-08-29 07:52 UTC, EreMaijala commented on themes/finna2/js/finna-linked-events.js
> +      spinner = VuFind.icon('map-marker', 'map-marker-icon');
Miksi spinneriksi asetetaan map-marker?

2023-08-29 07:52 UTC, EreMaijala commented on themes/finna2/js/finna-menu.js
> +        $element.html('<span title="' + VuFind.translate('account_has_alerts') + '">' + VuFind.icon('warning', 'warning-icon'));
Varmaan menee ihan oikein käytännössä, mutta eikö pitäisi olla sulkevan `</span>` myös?

2023-08-29 07:52 UTC, EreMaijala commented on themes/finna2/js/finna-popup.js
> +  var next = '<button class="popup-arrow popup-right-arrow next-record" type="button">' + VuFind.icon('record-next', 'record-next-icon') + '</button>';
Nämä voisivat olla `const`:eja, eikö?

2023-08-29 07:52 UTC, EreMaijala commented on themes/finna2/js/finna-record.js
> +      var rows = $(this).nextUntil('.holdings-container-heading');
Toi `$('.location .fa', this).hasClass('fa-arrow-down')`-tarkistus oli sitä varten, ettei tarkisteta varauksia piilotetuilta niteiltä. Se pitäisi säilyttää, mutta tarkistaa vaikka open-luokka.

2023-08-29 07:52 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/authority-link-element.phtml
> +<a<?=$titleAttr?> href="<?=$this->escapedUrl?>"<?=$linkClassesAttr?>><?php if ($isAuthorityLink): ?><?=$authorityIcon?>"><span class="sr-only"><?=$srLabel?></span> <?php endif; ?>
authorityIcon:n jälkeen on ylimääräinen `">` joka näkyy näytöllä, kun popoverit on pois päältä:
![kuva](https://github.com/NatLibFi/NDL-VuFind2/assets/1327659/050534ba-6f6a-4cf2-84b5-fb27c45220a5)

2023-08-29 07:52 UTC, EreMaijala commented on themes/finna2/less/finna/result-sidebar.less
> +    color: #fff;
Tällekin pitäisi olla muuttuja, kun tekstille ja taustallekin on.

2023-08-29 07:52 UTC, EreMaijala commented on themes/finna2/less/finna/tabs.less
> +      .i {
Mikä tämä on? Pitäisikö olla `.icon`?

2023-08-29 07:52 UTC, EreMaijala commented on themes/finna2/templates/Auth/MultiILS/login.phtml
> +  <?=$this->icon('info', 'login-info-icon') ?>
Tämä näyttää paremmalta kuin Database:n tai Shibboleth:n. Käytettäiskö kaikkiin, myös Suomifi?

2023-08-29 07:52 UTC, EreMaijala commented on themes/finna2/templates/Helpers/organisation-info-contacts.phtml
> +    <p><?=$this->icon('envelope') ?> <a href="#" class="email"><span class="email"></span></a></p>
Pitäisikö olla `contact-email`?

2023-08-29 07:52 UTC, EreMaijala commented on themes/finna2/templates/Helpers/organisation-info-email-page.phtml
> +  <li><p><?=$this->icon('envelope') ?><a href="mailto:<?=$this->escapeHtmlAttr($email['email'])?>"><?=$this->escapeHtml($email['email'])?></a><?= isset($email['name']) && count($this->emails) > 1 ? (
Pitäisikö olla `contact-email`?

2023-08-29 07:52 UTC, EreMaijala commented on themes/finna2/templates/Helpers/organisation-info.phtml
> +      <div class="details-link info-element"><a href="#" data-href="<?=$this->escapeHtmlAttr($this->url('organisationinfo-home'))?>" class="details"><?=$this->icon('home') ?> <?=$this->translate('org
Tälle ehkä parempi nimi kuin pelkkä "home"?

2023-08-29 07:52 UTC, EreMaijala commented on themes/finna2/templates/Recommend/SideFacets/usage-rights-facet.phtml
> +      <span class="status"><?=$this->icon('facet-status') ?></span>
Tässä pitäisi olla `facet-checked` (on yläjuoksulla), tosin sitten se näkyy rastina, eli ehkä ennemmin kokonaan pois.

2023-08-29 07:52 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/core.phtml
> +            <?=$this->icon('external-link') ?> <?=$this->transEsc('default::link_' . $desc, null, $desc)?>
Tämän pitäisi mennä ylläolevan mappauksen `$map` kautta, jotta eri tyyppisille tulisi omat ikonit.

2023-08-29 07:52 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/record-image-paginator.phtml
> +        <div class="iconlabel format-<?=$this->record($this->driver)->getFormatClass(end($formats))?>"></div>
Oikea sisennys muuttunut vääräksi?

2023-08-29 07:52 UTC, EreMaijala commented on themes/finna2/templates/ajax/resolverLinks.phtml
> +    <?php if (!empty($this->moreOptionsLink)): ?><a href="<?=$this->escapeHtmlAttr($this->moreOptionsLink)?>" target="_blank"><?=$this->transEsc('More options')?></a> <?=$this->icon('new-window') ?><
Tällä voisi olla oma ikoni tyyliin resolver-more-options

2023-08-29 07:52 UTC, EreMaijala commented on themes/finna2/templates/browse/home.phtml
> +        <?php if($currentOption['action'] == $this->currentAction): ?><?=$this->icon('arrow-down') ?><?php else: ?><?=$this->icon('arrow-right') ?><?php endif; ?>
Ehkä näillä voisi olla esim. browse-selected ja browse-unselected?

2023-08-29 07:52 UTC, EreMaijala commented on themes/finna2/templates/cart/email.phtml
> +        <?=count($this->records) . ' ' . $this->transEsc('items') ?> <?=$this->icon('arrow-down') ?>
show-more?

2023-08-29 07:52 UTC, EreMaijala commented on themes/finna2/templates/eds/advanced.phtml
> +    <?=$this->icon('info', 'search_place_holder') ?> <a href="#" class="add_search_link hidden"><?=$this->transEsc("add_search")?></a>
Tässä pitäisi olla add-ikoni, esim. adv-search-group-add

2023-08-29 07:52 UTC, EreMaijala commented on themes/finna2/templates/record/cart-buttons.phtml
> +        <?=$this->icon('cart') ?>
cart-add? Voi olla cart:n alias.

2023-08-29 07:52 UTC, EreMaijala commented on themes/finna2/templates/record/share-buttons.phtml
> +    <!--<a class="share-button-google-plus" title="Google+" href="https://plus.google.com/share?url=<?=urlencode($shareUrl)?>" target="_blank"><?=$this->icon('google-plus', 'google-plus-icon') ?></a>
Eiköhän tämän voi poistaa, kun koko palvelua ei enää ole.

2023-08-29 07:52 UTC, EreMaijala commented on themes/finna2/templates/search/results.phtml
> +            <a class="btn btn-primary" href="<?=$this->url('search-streetsearch')?>?go=1"><?=$this->icon('crosshairs') ?> <span><?=$this->transEsc('street_search_refresh')?></span></a>
Tälle parempi nimi?

2023-08-29 07:52 UTC, EreMaijala commented on themes/finna2/templates/search/searchbox.phtml
> +          <a href="<?=$this->url('summon-home');?>" class="btn btn-link btn-primo"><?=$this->icon('summon-search') ?> <?=$this->transEsc("Summon Search")?></a>
search-summon?

2023-08-29 07:52 UTC, EreMaijala commented on themes/finna2/templates/RecordTab/componentparts.phtml
> +            'previous' => '<span class="sr-only">' . $this->transEsc('component_parts_previous') . '</span> ' . $this->icon('paginate-prev'),
Ovatko paginate-next ja paginate-prev tarkoituksella erilaisia kuin pagination-next ja pagination-prev? Voisi käyttää jälkimmäisiä tässäkin, niin ei olisi kahta melkein samannimistä?

2023-08-29 07:52 UTC, EreMaijala commented on themes/finna2/templates/search/header.phtml
> +                        <a href="<?=$this->escapeHtmlAttr($this->recordLinker()->getUrl($this->scrollData['firstRecord']))?>" rel="nofollow"><?=$this->icon('remove-filter') ?><?=$this->icon('pager-fi
remove-filter ylimääräinen?

2023-08-29 07:52 UTC, EreMaijala commented on themes/finna2/theme.config.php
> +            'pager-last' => 'FinnaIcons:arrow-right-circle',
pager-first ja pager-last on väärät kuvakkeet. Jos first_last_navigation on päällä, näyttää lopputulos tältä:
![kuva](https://github.com/NatLibFi/NDL-VuFind2/assets/1327659/72befd63-99ba-428d-beaf-e711492be894)

Kaikki pager- -kuvakkeet voisivat olla aliaksia vastaaviin pagination-kuvakkeisiin, eli tyyliin `'pager-first' => 'Alias:pagination-first',` jne.

2023-08-29 13:06 UTC, LuomaJuha reviewed
![image](https://github.com/NatLibFi/NDL-VuFind2/assets/33253757/7f0ce834-49f8-4a42-8862-b58f02864a32)
Löysin vaan et mini-paginaattorin nuolet muuttu aika äkäsiksi tän myötä.

2023-08-31 07:27 UTC, EreMaijala requested changes
Organisaatioinfon kartassa vielä kaikki selitekuvakkeet mustia:
![image](https://github.com/NatLibFi/NDL-VuFind2/assets/1327659/13d78175-a0a1-4de1-963b-7876625daa7f)

2023-08-31 10:16 UTC, EreMaijala approved these changes

2023-08-31 10:29 UTC, LuomaJuha approved these changes

2023-08-31 10:31 UTC, merged