[FINNA-774] Improve advanced search multiselects accessiblity
NatLibFi/NDL-VuFind2 pull request #2666
Opened 2023-08-23 06:17 UTC by siiriylonen

2023-08-25 06:17 UTC, pasitiis commented
Vaikutti pieneltä ulkoasu säädöltä. Sinällään ei vaikutusta saavutettavuuteen.

2023-08-25 06:18 UTC, pasitiis approved these changes

2023-08-25 13:21 UTC, pasitiis commented
Tuli vielä mieleen että jos näkymässä on useampi kuin kaksi rajainta (esim. finna.fi) niin rajaiten väliin voisi lisätä ilmavuutta, nyt on aavistuksen liian tiivisti.

 <img width="780" alt="Näyttökuva 2023-8-25 kello 16 15 55" src="https://github.com/NatLibFi/NDL-VuFind2/assets/1954586/76feeb65-03e1-4ec0-893a-6b4d8681b542">

2023-08-29 07:49 UTC, EreMaijala approved these changes

2023-08-29 07:50 UTC, EreMaijala requested changes
Pitäisi varmaan päivittää search_placeholder se.ini:ssäkin?

2023-08-29 07:57 UTC, EreMaijala approved these changes

2023-08-29 09:51 UTC, merged