[FINNA-910] EAD3: Show dates without placeholder chars
NatLibFi/NDL-VuFind2 pull request #2676
Opened 2023-09-04 09:13 UTC by siiriylonen

2023-09-05 08:53 UTC, EreMaijala requested changes

2023-09-05 08:53 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrEad3.php
> +                    foreach (str_split($start) as $number) {
Tämä ei varmaan ole kovin tehokas ratkaisu. Mitä jos laittaisi vähän toisella tavalla tyyliin:
```
foreach (['u', 'x', 'U', 'X'] as $char) {
    if (str_contains($start, $char)) {
        $unknown = true;
        break;
    }
}
```
Tälle voisi tehdä vaikka oman funktion, jota kutsuttaisiin myös alemmissa tarkistuksissa. Sama tarkistus toimii varmaan myös `$parts[1]`:n kohdalla.

2023-09-05 11:35 UTC, siiriylonen commented
Lisäsinkin nyt ne molemmat parts[1] ja [2] käyttämään sitä funktiota, että kai tämä nyt vielä toimii halutulla tavalla? Vai kannattaisiko vain yksittäisistä kirjaimista olla se erillinen funktio?

2023-09-05 12:17 UTC, EreMaijala requested changes

2023-09-05 12:17 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrEad3.php
> +    public function unknownCharsExist($string)
Nimeksi jotain, mikä kertoo, että kyse on päivämäärästä, esim. `unknownDateCharsExist`.

2023-09-05 12:17 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrEad3.php
> +        $addDate = !$this->unknownCharsExist($parts[0]);
Jos edellisellä rivillä korvataan u ja x, niin ei niitä voi enää sitten olla. Ehkä olisi selkeämpää tehdä tyyliin:
```
    if ($this->unknownCharsExist($parts[0])) {
        return str_ireplace(['u', 'x'], $start ? '0' : '9', $parts[0]);
    }
    // tähän dayn ja monthin tarkistus resultin kokoaminen
    

```

2023-09-06 09:49 UTC, EreMaijala requested changes

2023-09-06 09:49 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrEad3.php
> +     * Check if given string contains specified characters
Check if date string contains "unknown" characters

2023-09-06 09:49 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrEad3.php
> +        foreach (['uu', 'xx', 'u', 'x'] as $char) {
Laita tähän `['u', 'U', 'x', 'X']` niin ei tartte strtolower:ia. Tuplamerkkejä ei tarvita.

2023-09-06 09:49 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrEad3.php
> +        if (isset($parts[2]) && !$this->unknownDateCharsExist($parts[2])) {
Nämä tehdään liian aikaisin. Jos vuodessa on unknown chars:eja, ei kuukaudella tai päivällä tehdä mitään, eli ensin tarkistettava vuosi.

2023-09-06 12:59 UTC, EreMaijala requested changes

2023-09-06 12:59 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrEad3.php
> +        } else {
Ei tarvita else:ä tässä.

2023-09-06 12:59 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrEad3.php
>          }
Jos ei saada päivää, voidaan saman tien palauttaa `$year`, eikö?

2023-09-08 10:51 UTC, EreMaijala requested changes

2023-09-08 10:51 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrEad3.php
>          }
... `else { return $year; }`

2023-09-08 10:51 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrEad3.php
> +                $value = true;
`return true;`Ei tarvita `$value`:ta.

2023-09-08 10:51 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrEad3.php
> +        if (isset($parts[2]) && !$this->unknownDateCharsExist($parts[2])) {
Vaihda `isset`-tarkistukset vielä `!empty` niin ei tarvita lopussa tarkistusta `if ($day && $month)`.

2023-09-12 09:22 UTC, EreMaijala approved these changes

2023-09-12 09:22 UTC, merged