[FINNA-382] Add possibility to display similar records as a carousel at the bottom of record view
NatLibFi/NDL-VuFind2 pull request #2687
Opened 2023-09-13 14:23 UTC by rajaro

2023-09-14 10:01 UTC, pasitiis commented
Katsottiin Sagan kanssa tyylijuttuja. Muutamia korjauksia tyyleihin kaivattiin.
-mittasuhde (laatikon koko leiskassa 200 x 300px) -> supista korkeutta.
-kuvien skaalautuminen (osa kirjaston kansikuvista skaalautuu väärin)
-varjoon blurria
-viiva ohuemmaksi & saman väriseksi kuin tuo toinen vaaleanharmaa
-aineistotyyppi laatikon padding & siirto (nyt liian lähellä tekijä-tekstiä)
-rivin katkaisu otsikkoon ja tekijäkenttään (molemmat kentät omille riveille ja katkaisu)
<img width="1249" alt="Näyttökuva 2023-9-14 kello 12 19 40" src="https://github.com/NatLibFi/NDL-VuFind2/assets/1954586/b8628e74-eb00-4613-aa38-fe6cac7d174d">

2023-09-19 07:02 UTC, EreMaijala requested changes
Voisiko toteutuksessa hyödyntyy olemassaolevaa samankaltaisten teosten välilehteä SimilarItemsCarousel (muokata sitä tarpeen mukaan)? Sen voi toki tarvittaessa renderöidä välilehtien alapuolella, mutta tuntuu turhalta tehdä uutta toteutusta samaa asiaa varten.

2023-09-25 09:37 UTC, pasitiis commented on themes/finna2/templates/RecordTab/similar-carousel-item.phtml
> +    <b><span><?=$this->truncate($this->escapeHtml($this->item->getTitle()), 22)?></b></span>
Tee tyylin boldaus css-tyyliin.

2023-09-28 13:35 UTC, pasitiis approved these changes

2023-10-03 13:30 UTC, EreMaijala requested changes

2023-10-03 13:30 UTC, EreMaijala commented on themes/finna2/js/finna-record.js
> +    if (container.length === 0 ) {
querySelector palauttaa null:n, jos ei löydy

2023-10-03 13:30 UTC, EreMaijala commented on themes/finna2/js/finna-record.js
> +    finna.carouselManager.createCarousel(container.querySelector('.splide'), settings);
Pitäisikö tarkistaa, että `.splide` löytyy?

2023-10-03 13:30 UTC, EreMaijala commented on themes/finna2/templates/record/view.phtml
> +    <?php if (!$this->config()->similarRecordsCarouselEnabled()): ?>
Tämä tarkistus on väärässä paikassa. Sivupalkissa voi olla mitä tahansa related-toimintoja, ja karusellin pitäisi korvata vain samankaltaiset teokset. Toisaalta, ei välttämättä tarvitse edes tätä tarkistusta, kun on erilliset toiminnot, jotka voi poistaa käytöstä erikseen.

2023-10-03 13:30 UTC, EreMaijala commented on local/config/finna/config.ini.sample
> +; of sidebar. Records will be displayed as a carousel. Requires SimilarItemsCarousel
Miksei tämä voisi toimia ilman SimilarItemsCarousel-tabin käyttöönottoa?

2023-10-04 08:08 UTC, rajaro commented on local/config/finna/config.ini.sample
> +; of sidebar. Records will be displayed as a carousel. Requires SimilarItemsCarousel
No kyllähän se voisikin. Muutin nyt

2023-10-04 08:09 UTC, rajaro commented on themes/finna2/templates/record/view.phtml
> +    <?php if (!$this->config()->similarRecordsCarouselEnabled()): ?>
Jees, tuo tarkistus otettu pois

2023-10-09 08:21 UTC, EreMaijala requested changes

2023-10-09 08:21 UTC, EreMaijala commented on local/config/finna/config.ini.sample
> +;similar_bottom_items = 15
Tällä pitäisi olla oletusarvo, ja sen voisi mainita kommentissa.

2023-10-09 08:21 UTC, EreMaijala commented on module/Finna/src/Finna/RecordTab/SimilarItemsCarousel.php
> +    public function getResults(int $amount = 15)
SimilarItemsCarousel voisi lukea itse konfiguraationsa niin, ettei tietueiden määrää tarvitsisi kierrättää kutsujan kautta. Oletuksen säilyttäisin. Parempi olisi myös, että lukumäärän konfigurointi olisi yläjuoksulla, niin ei tarvitsisi yliajaa tässä.

2023-10-09 08:21 UTC, EreMaijala commented on module/Finna/src/Finna/View/Helper/Root/Config.php
> +     * @return boolean
käytä `bool`

2023-10-09 08:21 UTC, EreMaijala commented on module/Finna/src/Finna/View/Helper/Root/Config.php
> +     * @return boolean
int

2023-10-09 08:21 UTC, EreMaijala commented on module/Finna/src/Finna/View/Helper/Root/Config.php
> +    public function similarRecordsCarouselEnabled()
paluuarvon tyyppi metodille

2023-10-09 08:21 UTC, EreMaijala commented on module/Finna/src/Finna/View/Helper/Root/Config.php
> +    public function similarRecordsCarouselItems()
jos tätä tarvitaan, niin paluuarvon tyyppi metodille

2023-10-09 08:21 UTC, EreMaijala commented on module/Finna/src/Finna/RecordTab/TabManager.php
> +    public function getSimilarItemsCarouselTab(AbstractRecordDriver $driver)
paluuarvon tyyppi metodille

2023-10-09 08:21 UTC, EreMaijala commented on themes/finna2/js/finna-feed-element.js
> +    if (!this.classList.contains('similar-items-carousel')) {
Mihin tätä tarvitaan?

2023-10-09 08:21 UTC, EreMaijala commented on themes/finna2/templates/RecordTab/similar-carousel-item.phtml
> +    <div class="iconlabel format-<?=$this->record($driver)->getFormatClass(end($formats))?>"></div>
sisennys pielessä

2023-10-09 08:21 UTC, EreMaijala commented on themes/finna2/templates/RecordTab/similar-carousel-item.phtml
> +      <span class="similar-carousel-format"><?=$this->transEsc(end($formats))?></span>
käytä Record-helperin `getFormatList()`

2023-10-11 12:57 UTC, rajaro commented on themes/finna2/js/finna-feed-element.js
> +    if (!this.classList.contains('similar-items-carousel')) {
Jos on käytössä SimilarItemsCarousel-välilehti, niin ilman tuota karuselli katoaa jos siirtyy välilehdeltä toiselle ja takaisin

2023-10-11 12:58 UTC, rajaro commented on themes/finna2/templates/RecordTab/similar-carousel-item.phtml
> +      <span class="similar-carousel-format"><?=$this->transEsc(end($formats))?></span>
`getFormatList()` tuottaa myös sen tyypin ikonin, jota ei tuohon haluta

2023-10-11 12:58 UTC, rajaro commented on module/Finna/src/Finna/RecordTab/SimilarItemsCarousel.php
> +    public function getResults(int $amount = 15)
vufind pr: https://github.com/vufind-org/vufind/pull/3158

2023-10-25 07:40 UTC, EreMaijala commented
@rajaro Mergeäisitkö uusimmat muutokset dev:stä? Siellä on yläjuoksulta se näytettävien määrä mukana.

2023-10-25 08:21 UTC, rajaro commented
@EreMaijala tehty

2023-10-25 08:57 UTC, EreMaijala commented on module/Finna/src/Finna/View/Helper/Root/Config.php
> +        return !empty($this->get('config')->Record->similar_carousel);
Käytä null coalescing -operaattoria (ja oikeaa asetuksen nimeä), niin on selkeämpää, mikä on oletus:
`return $this->get('config')->Record->similar_carousel_bottom ?? false;`
tai asetuksen toiminnan muutoksen jälkeen:
`return $this->get('config')->Record->similar_carousel_display ?? '';`

2023-10-25 08:57 UTC, EreMaijala commented on local/config/finna/config.ini.sample
> +;similar_carousel_bottom = true
Voisi laittaa tämän vielä muotoon `similar_carousel_display = "after_tabs"`, niin on sitten mahdollisuus tehdä muita vaihtoehtoja (jos vaikka tarvitaan "before_tabs" tms.).

2023-10-25 08:57 UTC, EreMaijala commented on themes/finna2/templates/RecordTab/similar-carousel-item.phtml
> +      <span class="similar-carousel-format"><?=$this->transEsc(end($formats))?></span>
Ikonin voi piilottaa tyyleillä, sitten sen saa halutessaan myös näkyviin.

2023-10-25 08:57 UTC, EreMaijala commented on themes/finna2/js/finna-feed-element.js
> +    if (!this.classList.contains('similar-items-carousel')) {
Totta. Nähdäkseni tuo on kuitenkin ongelma feed-elementissä ylipäänsä, eli pitäisi jättää sisältö tyhjentämättä aina.

2023-10-25 08:58 UTC, EreMaijala commented on themes/finna2/templates/RecordTab/similar-carousel-item.phtml
> +      <span class="similar-carousel-format"><?=$this->transEsc(end($formats))?></span>
Ikonin voi piilottaa tyyleillä, sitten sen saa halutessaan myös näkyviin.

2023-10-25 12:11 UTC, EreMaijala requested changes

2023-10-25 12:11 UTC, EreMaijala commented on module/Finna/src/Finna/View/Helper/Root/Config.php
> +    public function similarRecordsCarouselEnabled(): bool
Tämän pitäisi nyt palauttaa se karusellin paikka ennemmin. Esim. `getSimilarRecordsCarouselLocation`

2023-10-25 12:11 UTC, EreMaijala commented on local/config/finna/config.ini.sample
> +; Records will be displayed as a carousel.
Lisää tähän vielä `The only available option at the moment is "after_tabs".`.

2023-10-25 12:11 UTC, EreMaijala commented on themes/finna2/templates/RecordTab/similar-carousel-item.phtml
> +    <span class="similar-carousel-item-title" <?=strlen($this->item->getTitle()) > $truncateLength ? 'title="' . $this->item->getTitle() . '"' : ''?>><?=$this->truncate($this->escapeHtml($this->item-
strlen:n sijaan pitäisi käyttää `mb_strlen(..., 'UTF-8')` (vaikka onkin pielessä truncate-helperissä), mutta miksei titleä voisi asettaa aina? title-attribuutista puuttuu escape. Lisäksi truncate pitää tehdä ennen escapea.

2023-10-25 12:11 UTC, EreMaijala commented on themes/finna2/templates/RecordTab/similar-carousel-item.phtml
> +    <?php if (!$noImage): ?>
Käännä if-else toisin päin, niin ei tule tupla-negaatiota.

2023-10-25 12:11 UTC, EreMaijala commented on themes/finna2/templates/RecordTab/similar-carousel-item.phtml
> +        <span class="similar-carousel-item-author" <?=strlen($authors[0]) > $truncateLength ? 'title="' . $authors[0] . '"' : ''?>><?=$this->truncate($this->escapeHtml($authors[0]), $truncateLength)?
truncate ennen escapea

2023-10-25 13:03 UTC, rajaro commented on themes/finna2/templates/RecordTab/similar-carousel-item.phtml
> +    <span class="similar-carousel-item-title" <?=strlen($this->item->getTitle()) > $truncateLength ? 'title="' . $this->item->getTitle() . '"' : ''?>><?=$this->truncate($this->escapeHtml($this->item-
Saavutettavuustyökalut valittaa, jos title on sama kuin sisältö

2023-10-26 10:26 UTC, EreMaijala commented on themes/finna2/templates/RecordTab/similar-carousel-item.phtml
> +    <span class="similar-carousel-item-title" <?=strlen($this->item->getTitle()) > $truncateLength ? 'title="' . $this->item->getTitle() . '"' : ''?>><?=$this->truncate($this->escapeHtml($this->item-
ok

2023-10-26 16:54 UTC, EreMaijala commented on themes/finna2/templates/RecordTab/similar-carousel-item.phtml
> +    <span class="similar-carousel-item-title" <?=strlen($this->item->getTitle()) > $truncateLength ? 'title="' . $this->item->getTitle() . '"' : ''?>><?=$this->truncate($this->escapeHtml($this->item-
Tarkennatko vielä, missä näin käy? En saanut aikaiseksi ainakaan Axella.

2023-10-26 17:01 UTC, EreMaijala commented
@rajaro Voisiko tässä muuten käyttää samaa tapaa kuin #2739:ssa?

2023-10-27 05:47 UTC, EreMaijala commented on themes/finna2/templates/RecordTab/similar-carousel-item.phtml
> +    <span class="similar-carousel-item-title" <?=strlen($this->item->getTitle()) > $truncateLength ? 'title="' . $this->item->getTitle() . '"' : ''?>><?=$this->truncate($this->escapeHtml($this->item-
Pasin kanssa selvitetty, ei tartte enempää selityksiä.

2023-10-27 06:46 UTC, EreMaijala commented on themes/finna2/templates/RecordTab/similar-carousel-item.phtml
> +    <span class="similar-carousel-item-title" <?=strlen($this->item->getTitle()) > $truncateLength ? 'title="' . $this->item->getTitle() . '"' : ''?>><?=$this->truncate($this->escapeHtml($this->item-
Päädyttiin siihen, että käytetään tooltip:iä koko nimen näyttämiseen, tehdään samoin tässä. Ja tosiaan clamp toimii paremmin kuin truncate, niin sitä voisi tässäkin hyödyntää.

2023-10-27 07:52 UTC, EreMaijala requested changes
Vielä siis puuttuu truncate => clamp ja tooltip kuten feed-grid-item.phtml/finna-linked-events.js.

2023-10-27 07:52 UTC, EreMaijala commented on themes/finna2/templates/RecordTab/similar-carousel-item.phtml
> +      if (!empty($authors)): ?>
sisennys pielessä

2023-10-27 08:27 UTC, rajaro commented
@EreMaijala just laitoinkin muutoksia ennen kun luin ton vikan kommentin :D mutta laitoin ton hover tooltipin suoraan `initToolTips()`:iin, ajatuksena että ois sitten aina yhtenäiset hover tooltipit jos niitä käytellään. Voin kyl ottaa suoraan ton finna-linked-events.js pätkän myös jos on parempi.

Truncaten korvasin tyyleillä
`white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;`
näytti tuottavan siististi pisteet katkon loppuun ja kuitenkin vain 1 rivi aina noilla teksteillä

2023-10-27 09:23 UTC, EreMaijala commented
> just laitoinkin muutoksia ennen kun luin ton vikan kommentin :D mutta laitoin ton hover tooltipin suoraan `initToolTips()`:iin, ajatuksena että ois sitten aina yhtenäiset hover tooltipit jos niitä käytellään.

Toi on hyvä, voin muuttaa linked eventsit käyttämään samaa kun on mergetty.

2023-10-27 09:24 UTC, EreMaijala requested changes

2023-10-27 09:24 UTC, EreMaijala commented on themes/finna2/less/finna/record.less
> +  width: 100%;
sisennykset vielä tässä

2023-10-27 09:24 UTC, EreMaijala commented on themes/finna2/templates/RecordTab/similar-carousel-item.phtml
> +      <?php endif; ?>
tässä edelleen sisennykset pielessä

2023-10-27 09:55 UTC, EreMaijala commented on themes/finna2/less/finna/record.less
> +  width: 100%;
Korjasin, jotta saan mergettyä.

2023-10-27 09:55 UTC, EreMaijala commented on themes/finna2/templates/RecordTab/similar-carousel-item.phtml
> +      <?php endif; ?>
Korjasin, jotta saan mergettyä.

2023-10-27 09:55 UTC, EreMaijala approved these changes

2023-10-27 09:59 UTC, merged