[FINNA-1089] Fix the close button positioning on smaller widths in rss carousel
NatLibFi/NDL-VuFind2 pull request #2709
Opened 2023-10-02 13:36 UTC by siiriylonen

2023-10-02 13:46 UTC, siiriylonen commented
Tein nyt näin, että jos sen sisällön holder on yli tietyn pituuden niin otsikon leveys on myös isompi (90%), koska esim. jos tabletissa oli vain yksi slide per pagination -> varsinainen teksti alkoi taas rivittymään otsikon ja napin väliin...
En tiedä onko tämä nyt optimaalisin ratkaisu tähän.

2023-10-04 11:32 UTC, pasitiis commented
Jäin pohtimaan onko tarpeellista varata sulkupainikkeelle pystysuunnassa vastaava korkeus kuin otsikolla? Sulkupainikkella näytti olevan lisäksi paddingiä, jota otsikolla ei ole, ja joka sotkee hieman alemman tekstin rivittymistä verattuna otsikkoon. 

Huomasin että desktopissa kuvake on siirtynyt vasemalle, nyt ei enää näytä kovinkaan tasapainoiselta. 
<img width="272" alt="Näyttökuva 2023-10-4 kello 14 25 09" src="https://github.com/NatLibFi/NDL-VuFind2/assets/1954586/aad89c54-4380-4615-96aa-645614b93dd7">

2023-10-05 04:59 UTC, siiriylonen commented
Sulje-ikonilla on padding, koska se painike niin tarvitsee ylimääräistä tilaa siihen vai olisiko parempi asettaa tietty leveys ja korkeus?
Tarkistin myös sen korkeus-asian ja näinhän siinä käy (mutta ei varmaan ole järkeä vain kapeassa kuvassa poistaa sitä korkeutta kun siinä tietenkin ok..):
<img width="369" alt="Screenshot 2023-10-05 at 7 53 00" src="https://github.com/NatLibFi/NDL-VuFind2/assets/117457514/356901cc-d864-440b-b1b2-808eaec6ce53">
(Desktopin ikonia muokkaan ainakin siis vielä.)

2023-10-23 11:58 UTC, pasitiis commented on themes/finna2/js/finna-feed-element.js
> +            if (feedItemWidth > 200) {
Olisi parasta, että sulkupainiketta ei tarvitsisi ronkkia js:llä. Sulkupainikkeen sijainnin pitäisi pystyä määritellämään pelkästään css-tyyleillä. Ei suoraa liitty tähän pr:ään. mutta jäin vielä ihmettelmään, miksi sulkupainikkeen ympärille on asetettu p-elementti, parempi olisi käyttää span- tai div-elementtiä.

2023-10-31 08:55 UTC, EreMaijala commented
@siiriylonen Pyydä katselmointia, kun Pasin kommentit on selvitetty.

2023-11-06 14:38 UTC, pasitiis approved these changes

2023-11-09 17:14 UTC, EreMaijala requested changes

2023-11-09 17:14 UTC, EreMaijala commented on themes/finna2/js/finna-feed-element.js
> +          holder.querySelectorAll('.carousel-hover-title').forEach(el => {
Miksi tämä on JS:ssä? Eikö menisi css:llä  tyyliin:
.carousel-non-touch-device .carousel-hover-title {
  width: 100%
}

2023-11-15 07:41 UTC, EreMaijala requested changes
Ei ihan toimi tuossa 600-700 leveyksien nurkilla. Toisin kuin ... -nappulalle, ei sulkunappulalle jää tilaa:
![kuva](https://github.com/NatLibFi/NDL-VuFind2/assets/1327659/11e9f3a4-95a2-415d-819f-673db33d95b8)

2023-11-16 09:26 UTC, EreMaijala approved these changes

2023-11-16 09:26 UTC, merged