[FINNA-1068] EAD3: alter the presenting of video and image links on item page
NatLibFi/NDL-VuFind2 pull request #2725
Opened 2023-10-11 07:50 UTC by siiriylonen

2023-10-17 11:53 UTC, EreMaijala requested changes
Eikö tämä mene nyt juuri päinvastoin kuin tiketissä? Ymmärsin, että EAD3:n video- ja äänitiedostot piti olla vain ladattavia, mutta nyt kaikki muu menee ladattavaksi.

Tätä dokumenttien käsittelyä pitäisi käsitellä kokonaisuutena, ja korjata vastaavat ongelmat LIDO-tietueista myös. Uskoisin, ettei myöskään tarvita formaattikohtaisia document-links -templaatteja, jos lisätään esim. 'downloadOnly' -attribuutti url-listaan.

2023-10-17 11:53 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrEad3.php
> +                    foreach ($notImages as $format) {
Laita `$isImage = true;` heti tämän yläpuolelle, ei tarvitse sitten muualla säätää sitä.

2023-10-17 11:53 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrEad3.php
> +                        if (str_starts_with($role, $format)) {
Paitsi ettei tämä niin voi mennä, että kaikki mikä ei ole audiota tai videota olisi kuvia. Voihan siellä olla vaikka mitä muutakin.

2023-10-17 11:53 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrEad3.php
> +                    if ($isImage) {
Tarkistetaan tämä ihan aluksi luupissa, ja sitten continue heti, jos ei kelpaa.

2023-10-17 11:53 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrEad3.php
> +                        [$fileType, $format] = strpos($role, '/') > 0
`[,$format] = explode('/', $role . '/jpg');`

2023-10-17 11:53 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrEad3.php
> +                    'format' => (string)$attr->linkrole,
Ei kai me haluta mediatyyppiä tms. suoraan näyttää käyttäjälle?

2023-10-25 12:33 UTC, EreMaijala requested changes

2023-10-25 12:33 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrEad3.php
> +            $role = (string)$attr->linkrole ?? '';
Vaikka tämä käytännössä toimisikin, kun castaa null:n stringiksi, niin pitää olla sulut `(string)($attr->linkrole ?? '')`

2023-10-25 12:33 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrEad3.php
>                  (string)$attr->linkrole === 'image/jpeg'
tähän $role

2023-10-25 12:33 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrEad3.php
> +            if (preg_match('(audio|video)', $role) === 1) {
Pitää verrata mediatyypin ensimmäiseen osaan, ettei osu mihinkään `application/vnd.audiograph`-tyyppiseen.

2023-10-25 12:33 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrEad3.php
> +                    $show = (string)$attr->show ?? 'none';
Tässä on oltava sulut: `(string)($attr->show ?? 'none')`, jos halutaan, ettei $show jää tyhjäksi attribuutin puuttuessa. Mutta halutaanko? Jos attribuuttia ei ole, pitäisikö sallia näyttäminen?

2023-10-25 12:33 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/SolrEad/core.phtml
>          <div class="recordURLs local-available-online-record">
Sisennykset pielessä

2023-10-27 08:00 UTC, EreMaijala requested changes

2023-10-27 08:00 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrEad3.php
> +            $role = (string)($attr->linkrole) ?? '';
sulut näin: `$role = (string)($attr->linkrole ?? '');`

2023-10-27 08:00 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrEad3.php
> +            foreach ($checkedTypes as $checkType) {
Koska tarkistettavia vaihtoehtoja on vain kaksi, on luuppi turhan järeä rakenne. Laita `if (str_starts_with($role, 'audio') || str_starts_with($role, 'video'))`

2023-10-27 08:00 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/document-links.phtml
> +        $showCC = $document['downloadOnly'] ?? true;
Mitä showCC tarkoittaa? Jos oikeuksien näyttämistä, niin showRights ennemmin.

2023-10-27 08:00 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/document-links.phtml
> +        <div class="link-wrapper <?php if ($rightsDescription):?>additional-info<?php endif; ?>">
välilyönti if:n sisään, niin ei tule turhaan tyhjää, jos rightsDescriptionia ei ole

2023-10-27 08:00 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/document-links.phtml
> +    <?php endif; ?>
sisennykset jotenkin vinksallaan

2023-10-27 08:00 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/document-links.phtml
> +                <?php if (!empty($document['posterUrl'])): ?> data-poster-url="<?= $this->escapeHtmlAttr($url['posterUrl']) ?>"<?php endif; ?>
sisennys?

2023-10-27 08:00 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/document-links.phtml
> +                <a href="<?=$this->escapeHtmlAttr($this->proxyUrl($document['url']))?>" target="_blank" aria-label="<?=$this->transEscAttr('external_online_link')?>"
downloadOnly ei vaikuta tässä mitenkään, eikö pitäisi? Tiketin ensimmäinen tietue esimerkkinä.

2023-10-31 09:12 UTC, EreMaijala requested changes

2023-10-31 09:12 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrEad3.php
> +                    'description' => (string)$desc,
getURLs:n paluuarvon muoto ei voi muuttua näin. desc-elementti jo yläjuoksulla.

2023-10-31 09:12 UTC, EreMaijala commented on themes/finna2/less/finna/record.less
> +  .link-wrapper {
Miksi tämä on tässä kun muut link-wrapperin säännöt ovat alempana? Tai oikeastaan, miksi muut säännöt ovat tuossa alempana eivätkä tässä?

2023-10-31 09:12 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/document-links.phtml
> +    <?php endif; ?>
sisennykset ovat edelleen vinksallaan, tsekkaa tästä eteenpäinkin

2023-10-31 09:12 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/document-links.phtml
> +    <?php if ($showRights): ?>
Tämä pitäisi ehkä nyt pilkkoa kahteen templaattiin tai tehdä linkki ensin ob:lla samaan tapaan kuin esim. themes/finna2/templates/myresearch/profile.phtml. Muuten on aika sekava kokonaisuus, kun showRights tarkistetaan monessa kohdassa ja siinä välissä tapahtuu paljon.

Linkeillä on myös niin paljon attribuutteja, että ne voisi tehdä HTMLAttributes-helperillä.

2023-10-31 09:12 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/document-links.phtml
> +                <?php if ($document['downloadOnly']): ?> download=""<?php endif; ?>
download riittää yksinään ilman arvoa, kuten ylempänä

2023-11-02 06:16 UTC, siiriylonen commented on themes/finna2/templates/RecordDriver/DefaultRecord/document-links.phtml
> +    <?php if ($showRights): ?>
Selkenikö tällä vai olisiko toinen template parempi?

2023-11-02 11:03 UTC, EreMaijala requested changes

2023-11-02 11:03 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/document-links.phtml
> +        $description = $document['description'] ?? $document['desc'] ?? $this->translate('Download the file');
Tässä on nyt aiempaan verrattuna ongelma: jos description on tyhjä stringi, ei näytetä 'Download the file'. Pitäisi siis tarkistaa tyyliin `($document['description'] ?? $document['desc'] ?? null) ?: $this->translate('Download the file');`

2023-11-02 11:03 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/document-links.phtml
> +        !empty($document['posterUrl']) ? $aAttrs['data-poster-url'] = $url['posterUrl'] : null;
if:llä ennemmin, ettei mennä sivuvaikutuksien pohjalta

2023-11-02 11:03 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/document-links.phtml
>          $language = $this->layout()->userLang;
Tässä menee sisennykset solmuun, kun kaksoispiste-operaattorin käyttäminen pidemmässä php-blokissa ei ole luontevaa. Laita vaikka näin (huolehtii samalla $i:n kasvattamisesta, niin sitä ei tarvitse tehdä erikseen):
```
<?php foreach (array_values($documents) as $i => $document): ?>
    <?php
        $language = $this->layout()->userLang;
        $description = $document['description'] ?? $document['desc'] ?? $this->translate('Download the file');
        $rights = $this->driver->getAccessRestrictionsType($language);
        $rightsDescription = $this->driver->getAccessRestrictions($language);
        $format = $document['format'] ?? null;
        $hasLink = isset($rights['link']) && !empty($rights['link']);
        $showRights = $document['downloadOnly'] ?? true;
        $externalLink ??= false;
    ?>
```

2023-11-02 11:03 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/document-links.phtml
> +        <?=!$externalLink ? $this->icon('download') : $this->icon('external-link'); ?>
if ... else ennemmin kuin tehdä sama vertailu kahteen kertaan

2023-11-02 11:03 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/document-links.phtml
> +    <?php if ($showRights): ?>
Selkeni vähän, mutta loppuosa on edelleen sotkuinen. Pitäisi tehdä siis niin, että on kaksi vaihtoehtoa:

`if showrights ...
else ... 
endif 
`

Lisäksi sellainen ongelma, että url-helperi palauttaa valmiiksi escapetun url:n, eli sitä ei voi laittaa helperin kautta. Jos laitat koko a-elementin rakentamisen kumpaankin haaraan erikseen, niin selkenee lisää.

2023-11-02 11:03 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/document-links.phtml
> +    <?php if ($showRights): ?>
Liian vähän sisennetty

2023-11-02 12:57 UTC, siiriylonen commented on themes/finna2/templates/RecordDriver/DefaultRecord/document-links.phtml
> +        !empty($document['posterUrl']) ? $aAttrs['data-poster-url'] = $url['posterUrl'] : null;
Mutta tätä arvoa ei ilmeisesti ole aina asetettu -> tulee virhe
(Jos siis tarkoitit näin: $document['posterUrl'] ? ... : ...)
Niin !empty(), isset() vai ymmärsin vain väärin?

2023-11-02 13:02 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/document-links.phtml
> +        !empty($document['posterUrl']) ? $aAttrs['data-poster-url'] = $url['posterUrl'] : null;
Ei vaan tarkoitin, että parempi olisi kirjoittaa muodossa:
```
if (!empty($document['posterUrl'])) {
    $aAttrs['data-poster-url'] = $document['posterUrl'];
}
```

2023-11-02 13:03 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/document-links.phtml
> +        !empty($document['posterUrl']) ? $aAttrs['data-poster-url'] = $url['posterUrl'] : null;
Kun käytetään vielä muuttujaa välissä, niin vältetään se, että haetaan sama kenttä kahteen kertaan, eikä voi tulla sekaannusta tyyliin document vai url.

2023-11-08 10:15 UTC, EreMaijala requested changes

2023-11-08 10:15 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/document-links.phtml
> +        $showRights = $document['downloadOnly'] ?? true;
Miksei oikeuksia näytetä, jos downloadOnly = false?

2023-11-08 10:15 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/document-links.phtml
>                      <?=$this->partial('Helpers/copyright-icons.phtml', ['copyright' => $rights['copyright']])?>
Sisennys pielessä.

2023-11-08 10:15 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/document-links.phtml
> +            <?=$this->escapeHtml($this->translate('link_' . $description, null, $description))?>
Käytä transEscWithPrefix.

2023-11-08 10:15 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/document-links.phtml
> +        $document['downloadOnly'] ? $aAttrs['download'] = '' : null; ?>
Tämä edelleen muuttamatta if:ksi.

2023-11-08 10:15 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/document-links.phtml
> +        <a href="<?=$this->escapeHtmlAttr($this->proxyUrl($document['url']))?>" <?=$this->htmlAttributes($aAttrs)?>>
Miksei href-attribuuttia laitetaan aAttrs:iin?

2023-11-08 10:15 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/document-links.phtml
> +        <a href="<?=$this->escapeHtmlAttr($this->url('record-downloadfile', [], ['query' => ['id' => $this->driver->getUniqueID(), 'index' => $i, 'format' => $document['format'], 'type' => 'document'
url-helper palauttaa escapetun url:n, ei enää escapeHtmlAttr:a lisäksi

2023-11-08 10:15 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/document-links.phtml
> +        $externalLink ??= false;
Tämähän ei ole linkkikohtainen tieto, vaan templaatin kutsujalta. Alustetaan alussa. Ja nimeksi jotain ihan muuta, vaikka showDownloadLinks (oletus true), niin kuvaisi tarkoitusta.

2023-11-08 10:39 UTC, siiriylonen commented on themes/finna2/templates/RecordDriver/DefaultRecord/document-links.phtml
> +        $showRights = $document['downloadOnly'] ?? true;
Katsoin tiketin kolmatta kohtaa, jossa näin annettin ymmärtää: "Jos tietueilla, joilla on vain ladattavia tiedostoja, tulee käyttöoikeusmerkintöjä, niin näytetään merkinnät latauslinkin yhteydessä..."
Niin otinko nyt liian kirjaimellisesti vai kai tässä kohdassa siitä on kyse?

2023-11-08 10:56 UTC, siiriylonen commented on themes/finna2/templates/RecordDriver/DefaultRecord/document-links.phtml
> +        <a href="<?=$this->escapeHtmlAttr($this->proxyUrl($document['url']))?>" <?=$this->htmlAttributes($aAttrs)?>>
Aaa, siis sen joka tulee $this->url() kautta ei voi laittaa, mutta sen toisen voi koska ei muodosteta erikseen

2023-11-15 08:08 UTC, EreMaijala requested changes
Muuten näyttää hyvältä, mutta ilmeisesti silloin, kun ei ole lisätietoja, on lisenssikuvakkeiden asemointi pielessä ja sulkujen ympärillä ylimääräistä whitespacea:
![kuva](https://github.com/NatLibFi/NDL-VuFind2/assets/1327659/d2ecd55d-5b15-4ed6-8f8e-e41eeba6b23d)
vrt:
![kuva](https://github.com/NatLibFi/NDL-VuFind2/assets/1327659/09db5f04-1dee-435e-ae93-68be3a0d56db)

2023-11-16 08:44 UTC, EreMaijala requested changes
Poistetaan mieluummin whitespace sulkujen ympäriltä, niin ei tarvitse kikkailla negatiivisella marginaalilla, kun siitä tulee helposti ongelmia.

2023-11-17 05:49 UTC, EreMaijala approved these changes

2023-11-17 05:51 UTC, merged