[FINNA-1075] Fix spinner and screen reader issues for linked events feed.
NatLibFi/NDL-VuFind2 pull request #2728
Opened 2023-10-12 08:18 UTC by pasitiis

Vaihdoin spinnerin js:stä templateen. Jouduin vähän muuttaa rakennetta. Tein pieniä korjauksia/parannuksia, jotka toivottavasti parantavat ruudunlukija käyttöä.

2023-10-12 10:07 UTC, rajaro approved these changes

2023-10-17 12:01 UTC, EreMaijala requested changes

2023-10-17 12:01 UTC, EreMaijala commented on themes/finna2/js/finna-linked-events.js
> +        spinner.classList.add("hidden");
Tässä pitäisi myös olla `if (spinner)` -tarkistus, eikö?

2023-10-17 12:01 UTC, EreMaijala commented on themes/finna2/templates/Helpers/linkedeventstabs.phtml
> +        <label for="event-date-start" class="sr-only"><?=$this->transEsc('event_date_start');?></label>
Kun näitä nyt muokataan, niin voisiko korjata id:t käyttämään alaviivoja samalla? Erityisen hämäävää, kun on sama id ja luokka.

2023-10-18 08:54 UTC, EreMaijala approved these changes

2023-10-18 08:54 UTC, merged