[FINNA-894] Display CC licences on record view
NatLibFi/NDL-VuFind2 pull request #2731
Opened 2023-10-13 08:39 UTC by jlehmus

2023-10-18 11:41 UTC, EreMaijala requested changes

2023-10-18 11:41 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/data-termsOfUse.phtml
> +  <?=!empty($field['sourcecode']) ? $this->escapeHtml($this->translate('accessrestriction_source_' . $field['sourcecode'])) : '' ?>
Käytä `$this->transEscWithPrefix('accessrestriction_source_', $field['sourcecode'])`. Se näyttää sitten pelkän sourcecode:n, jos ei ole käännöstä.

2023-10-18 11:41 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrMarc.php
> +            $code = $this->getSubfield($field, 'f');
Voisiko `$code` olla kuvaavampi `$rights`? Ja `$sourcecode` `$rightsSource`?

2023-10-18 11:41 UTC, EreMaijala commented on local/languages/finna/en-gb.ini
> +accessrestriction_source_cc = "Creative Commons"
Laittaisin alaviivan `access_restriction_source_cc` kun ylemmissäkin on.

2023-10-18 11:41 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrMarc.php
> +     * - sourcecode Source of the access licence (e.g. Creative Commons)
`(e.g. 'cc' for Creative Commons)`?

2023-10-18 11:41 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/data-termsOfUse.phtml
> -  <?=$this->escapeHtml(!empty($field['source']) ? $field['source'] : $this->truncateUrl($field['url'])) ?>
Miksei source enää näy? Ei käy ilmi tiketistä.

2023-10-18 15:45 UTC, jlehmus commented on themes/finna2/templates/RecordDriver/DefaultRecord/data-termsOfUse.phtml
> -  <?=$this->escapeHtml(!empty($field['source']) ? $field['source'] : $this->truncateUrl($field['url'])) ?>
No äh, taisin vahingossa poistaa ton source -rivin... Pitää tarkistaa

2023-11-07 18:21 UTC, jlehmus commented on themes/finna2/templates/RecordDriver/DefaultRecord/data-termsOfUse.phtml
> -  <?=$this->escapeHtml(!empty($field['source']) ? $field['source'] : $this->truncateUrl($field['url'])) ?>
piti tehdä tommonen vähän ruma if-elseif-else -logiikka

2023-11-08 11:35 UTC, EreMaijala requested changes

2023-11-08 11:35 UTC, EreMaijala commented on local/languages/finna/se.ini
> +accessrestriction_source_cc = "Creative Commons"
Alaviiva puuttuu

2023-11-08 11:35 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/data-termsOfUse.phtml
> +  <?=!empty($field['rightsSource']) ? $this->escapeHtml($this->transEscWithPrefix('access_restriction_source_' . $field['rightsSource'])) : '' ?>
transEscWithPrefix:n kanssa ei escapeHtml:ää enää. Ja prefix ja käännös erillisinä parametreina: `$this->transEscWithPrefix('access_restriction_source_', $field['rightsSource'])`

2023-11-08 11:35 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/data-termsOfUse.phtml
> +    if(!empty($field['rights'])):
Välilyönnit ennen sulkua: `if (` ... `elseif (`

2023-11-08 13:51 UTC, jlehmus commented on themes/finna2/templates/RecordDriver/DefaultRecord/data-termsOfUse.phtml
> +    if(!empty($field['rights'])):
no nyt olis

2023-11-09 17:33 UTC, EreMaijala approved these changes

2023-11-09 17:34 UTC, merged