[FINNA-916] Add information for screen reader about feed link
NatLibFi/NDL-VuFind2 pull request #2733
Opened 2023-10-16 11:30 UTC by siiriylonen

2023-10-17 12:14 UTC, EreMaijala requested changes

2023-10-17 12:14 UTC, EreMaijala commented on module/Finna/src/Finna/Feed/Feed.php
> +                            $isExternal = true;
Turha muuttuja, isExternaliin suoraan arvoksi tarkistuksen tulos.

2023-10-17 12:14 UTC, EreMaijala commented on module/Finna/src/Finna/Feed/Feed.php
> +                            if (str_contains($value, $host)) {
Tosin tämä tarkistus ei toimi. Jos $host on 'finna.fi', niin ei voi kelvata, jos $value:ssa on vaikka 'finna.fiksu.fi'.

2023-10-17 12:14 UTC, EreMaijala commented on themes/finna2/templates/ajax/feed-carousel.phtml
> +              if (isset($item['isExternal']) && $item['isExternal']) {
`if ($item['isExternal'] ?? false) {`

2023-10-17 12:14 UTC, EreMaijala commented on local/languages/finna/Carousel/en-gb.ini
> +external_link = "External link."
Meillä on jo external_link -käännös oletusdomainissa, ei varmaan mitään syytä tehdä uutta.

2023-10-17 12:14 UTC, EreMaijala commented on local/languages/finna/Carousel/en-gb.ini
> +opens_new_tab = "Opens in a new tab."
Muualla on käytetty "Open in a new window" -käännöstä. Käytetään samaa kaikkialla. Jos pitää olla tab, niin sitten uusi käännös kaikkialle.

2023-10-19 12:31 UTC, siiriylonen commented on module/Finna/src/Finna/Feed/Feed.php
> +                            if (str_contains($value, $host)) {
Eli onko tämä asia jonka saa kuitenkin tällä tarkistettua? Jos esim. katsoo sen jotenkin ilman loppuliitettä vai olisiko vielä jotain mahdollisia poikkeuksia yms. joita ei saisi tarkistettua -> onko kannattavaa

2023-10-20 05:31 UTC, siiriylonen commented
Tässä on nyt luotettu siihen että pääasiallinen host nimi on ennen '.', mutta kai se nyt myös pitää paikkansa. (Kieliversiokin annetaan osoitteen perässä, mutta en tiedä onko vielä jokin eri variaatio olemassa)

2023-10-20 05:33 UTC, siiriylonen commented
Noniin meni vielä väärin päin tarkistus, korjaan..

2023-10-20 06:15 UTC, EreMaijala commented
@siiriylonen Eikö voi tehdä yksinkertaisesti esim. näin: `$isExternal = $linkHost && $linkHost !== $this->serverUrl->getHost();`?

2023-10-20 06:28 UTC, siiriylonen commented
> @siiriylonen Eikö voi tehdä yksinkertaisesti esim. näin: `$isExternal = $linkHost && $linkHost !== $this->serverUrl->getHost();`?

No sekin näyttää toimivan samoin, mutta vieläkin itsellä lokaalisti yksi tapaus antaa väärän tuloksen. Kun karuselli-linkissä näkyy koko osoite -> en näe että toimiiko se sitten varsinaisella sivulla.
(Ja se karuselli siis sellainen jossa näkyy haun tulokset.)

2023-10-20 06:44 UTC, EreMaijala commented
Voit parsia server-url:stakin host:n parse_url:lla. Sitten ei ainakaan ole porttia tms. sotkemassa. Ja toki sitten voi vielä käyttää strcasecmp vertailussa, niin ei haittaa, vaikka olisi kirjoitettu isoilla.

2023-10-20 06:54 UTC, siiriylonen commented
Okei no kokeilin ja ilmeisesti se on se "**if ($item['isExternal'] ?? false)**" siellä feed-carousel.phtml joka nyt aiheutti sen? Ainakin kun vaihdoin sen takaisin " ... && $item['isExternal])" niin toimi kuten piti.

2023-10-23 12:37 UTC, pasitiis approved these changes

2023-10-25 12:35 UTC, EreMaijala requested changes

2023-10-25 12:35 UTC, EreMaijala commented on themes/finna2/templates/ajax/feed-carousel.phtml
> +              $ariaLabel = '';
Kun tähän lisätään mahdollisesti useampi osa, olisi siistimpää tehdä tästä `$ariaLabelParts = []` ja lisätä sitten osat taulukkoon. Lopuksi implode:lla palaset yhteen.

2023-10-27 05:43 UTC, EreMaijala approved these changes

2023-10-27 05:43 UTC, merged