[FINNA-1111] Added option to disable dynamic content in popovers
NatLibFi/NDL-VuFind2 pull request #2734
Opened 2023-10-18 08:30 UTC by LuomaJuha

2023-10-18 08:34 UTC, LuomaJuha commented
Eikun pitääkin tarkentaa vielä missä tilanteissa sen voi ottaa pois päältä. Suljetaan hetkeksi.

2023-10-19 08:04 UTC, EreMaijala requested changes

2023-10-19 08:04 UTC, EreMaijala commented on module/Finna/src/Finna/AjaxHandler/GetFieldInfo.php
> +        $allowAuthoritySummary
Menee yhdelle riville.

2023-10-19 08:04 UTC, EreMaijala commented on module/Finna/src/Finna/AjaxHandler/GetFieldInfo.php
> +            if (!empty($this->dynamicContent['label_enrichment'] ?? true)) {
`!empty` on turha näissä

2023-10-19 08:04 UTC, EreMaijala commented on local/config/finna/config.ini.sample
> +;dynamic_content[authority_summary] = false
Meillä on jo authority_fields -asetus, tämä vaikuttaa päällekkäiseltä.

2023-10-19 08:04 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/ajax-field-info.phtml
> +<?php if ($this->allowAuthoritySummary && $this->authority): ?>
Parempi jättää vain auktoriteetti lataamatta, jos sitä ei haluta.

2023-10-20 08:27 UTC, LuomaJuha commented on local/config/finna/config.ini.sample
> +;dynamic_content[authority_summary] = false
hmm, joo voisin koittaa laittaa authorityFieldsin kautta mieluummin

2023-10-24 08:29 UTC, LuomaJuha commented on themes/finna2/templates/RecordDriver/DefaultRecord/ajax-field-info.phtml
> +<?php if ($this->allowAuthoritySummary && $this->authority): ?>
joo, täs oli vaa sellanen et haluttiin toi lisätiedot linkki näkyviin ja se poistettiin näkyvistä jos authoritya ei ladattu.

2023-10-25 09:03 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/ajax-field-info.phtml
> +<?php if ($this->allowAuthoritySummary && $this->authority): ?>
Just, okei.

2023-10-26 17:15 UTC, EreMaijala requested changes

2023-10-26 17:15 UTC, EreMaijala commented on module/Finna/src/Finna/AjaxHandler/GetFieldInfo.php
> +            ? array_filter($this->config->LinkPopovers->authority_fields->toArray())
Pitäisiköhän tässäkin oikeastaan käyttää `?->`-operaattoria?

2023-10-26 17:15 UTC, EreMaijala commented on module/Finna/src/Finna/AjaxHandler/GetFieldInfo.php
>          $enrichmentData = $this->getEnrichmentData($ids[0], $label);
Tässä voisi olla hyvä katsoa, halutaanko mitään rikastusdataa. Jos ei haluta, niin turha sitä on hakeakaan.

2023-10-27 07:11 UTC, LuomaJuha commented on module/Finna/src/Finna/AjaxHandler/GetFieldInfo.php
>          $enrichmentData = $this->getEnrichmentData($ids[0], $label);
jees!

2023-10-27 07:13 UTC, LuomaJuha commented on module/Finna/src/Finna/AjaxHandler/GetFieldInfo.php
> +            ? array_filter($this->config->LinkPopovers->authority_fields->toArray())
kyllähän se poistais tavaraa.

2023-10-31 14:30 UTC, EreMaijala approved these changes

2023-10-31 14:41 UTC, merged