[FINNA-1114] Add place popover to location field
NatLibFi/NDL-VuFind2 pull request #2736
Opened 2023-10-19 09:53 UTC by siiriylonen

2023-10-25 11:26 UTC, EreMaijala requested changes

2023-10-25 11:26 UTC, EreMaijala commented on local/languages/finna/en-gb.ini
> +Location LIDO = "Location"
Laita title context:iin RecordDataFormatterFactory:ssa, niin ei tarvitse uutta käännöstä.

2023-10-25 11:26 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +            $placeId = $repository->repositoryLocation->placeID ?? [];
Metodien pitää palauttaa yhtenäiset tiedot eri formaateilla. Laajennettu versio vaikka nimelle getPhysicalLocationsExt. Ja metodin dokumentaatiossa olisi hyvä kertoa, mitä se palauttaa. Ja palautetaan aina samaa muotoa, vaikkea kaikkia kenttiä olisikaan.

2023-10-25 11:26 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +                    $displayPlace = [
$displayPlace viittaisi näytettävään nimeen, laita ennemmin vaikka $result

2023-10-25 11:26 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +                    foreach ($repository->repositoryLocation->placeID ?? [] as $placeId) {
on jo $placeId-muuttujassa

2023-10-25 11:26 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +                        $details[] = $typeDesc;
Jos tyyppi otettiin jo ekasta, niin mihin tätä details:ia tarvitaan? En näe sitä käytettävän missään.

2023-10-25 11:26 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +                    $displayPlace['externalLinks'] = $this->getPhysicalLocationLinks();
Miksi jokaiseen paikkaan liitetään kaikki linkit?

2023-10-25 11:26 UTC, EreMaijala commented on module/Finna/src/Finna/View/Helper/Root/Record.php
> +                $linkText = $linkType = $link['label'];
Tässä ei kannata käyttää compact:ia. Laita vaan suoraan oikeannimisiin alkioihin array:ssa.

2023-10-25 11:26 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/SolrLido/data-lidoLocations.phtml
> +        <?=$this->record($this->driver)->getLinkedFieldElement($this->headingType ?? 'place', $field, ['name' => $field], ['class' => ['backlink'], 'description' => true])?><br>
Ei kai tällaista tilannetta pitäisi olla?

2023-10-25 11:26 UTC, EreMaijala commented on module/Finna/src/Finna/View/Helper/Root/Record.php
> +                $escapedUrl = $link['url'];
Ei ole escapettu, pitää tehdä.

2023-10-25 11:26 UTC, EreMaijala commented on module/Finna/src/Finna/View/Helper/Root/RecordDataFormatterFactory.php
> +            'data-lidoLocations.phtml',
Ei formaatin nimeä templaattiin, vaan templaatti formaatin hakemistoon.

2023-10-25 11:26 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/SolrLido/data-lidoLocations.phtml
> +              $field['placeName'],
Jos `placeName` olisi `name`, voisi laittaa suoraan $field:n getLinkedFieldElement:n parametriksi.

2023-10-30 07:56 UTC, LuomaJuha reviewed
Jätetty pari kommenttia slackissa.

2023-10-30 09:20 UTC, LuomaJuha requested changes
Pari hommaa mitä vielä löytyi

2023-10-30 09:20 UTC, LuomaJuha commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +     * Returns an array with the keys:
Returns a multidimensional array containing arrays with keys:?

2023-10-30 09:20 UTC, LuomaJuha commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +                            if (!empty(($idItem))) {
ylemmässä === ja !== ja !empty($idItem) on turha.

2023-10-30 09:20 UTC, LuomaJuha commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +                    $idTypeFirst = (string)($placeId->attributes()->type ?? '');
käytä ylempänä olevaa $attr -> type, ei tarvitse null coalescing ja trim() ympärille

2023-10-30 09:20 UTC, LuomaJuha commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +                    $idType = (string)($attr->type ?? '');
tätä ei taideta käyttää mihinkään kun alemmassa loopissa yliajetaan

2023-10-30 09:21 UTC, LuomaJuha commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +                    $idTypeFirst = (string)($placeId->attributes()->type ?? '');
trim( voi laittaa varmuudeksi kaikkien (string) castattavien ympärille

2023-10-31 08:43 UTC, LuomaJuha requested changes

2023-10-31 08:43 UTC, LuomaJuha commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +                        $idAttr = $idItem->attributes();
voi siirtää iffin jälkeen.

2023-10-31 08:43 UTC, LuomaJuha commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +                    foreach ($placeId as $idItem) {
Nää voi kattoa kaikki samassa loopissa ja esim $i = 0; kattoa onko ensimmäinen mistä otetaan arvot.

foreach ($repository->repositoryLocation->placeID ?? [] as $placeID)

if ($i++ = 0) { 
 // Talleta eka id ja type omiinsa.
}

2023-10-31 09:07 UTC, LuomaJuha commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +                    foreach ($placeId as $idItem) {
Mietin et miksköhän tosta ekasta otetaan noi idtyypit ja id kun se luottaa sitten metadatan järjestykseen mikä ei oo validi. Pitäis olla ennemmin joku tunniste minkä mukaan se otetaan.

2023-10-31 11:12 UTC, LuomaJuha approved these changes
Omasta mielestäni näyttää nyt kivalta.

2023-10-31 11:31 UTC, EreMaijala requested changes

2023-10-31 11:31 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +                        $result['externalLinks'] = [
externalLinks pitäisi olla kokoelma linkkejä, eli `$result['externalLinks'][] = ...`

2023-10-31 11:31 UTC, EreMaijala commented on module/Finna/src/Finna/View/Helper/Root/Record.php
> +            $fieldLinks[] = [
Miksi externalLinks ympätään mukaan fieldLinks:iin? Ne ovat kaksi eri asiaa ja pitäisi esittää omissa blokeissaan.

2023-11-02 10:34 UTC, EreMaijala requested changes

2023-11-02 10:34 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +                $result = [];
Nyt on hämmentävä nimi muuttujalla. `$result` ennemmin vaikka `$locationInfo`, niin ei vaikuttaisi siltä, että se liittyisi jotenkin `$results`:iin.

2023-11-02 10:34 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +                $location = implode(', ', $locations);
Tätä muuttujaa ei tarvita mihinkään, voi laittaa imploden tuloksen suoraan results:iin.

2023-11-02 10:34 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/SolrLido/data-locations.phtml
> +<?php if (empty($data)) {
Turha testi, ei tänne tulla ellei ole näytettävää

2023-11-02 10:34 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/SolrLido/data-locations.phtml
> +  <?=$this->escapeHtml($data) ?><br>
Tätä tilannetta ei pitäisi koskaan tulla, eli pois moinen ja is_array-tarkistukset.

2023-11-02 11:19 UTC, EreMaijala approved these changes

2023-11-02 11:20 UTC, merged