[FINNA-704] Add a new carousel type
NatLibFi/NDL-VuFind2 pull request #2763
Opened 2023-11-09 14:46 UTC by siiriylonen

2023-11-10 05:48 UTC, siiriylonen commented
Huomioita:
- Suunnitelmissa oli myös eri ikoni desktop-karuselliin? (nykyinen ei taida skaalautua kuvassa olevalla tavalla)
- Tekstimäärän rajaaminen on vähän hankala arvioida kun se riippuu myös karusellin korkeudesta.
- Suunnitelmissa oli isommat pagination pallot, mutta koska niitä ei muutettu silloin aiemminkaan niin en tässä ole sitä tehnyt, teenkö?

2023-11-28 11:32 UTC, pasitiis commented
- Korkeus varmaan pitää tehdä siten että määritetään kuvan korkeus height-asetuksella, muuten on vaikea saada karuselli toimimaan mobiilissa ilman että teksti katkeaa (nyt katkeaa helposti)?
- Mobiilissa nuolet keskitettyinä (nyt menee osittain sivutuspainikkeiden kanssa päällekkäin mobiilissa)
- Voi olla tarve näyttää kuva ensimäisenä, asetuksiin tuki järjestyksen vaihtamiseen (kuva/otsikko)?

2023-12-05 10:46 UTC, pasitiis commented
Ehdin pikaisesti testaa muutoksia. Vaikutti ihan toimivalta.

2024-02-19 06:29 UTC, pasitiis approved these changes

2024-02-22 13:23 UTC, EreMaijala requested changes

2024-02-22 13:23 UTC, EreMaijala commented on local/config/vufind/rss.ini.sample
> +;; Optional slider settings:
Slider puuttuu type-kentästä ylhäältä.

2024-02-22 13:23 UTC, EreMaijala commented on module/Finna/src/Finna/AjaxHandler/FeedTrait.php
> +        if (str_contains($type, 'carousel') || $type === 'slider') {
Tämä tarkistus toistuu alempana, ota talteen vaikka `$isCarouselStyle`-muuttujaan ja käytä sitä molemmissa.

2024-02-22 13:23 UTC, EreMaijala commented on themes/finna2/js/finna-feed-element.js
> +        if (finna.layout.isTouchDevice() && typeof settings.linkText === 'undefined' && !slider) {
`!slider` on "halvin" tarkistus, laita se if:ssä ekaksi.

2024-02-22 13:23 UTC, EreMaijala commented on themes/finna2/templates/ajax/feed-carousel.phtml
> +  <?php $feedTitle = $this->translateTitle ? $this->transEsc($this->translateTitle) : $this->escapeHtml($this->title); ?>
Jätä feedTitle escapetettamatta tässä ja escapea siellä, missä sitä käytetään. Muuten jää feed-slider-item:ssa epäselväksi, onko escapet kunnossa.

2024-02-23 12:50 UTC, EreMaijala requested changes

2024-02-23 12:50 UTC, EreMaijala commented on module/Finna/src/Finna/AjaxHandler/FeedTrait.php
> +        if ($isCarouselStyle) {
Tämän voisi lyhentää: `$template = $isCarouselStyle ? 'carousel' : $type;`

2024-02-23 13:12 UTC, EreMaijala approved these changes

2024-02-23 13:14 UTC, merged