[FINNA-1182] Add support for Icareus player
NatLibFi/NDL-VuFind2 pull request #2768
Opened 2023-11-15 11:49 UTC by LuomaJuha

2023-11-15 12:58 UTC, LuomaJuha commented
Laitoin @pasitiis jos sul o jotai sanottavaa mut eipä täs hirveesti oo tyylimuutoksia.

2023-11-16 07:30 UTC, pasitiis commented on themes/finna2/templates/RecordDriver/SolrForward/core.phtml
> +                  <?php if (!empty($icon)): ?><i class="fa <?=$icon?>"></i> <?php endif; ?><?=$this->transEsc('default::link_' . $desc, null, $desc) ?>
Varmaan olisi hyvä käyttää tässä icon helpperiä.

2023-11-16 07:33 UTC, LuomaJuha commented on themes/finna2/templates/RecordDriver/SolrForward/core.phtml
> +                  <?php if (!empty($icon)): ?><i class="fa <?=$icon?>"></i> <?php endif; ?><?=$this->transEsc('default::link_' . $desc, null, $desc) ?>
jeppis

2023-11-16 08:32 UTC, EreMaijala commented
@LuomaJuha Mitä jos kuitenkin olisi icareus-helper, jolle vaan välitetään pelkän id:n sijaan koko polku tai koko url? Muuten ei voi olla [tätäkään](https://github.com/NatLibFi/NDL-VuFind2/pull/2768/files#diff-fcfe4b757d25d6c27980ace012c605f1ba6e23e8405e0dadfa3349b73f1f744aR109).

2023-11-16 08:42 UTC, LuomaJuha commented
@EreMaijala ah, totta en huomioinu tuota kaveria. Voisihan se olla näppärä. Muokkaan vähän, että tulis jotenkin järkevän oikea.

2023-11-16 11:37 UTC, LuomaJuha commented
@EreMaijala noni, tajusin et miehän voin vaa palauttaa suoraan sen linkin siitä recordlinkeristä ku ne embedit on niillä aina samoja. Tein iframeen icareus funktion taas niin nyt ne toimii kun laittaa url:n ja categoriat.

2023-11-17 05:55 UTC, EreMaijala requested changes

2023-11-17 05:55 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrForward.php
> +                $videoType
Tää varmaan mahtuisi yhdelle riville...

2023-11-17 05:55 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrForward.php
> +                    $tmpWarnings
Tää varmaan mahtuisi yhdelle riville...

2023-11-17 05:55 UTC, EreMaijala commented on themes/finna2/js/finna-video-element.js
> +      <iframe class="player finna-popup-iframe" frameborder="0" scrolling="no"  allowfullscreen></iframe>
Ylimääräinen välilyönti scrolling-attribuutin jälkeen.

2023-11-17 05:55 UTC, EreMaijala commented on themes/finna2/less/finna/video-player.less
> +        padding-top: 56.25%;
Tämä voisi ehkä kaivata jonkin kommentin, mistä maaginen luku tulee.

2023-11-17 05:56 UTC, EreMaijala commented
> @EreMaijala noni, tajusin et miehän voin vaa palauttaa suoraan sen linkin siitä recordlinkeristä ku ne embedit on niillä aina samoja. Tein iframeen icareus funktion taas niin nyt ne toimii kun laittaa url:n ja categoriat.

Eikö niissä linkeissä ole joku 'elonet' mukana myös? Mistä se tulee? Vai eikö näytetä koskaan missään muualla kuin elonet.finna.fi:ssä?

2023-11-17 08:46 UTC, LuomaJuha commented
@EreMaijala joo, se ei oo vaan tos host:ssa mut tos pathissa ilmenee.

2023-11-17 09:18 UTC, LuomaJuha commented on themes/finna2/less/finna/video-player.less
> +        padding-top: 56.25%;
Laitoin tuohon kommentin mistä hain ne, mut tajusin et voisin laittaa tolla padding-top ihan selityksen kanssa.

2023-11-17 13:52 UTC, pasitiis approved these changes
Testailin embed ja popup -tilassa. Näytti toimivan.

2023-11-28 11:42 UTC, EreMaijala requested changes

2023-11-28 11:42 UTC, EreMaijala commented on themes/finna2/templates/Helpers/iframe.phtml
> +  <?php if ($this->wrapper ?? false): ?>
En tykkää näistä, että avataan ja suljetaan tageja kaukana toisistaan ehtojen perusteella. Otetaan mieluummin välissä oleva sisältö ob_start/ob_get_clean:lla talteen ja rendataan sitten joko diviin tai ilman.

2023-11-28 12:21 UTC, EreMaijala approved these changes

2023-11-28 12:21 UTC, merged