[FINNA-1184] Fix singular known year with wrong time depiction word
NatLibFi/NDL-VuFind2 pull request #2771
Opened 2023-11-16 13:19 UTC by siiriylonen

2023-11-17 07:00 UTC, EreMaijala requested changes
Eikö `$unknown` ole tämän muutoksen myötä ihan tarpeeton?

2023-11-27 07:48 UTC, EreMaijala requested changes
Lisää testitapaus vielä.

2023-11-28 12:20 UTC, EreMaijala requested changes
Testitapauksen pitäisi kattaa myös tuo $yearUncertain-tapaus. Nyt ei kata, vai kuinka?

2023-11-28 12:34 UTC, siiriylonen commented
Tuolla näytti olevan yksi aiempi, johon tulee 1660-luku (vuosi 166u). Mutta teen siis vielä tätä vastaavan merkinnän?

2023-11-28 12:42 UTC, EreMaijala commented
@siiriylonen Sori, en huomannut sitä. Ei sitten tarvitse enempää.

2023-11-28 13:03 UTC, EreMaijala approved these changes

2023-11-28 13:04 UTC, merged