[FINNA-1274] Refactor description loading and add provider for Kirjavälitys.
NatLibFi/NDL-VuFind2 pull request #2773
Opened 2023-11-16 18:54 UTC by EreMaijala

Description loading has been refactored to proper providers. The configuration now allows one to choose the preferred service order and inject shared services with the desired priority. Kirjavalitys provider is meant to be enabled via datasources.ini only.

2023-11-27 14:18 UTC, LuomaJuha requested changes
Pari pientä huomiota ja tuo pieni erovaisuus vanhaan tyhjien descriptionien tallentamisiin.

2023-11-27 14:18 UTC, LuomaJuha commented on local/config/finna/datasources.ini.sample
> +;coverimages = Kirjavalitys:customerId,shared
Pitikö olla descriptions = ..?

2023-11-27 14:18 UTC, LuomaJuha commented on module/Finna/src/Finna/Content/Description/PluginManager.php
> + * Copyright (C) The National Library of Finland 2023.
Vähän kummallinen kommentti?

2023-11-28 11:50 UTC, EreMaijala commented on local/config/finna/datasources.ini.sample
> +;coverimages = Kirjavalitys:customerId,shared
Piti, korjattu.

2023-11-28 11:50 UTC, EreMaijala commented on module/Finna/src/Finna/Content/Description/PluginManager.php
> + * Copyright (C) The National Library of Finland 2023.
Hups, korjattu.

2023-11-28 11:52 UTC, EreMaijala commented
Tosiaan se tyhjänkin kakuttaminen on tarkoituksellista. Kyllä se sieltä cachesta sitten vanhenee ennen pitkää (oletuksena vuorokaudessa, mitä pitäisin ihan kohtuullisena aikana), niin haetaan uudelleen.

2023-11-28 13:43 UTC, LuomaJuha commented
Joo, eiköhän se oo mukava ettei turhaan lähe pyyntöjä.

2023-11-28 14:30 UTC, LuomaJuha approved these changes
Näyttäis toimivan kivasti.

2023-11-28 14:31 UTC, merged