[FINNA-1321] Fix carousel not opening consistently on mobile
NatLibFi/NDL-VuFind2 pull request #2778
Opened 2023-11-21 08:36 UTC by siiriylonen

2023-11-28 08:19 UTC, pasitiis commented
Testasin nopeasti iphonella. Julkaisu kenttä asettuu nyt virheellisesti. Sulkupainikkeen event olisi hyvä olla carousel-close-elemetissä niin ei tule niin paljon virhepainalluksia.  
![rss-karuselli-iphone](https://github.com/NatLibFi/NDL-VuFind2/assets/1954586/ad773e90-7c66-4e6f-9910-af1e130cb707)

2023-12-04 09:22 UTC, pasitiis approved these changes

2023-12-04 10:13 UTC, EreMaijala requested changes
Mulla tulee outo tulos, kun hoveroi alareunan tekstin päällä. Se katoaa, mutta ylhäältä alkava teksti ei tule näkyviin, ellei siirrä kursoria ylemmäs. Ei kai sen niin pitäisi toimia? Feedin asetukset:
```
type = "carousel"
items = 8
displayHTML = "true"
moreLink = 0
title = "uutiset"
linkTarget = "_blank"
height = 400
itemsPerPage[desktop] = 8
itemsPerPage[desktop-small] = 6
itemsPerPage[tablet] = 4
itemsPerPage[mobile] = 2
scrolledItems[desktop] = 8
scrolledItems[desktop-small] = 6
scrolledItems[tablet] = 4
scrolledItems[mobile] = 2
autoplay = 0
linkTo = "modal"
content[text] = 0
content[date] = 0
visualItems = 8

```

2023-12-04 10:13 UTC, EreMaijala commented on themes/finna2/js/finna-feed-element.js
> +        }
setTitleBottom-metodissa on jo kovin samankaltainen blokki, laita sinne tarvittavat säädöt.

2023-12-04 11:56 UTC, siiriylonen commented on themes/finna2/js/finna-feed-element.js
> +        }
Jos näiden lisäksi niin en lisännyt, koska jos titleBottom, niin silloin jos .no-text olisi :hover tyhjä, koska ei näy otsikkoa tai sitä linkki-nuolta -> ei tarvetta .show-hover?

2023-12-04 14:08 UTC, EreMaijala requested changes
Nuoli ei mahdu näytölle, jos tekstiin sattuu liian pitkä sana:
![Näyttökuva 2023-12-4 kello 16 07 00](https://github.com/NatLibFi/NDL-VuFind2/assets/1327659/8a0b9bc6-4615-4d6a-8a9e-8709fbd28737)

2023-12-04 14:08 UTC, EreMaijala commented on themes/finna2/js/finna-feed-element.js
> +        }
Nyt en ymmärtänyt, voitko tarkentaa?

2023-12-04 14:16 UTC, siiriylonen commented on themes/finna2/js/finna-feed-element.js
> +        }
Siis jos tarkotit tarvittavien säätöjen laittamisella sitä, että lisäisi tuon lisäksi mitä nyt tuossa laitetaan myös sinne setTitleBottom kohtaan. Niin siellä ne ovat jo riittävät, sillä sitä .show-hover ei tarvita, koska näyttäisi vain tyhjää jos ei tekstiä.

2023-12-05 08:12 UTC, EreMaijala commented on themes/finna2/js/finna-feed-element.js
> +        }
Okei, voiko siis tämän riviltä 175 alkavan blokin poistaa?

2023-12-05 10:41 UTC, EreMaijala requested changes
ks. https://github.com/NatLibFi/NDL-VuFind2/pull/2778/files#r1415090936

2023-12-05 10:54 UTC, siiriylonen commented on themes/finna2/js/finna-feed-element.js
> +        }
Joo olen katsellut mitä tässä tapahtuisi. Voi poistaa -> poistan.

2023-12-05 11:54 UTC, EreMaijala approved these changes

2023-12-05 11:54 UTC, merged