[FINNA-1144] LIDO: Fix displaying document rights
NatLibFi/NDL-VuFind2 pull request #2782
Opened 2023-11-21 14:26 UTC by mshroom

2023-11-28 12:17 UTC, EreMaijala requested changes

2023-11-28 12:17 UTC, EreMaijala commented on themes/finna2/less/finna/record.less
> +      line-height: 1.3em;
Tarvitaanko justify-content:ia johonkin?
Jos laittaisi myös wrapperilla:
```
.copyright-wrapper {
    display: inline-flex;
    align-items: center;
}
```
niin ei tarvitsisi tätä maagista line-heightia, vai mitä?

2023-11-28 12:17 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/document-links.phtml
> +                    <span>(</span><?php if ($format):?><span><?=$this->escapeHtml($format)?></span><?php endif; ?><?php if (!$copyright): ?><span>)</span><?php else: ?><?php if ($format):?><span>: </
Tämä alkaa mennä sen verran monimutkaiseksi, että olisi selkeämpää koota stringi ensin. Tyyliin:
```
$content = '';
if ($format) {
  $content .= '<span>' . $this->escapeHtml($format) . '</span>';
}
[...]
$content = '(' . $content . ')';
```
Tarvitaankohan kaikkia span:eja? Vai auttaisiko css:ssä align-content tai se, että koko tämä rimpsu olisi kääritty div:iin?

2023-11-28 12:41 UTC, mshroom commented
Hyviä kysymyksiä... Huomasin nyt myös että mobiilinäkymä on kauhea, joten pitää vielä muokata

2023-11-28 14:30 UTC, mshroom commented on themes/finna2/templates/RecordDriver/DefaultRecord/document-links.phtml
> +                    <span>(</span><?php if ($format):?><span><?=$this->escapeHtml($format)?></span><?php endif; ?><?php if (!$copyright): ?><span>)</span><?php else: ?><?php if ($format):?><span>: </
Muokkasin nämä toivon mukaan järkevämmiksi

2023-11-28 14:32 UTC, mshroom commented on themes/finna2/less/finna/record.less
> +      line-height: 1.3em;
justify-contentin otin pois mutta noita muita jos muokkaan, niin en saa millään toimimaan oikein. Aina joku menee asettelussa pieleen

2023-11-28 14:33 UTC, mshroom commented
Muokattu ja nyt pitäis mobiilissakin näkyä ok

2023-11-29 12:00 UTC, EreMaijala approved these changes

2023-11-29 12:01 UTC, merged