[FINNA-1116] EAD3: Fix display of parsed unknown end year in daterange
NatLibFi/NDL-VuFind2 pull request #2789
Opened 2023-11-28 14:38 UTC by siiriylonen

2023-11-29 12:04 UTC, EreMaijala requested changes

2023-11-29 12:04 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrEad3.php
> +                    $startDateParts = explode('-', $start);
Tämä olisi selkeämpi, jos laittaisi näin: `[$startYear] = explode('-', $start); `Ja vastaavasti loppuvuoden puolella, niin ei tarvitse sitten mitään parts-arrayta käyttää.

2023-12-01 11:31 UTC, EreMaijala requested changes

2023-12-01 11:31 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrEad3.php
> +                    if (in_array(strtolower($endYear), ['uuuu', 'xxxx'])) {
Pitäisikö tässäkin käyttää `unknownDateCharsExist` -metodia? Jos on vaikka 2023-20XX, tulee se muuten näkyviin.

2023-12-01 12:48 UTC, siiriylonen commented on module/Finna/src/Finna/RecordDriver/SolrEad3.php
> +                    if (in_array(strtolower($endYear), ['uuuu', 'xxxx'])) {
Kysyin ja, jos on esim.  2023-20XX niin se kuuluisi epävarmoihin aikamerkintöihin jolloin pitäisi näyttää "2023-20XX (epävarma)" (Eli kuuluisiko se vai olisiko kuulunut siihen suljettuun pr ALLI-7544?)

2023-12-01 13:07 UTC, siiriylonen commented on module/Finna/src/Finna/RecordDriver/SolrEad3.php
> +                    if (in_array(strtolower($endYear), ['uuuu', 'xxxx'])) {
Voin siis vaihtaa sen tyhjäksi, koska nytkin se laittaisi sen 2099 eikä kuten pitäisi, mutta sen siis kuuluisi olla kuitenkin jotain muuta..

2023-12-04 14:13 UTC, EreMaijala approved these changes

2023-12-04 14:13 UTC, merged