[FINNA-1417] Fix multiple open times widgets.
NatLibFi/NDL-VuFind2 pull request #2790
Opened 2023-11-29 11:42 UTC by EreMaijala

Makes it possible to use the organisationInfo helper in multiple places on a single page. Reduces the number of variables in the finna.organisationInfo scope to some essential ones for the organisation info page.

2023-12-01 13:39 UTC, LuomaJuha requested changes
Kivasti näytti toimivan eikä mitään oikein paistanu silmäänkään

2023-12-01 13:39 UTC, LuomaJuha commented on themes/finna2/templates/Helpers/holding-callnumber.phtml
>      <?php endif; ?>
Onkohan tän tiedoston muutokset jääny vahingossa?

2023-12-01 13:39 UTC, LuomaJuha commented on themes/finna2/js/finna-organisation-info.js
> +   * @param {String} id
Vaikka onkin js kommentti niin varmaa description olis ihan ok olla?

2023-12-01 13:39 UTC, LuomaJuha commented on themes/finna2/js/finna-organisation-info.js
> +   * @param {String} id
Vaikka onkin js kommentti niin varmaa description olis ihan ok olla?

2023-12-01 13:46 UTC, EreMaijala commented on themes/finna2/templates/Helpers/holding-callnumber.phtml
>      <?php endif; ?>
Oho, väärään branchiin meni. Peruttu.

2023-12-01 13:46 UTC, EreMaijala commented on themes/finna2/js/finna-organisation-info.js
> +   * @param {String} id
Fiksattu.

2023-12-01 13:46 UTC, EreMaijala commented on themes/finna2/js/finna-organisation-info.js
> +   * @param {String} id
Fiksattu.

2023-12-04 07:48 UTC, LuomaJuha approved these changes

2023-12-04 07:49 UTC, merged