[FINNA-1321] Change feed icon element location
NatLibFi/NDL-VuFind2 pull request #2798
Opened 2023-12-05 13:49 UTC by siiriylonen

2023-12-05 13:56 UTC, siiriylonen commented
Näinkö?
Ja tässä nyt myös lisättynä taas se .no-text-luokan lisäys tyhjään normi karuselliin, koska en vain kuvitellutkaan asiaa vaan se luki siinä alkuperäisessä tiketissä ('...' tulee mobiilissa vaikka tyhjä). Laitoin sen vaan nyt suoraan mobiili-karusellin tekemiskohtaan (ja poistin jääneet .show-hover viittaukset).
(Ja myös, pitääkö tällä pr olla eri nimi/numero.)

2023-12-07 12:25 UTC, pasitiis commented
Jäin pohtimaan onko hyvä että sulkupainikeella on koko rivin mittainen event alue. Menee päällekäin linkin avauksen kanssa. Pienentäisin aluetta johon sulkupainikkeen event kohdistuu (vaakasuunassa n. 48px). Yleisesti 48dp (device pixel) on [suositeltu](https://support.google.com/accessibility/android/answer/7101858?hl=en) koko linkin kohteelle. 
<img width="282" alt="Näyttökuva 2023-12-7 kello 13 37 41" src="https://github.com/NatLibFi/NDL-VuFind2/assets/1954586/ba963a64-769d-4901-a158-98b629b061a7">

2023-12-11 08:54 UTC, siiriylonen commented
Tässä nyt vain sellainen, että jos pienennän leveyttä niin napin joutuu asemoimaan uudestaan oikealle, jolloin se taas ei ole mukana elementeissä ja tapahtuu sama päällekkäisyys ongelma otsikon kanssa. margin-left: auto; kyllä toimii myös, mutta silloin se elementin "leveys" on vieläkin koko leveys.

2023-12-18 09:19 UTC, pasitiis approved these changes

2023-12-18 10:02 UTC, EreMaijala requested changes

2023-12-18 10:02 UTC, EreMaijala commented on themes/finna2/js/finna-feed-element.js
> +                el.classList.add('no-text');
Olisiko siitä jotain haittaa, että `no-text` -luokka asetettaisiin jo templaatissa? Jos olisi, niin voisiko muuttaa niin, ettei olisi? Nyt sen vaikutus käytännössä on vähän hämmentävä.

2023-12-22 06:56 UTC, EreMaijala approved these changes

2023-12-22 06:56 UTC, merged