[FINNA-1454] AIPA: Record page style, display and text changes
NatLibFi/NDL-VuFind2 pull request #2806
Opened 2023-12-08 10:00 UTC by aleksip

2023-12-08 10:42 UTC, aleksip commented
@EreMaijala Tätä saa mielellään jo katselmoida, mutta jos pidetään mergeämättä viimeiseen asti, niin ei tarvi avata kolmatta viimeistely-PR:ää.

2023-12-11 09:01 UTC, pasitiis approved these changes

2023-12-11 14:11 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/SolrAipa/core-fields.phtml
>    unset($defaults['Subjects']); // Subjects are displayed in a different part of the record page
Olisi varmaan ainakin yhtenäisempää laittaa oma filtteri getDefaults-metodiin.

2023-12-12 17:38 UTC, EreMaijala requested changes
Näyttää muuten ihan hyvältä, mutta jäin pohtimaan, sitä kun noi CuratedRecord:n result-templaatit puskevat useita muuttujia globaaliin kontekstiin eivätkä siivoa jälkiä, niin onko tilannetta, jossa esim. listNoteTitle jää sinne myös muille tietueille? Olisi selkeämpää, jos noi templaatit kutsuisivat suoraan Record-helperin `getSearchResult`:n sijaan `renderTemplate`-metodia, jolle voi antaa parametrina tarvittavat muuttujat, jotka se lisää globaaliin kontekstiin väliaikaisesti. Tämä varsinkin, kun tällä hetkellä `getSearchResult`:lle annetaan kaksi parametria, vaikka se ottaa vain yhden, eikö?

2023-12-13 08:55 UTC, EreMaijala approved these changes

2023-12-13 08:56 UTC, merged