[FINNA-1231] Fix inaccurate carousel pagination on md screen
NatLibFi/NDL-VuFind2 pull request #2812
Opened 2023-12-12 09:09 UTC by siiriylonen

2023-12-12 09:14 UTC, siiriylonen commented
Ongelma näyttäisi johtuvan splide.js, koska se lisää se .is-overflow -luokan tarpeettomast. Eli tämä olisi väliaikaratkaisu?

2023-12-12 14:07 UTC, EreMaijala requested changes

2023-12-12 14:07 UTC, EreMaijala commented on themes/finna2/js/finna-feed-element.js
> +      var perPage = this.splide.options.perPage;
Tässä verrataan desktop-kokoon, mutta md-koossa voi olla vähemmän näytettäviä, jolloin menee pieleen.

2023-12-13 08:33 UTC, EreMaijala commented
Ongelma taitaa juontaa juurensa siihen, että `finna.carouselManager` asettaa gap:ksi arvon, josta tulee pyöristysvirhe. Toki se voisi tehdä homman paremmin, mutta ongelman voi käsittääkseni kiertää huolehtimalla siitä, että kaikilla breakpointeilla on niille sopiva gap. Esim. kolmella slidella tarvitaan kaksi gap:ia, jotka jaetaan vähennetään kolmen sliden leveydestä, eli jos gap*2/3 menisi tasan, ei tulisi pyöristysongelmaa.

2023-12-22 11:31 UTC, LuomaJuha commented on themes/finna2/js/finna-carousel-manager.js
> -    gap: 'gap',
Tuli vaan mieleen, et nytku tää asetus poistetaan niin esim similar carousel gap 2px ei taideta ottaa huomioon?

2024-01-03 12:42 UTC, EreMaijala requested changes

2024-01-03 12:42 UTC, EreMaijala commented on themes/finna2/js/finna-carousel-manager.js
> +  function countGapValue(perPage) {
Olisko `calculateGapValue` tai `determineGapValue` (myös kommenttiin)?

2024-01-15 09:03 UTC, EreMaijala approved these changes

2024-01-15 09:03 UTC, merged