[FINNA-290] Fix missing article translations on rss feed
NatLibFi/NDL-VuFind2 pull request #2824
Opened 2023-12-27 11:12 UTC by siiriylonen

2024-01-03 08:55 UTC, EreMaijala requested changes
Eikö tämä sotke käännösten lisäyksen silloin, kun artikkeli näytetään erillisellä sivulla modaalin sijaan?

2024-01-16 05:56 UTC, siiriylonen commented
Hmm, no ainakin nuo käännökset lisätään jos $this->modal eli näkyisikö se sitten muilla tapauksilla? Ainakaan en saa sellaista erillistä sivua näkyviin viallisella rss-syötteellä (tulee vain tietuetta/sivua ei löydy).

2024-01-17 11:58 UTC, EreMaijala commented
Tuota sivupohjaa käytetään myös, kun rss.ini:ssä `linkTo = "content-page"`, jolloin `$this->modal` on false.

2024-02-01 08:46 UTC, EreMaijala requested changes

2024-02-01 08:46 UTC, EreMaijala commented on themes/finna2/templates/feedcontent/content.phtml
> +  if (!$this->modal) {
Käytä ennemmin `$this->jsTranslations()->addStrings()` ei-modaalissa, niin menee samassa kaikkien muiden käännösten kanssa.

2024-02-02 12:49 UTC, EreMaijala approved these changes

2024-02-02 12:49 UTC, merged