[FINNA-1559] Fix supposedly sticky more-button not sticking
NatLibFi/NDL-VuFind2 pull request #2825
Opened 2023-12-29 09:57 UTC by siiriylonen

2023-12-29 09:58 UTC, siiriylonen commented
ALLI-7698 css-muutokset olivat kadonneet FINNA-292 myötä -> nappi ei enää sticky. Olen nyt vain lisännyt ne puuttuvat tässä takaisin.

2024-01-02 13:41 UTC, EreMaijala requested changes

2024-01-02 13:41 UTC, EreMaijala commented on themes/finna2/less/finna/record.less
> +  button.less-link {
Tämä sääntö voisi olla ylempänä ja `&.top-button` sen sisällä.

2024-01-02 13:41 UTC, EreMaijala commented on themes/finna2/less/finna/record.less
> +.record-information {
Miksi tämä muutos? Vähän hirvittää, että ainakin tuo `vertical-align: baseline;` sotkee helposti jotain muuta.

2024-01-15 09:09 UTC, EreMaijala approved these changes

2024-01-15 09:09 UTC, merged