[FINNA-893] MARC: Display other version details on record page
NatLibFi/NDL-VuFind2 pull request #2836
Opened 2024-01-17 08:35 UTC by jlehmus

2024-02-08 14:03 UTC, EreMaijala requested changes
Tässä olisi parempi laajentaa getAllRecordLinks-metodia niin, että se palauttaa tarvittavat osakentät 775:lle. Muuten tulee kahteen kertaan vähän eri tavalla ja ilman linkitystä. Lisäksi tällä tavalla voisi välttää sen, että meillä olisi Muu versio -kenttä ja Muut versiot -välilehti.
![kuva](https://github.com/NatLibFi/NDL-VuFind2/assets/1327659/7decae89-a1e3-4546-a08b-62ce8fa63eda)

2024-02-08 14:36 UTC, jlehmus commented
Tuossa oli vähän ongelmana se kun 775 on toistettava kenttä, että miten getAllRecordLinks käsittelisi tuommoisen tapauksen. Tässä esim on kaksi 775-kenttää: https://testi-instituutio.finna-pre.fi/finna-893/Record/fikka.4277362

2024-02-08 14:38 UTC, jlehmus commented
Ja tarkoitus oli vielä näkymän asetuksissa ottaa 775 pois noista linkkikentistä

2024-02-08 14:41 UTC, EreMaijala commented
@jlehmus Tuossa esimerkissä on kentät piilotettu näkyvyysindikaattorilla, mutta jos se kytketään pois, niin toimii ihan hyvin:
![kuva](https://github.com/NatLibFi/NDL-VuFind2/assets/1327659/a184b73a-529a-412f-92a7-f5eb882847e0)

2024-02-09 07:33 UTC, jlehmus commented
Okei

2024-02-23 15:19 UTC, closed without merging