[FINNA-1689] Copy notes if item moved to another list
NatLibFi/NDL-VuFind2 pull request #2851
Opened 2024-02-05 07:02 UTC by siiriylonen

2024-02-07 12:19 UTC, EreMaijala requested changes
Tämä pitäisi tehdä serveripuolella.

2024-02-16 06:29 UTC, siiriylonen commented
Menikö nyt oikeaa kautta? Ja jos kyllä, niin en ole ihan varma mitä tässä pitäisi varmistaa, koska AddToList taitaakin olla kutsuttu vain juuri tässä yhdessä tapauksessa? (Listasta toiseen siirrettäessä.)

2024-02-21 08:19 UTC, EreMaijala requested changes

2024-02-21 08:19 UTC, EreMaijala commented on themes/finna2/js/finna-mylist.js
> +      var currentListId = getActiveListId();
`currentListId` turha muuttuja

2024-02-21 08:19 UTC, EreMaijala commented on themes/finna2/js/finna-mylist.js
> +  function addResourcesToList(listId, currentListId = null) {
null on vähän hassu oletusarvo, kun se ei sellaisenaan siirry pyynnössä. Tyhjä stringi tms. ennemmin.

2024-02-21 08:19 UTC, EreMaijala commented on module/Finna/src/Finna/AjaxHandler/AddToList.php
> +                    $notes = reset($notes);
Tämä hukkaa muut paitsi ensimmäisen.

2024-02-22 13:07 UTC, EreMaijala requested changes
Äh, just hokasin, että notet kopioidaan vain, jos on valittuna lista. Jos se näin halutaan, niin sitten se ensimmäisen huomautuksen kopiointi olisi riittänyt. Mutta onko varmasti niin, että jos kopioidaan päälistalta, ei haluta ottaa huomautuksia ollenkaan?

2024-02-22 13:27 UTC, siiriylonen commented
No ainakin siinä alkuperäisessä palautteessa vain kommentoitiin että näin nyt tapahtuu (tai että ne eivät siirry), että ei varmaan mitään tiettyä haluttua tapaa.
Mutta olisiko tässä siis joko:
- siirrettäessä kopioidaan kaikki muistiinpanot -> ei tarvitse nyk. listan id ja jos siirtää kaikista suosikeista se kopioi aina ne kaikki
- kuten nyt, eli tietyltä listalta ja tarvitsisi vain ensimmäisen (reset())
Onko sillä kaikilla suosikeilla ([0]-lista) muutenkaan tallennettuna muistiinpanoja? (Koska siihen listaan ei voi kirjoittaa tai siihen siirtää?)

2024-02-22 13:32 UTC, EreMaijala commented
@siiriylonen Kaikki suosikit -listalla siihen tulee muistiinpanot kaikilta listoilta, joilla tietue on. Sehän on tavallaan vain virtuaalinen kokoelma muista listoista.

Minusta loogisin olisi, että käytetään nykyisen listan id:tä, mutta sen sijaan, että tsekataan `if ($currentListId)` olisi vain `$notes = $driver->getListNotes($currentListId ?: null, $this->user->id);`

2024-02-23 12:44 UTC, EreMaijala requested changes

2024-02-23 12:44 UTC, EreMaijala commented on module/Finna/src/Finna/AjaxHandler/AddToList.php
> +            $notes = '';
Tarvitaanko tätä?

2024-02-23 12:55 UTC, siiriylonen commented on module/Finna/src/Finna/AjaxHandler/AddToList.php
> +            $notes = '';
Ei enää, koska se aina palauttaa edes tyhjän array?

2024-02-23 12:57 UTC, EreMaijala commented on module/Finna/src/Finna/AjaxHandler/AddToList.php
> +            $notes = '';
Ota pois sitten. :)

2024-02-23 13:02 UTC, EreMaijala approved these changes

2024-02-23 13:04 UTC, merged