[FINNA-1408] Separate publishers with linebreaks in Record View
NatLibFi/NDL-VuFind2 pull request #2876
Opened 2024-02-21 16:07 UTC by tmikkonen

2024-02-22 13:16 UTC, EreMaijala requested changes
Eikö tuosta nyt katoa pilkku vuoden edestä jos syötetään vain escapeHtml:lle toi?

2024-02-22 14:03 UTC, tmikkonen commented
Niin se tosiaan tekee. Täytyy varmaan sittenkin muokata publicationDetailsia; escapeHtml vaikuttikin liian helpolta ratkaisulta.

2024-02-23 12:46 UTC, EreMaijala requested changes

2024-02-23 12:46 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/data-publicationDetails.phtml
> +        <span><?=$this->escapeHtml($pubDate)?></span><br>
Miksei br voi olla aina yksinään lopussa?

2024-03-04 14:35 UTC, EreMaijala approved these changes

2024-03-04 14:36 UTC, merged