[FINNA-1929] LinkedEvents: Fix language parameter handling
NatLibFi/NDL-VuFind2 pull request #2877
Opened 2024-02-22 14:58 UTC by rajaro

2024-02-23 10:54 UTC, EreMaijala requested changes

2024-02-23 10:54 UTC, EreMaijala commented on module/Finna/src/Finna/Feed/LinkedEvents.php
> +                $paramArray['language'] = $this->language;
Koko logiikka on vähän pielessä. Miksi language:n tarvitsee olla mukana query:ssa? Eikö se ole aina sama kuin käyttäjän kieli, jolloin $this->language on jo se? 
Nykyisellään jos paramArray:ssa ei tulisi languagea, ei $this->language:akaan koskaan mapattaisi oikein (ts. jos siinä olisi en-gb, niin se ei muutu en:ksi) eikä lisättäisi paramArray:yn.

Voisi siirtää mappauksen constructoriin, poistaa language-parametrin ja lisätä languagen vain paramArrayyn tässä.

2024-02-27 15:10 UTC, rajaro commented on module/Finna/src/Finna/Feed/LinkedEvents.php
> +                $paramArray['language'] = $this->language;
Otin languagen pois query:sta. Eikö käyttäjän kieli pidä ottaa tosta getTranslatorLocale:sta?

2024-03-01 11:03 UTC, EreMaijala approved these changes

2024-03-01 11:03 UTC, EreMaijala commented on module/Finna/src/Finna/Feed/LinkedEvents.php
> +                $paramArray['language'] = $this->language;
Juu. Näin on hyvä.

2024-03-01 11:04 UTC, merged