[FINNA-893] [FINNA-1512] MARC: Display other version details on record page
NatLibFi/NDL-VuFind2 pull request #2880
Opened 2024-02-23 15:03 UTC by jlehmus

2024-02-26 08:22 UTC, EreMaijala requested changes

2024-02-26 08:22 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrMarc.php
> +        $fieldsNames[] = '730';
Laita tämän ympärille tarkistus, ettei ole jo. Esim.  `if (!in_array('730', $fieldNames)) { ... }`. Muuten tulee tuplat, jos 730 lisätään konfiguraatioon.

2024-02-26 08:22 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrMarc.php
> +                    if (is_array($tmp)) {
Tässä riittää `if ($tmp) {`

2024-02-26 08:22 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrMarc.php
> +                        if (!preg_match('/[ilw4678]/', $subfield['code'])) {
preg_match on suhteellisen hidas, käytä ennemmin `if (!in_array($subfield['code'], ['i', 'l', 'w', '4', '6', '7', '8'])) {`

2024-02-26 08:22 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrMarc.php
>                  if (null === $result) {
$result ei voi olla null, joten tämä tarkistus on turha. Samoin toinen alempana.

2024-02-27 11:16 UTC, jlehmus commented on module/Finna/src/Finna/RecordDriver/SolrMarc.php
> +        $fieldsNames[] = '730';
ok

2024-03-05 08:43 UTC, EreMaijala approved these changes

2024-03-05 08:47 UTC, merged