[FINNA-558] Add Producer field in Record View
NatLibFi/NDL-VuFind2 pull request #2884
Opened 2024-02-29 17:22 UTC by tmikkonen

2024-03-05 09:08 UTC, EreMaijala requested changes

2024-03-05 09:08 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrMarc.php
> +                $result = $this->stripTrailingPunctuation($this->getSubfieldArray($field, ['a', 'b', 'c']));
Tämä yliajaa $result:n sisällön joka kierroksella.

2024-03-05 09:08 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrMarc.php
> +    public function getProducer()
Pitäisikö olla getProducers, joka palauttaa kaikkien tiedot?

2024-03-05 09:08 UTC, EreMaijala commented on module/Finna/src/Finna/View/Helper/Root/RecordDataFormatterFactory.php
> +                'context' => ['class' => 'recordManufacturer'],
Miksi recordManufacturer eikä `record-producer` tai `record-producers`?

2024-03-05 12:57 UTC, tmikkonen commented on module/Finna/src/Finna/RecordDriver/SolrMarc.php
> +                $result = $this->stripTrailingPunctuation($this->getSubfieldArray($field, ['a', 'b', 'c']));
Joo *blush*.

2024-03-05 12:57 UTC, tmikkonen commented on module/Finna/src/Finna/RecordDriver/SolrMarc.php
> +    public function getProducer()
Luultavasti parempi monikossa.

2024-03-05 12:57 UTC, tmikkonen commented on module/Finna/src/Finna/View/Helper/Root/RecordDataFormatterFactory.php
> +                'context' => ['class' => 'recordManufacturer'],
Manufacturer ja Producer olivat vieressä molemmat recordManufacturer ja järkeilin, että tämä voisi olla 'samaa sarjaa', kun taskissa mainittiin "vastaisi muodoltaan" ja Manufacturer haetaan myös kentästä 264.

2024-03-05 13:27 UTC, EreMaijala commented on module/Finna/src/Finna/View/Helper/Root/RecordDataFormatterFactory.php
> +                'context' => ['class' => 'recordManufacturer'],
Luokkaa voi kuitenkin käyttää kentän piilottamiseen, jolloin tarkempi on parempi.

2024-03-08 07:56 UTC, EreMaijala commented
@tmikkonen Vielä varmistus: onko tosiaan tarpeen tehdä erillinen kenttä eikä käyttää olemassaolevaa 'Production'-kenttää, joka Forward-tietueissa on käytössä? Pitäisi välttää tekemästä samaa asiaa eri tavoilla, ja tuosta voi tulla myöhemmin ongelmia.

2024-03-08 11:49 UTC, tmikkonen commented
Ok, tarkastelen tätä vielä siltä kannalta.

2024-04-02 08:01 UTC, EreMaijala requested changes

2024-04-02 08:01 UTC, EreMaijala commented on module/Finna/src/Finna/View/Helper/Root/RecordDataFormatterFactory.php
> +            'Production',
Production-otsikolla on jo getProducers, käytetään samaa. Tai päivitetään Forward:inkin metodin nimi.

2024-04-02 12:17 UTC, tmikkonen commented on module/Finna/src/Finna/View/Helper/Root/RecordDataFormatterFactory.php
> +            'Production',
Forwardin nimi näytti omaan silmään perustellummalta, niin mennään sillä.

2024-04-12 08:02 UTC, EreMaijala requested changes

2024-04-12 08:02 UTC, EreMaijala commented on module/Finna/src/Finna/View/Helper/Root/RecordDataFormatterFactory.php
> +        $setTemplateLine(
Tämä on nyt tupla ylläolevan kanssa lukuunottamatta class:ia, joka taas näyttäisi olevan väärä. Korjataan vain class ylläolevaan ja jätetään tämä pois.

2024-04-15 13:17 UTC, EreMaijala approved these changes

2024-04-15 13:18 UTC, merged