[FINNA-1243] Sort original work languages by languages order
NatLibFi/NDL-VuFind2 pull request #2890
Opened 2024-03-07 17:43 UTC by tmikkonen

Spacehip operator itselle uusi ja mallia haettu muualta uasortinkin suhteen.

2024-03-08 09:27 UTC, EreMaijala requested changes
Ongelma on siinä, että kun tieto otetaan suoraan indeksikentästä, ei sen järjestys ole taattu. Oikea ratkaisu olisi hakea tiedot MARC:sta oikeassa järjestyksessä. Vrt. [RecordManagerin metodi](https://github.com/NatLibFi/RecordManager-Finna/blob/dbfca05636d2259dd3dec3bfd01fbc1a0c4fdb85/src/RecordManager/Finna/Record/Marc.php#L2614)) ja ehkäpä niin, ettei sitä edes näytetä, ellei ole käännös kyseessä.

2024-04-12 08:34 UTC, EreMaijala requested changes
Onko tämä varmasti järkevä muutos? Ks. https://jira.it.helsinki.fi/browse/FINNA-1243?focusedId=203813&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-203813

2024-04-15 13:16 UTC, EreMaijala requested changes

2024-04-15 13:16 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrMarc.php
> +        foreach ($this->getMarcReader()->getFields('041') as $field) {
Nyt en ole enää ihan varma, mitä tässä tapahtuu. Luupataan 041:t, mutta sopivalla indikaattorilla haetaan kaikki 041:t ja 979:t ja lisätään resultiin. Varmaan pitäisi ottaa vain tuosta luupattavasta? Ja sit 979 erikseen?

2024-04-15 13:17 UTC, EreMaijala commented
Nyt jos ei sortatakaan, niin voisi otsikon päivittää myös.

2024-04-19 15:30 UTC, tmikkonen commented on module/Finna/src/Finna/RecordDriver/SolrMarc.php
> +        foreach ($this->getMarcReader()->getFields('041') as $field) {
Köh. Aivopieruna en huomionut, että indikaattoria varten luupataan jo 041:t.

2024-04-22 08:16 UTC, EreMaijala approved these changes

2024-04-22 08:16 UTC, merged