Add possibility to display certain linkResources as external links
NatLibFi/NDL-VuFind2 pull request #2901
Opened 2024-03-20 16:00 UTC by LuomaJuha

2024-04-02 07:58 UTC, EreMaijala requested changes

2024-04-02 07:58 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +                        if (str_contains($host, '.')) {
Tässä voisi tsekata suoraan strrpos:n paluuarvon ja käyttää sitä, jos ei ole false. Mutta onko tämä viritys tarpeen? Voisiko olla koko host käännösavaimessa? Muuten voisi ainakin periaatteessa mennä kaksi eri palvelua sekaisin.

2024-04-02 07:58 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +                        $documentDesc = "external_$host";
Tämän pitäisi olla TranslatableString, jotta sillä voisi olla etuliitteetön oletusarvo, jos käännöstä ei löydy.

2024-04-10 09:01 UTC, LuomaJuha commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +                        if (str_contains($host, '.')) {
Sitä pallottelin et olis kokonaan laittanu mut näytti kivemmalta noin. Voisin laittaa kokonaisuudessaankin. :)

2024-04-12 09:02 UTC, EreMaijala approved these changes

2024-04-12 09:02 UTC, merged