[FINNA-2048] Fix carousel templates regarding link text
NatLibFi/NDL-VuFind2 pull request #2903
Opened 2024-03-22 09:30 UTC by siiriylonen

2024-03-22 09:31 UTC, siiriylonen commented
Muutin myös linkkitekstin paikkaa, koska se oli jäi sen varjostuksen ulkopuolelle jos oli asetettu.

2024-03-27 10:37 UTC, EreMaijala requested changes

2024-03-27 10:37 UTC, EreMaijala commented on themes/finna2/templates/ajax/feed-carousel-item.phtml
> +  $clickableElement = !$this->touchDevice && !$hasLinkText;
Tämä pommittaa, jos on jossain kustomoitu feed-carousel.phtml, josta puuttuu hasLinkText-parametri. Laita `!$this->hasLinkText`.

2024-03-27 11:05 UTC, EreMaijala approved these changes

2024-03-27 12:10 UTC, merged