[FINNA-2075] EAD: fix id prepended titles handling for alternative title collection
NatLibFi/NDL-VuFind2 pull request #2906
Opened 2024-03-28 15:10 UTC by siiriylonen

2024-04-11 10:10 UTC, siiriylonen commented
Huomattiin vielä yksi tähän liittyvä asia niin korjaan samassa.

Tulee mahdollisesti siis näkyviin myös "Muut nimekkeet"-kohdassa.

2024-04-12 09:11 UTC, EreMaijala requested changes

2024-04-12 09:11 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrEad.php
> +            if (str_starts_with($mainTitle, \Normalizer::normalize($unitId, \Normalizer::FORM_KC))) {
Tämä ei toimi, kun riippuu indeksoinnin asetuksista, onko unit id titlen edessä. Lisäksi tämän luupin seurauksena `$unitId` asetetaan riippumatta siitä, löytyikö vastaavuus.

2024-04-17 10:52 UTC, siiriylonen commented on module/Finna/src/Finna/RecordDriver/SolrEad.php
> +            if (str_starts_with($mainTitle, \Normalizer::normalize($unitId, \Normalizer::FORM_KC))) {
Korjasiko alempana oleva else asian? (Koska muuten en ehkä ymmärtänyt indeksoinnin asetusongelmaa, sehän kuitenkin olisi mukana mainTitle se unitId, jos se sinne laitettu.)

2024-04-22 06:22 UTC, EreMaijala requested changes

2024-04-22 06:22 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrEad.php
> +            if (str_starts_with($mainTitle, \Normalizer::normalize($unitId, \Normalizer::FORM_KC))) {
Totta joo, jos siis tarkoitus onkin tsekata, onko unit id titlen edessä, niin toimiihan tuo. Mutta parempi olisi luupissa tehdä niin, että `$unitId` asetetaan vasta sitten, kun vastaavuus löytyy. Eli toiseen muuttujaan se tarkistettava arvo ja ennen break:ia asetus unitId:hen.

2024-05-13 11:03 UTC, EreMaijala approved these changes

2024-05-13 11:03 UTC, merged