[FINNA-2083] LIDO: Display language version of author's role in creation field
NatLibFi/NDL-VuFind2 pull request #2913
Opened 2024-04-08 05:33 UTC by siiriylonen

2024-04-08 06:07 UTC, siiriylonen commented
Kannattaako tehdä noin vai vaan käydä termejä läpi lang-attribuutilla ilman getAllLanguageSpecificItemia, koska silloinkin pitäisi sen jälkeen ottaa ensimmäinen jos ei olekaan lang :mag:
```
foreach ($actor->actorInRole->roleActor->term ?? [] as $roleTerm) {
  if (trim((string)$roleTerm->attributes()->lang ?? '') === $language) {
    $role = trim((string)$roleTerm);
    break;
  }
}
if (!$role) {
  $role = trim((string)$actor->actorInRole->roleActor->term ?? '');
}
```

2024-04-09 14:23 UTC, siiriylonen commented
Muutin että hakutulos- ja tietue-sivu eivät hae tekijän roolia suoraan author-kentästä, koska indeksin keräystä ei varmaan käyttäjän kielen mukaan voi tehdä. Nyt lidolla näyttäisi kyllä tekijän mukana tulevan myös rooli author-indeksiin, muilla formaateilla näin ei ollut. Mutta se teki tekijähaun siinä sen tiedon kanssa niin sen linkin muodostus nyt samoin kuin otsikon alla.

2024-04-12 08:47 UTC, EreMaijala requested changes
Toimisiko `iterator_to_array` sen sijaan, että kokoat $langRoles-arrayn luupissa?

2024-04-12 08:47 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +                            $role = (string)(reset($roles));
Jos on monta roolia, pitäisikö ottaa kaikki ennemmin?

2024-04-18 12:42 UTC, siiriylonen commented
> Toimisiko `iterator_to_array` sen sijaan, että kokoat $langRoles-arrayn luupissa?

En tiedä enkö vain osaa käyttää sitä vai sitä ei voi. Ymmärsin siis että olisi jotenkin:
 `$langRoles = iterator_to_array($actor->actorInRole->roleActor->term, true);`?
mutta se kerää vain sen viimeisen term per roleActor. Ja jos otan ->term pois, niin se kerää ne kaikki, mutta se sitten kerää myös ne eri eventActorin termit mukaan?

2024-05-14 11:26 UTC, EreMaijala approved these changes

2024-05-14 11:27 UTC, merged