[FINNA-2153] Fix accessibility issues in OrganisationInfo-page
NatLibFi/NDL-VuFind2 pull request #2917
Opened 2024-04-11 17:30 UTC by pasitiis

Select2 vaihdettu Select-a11y-kirjastoon (https://sr.ht/~nicolaskempf57/select-a11y/). Kirjastoa testattu Joonan toimesta eri ruudunlukijoilla. Lisäksi pieniä saavutettavuuskorjaksia tehty OrganisationInfo-sivulla (fokuksen siirryminen oikeaan kohtaan).

Käännökset puuttuu sekä kirjaston alustus pitää miettiä.

2024-05-14 12:49 UTC, EreMaijala requested changes
"No results"-käännös ei näy, sen sijaan tulee "select_a11y_noresults":
![Näyttökuva 2024-05-14 kello 15 37 30](https://github.com/NatLibFi/NDL-VuFind2/assets/1327659/1b96209b-bf3f-49b4-be72-305c68ee5b75)

Palvelua haettaessa haku-urliin tulee ylimääräinen tyhjä parametri valitun palvelun perään:
http://localhost/finna2-review/AJAX/JSON?method=getOrganisationInfo&element=location-search&id=Helmet&sectors=&buildings=&service_type=A-tikkaat&=&service_location=&service_nearest=0&service_open=0

2024-05-14 12:49 UTC, EreMaijala commented on themes/finna2/js/finna-organisation-info.js
> +      let searchLocationIsActive = searchLocationToggle.getAttribute('aria-expanded');
Nämä `const`:ksi. Pitää myös tarkistaa `searchLocationToggle && searchLocationToggle...`.

2024-05-14 12:49 UTC, EreMaijala commented on themes/finna2/js/finna-organisation-info.js
> +      let searchLocationEl = searchContainer.querySelector('.js-location-search');
const

2024-05-14 12:49 UTC, EreMaijala commented on themes/finna2/templates/organisationinfo/elements/location-search-fields.phtml
> +      <option hidden value=""><?=$this->transEscAttr('Select Service')?></option>
Pitäisi olla transEsc

2024-05-14 12:49 UTC, EreMaijala commented on local/languages/finna/en-gb.ini
> +select_a11y_noresult = "No results"
`select_a11y_no_results`?

2024-05-14 12:49 UTC, EreMaijala commented on themes/finna2/js/finna-select-a11y.js
> +// Add global space.
Add to global namespace?

2024-05-15 08:21 UTC, EreMaijala approved these changes

2024-05-15 08:31 UTC, LuomaJuha approved these changes
koodi näytti kivalta ja näytti toimivan

2024-05-15 08:48 UTC, merged