[FINNA-2001] LIDO: Display language version in collection field
NatLibFi/NDL-VuFind2 pull request #2939
Opened 2024-04-30 07:20 UTC by siiriylonen

2024-05-02 12:06 UTC, EreMaijala requested changes

2024-05-02 12:06 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +                    if ($object) {
Tämä ei enää tarkista samaa asiaa kuin vanha koodi, eli että kenttä ei ole tyhjä trimmattuna. Lienee syytä tehdä tarkistus kuten aiemminkin.

2024-05-02 15:52 UTC, siiriylonen commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +                    if ($object) {
Olin vaihtamassa, mutta mietin että korvaako se checkAllLanguageSpecificItems() sen kohdan, jos ne menevät vielä sen läpi?
`2397  if ('' !== trim((string)$item)) {`
(Siellä ei nyt kyllä ole trim() sisällä `?? ''` tarkistusta.)

2024-05-15 12:04 UTC, EreMaijala requested changes

2024-05-15 12:04 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +                    if (trim((string)$object ?? '')) {
Tästä puuttuu nyt vertailu tyhjään stringiin. Silloin myös nolla tai muu falsy arvo jää näkymättä. Riippumatta siitä, onko se olennaista, pitäisi vertailla kuitenkin tyhjään stringiin.

2024-05-15 12:04 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +        $language = $this->getLocale();
Jos ei tätä tarvita muualla kuin `getAllLanguageSpecificItems`-kutsussa, niin turha muuttuja.

2024-06-04 11:10 UTC, EreMaijala requested changes

2024-06-04 11:10 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +        $results = $this->getAllLanguageSpecificItems($results, $this->getLocale());
Turha asetus muuttujaan, palauta suoraan getAllLanguageSpecificItems:n tulos.

2024-06-10 11:24 UTC, EreMaijala approved these changes

2024-06-10 11:24 UTC, merged