[FINNA-2084] LIDO: Add and fix language versions regarding places
NatLibFi/NDL-VuFind2 pull request #2941
Opened 2024-05-03 11:36 UTC by siiriylonen

2024-05-07 10:32 UTC, siiriylonen commented
Yso-linkit (kieliversiot) eivät näkyneet, koska se type laitettiin sinne id:n (eli yso-linkin) eteen.

Mutta paikkatietoja tulee myös pelkkänä id-numerona (mjr ja rpr), jolloin se type pitääkin olla sen id:n edessä? Ainakin kun kokeilin niin näin näytti olevan, (mutta testitiedostossa oli mjr ilman sellaista, joten en ole ihan varma).
(Lisäksi on se Helsingin karttapalvelu -linkki, jossa se karttapalvelun osoite, mutta se muutenkin menee sieltä external_links kautta.)

-> Joten tässä erottelin ne tyypit, joihin ei laitettaisi sitä type eteen, ehdoksi kaikkiin paikkatietoja laittaviin kohtiin.
(..ja se lista nyt periaatteessa sama kuin $subjectConceptTypes, mutta ei voi käyttää samaa koska eri tarkoitus?)

getSubjectPlaces():ssa oli metodin muuttuja, että lisätäänkö se type vai ei, [mutta voi näköjään tulla molempia](https://finna.fi/Record/hkm.C9FCC60D-F266-4C6A-B521-A6B1B9CE1B58?sid=4709493344), niin otin sen nyt pois.

2024-05-14 12:17 UTC, EreMaijala requested changes

2024-05-14 12:17 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +    public function getSubjectPlaces(bool $extended = false)
`$prependType`-parametrin poistaminen johtaa siihen, että `getAllSubjectHeadings` palauttaakin tyypit sisältäviä tunnisteita. Pitää säilyttää parametri mutta muuttaa toiminta niin, ettei tyyppiä lisätä url:eille, vaikka `$prependType` olisi true.

2024-05-14 12:19 UTC, EreMaijala commented
Onko jonkin syy siihen, että eteen lisätään tyyppi nyt pikkukirjaimilla?

2024-05-17 10:02 UTC, siiriylonen commented
> Onko jonkin syy siihen, että eteen lisätään tyyppi nyt pikkukirjaimilla?

Ei tainnut muuten kuin se vertailu. Eli mielummin ei kirjainkoosta välittävä vertailu ja tyypin kirjoitusasu pysyy kuten annettu?

2024-06-04 11:19 UTC, EreMaijala requested changes

2024-06-04 11:19 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +    protected $placeIDTypes = ['uri', 'url'];
Epäselvä muuttujan nimi. Ehkä jotain tyyliin `$alwaysUniqueIDType` tai `$uniquePlaceIDTypes`.

2024-06-04 11:19 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +                    if ($type && !$isTypeInArray && $prependType) {
Mieti tarkistusten järjestys ja jätä tekemättä hankalammat, jos helpot ei täyty. Eli `if ($type && $prependType && !in_array(...))`. Samalla pääset eroon `$isTypeInArray`-muuttujasta, jonka nimi ei ole kovin kuvaava.

2024-06-10 11:30 UTC, EreMaijala requested changes

2024-06-10 11:30 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +                    $idTypeFirst = trim((string)($placeId->attributes()->type ?? ''));
Mitäs nyt käy, jos type on tyhjä?

2024-06-18 11:13 UTC, EreMaijala requested changes

2024-06-18 11:13 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +                    $prependType = !empty($idTypeFirst)
Vertaa mieluummin tyhjään stringiin ja käytä `&&` ternary-operaattorin sijaan.

2024-06-27 06:51 UTC, EreMaijala approved these changes

2024-06-27 06:52 UTC, merged