[FINNA-2008] Quria implementation
NatLibFi/NDL-VuFind2 pull request #2942
Opened 2024-05-06 12:08 UTC by LuomaJuha

2024-05-29 17:42 UTC, EreMaijala requested changes

2024-05-29 17:42 UTC, EreMaijala commented on local/config/finna/Quria.ini.sample
> +updateFields = pickUpLocation:requiredByDate
Puuttuu kommentti, joka kertoo, mitä kenttiä voi käyttää.

2024-05-29 17:42 UTC, EreMaijala commented on local/config/finna/Quria.ini.sample
> +; valid value is 'driver'.
tästä taitaa puuttua rivi 
`; Changing of loan history state is enabled if method parameter is set. Only`

2024-05-29 17:42 UTC, EreMaijala commented on local/config/finna/Quria.ini.sample
> +; if you have patron quria you can use driver method.
patron quria?

2024-05-29 17:42 UTC, EreMaijala commented on module/Finna/src/Finna/ILS/Driver/Quria.php
> +                    /*&& 'yes' === $reservation->isDeletable*/
Tämä ei nyt mene ihan yhteen yläpuolella olevan kommentin kanssa, vai?

2024-05-29 17:42 UTC, EreMaijala commented on module/Finna/src/Finna/ILS/Driver/Quria.php
> +                'success' => true,
sisennys?

2024-05-30 06:50 UTC, LuomaJuha commented on module/Finna/src/Finna/ILS/Driver/Quria.php
> +                    /*&& 'yes' === $reservation->isDeletable*/
Joo, mitä soappia katon niin eihän tota oo ees viel implementoitu muutaku normal

2024-05-30 17:53 UTC, EreMaijala approved these changes

2024-05-30 17:54 UTC, merged