[FINNA-2091] Adjust image caching functionality
NatLibFi/NDL-VuFind2 pull request #2947
Opened 2024-05-16 13:09 UTC by LuomaJuha

- Downloads an unsized image first
- If width and height is required, then creates a new image from unsized image instead of calling the api again

2024-06-10 10:48 UTC, EreMaijala requested changes

2024-06-10 10:48 UTC, EreMaijala commented on module/Finna/src/Finna/Cover/Loader.php
> +        $tempFile = str_replace('.jpg', uniqid(), $this->unsizedImageFile . '-jeppis-');
`-jeppis-`?

2024-06-10 10:48 UTC, EreMaijala commented on module/Finna/src/Finna/Cover/Loader.php
> +        // If the requested image has width and height of 0, then reuturn the unsized image
typo `reuturn`

2024-06-10 10:48 UTC, EreMaijala commented on module/Finna/src/Finna/Cover/Loader.php
> +            $this->unsizedImageFile = $this->determineLocalFile($this->getIdentifiers(), 'default', true);
Miksi tämä asetetaan kahdessa eri paikassa?

2024-06-10 10:53 UTC, LuomaJuha commented on module/Finna/src/Finna/Cover/Loader.php
> +        $tempFile = str_replace('.jpg', uniqid(), $this->unsizedImageFile . '-jeppis-');
ohoppista...

2024-06-10 11:20 UTC, LuomaJuha commented on module/Finna/src/Finna/Cover/Loader.php
> +            $this->unsizedImageFile = $this->determineLocalFile($this->getIdentifiers(), 'default', true);
Hmm, jostain syystä toi loadRecordImage kutsuu parent:fetchFromApi mut pystyisihän se varmaan omaakin kutsumaan.

2024-06-11 09:46 UTC, EreMaijala requested changes

2024-06-11 09:46 UTC, EreMaijala commented on module/Finna/src/Finna/Cover/Loader.php
> +        if (!$this->localFile) {
Onko tämä tarkistus oikeassa kohdassa, kun `$this->localFile` käytetään jo ylempänä?

2024-06-11 09:46 UTC, EreMaijala commented on module/Finna/src/Finna/Cover/Loader.php
> +
Turha tyhjä.

2024-06-11 09:46 UTC, EreMaijala commented on module/Finna/src/Finna/Cover/Loader.php
> +        // Save unsized image, with quality 100,
ylim pilkku perässä

2024-06-11 12:21 UTC, EreMaijala approved these changes

2024-06-11 12:22 UTC, merged