[FINNA-2279] Exclude large-image-layout rules from record-accordions
NatLibFi/NDL-VuFind2 pull request #2951
Opened 2024-05-20 10:08 UTC by LuomaJuha

Other versions tab images looks pretty bonkers now: Record/ham.2B534BB442C44A1D964357F8581850EB?sid=4716189690&imgid=1#versions

2024-05-20 10:10 UTC, LuomaJuha commented
Oh, small adjustment..

2024-06-04 11:52 UTC, EreMaijala requested changes

2024-06-04 11:52 UTC, EreMaijala commented on themes/finna2/less/finna/record.less
> +.large-image-layout.record .record-main > :not(.record-tabs) {
Oliskohan turvallisempaa, jos tämä olisi `.large-image-layout.record .record-main > .media`?

2024-06-06 09:00 UTC, LuomaJuha commented on themes/finna2/less/finna/record.less
> +.large-image-layout.record .record-main > :not(.record-tabs) {
No ainakin selkeämpi! Muokattu

2024-06-06 10:06 UTC, EreMaijala approved these changes

2024-06-06 10:06 UTC, merged