[FINNA-2283] EAD: Add archive citation
NatLibFi/NDL-VuFind2 pull request #2955
Opened 2024-05-22 10:54 UTC by siiriylonen

2024-06-04 11:42 UTC, EreMaijala requested changes

2024-06-04 11:42 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrEad3.php
>      protected function getSupportedCitationFormats()
Tarvitaanko tätä metodia?

2024-06-04 12:19 UTC, siiriylonen commented on module/Finna/src/Finna/RecordDriver/SolrEad3.php
>      protected function getSupportedCitationFormats()
Ainakaan se ei hakenut sitä arkistoviitettä sille, jos poistin sen tästä ead3 (ja olisi vain ead puolella metodi).

2024-06-11 10:53 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrEad3.php
>      protected function getSupportedCitationFormats()
Varmastiko? Mä en saa eroa aikaiseksi, vaikka poistan metodin.

2024-06-11 11:18 UTC, siiriylonen commented on module/Finna/src/Finna/RecordDriver/SolrEad3.php
>      protected function getSupportedCitationFormats()
No jo on, johtui siitä `use Feature\SolrFinnaTrait;`. Otan pois..

2024-06-11 11:49 UTC, siiriylonen commented on module/Finna/src/Finna/RecordDriver/SolrEad3.php
>      protected function getSupportedCitationFormats()
...Eli tarkennuksena, kyllä se itselläni niin vieläkin tekee, paitsi jos poistan sen SolrFinnaTrait, mutta se näköjään oli siellä jo ennen koko viitettä niin en voi sitä tehdä? (Vai voiko se vika olla muualla, en tiedä)

2024-06-11 12:23 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrEad3.php
>      protected function getSupportedCitationFormats()
SolrEad:lla on jo SolrFinnaTrait, joten ei tartte SolrEad3:ssa uudelleen. Se yliajaisi `getSupportedCitationFormats` -metodin, mistä tietysti tulee ongelmia..

2024-06-12 04:56 UTC, EreMaijala approved these changes

2024-06-12 04:56 UTC, merged