[FINNA-1167] Reservation List ordering
NatLibFi/NDL-VuFind2 pull request #2957
Opened 2024-05-24 09:59 UTC by LuomaJuha

2024-08-09 10:11 UTC, EreMaijala requested changes
En ole vielä käynyt tätä kunnolla läpi, mutta yksi aika merkittävä asia tuli eteen: toteutus on monelta osin geneerinen, mutta kuitenkin osittain lukusalitilaus-spesifinen. Olisi ehkä hyvä, että olisi pohjalla geneerinen tilauslista, ja lukusalitilaus olisi sitten siitä peritty toiminto. Fiksulla toteutuksella voisi samaa pohjaa sitten käyttää esim. kuvatilaukseen tai muihin vastaaviin tilaustoimintoihin.
Myös controllerin nimi, reitit (esim. /ResearchRoom/Order/[listan id]) ym. pitäisi miettiä niin, etteivät ole liian geneerisiä ja sitten tiellä, jos tulee muutakin tilaustoiminnallisuutta.

2024-08-09 10:11 UTC, EreMaijala commented on local/config/finna/FeedbackForms.yaml.sample
> +#     reservationlist Form data is sent through
sent through where?

2024-08-09 10:11 UTC, EreMaijala commented on local/languages/finna/ReservationList/fi.ini
> +Delivery Time Request to Organisations Research Room = "Toimitusaikatoive organisaation luku-tai tutkijasaliin"
Viivan jälkeen pitää olla välilyönti ("luku- tai tutkijasaliin").

2024-08-09 10:11 UTC, EreMaijala commented on module/Finna/config/module.config.php
> +                    'route'    => '/ReservationList/AddItem[/:id]',
Missä id-parametria käytetään?

2024-10-07 09:40 UTC, EreMaijala requested changes
- Tarvitaanko getUserId-metodia entityissä?
- CSRF käyttöön?

2024-10-07 09:40 UTC, EreMaijala commented on module/Finna/sql/mysql.sql
> +CREATE TABLE `finna_resource_list_details` (
Miksi tämän taulun tiedot eivät ole suoraan finna_resource_list-taulussa?

2024-10-07 09:40 UTC, EreMaijala commented on module/Finna/src/Finna/Controller/ReservationListController.php
> +        return $this->params()->fromRoute(
Null coalescing olisi parempi, eli tyyliin  `fromRoute() ?? fromPost() ?? fromQuery()`, niin metodeja kutsuttaisiin vasta tarvittaessa.

2024-10-07 09:40 UTC, EreMaijala commented on module/Finna/src/Finna/Controller/ReservationListController.php
> +         * Check if the driver is really compatible with given list
Miksi block-kommentti eikä `// ...`?

2024-10-07 09:40 UTC, EreMaijala commented on module/Finna/src/Finna/Controller/ReservationListController.php
> +                  : $this->redirect()->toRoute('home');
Onko tämä oikea route?

2024-10-07 09:40 UTC, EreMaijala commented on module/Finna/src/Finna/Controller/ReservationListController.php
> +                $list = $this->reservationListService->createListForUser(
Mahtuisi hyvin yhdelle riville.

2024-10-07 09:40 UTC, EreMaijala commented on module/Finna/src/Finna/Controller/ReservationListController.php
> +        $details = $list['details_entity'];
Missä tässä tarkistetaan, löytyikö lista?

2024-10-07 09:40 UTC, EreMaijala commented on module/Finna/src/Finna/Controller/ReservationListController.php
> +            throw new \VuFind\Exception\Forbidden('List not found or ordered');
`'List already ordered'`

2024-10-07 09:40 UTC, EreMaijala commented on module/Finna/src/Finna/Controller/ReservationListController.php
> +    public function orderAction()
Voisiko olla vaikka `placeOrderAction`, niin ei sekoittuisi sorttaamiseen?

2024-10-07 09:40 UTC, EreMaijala commented on module/Finna/src/Finna/Controller/ReservationListController.php
> +                 'name' => $user->getFirstname() . ' ' . $user->getLastname(),
trim ympärille?

2024-10-07 09:40 UTC, EreMaijala commented on module/Finna/src/Finna/Controller/ReservationListController.php
> +        // Override recipients to match lists configured recipients:
list's

2024-10-07 09:40 UTC, EreMaijala commented on module/Finna/src/Finna/Controller/ReservationListController.php
> +    protected function confirmDelete(
Tämä ei vaikuta kauhean hyödylliseltä apumetodilta, poistoon?

2024-10-07 09:40 UTC, EreMaijala commented on module/Finna/src/Finna/Db/Entity/FinnaResourceListDetailsEntityInterface.php
> +     * @return self
Parempi olisi `     * @return static` ja paluuarvon tyyppinä `static`. Ks. https://github.com/vufind-org/vufind/pull/3902

2024-10-07 09:40 UTC, EreMaijala commented on module/Finna/src/Finna/Db/Service/FinnaResourceListDetailsService.php
> +        UserEntityInterface|int $userOrId,
ID:t on näissä mukana muualla yhteensopivuussyistä. Jätetään mieluummin pois ja käytetään pelkkiä entiteettejä.

2024-10-07 09:40 UTC, EreMaijala commented on module/Finna/src/Finna/Form/Form.php
> +        if ($this->reportPatronId() && $catId = $this->user?->getCatId() ?? '') {
Taitaa tarvita sulut jälkimmäisen osan ympärille, että menee null coalescing oikein. Tai mieluummin vaan jättää ` ?? ''` pois...

2024-10-07 09:40 UTC, EreMaijala commented on themes/finna2/scss/finna/reservationlist.scss
> +.archive-request-table {
Miksi "archive"?

2024-10-07 09:40 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/reservation-list-entry.phtml
> +<!-- START of: finna - RecordDriver/DefaultRecord/reservation-list-entry.phtml -->
Tarvitaanko tälle tosiaan oma templaatti, eikä list-entry kelpaa?

2024-10-07 09:40 UTC, EreMaijala commented on themes/finna2/templates/reservationlist/deletebulk.phtml
> +      <div class="alert alert-info"><?=$this->transEsc('fav_delete_warn') ?></div>
Väärä teksti?

2024-10-07 09:40 UTC, EreMaijala commented on themes/finna2/templates/reservationlist/list.phtml
> +  $listTranslations = $this->reservationList($user)->getListTranslationKeys($this->details->getInstitution(), $this->details->getListConfigIdentifier());
Eikö getListConfiguration voisi palauttaa myös käännösavaimet ellei peräti käännökset? Nyt joka paikassa tarvitaan kaksi kutsua.

2024-10-08 07:06 UTC, LuomaJuha commented on module/Finna/src/Finna/Controller/ReservationListController.php
> +    public function orderAction()
aijoo, laitan noihin muihinkin vähän tarkempaa esim deletelist, displaylist jne

2024-10-08 16:36 UTC, LuomaJuha commented
csrf laitettu mihin tajusin sen laittaa ja aika paljon turhaa poistu tos samalla.

2024-10-09 17:50 UTC, EreMaijala requested changes

2024-10-09 17:50 UTC, EreMaijala commented on module/Finna/src/Finna/Controller/ReservationListController.php
> +            'properties' => $listProperties,
Mä en ole koskaan ennen nähnyt tätä syntaksia. Ovelaa. Mutta useimmiten tarpeeton ja hämääväkin. Nyt tehdään muuttujia, joita ei tarvita. Jos tarvitaan vain yhtä elementtiä, kuten tässä, olisi selkeämpää ottaa vain se:
`$listProperties = ($this->reservationListHelper)($user)->getListProperties($view->institution, $view->listIdentifier)['properties'];`
Muissa kohdissa jättäisin elementit assosiatiiviseen taulukkoon, ellei ole painavaa syytä ottaa niitä erilleen.

2024-10-09 17:50 UTC, EreMaijala commented on module/Finna/src/Finna/Controller/ReservationListController.php
> +                $this->translate('could_not_process_feedback')
Ei tartte translate:a tässä.

2024-10-09 18:11 UTC, EreMaijala commented on local/config/finna/ReservationList.yaml.sample
> +Example Organisation:
Lisätään päätasolle asetus, onko listat ylipäänsä käytössä, niin ei tartte tehdä niin paljon kaikkea näkymissä, joissa ei ole. Esim. ihan vaan `enabled: true/false`. Ja sitten organisaatiot vaikka Organisations-avaimen alle.

2024-10-10 13:56 UTC, EreMaijala approved these changes

2024-10-10 13:59 UTC, merged