[FINNA-2247] Fix small image stretched on record page and popup
NatLibFi/NDL-VuFind2 pull request #2962
Opened 2024-06-04 05:41 UTC by siiriylonen

2024-06-10 11:50 UTC, EreMaijala requested changes

2024-06-10 11:50 UTC, EreMaijala commented on themes/finna2/js/finna-image-paginator.js
> +      } else if (_.root.parents().hasClass('record-main') && width < 400 && height < 400) {
Tämä kaipaisi vähintään kommenttia, mistä 400x400 tulee. Entä jos ei ole large image layout?

2024-06-12 10:56 UTC, LuomaJuha reviewed
Keskusteltiin vähän, että voisi mieluummin katsoa ympäröivästä tilasta nuo rajat.

2024-06-20 07:43 UTC, LuomaJuha requested changes
Pari pientä mitä huomasin

2024-06-20 07:43 UTC, LuomaJuha commented on themes/finna2/js/finna-image-paginator.js
> +    var containerWidth = img.parents('.recordcover-container').width();
mitä jos laittais kertaalleen:

const recordCoverContainer = img.closest('.recordcover-container');
ja sit vaa width = recordCoverContainer.width() jne

2024-06-20 07:43 UTC, LuomaJuha commented on themes/finna2/js/finna-image-paginator.js
> +      } else if (_.root.parents().hasClass('record-main') && (width / containerWidth < 0.6) && (height / containerHeight < 0.6)) {
Ehkä pien kommentti noista suhdeluvuista vois olla kiva!

2024-06-20 10:14 UTC, LuomaJuha approved these changes
Omasta mielestä kiva muutos!

2024-06-27 06:53 UTC, EreMaijala approved these changes

2024-06-27 06:55 UTC, merged