[FINNA-2024] Darken the summary text colour on item page
NatLibFi/NDL-VuFind2 pull request #2964
Opened 2024-06-04 09:32 UTC by siiriylonen

2024-06-10 11:23 UTC, EreMaijala requested changes

2024-06-10 11:23 UTC, EreMaijala commented on themes/finna2/less/finna/record.less
> +  .summary.recordSummary p {
Miksi vain `p` eikä koko recordSummary? Laita .summary:n alle (rivi 375).

2024-06-11 10:07 UTC, pasitiis commented
Voisiko tässä käyttää text-color less-muuttuujaa? Nyt teksti on tummempi kuin muu teksti sivulla.

2024-06-11 10:40 UTC, pasitiis approved these changes

2024-06-11 10:49 UTC, EreMaijala approved these changes

2024-06-11 10:49 UTC, merged