[FINNA-529] Collection list to show content on all archive levels
NatLibFi/NDL-VuFind2 pull request #2967
Opened 2024-06-07 11:48 UTC by siiriylonen

2024-06-10 08:18 UTC, LuomaJuha requested changes

2024-06-10 08:18 UTC, LuomaJuha commented on module/Finna/src/Finna/RecordDriver/SolrDefault.php
> +            if ($topId && $topId !== $id) {
Tän voi varmaan tiivistää; return $this->getHierarchyTopID()[0] ?? $this->getUniqueID(); ?

2024-06-10 09:47 UTC, LuomaJuha commented on module/Finna/src/Finna/RecordDriver/SolrDefault.php
> +        if ($this->mainConfig->Hierarchy->showFullHierarchyTree) {
Ja tässä pitäisi olla joku tarkastus ettei nullista yritä katsoa arvoa,
esim $this->mainConfig->Hierarchy->showFullHierarchyTree ?? false

2024-06-11 08:59 UTC, LuomaJuha approved these changes

2024-06-12 04:57 UTC, EreMaijala approved these changes

2024-06-12 04:58 UTC, merged