[FINNA-1726] Add additional user's account information on the account page
NatLibFi/NDL-VuFind2 pull request #2979
Opened 2024-06-26 10:17 UTC by siiriylonen

2024-06-28 10:04 UTC, EreMaijala requested changes
- Minusta se sekoittaa, että kirjastokortin valinta on ennen tilin perustietoja. Tulee vaikutelma siitä, että kyseessä on kirjastokortin tiedot. Sekoittuu muutenkin liian helposti, niin voi olla aika hämmentävä. Leiskassa alakohdat ovat collapsoituvia ja suljettuna, joka ehkä vähän lieventää, mutta kuitenkin nyt on kolme kohtaa, joissa on tilitietoja, ja tässä ilman mitään otsikkoa.
- Ei kai käyttäjätunnuksessa pitäisi näyttää source-prefiksiä?
- Tiedot ovat eri järjestyksessä kuin leiskassa, miksi?

2024-06-28 10:04 UTC, EreMaijala commented on local/languages/finna/fi.ini
> +account_creation_date = "Tilin luomispäivä"
Muualla käytetty muotoa "luonti...", ja sanoisin, että "luontipäivä" olisi parempi muoto.

2024-06-28 10:04 UTC, EreMaijala commented on themes/finna2/templates/myresearch/profile.phtml
> +          <div><span class="profile-title"><?=$this->transEsc('account_login_method')?>: </span><span><?=$this->transEsc('login_method_' . $user->auth_method)?></span></div>
Käytä transEscWithPrefix-helperiä.

2024-06-28 10:04 UTC, EreMaijala commented on themes/finna2/templates/myresearch/profile.phtml
> +          <div><span class="profile-title"><?=$this->transEsc('account_creation_date')?>: </span><span><?=date('d.m.Y', strtotime($user->created))?></span></div>
Käytä convertToDisplayDate-metodia dateTime-helperin kautta.

2024-06-28 12:26 UTC, siiriylonen commented
Figma suunnitelmaa muokattu hieman kommenttien perusteella (ja ne myös tähän muutettu).

2024-08-07 07:18 UTC, pasitiis commented
Laittaisin tiedot omalla riville. Leiska vähän hajoaa jos display-name on pitkä desktopissa, mobiilissa toimii paremmin.

<img width="870" alt="Näyttökuva 2024-08-07 kello 10 15 12" src="https://github.com/user-attachments/assets/f894a1f0-d1a4-45f3-a18b-40d3f3a86365">

2024-08-12 09:34 UTC, EreMaijala requested changes
Tiedot eivät näy, ellei käyttäjällä ole kirjastokorttia.

2024-08-12 09:34 UTC, EreMaijala commented on module/Finna/src/Finna/Db/Row/FinnaUserTrait.php
> +        $username = trim(substr($username, strpos($username, '.') + 1));
Source-prefixin pitäisi tietysti olla aina paikallaan, mutta siitä huolimatta pitäisi myös selviytyä tilanteesta, jossa pistettä ei löydy. Voi olla helpompi vaikka explode:lla:
```
$parts = explode('.', $username, 2);
return $parts[1] ?? $parts[0];
```

2024-08-12 09:34 UTC, EreMaijala commented on themes/finna2/templates/myresearch/profile.phtml
> +          <div class="display-name"><?=$this->icon('profile', 'profile-icon') ?><span class="sr-only"><?=$this->transEsc('logged_in_as')?>: </span><?=$this->escapeHtml($user->getDisplayName()) ?></di
Miksi kaikki yhdellä rivillä?

2024-08-12 09:34 UTC, EreMaijala commented on themes/finna2/templates/myresearch/profile.phtml
> +            <div><span class="profile-title"><?=$this->transEsc('account_creation_date')?>: </span><span> <?=$this->dateTime()->convertToDisplayDate('U', strtotime($user->created))?></span></div>
Turha välilyönti `<span>`-tagin jälkeen?

2024-08-15 12:14 UTC, EreMaijala requested changes

2024-08-15 12:14 UTC, EreMaijala commented on themes/finna2/templates/myresearch/profile.phtml
> +    </div>
Tämän blokin sisennys on nyt pielessä.

2024-08-15 12:14 UTC, EreMaijala commented on themes/finna2/templates/myresearch/profile.phtml
> +        <div><span class="profile-title"><?=$this->transEsc('account_creation_date')?>: </span><span><?=$this->dateTime()->convertToDisplayDate('U', strtotime($user->created))?></span></div>
$user->created on aina muodossa `'Y-m-d H:i:s'`, joten ei ole tarvetta parsia sitä strtotime:lla, vaan konvertoi suoraan alkuperäisestä muodosta.

2024-08-16 09:55 UTC, pasitiis approved these changes

2024-08-16 09:56 UTC, EreMaijala approved these changes

2024-08-16 09:56 UTC, merged