[FINNA-2334] Make mobile menu focus visible.
NatLibFi/NDL-VuFind2 pull request #2984
Opened 2024-07-04 12:10 UTC by pasitiis

2024-08-15 11:24 UTC, EreMaijala commented
@pasitiis Annetaanko sen häiritä, että headerin tab order on vähän outo?

2024-08-16 12:15 UTC, pasitiis commented
> @pasitiis Annetaanko sen häiritä, että headerin tab order on vähän outo?

Korjaan sen samalla.

2024-09-05 06:19 UTC, EreMaijala requested changes
Merkkaan odottamaan muutoksia..

2024-09-09 11:41 UTC, LuomaJuha commented
Otin pois itteni ku on hoidossa jo muuten :)

2024-09-11 10:19 UTC, EreMaijala approved these changes

2024-09-11 10:19 UTC, merged