[FINNA-1497] Fix author and presenter fields
NatLibFi/NDL-VuFind2 pull request #2989
Opened 2024-07-19 05:43 UTC by siiriylonen

2024-07-19 06:11 UTC, siiriylonen commented
Laitan nyt miten tiketin tekstin perusteella olen järkeillyt tämän:
100 ja 110 kentissä on “päätekijä”?
Eli ylemmässä kentässä halutaan näyttää aina (roolitermistä huolimatta) kentän 100 ja 110 tiedot, sekä 700 ja 710 tiedot, joiden roolit eivät kuulu presenter_roles.
Ja alempaan - mielummin - ei haettaisi 100 ja 110 kentän tietoja, koska ne aina ylemmässä, mutta sisältäisi aina 700 ja 710 kentän tiedot, joissa roolit, jotka kuuluvat presenter_roles.

2024-08-12 09:25 UTC, EreMaijala requested changes
Tämä voi toimia, mutta menee sotkuksi, kun getNonPresenterAuthors voikin palauttaa esittäjiä. Pitää siis miettiä tarkemmin/laajemmin tuo kokonaisuus ja käyttää esim. getPrimaryAuthors tuossa yläosassa. Siinäkin tapauksessa pitää tietysti huolehtia, että mahdolliset väliinputoajat tulevat mukaan johonkin.

2024-08-30 06:05 UTC, siiriylonen commented
Olisko näin ok tehdä?
(Marc-templaateista en ole ihan varma, koska yksi hakufunktion muutos -> tarvitseeko oman)

2024-09-05 07:51 UTC, EreMaijala commented
@siiriylonen Kyllä tämä voi toimia MARC-tietueille, mutta riittääkö se, vai pitäisikö käytäntöä tarkastella laajemminkin? Ehkä jopa niin, että tämä olisi DefaultRecord:ssa näin, ja mahdolliset poikkeukset sitten formaattikohtaisesti? Ja pitäisikö asia miettiä myös export-formaattien osalta?

2024-09-06 07:06 UTC, EreMaijala commented
Peruin review-pyynnön. Voi laittaa uuden, kun on kysymykset ratkaistu.

2024-09-27 17:47 UTC, EreMaijala requested changes

2024-09-27 17:47 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrMarc.php
> +        foreach ($this->getAuthorFields(true) as $field) {
array_column

2024-09-27 17:47 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrMarc.php
> +    public function getPrimaryAuthors(bool $extended = false): array
Ehkä olisi selkeämpää tehdä getPrimaryAuthorsExtended, joka palauttaa tarkemmat tiedot, ja pitää tämä yksinkertaisena. Säilyy noin ulkomuodoltaan ainakin yhteensopivana yläjuoksun version kanssa.

2024-09-27 17:47 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrMarc.php
> +    public function getAuthorFields(bool $getPrimaryPresenters = false): array
Tämän ei kai tarvitse olla public, vai?

2024-09-30 11:06 UTC, EreMaijala approved these changes

2024-09-30 11:06 UTC, merged