[FINNA-2335 & FINNA-2407] EAD3: Fix download only links
NatLibFi/NDL-VuFind2 pull request #2992
Opened 2024-07-24 14:26 UTC by siiriylonen

2024-07-25 05:39 UTC, siiriylonen commented
Tässä siis oli ne .tiff-linkit -> lataa heti vaikka ulkoinen linkki.
Ja se, että ead3:ssa menee aina linkiksi, koska ei haeta formaattia jonka se latauslinkki tarvitsee. Laitoin sen ne hakemaan dao->daoset linkrole, mutta muodosta en ole varma.

(Mietin myös halutaanko se formaatti tässä näyttää käyttöoikeus-suluissa.)

2024-07-29 10:53 UTC, LuomaJuha requested changes

2024-07-29 10:53 UTC, LuomaJuha commented on themes/finna2/templates/RecordDriver/DefaultRecord/document-links.phtml
> -            <?=$this->icon('external-link')?>
sit jos se määriteltäis siel niin tähä vois laittaa vaa $this->icon($document['icon'] ?? eternal-link)

2024-07-29 10:53 UTC, LuomaJuha commented on themes/finna2/templates/RecordDriver/DefaultRecord/document-links.phtml
> +    <?php if (!isset($document['downloadOnly']) && empty($document['displayAsLink'])): ?>
Mitä jos poistais ton downloadOnly ja driveris vaan laittais icon = 'download'

2024-08-09 08:34 UTC, EreMaijala requested changes
Pitäisikö proxy/proxy-link -kuvakkeen olla alias download-kuvakkeelle, vai mikä tässä on ajatus?

2024-08-09 08:34 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +                    $displayAsLink ??= false;
Laittaisin mieluummin niin, että `$displayAsLink = in_array($type, $this->displayExternalLinks)` tehdään ennen if-lausetta. Muutenhan tuo voisi periaatteessa mennä falseksi silloinkin kuin ei pitäisi.

2024-08-09 08:34 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +     * @param bool   $linkType    Type of link document is displayed as, default is 'proxy'
Kommentti vähän sekava, laita vaikka "Type of document link, default is 'proxy-link'".

2024-08-09 08:34 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +                    $linkType = $displayAsLink ? 'external-link' : 'proxy';
Kun tätä nyt käytetään myös ikonin tunnisteena, niin ehkä 'proxy-link' olisi parempi?

2024-08-09 08:36 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/document-links.phtml
> +    <?php if (!isset($document['downloadOnly']) && empty($document['displayAsLink'])): ?>
Mun mielestä ei hyvä. Parempi, ettei driveri sekaantuisi siihen, miten asioita esitetään.

2024-08-09 12:27 UTC, siiriylonen commented
Niin tämä oli sellaisella ajatuksella, että $downloadOnly ja $displayAsLink yhdistyisivät $linkType, jossa 'proxy' (=>'proxy-link') olisi että muodostetaan se latauslinkki ja ulkoisen linkin näyttäisivät 'external-link' ja 'download', jotka määrittelisivät myös millainen ikoni sen linkin edessä on.

2024-08-14 11:50 UTC, EreMaijala requested changes

2024-08-14 11:50 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +                if (in_array($type, $documentTypeKeys) || ($displayAsLink)) {
Turhat sulut `$displayAsLink`:n ympärillä.

2024-08-14 11:50 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/document-links.phtml
> +        $descriptionDefault = $linkType !== 'download' ? $this->translate($this->translate('external_online_link')) : null;
Tupla-translate pois.

2024-08-15 05:19 UTC, EreMaijala approved these changes

2024-08-15 05:20 UTC, merged