[FINNA-2348] Change the location of export loan history in my account
NatLibFi/NDL-VuFind2 pull request #2993
Opened 2024-07-25 07:47 UTC by siiriylonen

2024-08-07 07:00 UTC, pasitiis commented
Sijoittaisin Vie kaikki painikeen toolbariin. 

<img width="867" alt="Näyttökuva 2024-08-07 kello 9 46 54" src="https://github.com/user-attachments/assets/14c33e10-c77b-430f-89a5-37219834b82b">

2024-08-07 07:35 UTC, siiriylonen commented
(Se 2119 vaikuttaakin todnäk tuohon toolbarin rivitykseen niin se pitää vielä tarkistaa kunhan on valmis.)

2024-08-07 07:42 UTC, pasitiis approved these changes

2024-08-14 11:46 UTC, EreMaijala requested changes

2024-08-14 11:46 UTC, EreMaijala commented on local/languages/finna/en-gb.ini
> +loan_history_save = "Export to favorites"
Lisäisin tähän käännökseen (kaikilla kielillä) perään kolme pistettä ilmaisemaan, että tästä seuraa vielä dialogi, varsinkin kun on vähän erilainen kuin muut viennit.

2024-08-14 12:00 UTC, EreMaijala approved these changes

2024-08-15 05:18 UTC, merged