[FINNA-2119] Improve clarity of button functions in my account
NatLibFi/NDL-VuFind2 pull request #2994
Opened 2024-07-26 07:52 UTC by siiriylonen

2024-07-26 09:46 UTC, siiriylonen commented
(FINNA-2348:sta tulisi lainaushistoriaan se "Lisää kaikki suosikkeihin"-napin poisto eli sitä ei lopulta sitten näkyisi siinä nappipalkissa.)

2024-08-07 06:33 UTC, pasitiis commented
Säätäisin vielä siten että "Valitse kaikki" olisi keskitettynä painikkeisiin desktopissa. Nyt ei ole täysin samassa linjassa muiden elementtien kanssa.

`.myresearch-table .toolbar { align-items: center; }`

Mobiilissa pitää olla baseline.

2024-08-07 06:53 UTC, siiriylonen commented
~~En nyt vaihtanut mobiiliin eri, koska se center näytti keskittävän molemmat samoin/paremmin?~~

//Nyt kyllä lainat osiossa tapahtuukin rivityksessä outoja, katson sen vielä! -> Joo jos monta riviä niin mielummin baseline, vaihdoin sen nyt kaikkiin mobiili

2024-08-07 07:10 UTC, pasitiis approved these changes

2024-08-12 08:17 UTC, EreMaijala requested changes
En ole varma, ovatko kaikki näistä uusia ongelmia, mutta mielellään laittaisin nyt kerralla kuntoon:

- "Valitse kaikki"-checkbox teksteineen ja nappulat rivittyvät eri tavalla eri sivuilla:
![kuva](https://github.com/user-attachments/assets/6e507096-88b8-4c70-b070-418f01845c49)
![kuva](https://github.com/user-attachments/assets/1ab4d8cf-2667-4450-acbb-df528a0d3fa5)
![kuva](https://github.com/user-attachments/assets/d332a134-a5a7-4e12-9551-69823b889a76)

- Jos yhtään varausta ei voi muokata, ei järjestyksen valinta näy leveämmillä näytöillä ollenkaan.
- Jos yhtään lainaa ei voi uusia, näkyy järjestäminen aika rumasti: 
![kuva](https://github.com/user-attachments/assets/9cfcf9b2-9ae8-4019-be32-c8948af9a521)
- Jos lainoilla on sivutus käytössä, pitäisi "Valitse kaikki" olla "Valitse sivu". Lainaushistoriassa lienee sama ongelma myös.
- Lainaushistoriassa kapealla näytöllä näkyy järjestämisvalinta, vaikka historia olisi tyhjä.

2024-08-14 05:43 UTC, siiriylonen commented
Varaukset-sivulla checkbox laitettu rivittymään mobiilissa alas.
Lainaushistoriassa napit vielä kahdella rivillä, mutta oikean marginaalin pienentämisen pitäisi mahduttaa toisesta pr tuleva "Vie kaikki" yhdelle riville.

2024-09-04 12:58 UTC, EreMaijala requested changes
- Sopivalla leveydellä menee lainoissa edelleen kiinni tekstit, ja järjestämis-valikon kuvake on oudon alhaalla (sama ongelma kapealla näytöllä myös ainakin varauksissa):
<img width="365" alt="Lainat" src="https://github.com/user-attachments/assets/74acad98-b8ea-4023-b6fc-57da7fd4b991">

- Miksi lainaushistoriassa rivitys menee eri tavalla eli nappulat eivät siirry yläpuolelle?

2024-09-05 09:34 UTC, EreMaijala requested changes
Vielä jotain häikkää leveämmillä näytöillä, jos ei ole uusittavia lainoja:
![kuva](https://github.com/user-attachments/assets/32f2136c-a0bd-4cfc-a4d7-66756173a57c)

2024-09-05 10:18 UTC, EreMaijala requested changes
Nyt järjestäminen lainoissa on oikealla, kun on uusittavia, mutta hyppää vasemmalle, jos ei ole.

2024-09-06 07:19 UTC, EreMaijala requested changes
- @max-width -määrityksissä pitäisi varmaan olla @screen-*-max, kun siellä on nyt pientä epäjatkuvuutta 993px - 992px välillä.
- "Ei uusittavia lainoja" hyppää ylemmäs 992px kohdalla, eikä asemoidu samalle korkeudelle "Järjestä"-tekstin kanssa.

2024-09-11 10:14 UTC, EreMaijala approved these changes

2024-09-11 10:14 UTC, merged