[FINNA-1956 & FINNA-2390] Add two new icons
NatLibFi/NDL-VuFind2 pull request #2995
Opened 2024-08-02 11:02 UTC by siiriylonen

2024-08-02 11:04 UTC, siiriylonen commented
Lisättiin nämä nyt erikseen, koska threads-ikonia tarvitaan elokuun puoliväliin mennessä.

2024-08-07 05:45 UTC, pasitiis approved these changes

2024-08-09 07:44 UTC, EreMaijala requested changes

2024-08-09 07:44 UTC, EreMaijala commented on themes/finna2/css/finnaicons.css
> +.fi-library-card-barcode:before { content: '\e8ce'; } /* '[]' */
Rivinvaihto lopusta kadonnut?

2024-08-09 07:57 UTC, EreMaijala approved these changes

2024-08-09 08:00 UTC, merged