[FINNA-2264] Show format field in RSS carousel, add title truncation configuration.
NatLibFi/NDL-VuFind2 pull request #2999
Opened 2024-08-06 13:34 UTC by pasitiis

2024-08-15 11:20 UTC, EreMaijala requested changes
- muuttaisin termin truncate size => truncate length

2024-08-15 11:20 UTC, EreMaijala commented on themes/finna2/less/global/icons.less
> +.iconlabel[class*="sound"]:before {
Vähän huolestuttaa, että jokin näistä yksinkertaisemmista luokista aiheuttaa konfliktin ei-formaatti-ikonin kanssa. On muuten sisäisestikin vähän sekaannuksen mahdollisuus esim. `[class*="sound"]` vs. `[class*="sounddisc"]`. Lisäisin ennemmin feedeissä tulevat vaihtoehdoiksi näille nykyisille joko kokonaisilla luokkien nimillä tai sitten niin, että niillä on erillinen luokka tyyliin `.iconlabel.feed-format[class*="sound"]`.

2024-08-15 11:20 UTC, EreMaijala commented on themes/finna2/templates/ajax/feed-carousel-item.phtml
> +          <span class="carousel-header-format"><?=$this->transEsc('format_' . $item['format']);?></span>
Käytä transEscWithPrefix

2024-08-15 11:20 UTC, EreMaijala commented on module/Finna/src/Finna/Feed/Reader/Extension/DublinCore/Entry.php
> +        if (! $format) {
Yleinen tyyli olisi pitää huutomerkki kiinni dollarissa, mutta tässä voisi ketjuttaa vaihtoehdot `?:`-operaattorilla. Pitäisi myös tarkistaa paluuarvon tyyppi siltä varalta, että sieltä tulee DOMNodeList.

2024-08-15 11:20 UTC, EreMaijala commented on module/Finna/src/Finna/Feed/FeedFactory.php
> +        $helper = new $requestedName(
`$helper`? Olisiko ennemmin `$feed`?

2024-08-15 11:20 UTC, EreMaijala commented on themes/finna2/templates/ajax/feed-carousel-item.phtml
> +  <div class="wrapper <?php if (isset($item['format'])): ?><?=$this->transEsc('iconlabel format-' . preg_replace('/[^a-z0-9]/', '', strtolower($item['format'])));?><?php endif; ?>" aria-hidden="true"
Mikä tämän tarkoitus on? Toimiiko tuo transEsc tässä jotenkin fiksusti?

2024-08-15 11:35 UTC, pasitiis commented on themes/finna2/templates/ajax/feed-carousel-item.phtml
> +  <div class="wrapper <?php if (isset($item['format'])): ?><?=$this->transEsc('iconlabel format-' . preg_replace('/[^a-z0-9]/', '', strtolower($item['format'])));?><?php endif; ?>" aria-hidden="true"
Ei ole tarvetta käyttää. Siivoan pois.

2024-09-05 07:13 UTC, EreMaijala approved these changes

2024-09-05 07:15 UTC, EreMaijala requested changes

2024-09-05 07:15 UTC, EreMaijala commented on themes/finna2/templates/ajax/feed-carousel-item.phtml
> +          <span class="carousel-header-format"><?=$this->transEscWithPrefix('format_' . $item['format']);?></span>
Hups, tämä jäi huomaamatta: pitäisi olla `transEscWithPrefix('format_', $item['format'])`.

2024-09-06 07:05 UTC, EreMaijala approved these changes

2024-09-06 07:05 UTC, merged