[FINNA-2442 & FINNA-2443] Alterations to hierarchy tree tab
NatLibFi/NDL-VuFind2 pull request #3001
Opened 2024-08-09 07:40 UTC by siiriylonen

2024-08-20 09:42 UTC, pasitiis commented
Lisäisin painkkeen ja tekstin väliin tyhjää tilaa. Nyt painke on mielestäni aavistuksen liian kiinni tekstissä ja näyttää aavistuksen epätasapainoiselta.

 <img width="614" alt="Näyttökuva 2024-08-20 kello 12 40 18" src="https://github.com/user-attachments/assets/740ef860-c071-4378-bf93-0ea666a4b2aa">

2024-09-05 06:44 UTC, EreMaijala requested changes

2024-09-05 06:44 UTC, EreMaijala commented on local/languages/finna/fi.ini
> +tree_search_limit_reached_html = "Haku tuotti runsaasti tuloksia ja näistä voidaan näyttää ensimmäiset <b>%%limit%%</b> kohdetta. Voit koettaa rajata hakua tarkentamalla hakusanaa."
pitäisi olla pilkku ennen ja-sanaa: `...tuloksia, ja näistä...`. Minusta myös "niistä" olisi parempi kuin "näistä".

2024-09-05 07:58 UTC, EreMaijala approved these changes

2024-09-05 07:59 UTC, merged