[FINNA-2408] LIDO: Download only videos to be displayed as links
NatLibFi/NDL-VuFind2 pull request #3002
Opened 2024-08-15 06:56 UTC by siiriylonen

2024-08-16 09:16 UTC, EreMaijala requested changes

2024-08-16 09:16 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +        'provided_video' => 'video',
Vaikka tällä saisi aikaan toivotun tuloksen, ei video ole dokumentti. Eli väärä paikka. Eikö saman saa lisäämällä `$displayExternalLinks`:iin?

2024-08-16 11:30 UTC, siiriylonen commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +        'provided_video' => 'video',
No mietinkin että voinkohan noin tehdä -_- Mutta sitten $displayExternalLinks mukana se näkyisi ulkoisena linkkinä (ja siihen haetaan external_ käännösavain) niin onko sekään sitten halutunlainen?

2024-08-16 11:56 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +        'provided_video' => 'video',
Jos 3D-linkki näytetään sillä tavalla, niin luulisin video-linkin kelpaavan myös. Jos ei kelpaa, tarvitaan jokin kolmas tyyppi.

2024-08-20 10:53 UTC, mshroom commented on module/Finna/src/Finna/RecordDriver/SolrLido.php
> +        'provided_video' => 'video',
displayExternalLinksin provided_3D-tyyppiset resurssit on linkkejä ulkoiselle sivulle jossa 3D-malli on katsottavissa. Nämä videolinkit taas ovat ladattavia tiedostoja eli halutaan näkyvän samalla lailla kuin ladattavat PDF:t (latausikoni, käyttöoikeustiedot)

2024-09-05 07:06 UTC, EreMaijala approved these changes

2024-09-05 07:07 UTC, merged