[FINNA-2235] Quria: Add support for multiple emails/phone numbers
NatLibFi/NDL-VuFind2 pull request #3022
Opened 2024-09-11 12:28 UTC by rajaro

2024-09-25 09:20 UTC, EreMaijala requested changes
Tämä lienee muuten ok, mutta ei voida lähteä siitä, että id:t välitetään käyttöliittymän kautta ILS-ajurille, koska silloin kuka vain voi lähettää minkä tahansa ID:n. Pitää käsitellä jotenkin niin, ettei ID näy.

2024-10-09 08:51 UTC, EreMaijala requested changes
Tässä olisi varmaan parempi käyttää yhteystietojen muutoslomaketta (ILS-ajurin updateAddress, MyRearchController::changeProfileAddressAction) . Silloin kaikki menisi samalla lomakkeella ja varsinainen päivityslogiikka pysyisi ILS-ajurin sisäisenä.

2024-10-09 08:51 UTC, EreMaijala commented on module/Finna/src/Finna/ILS/Driver/Quria.php
> +                            'emailId' => $emailAddress->id ?? '',
Oletusarvoksi null.

2024-10-09 08:51 UTC, EreMaijala commented on module/Finna/src/Finna/Controller/MyResearchController.php
> +        if (isset($values->profile_extra_email) && isset($values->profile_extra_email_id)) {
Mihin profile_extra_email_id:tä tarvitaan? Sehän sisältää nyt käytännössä kentän indeksin, joka on siis sama kuin `$i` alempana.

2024-10-09 08:51 UTC, EreMaijala commented on module/Finna/src/Finna/Controller/MyResearchController.php
> +                    && $catalog->checkFunction('updateEmail', compact('patron'))
Tämä luupin ulkopuolelle.

2024-10-09 08:51 UTC, EreMaijala commented on module/Finna/src/Finna/Controller/MyResearchController.php
> +                    $result = $catalog->updatePhone(
Miksei täällä ole checkFunction-kutsua kuten emailissa?

2024-10-09 08:51 UTC, EreMaijala commented on module/Finna/src/Finna/Controller/MyResearchController.php
> +                    $validator->isValid($extraEmail)
Jos email ei ole validi, niin eikö siitä pitäisi näyttää virheilmoitus?

2024-12-10 15:55 UTC, rajaro commented
Noniin, pienen veivaamisen jälkeen päädyttiin seuraavaan ratkaisuun:

- Listataan sähköpostit/numerot omat tiedot sivulla
- Muutokset lomakkeen kautta, jossa jokaisen osoitteen/numeron kohdalla täppä aktivointia varten
- Mahdollisuus asetuksissa määrittää, onko aktivointi mahdollista vai ei
- Ei tehdä erikseen kenttiä lisäykselle/poistolle, koska Qurian rajapinta ei tue spostin poistoa

2024-12-11 13:16 UTC, EreMaijala requested changes
Jaron kanssa keskusteltu. Muokataan vielä käyttämään enemmän olemassaolevaa toiminnallisuutta.

2024-12-20 08:09 UTC, EreMaijala requested changes

2024-12-20 08:09 UTC, EreMaijala commented on local/languages/finna/en-gb.ini
> +phone_active = "Use for SMS"
Voisiko käännös vastata paremmin merkitystä tyyliin `phone_use_for_sms`?

2024-12-20 08:09 UTC, EreMaijala commented on module/Finna/src/Finna/ILS/Driver/Quria.php
> +    public function updateEmail($patron, $email, $emailId = null, $active = false)
Pitäisikö tämän olla nyt protected? Ja ehkä vähän eri nimellä (`updateEmailAddress`?), ettei sekoitu tuohon vanhaan julkiseen metodiin?

2024-12-20 08:09 UTC, EreMaijala commented on themes/finna2/templates/myresearch/profile.phtml
> +            <?php elseif (!empty($this->profile['phone_0'])): ?>
Voisiko tätä ja email_0:aa vielä välttää mappaamalla phone_0:n myös phone-kenttään ja email_0:n myös email-kenttään? Tai oikeastaan ensimmäisen aktiivisen arvon, se kai voi olla muukin kuin indeksillä 0?

2024-12-20 08:32 UTC, EreMaijala commented on module/Finna/src/Finna/ILS/Driver/Quria.php
> +    public function updateEmail($patron, $email, $emailId = null, $active = false)
Sama tietty updatePhone:n kohdalla (`protected function updatePhoneNumber`?)

2025-01-15 07:14 UTC, EreMaijala approved these changes

2025-01-15 07:15 UTC, merged