[FINNA-1956] Add link to library card barcode to nav
NatLibFi/NDL-VuFind2 pull request #3033
Opened 2024-09-19 06:57 UTC by siiriylonen

2024-09-26 12:41 UTC, EreMaijala requested changes
- Näyttää username:n viivakoodina, pitäisi olla barcode
- Miksi niin iso riviväli? Nyt menee aika pitkäksi:
![kuva](https://github.com/user-attachments/assets/38520ea0-cd54-4f1b-bb16-0b6798e1f772)
Helposti ottaa ainakin kaksi riviä ihan tavallinenkin kortti, jolloin muutamalla kortilla lista alkaa jo olla melkoinen.

2024-09-27 05:11 UTC, siiriylonen commented
> * Näyttää username:n viivakoodina, pitäisi olla barcode

Otin sen linkin muodostuksen sieltä Kirjastokortti-sivulta, (tuolla testiympäristössä ei ole tule viivakoodeja(?) jos sen asetan ['barcode'] suoraan niin tulee sillä).
Mutta pitäisikö se siis piilottaa jos ei ole barcodea olemassa?

(Siellä librarycard nyt laitetaan myös näin: `$barcode = $record['barcode'] ?? $username;
`)

2024-09-27 06:05 UTC, EreMaijala commented
> Otin sen linkin muodostuksen sieltä Kirjastokortti-sivulta, (tuolla testiympäristössä ei tule viivakoodeja(?) jos sen asetan ['barcode'] suoraan niin tulee sillä). Mutta pitäisikö se siis piilottaa jos ei ole barcodea olemassa?
> 
> (Siellä librarycard nyt laitetaan myös näin: `$barcode = $record['barcode'] ?? $username; `)

Missäs tuolla uudessa koodissa on `$record`?

2024-10-02 08:34 UTC, pasitiis approved these changes
Tarkistin nyt toiminnallisuuden vain UI:n kautta. Muutettu ikoni on nyt myös selkeämpi kuin aiempi.

2024-10-08 08:15 UTC, siiriylonen commented
En tiedä pitäisikö tässäkin siis tehdä kuten homeAction vai olisiko riittänyt että hakee oikeasta paikasta viivakoodin ($card eikä $record), mutta noin nyt tein.

(Tuolla templaatin rivillä 3 myös käytetty pelkkä $user, eikä $this->user?)

2024-10-09 08:10 UTC, EreMaijala requested changes

2024-10-09 08:10 UTC, EreMaijala commented on themes/finna2/templates/librarycards/selectcard.phtml
> +                $profile = $this->ils()->getMyProfile($this->user->toArray());
Näin ei voi tehdä. getMyProfile tarvitsee parametrikseen patronin, joka saadaan patronLogin-metodilta.

getMyProfile-kutsua ei myöskään voi tehdä joka kerran, kun selectcard.phtml renderöidään. Siitä tulisi ihan tolkuttomasti lisää kuormaa kirjastojärjestelmän puolelle. Tarvitaan välimuisti tms. jotta getMyProfile-kutsut voidaan tehdä kerran. Lisäksi, jos barcode-kenttää ei tule, ei pidä yrittää tehdä viivakoodia. Silloin käyttäjätunnus ei ole sopivan muotoinen, vaan voi olla esim. sähköpostiosoite.

2024-11-06 12:41 UTC, EreMaijala requested changes
Mietin, että voisi olla parempi, jos displayBarcodeAction näyttäisi suoraan viivakoodin. Vaikka se ei olekaan mitenkään suuri salaisuus, niin sitä on välillä kyselty, miksi viivakoodin näkee kirjautumattakin. barcode-show:n voisi sitten ohjata tänne samaan.

2024-11-06 12:41 UTC, EreMaijala commented on module/Finna/src/Finna/Controller/LibraryCardsController.php
> +            $cardName = $card->getCardName();
Miksi cache käyttää nimeä eikä kortin id:tä?

2024-11-06 12:41 UTC, EreMaijala commented on module/Finna/src/Finna/Controller/LibraryCardsController.php
> +        } catch (\VuFind\Exception\LibraryCard $e) {
Pitää varmaan ottaa kiinni myös ILS, muuten yhteysongelmat tms. jäävät käsittelemättä.

2024-11-06 12:41 UTC, EreMaijala commented on module/Finna/src/Finna/Controller/LibraryCardsController.php
> +            $this->flashMessenger()->addMessage($e->getMessage(), 'error');
addErrorMessage olisi parempi

2024-11-06 12:41 UTC, EreMaijala commented on themes/finna2/templates/librarycards/selectcard.phtml
> +                <a href="<?=$this->url('displayBarcode')?>?id=<?=$this->escapeHtmlAttr($card->getId()) ?>">
Parametrit suoraan url-helperille arrayna

2024-11-11 08:08 UTC, siiriylonen commented
(...onko tässä ok return vain false vai pitäiskö ohjata muualle/antaa jokin yleinen tai tarkempi addErrorMessage?)

2024-11-18 09:59 UTC, EreMaijala requested changes

2024-11-18 09:59 UTC, EreMaijala commented on module/Finna/src/Finna/Controller/LibraryCardsController.php
> +            if (strstr($username, '.')) {
str_contains

2024-11-18 09:59 UTC, EreMaijala commented on module/Finna/src/Finna/Controller/LibraryCardsController.php
> +            $barcode = $card->barcode ?? $username;
Onkohan tämä jokin vanha virhe? Kortilla ei ole barcode-attribuuttia tai getteriä.

2024-11-18 09:59 UTC, EreMaijala commented on module/Finna/src/Finna/Controller/LibraryCardsController.php
> +            if ($patron && $patron['cat_username'] === $card->getCatUsername()) {
Justiinhan se oikea patron haettiin tossa yllä, miksi tämä tarkistus?

2024-11-18 09:59 UTC, EreMaijala commented on module/Finna/src/Finna/Controller/LibraryCardsController.php
> +            $this->disableSessionWrites();  // avoid session write timing bug
?? Tämä estää session tallennuksen, jollon toi session cache ei toimi..

2024-11-18 09:59 UTC, EreMaijala commented on module/Finna/src/Finna/Controller/LibraryCardsController.php
> +        SessionContainer $sessionContainer,
Käytä constructor property promotionia tälle omalle parametrille.

2024-11-18 09:59 UTC, EreMaijala commented on themes/finna2/templates/librarycards/selectcard.phtml
> +                <a href="<?=$this->url('displayBarcode', ['id' => $card->getId()])?>">
Käytä koko routen nimeä (controller-action), niin ei tule epäselvää.

2024-11-18 09:59 UTC, EreMaijala commented on themes/finna2/templates/librarycards/home.phtml
> +                <a href="<?=$this->url('displayBarcode', ['id' => $record['id']])?>" title="<?=$this->transEscAttr('show_barcode_title')?>">
Käytä koko routen nimeä (controller-action), niin ei tule epäselvää.

2024-11-28 09:02 UTC, EreMaijala requested changes
- Vanha Barcode/Show -reitti pitäisi säilyttää niin, että se ohjaa uuteen actioniin ja oikeaan korttiin siellä, kunhan se löytyy käyttäjän tililtä.
- Cache ei toimi.

2024-11-28 09:02 UTC, EreMaijala commented on module/Finna/src/Finna/Controller/LibraryCardsController.php
> +                [$target, $username] = explode('.', $username, 2);
`$target` on turha, jätä pois (jätä vain pilkku)

2024-12-10 09:21 UTC, EreMaijala requested changes

2024-12-10 09:21 UTC, EreMaijala commented on module/Finna/config/module.config.php
> +$config['router']['routes']['barcode-show'] = [
Vanhassa toiminnossa parametrina oli viivakoodi, ei id. Tämä ei voi toimia oikein. Tarkoitin, että jos mennään vanhaan osoitteeseen, pitäisi kaivaa annetun viivakoodin id ja ohjata uudelleen uuteen routeen. Ja tietysti kirjautumisen kautta tarpeen mukaan.

2024-12-18 07:10 UTC, EreMaijala requested changes

2024-12-18 07:10 UTC, EreMaijala commented on module/Finna/src/Finna/Controller/BarcodeController.php
> +                $auth = $this->getILSAuthenticator();
Nämä luupin ulkopuolelle.

2024-12-18 07:10 UTC, EreMaijala commented on module/Finna/src/Finna/Controller/BarcodeController.php
> +                if ($patron['cat_username'] === $card->getCatUsername()) {
Mihin tätä tarkistusta tarvitaan? Jos tuolla kortilla juuri kirjauduttiin, niin se on aina sama, eikö?

2024-12-20 08:43 UTC, EreMaijala approved these changes

2024-12-20 08:44 UTC, merged