[FINNA-2476] LIDO: add video download link and video/audio file information
NatLibFi/NDL-VuFind2 pull request #3039
Opened 2024-09-23 12:28 UTC by siiriylonen

2024-09-25 09:20 UTC, pasitiis commented on themes/finna2/templates/RecordDriver/DefaultRecord/record-video-player.phtml
> +        <div class="open-link"><a href="<?=$url['url'] ?>" target="_blank" rel="nofollow" download><?=$this->icon('download')?> <?=$this->transEsc('Download video') ?></a></div>
Ei kait latauslinkkiä tarvitse avata uuteen välilehteen? Ottaisin pois target="_blank". (sama myös äänitiedostoihin)

2024-11-06 12:32 UTC, EreMaijala commented
Poistin review-pyynnön, kunnes on paremmassa tilassa.

2024-12-10 09:52 UTC, pasitiis commented on local/languages/finna/fi.ini
> +Show information = "Näytä tiedot"
Laittaisin "Näytä videon tiedot" / Näytä äänitteen tiedot" koska kuvissa käytetty "Näytä kuvan tiedot", tuntuisi hassulta että videoissa/äänitteissä on pelkästään "Näytä tiedot". Toinen vaihtoehto olisi että kaikissa aineistossa olisi "Näytä tiedot".

2024-12-10 14:38 UTC, pasitiis approved these changes

2024-12-11 12:47 UTC, EreMaijala requested changes

2024-12-11 12:47 UTC, EreMaijala commented on themes/finna2/scss/finna/audio-player.scss
> +      font-size: 1em;
$font-size-base? Tai ehkä ennemmin koko sääntö 
```
.open-link:not(.download-audio) {
  font-size: $font-size-small;
}
```

2024-12-18 07:04 UTC, EreMaijala approved these changes

2024-12-18 07:04 UTC, merged