[FINNA-2472] & [FINNA-2603] Alter/Fix collection list tab search bar
NatLibFi/NDL-VuFind2 pull request #3044
Opened 2024-10-01 10:27 UTC by siiriylonen

2024-10-01 10:38 UTC, siiriylonen commented
Record-templaatissa vähemmän tilaa, mutta yritin tässä asetella niitä vähän paremmin siihen. (Jos pitäisi jotenkin suuremmin muutella niin ehkä erotan sen 2603 tästä..)

Tuolla mobile-toolbar.less noihin negatiivisiin marginaaleihin tuli arvoja katsoessa joku "Invalid property value" ja katsoin että se on myös dev, mutta ei tuotannossa -> siksi muutettu sitä.

2024-10-03 05:58 UTC, pasitiis commented on themes/finna2/templates/RecordTab/collectionlist.phtml
> +            <button class="btn btn-primary" type="submit" name="submitButton" >
Onko jokin syy miksei tässä voi käyttää BS:n ns. normaalia input-group rakennetta? 

<div class="input-group">
  <input type="text" class="form-control" aria-label="...">
  <div class="input-group-btn">
    <!-- Buttons -->
  </div>
</div>

2024-10-08 11:02 UTC, pasitiis commented
Jäin pohtimaan, onko tarpeellista pudottaa hakuikoni pois mobiilissa kun käytännössä rivittyy aina kahdelle riville, ja ikonia varten jäisi tilaa.   
<img width="490" alt="Näyttökuva 2024-10-08 kello 13 06 16" src="https://github.com/user-attachments/assets/8a669656-2dae-458f-8b37-0bd3a7373485">

Huomasin myös että Kokoelman sisällön järjestä valinnat ei toimi (sama myös tuotannossa tällä hetkellä).

Muutoksia on aika paljon (verratuna yläjuoksun toteutukseen), pohdin että aiheuttaako muutokset lisätyötä tulevaisuudessa.

2024-10-08 11:17 UTC, siiriylonen commented
Järjestä-nappiin liittyen tein jo tiketin, FINNA-2652. (Se järjestämisen osoite lähtee kokonaan pois /CollectionList.)

2024-10-08 13:19 UTC, pasitiis approved these changes
Tarkastelin pr:ää vain pintapuolisesti. Sivut näytti nyt skaalautuvan paremmin.

2024-10-09 08:35 UTC, EreMaijala requested changes
Muuten ok, mutta miksi pelkästään collectionlist:iä varten tehdään erilaiset kontrollit view:lle ja sorttaukselle? Olisi parempi pyrkiä yhtenäisyyteen eikä tehdä sivukohtaisesti eri tavalla.

2024-10-15 08:45 UTC, EreMaijala requested changes

2024-10-15 08:45 UTC, EreMaijala commented on themes/finna2/templates/search/controls/view.phtml
>  <div class="view-option-container text-right">
Täällä on jossain kohdassa jotain pielessä, koska sisennykset ja lopussa oleva endif eivät sovi yhteen.

2024-11-01 11:25 UTC, EreMaijala approved these changes

2024-11-01 11:25 UTC, EreMaijala commented
@siiriylonen Voisitko mergetä dev:n tähän vielä ja tsekata konfliktit?

2024-11-01 12:23 UTC, EreMaijala approved these changes

2024-11-01 12:24 UTC, merged