[FINNA-2446] Unify hierarchy tab names
NatLibFi/NDL-VuFind2 pull request #3045
Opened 2024-10-02 10:13 UTC by siiriylonen

2024-12-16 10:51 UTC, LuomaJuha reviewed
Tuli pari sivuhuomiota tuolta slackissa kysytystä kysymyksestä.

2024-12-16 10:51 UTC, LuomaJuha commented on module/Finna/src/Finna/RecordTab/CollectionHierarchyTree.php
> +            $this->driver instanceof \Finna\RecordDriver\SolrLido
SolrLido voisi toteuttaa oman version getArchiveType, vaikkakin kovakoodattuna, niin säästyisi tarkastuksia.

2024-12-16 10:51 UTC, LuomaJuha commented on module/Finna/src/Finna/RecordTab/HierarchyTree.php
> +            $this->driver instanceof \Finna\RecordDriver\SolrLido
SolrLidoon liittyvä lisäys.

2024-12-16 10:51 UTC, LuomaJuha commented on module/Finna/src/Finna/RecordTab/CollectionList.php
> +            $this->driver instanceof \Finna\RecordDriver\SolrLido
SolrLidoon liittyvä lisäys.

2024-12-16 10:51 UTC, LuomaJuha commented on module/Finna/src/Finna/RecordTab/CollectionList.php
> + * Copyright (C) Villanova University 2010.
Kommentti vaatinee viel lisäks natlibfi

2024-12-16 10:51 UTC, LuomaJuha commented on module/Finna/src/Finna/RecordDriver/SolrEad3.php
> +        if ($xml->{'add-data'}->archive->attributes()->type === 'collection') {
Vaatiiko nullsafe? $xml->{'add-data'}?->..?-> jne

2024-12-16 10:51 UTC, LuomaJuha commented on themes/finna2/templates/Recommend/CollectionSideFacets.phtml
> +    if ($this->driver instanceof \Finna\RecordDriver\SolrLido || $this->driver->tryMethod('getArchiveType') === 'collection') {
SolrLidoon liittyvä lisäys.

2024-12-16 10:51 UTC, LuomaJuha commented on themes/finna2/templates/RecordDriver/DefaultRecord/collection-record.phtml
> +        if ($this->driver instanceof \Finna\RecordDriver\SolrLido || $this->driver->tryMethod('getArchiveType') === 'collection') {
SolrLidoon liittyvä lisäys.

2024-12-20 09:07 UTC, EreMaijala requested changes
result-condensed:n kommentit koskevat myös result-list:iä. Olennaista noissa toiveissa olisi, että muuttujalla, jos sitä ylipäänsä tarvitaan, on kuvaava nimi.

2024-12-20 09:07 UTC, EreMaijala commented on module/Finna/src/Finna/RecordTab/CollectionList.php
> +{
```suggestion
{
```

2024-12-20 09:07 UTC, EreMaijala commented on module/Finna/src/Finna/RecordTab/HierarchyTree.php
> +        return 'hierarchy_tree_archive';
```suggestion
        return $this->driver->tryMethod('getArchiveType') === 'collection'
            ? 'hierarchy_tree_collection' : 'hierarchy_tree_archive';
```

2024-12-20 09:07 UTC, EreMaijala commented on module/Finna/src/Finna/View/Helper/Root/RecordDataFormatterFactory.php
> +                    return match ($driver->tryMethod('getArchiveType')) {
match on tarpeeton, kun on vain kaksi vaihtoehtoa. Ennemmin `?:`

2024-12-20 09:07 UTC, EreMaijala commented on module/Finna/src/Finna/View/Helper/Root/RecordDataFormatterFactory.php
> +                'labelFunction' => function ($data, $driver) {
match on tarpeeton, kun on vain kaksi vaihtoehtoa. Ennemmin `?:`

2024-12-20 09:07 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/collection-record.phtml
> +    <?=$this->transEsc('View Full ' . $term)?>
Olisi parempi koota heti alussa kokonainen stringi käännösavaimesta, jotta se löytyy tarvittaessa haulla. Eli jotain tyyliin `$linkText = 'View Full Collaction'`.

2024-12-20 09:07 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/DefaultRecord/result-compact.phtml
> +            <?php $term = $this->driver->tryMethod('getArchiveType') === 'collection' ? 'hierarchy_view_collection_structure' : 'hierarchy_view_context'; ?>
$term => $treeLinkText tms. Ja asetus lähempänä käyttökohtaa.

2024-12-20 09:07 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/SolrEad/result-condensed.phtml
> +            <?php $term = $typeIsArchive ? 'hierarchy_view_context' : 'hierarchy_view_collection_structure'; ?>
$term => $treeLinkText tms. Ja asetus lähempänä käyttökohtaa.

2024-12-20 09:07 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/SolrEad/result-condensed.phtml
> +            <span class="archive-label"><?=$this->transEsc($term)?>:</span>
```suggestion
            <span class="archive-label"><?=$this->transEsc($typeIsArchive ? 'Archive Origination' : 'CreatorRoles::rda:collector')?>:</span>
```

2024-12-20 09:07 UTC, EreMaijala commented on themes/finna2/templates/RecordDriver/SolrEad/result-condensed.phtml
> +            <span class="archive-label"><?=$this->transEsc($term)?>:</span>
```suggestion
            <span class="archive-label"><?=$this->transEsc($typeIsArchive ? 'Archive' : 'Parent Collection')?>:</span>
```

2024-12-20 10:49 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/SolrEad3.php
> +        if ($xml->{'add-data'}->archive->attributes()->type === 'collection') {
@siiriylonen Tämä vielä tekemättä. Ei pitäisi olla ongelma, mutta parempi olla varovainen.

2024-12-20 12:50 UTC, EreMaijala approved these changes

2024-12-20 12:51 UTC, merged