[FINNA-2131] Fix organisation info truncation
NatLibFi/NDL-VuFind2 pull request #3052
Opened 2024-10-11 07:40 UTC by siiriylonen

2024-10-15 08:55 UTC, EreMaijala requested changes

2024-10-15 08:55 UTC, EreMaijala commented on themes/finna2/js/finna-organisation-info.js
> +        lessBtn.blur();
Tämä tarvitsee vähän selvennystä. Missä tilanteessa lessBtn:ssa on fokus kun moreBtn:ia klikataan?

2024-10-15 09:21 UTC, siiriylonen commented on themes/finna2/js/finna-organisation-info.js
> +        lessBtn.blur();
Näyttäisi se toimivan ilmankin lessBtn.blur(), mutta tuo fokus siihen .less-btn laitetaan truncate.js. (Vai miten missä tilanteessa?)

2024-10-15 09:47 UTC, EreMaijala commented on themes/finna2/js/finna-organisation-info.js
> +        lessBtn.blur();
Se voi siis olla ihan ok, mutta tarttee selittävän kommentin.

2024-10-15 10:28 UTC, JJManner commented on themes/finna2/js/finna-organisation-info.js
> +        lessBtn.blur();
Saavutettavuustestit menivät läpi sekä Win / Mac puolella kaikilla selaimilla.

2024-10-15 10:59 UTC, pasitiis approved these changes

2024-10-15 11:15 UTC, EreMaijala requested changes
Tsekattu finna-ux -kanavalla, että truncate-muutos pitäisi tehdä muuhunkin toiminnallisuuteen, eli ei tehdä tässä toimintokohtaista viritystä.

2024-10-15 13:20 UTC, JJManner commented
Saavutettavuustestit menivät läpi sekä Win / Mac puolella kaikilla selaimilla tuon focus setting ja tab index poiston jälkeenkin.

2024-10-24 11:03 UTC, EreMaijala approved these changes

2024-10-24 11:03 UTC, merged