[FINNA-2662] Adjust loan history export to use paging
NatLibFi/NDL-VuFind2 pull request #3076
Opened 2024-11-04 14:51 UTC by LuomaJuha

Adjustments:
* Display max amount of pages to download from, select from which page to start download.
* Use post
* Download limits now configurable

TODO:
- [x] Translations checked

2024-11-05 07:15 UTC, LuomaJuha commented
Small adjustment to allow more large paging.

2024-11-06 13:25 UTC, EreMaijala requested changes
- Jos sivutus ei ole käytössä, paginator on false ja downloadhistory.phtml rivi 7 kaatuu
- Pitäisikö sivujen määrä olla jotenkin suhteessa sivun kokoon? Tyyliin `ceil(1000 / sivun pituus)`?
- Lomakkeen toimintaa pitää vielä miettiä. Ehkä olisi parempi, että siinä olisi vaikka checkbox, jolla valitaan, lisätäänkö olemassaolevaan tiedostoon. Nykyinen ei ole kovin ymmärrettävä. Ei se ihan selväksi tulisi sittenkään, kun lopullisen tiedoston tallennuksessa tulee alkuperäinen yliajettavaksi ja siitä tietysti varoitus.
- Toisaalta en tykkää ajatuksesta, että käyttäjä pystyy lataamaan palvelimelle jonkin sattumanvaraisen tiedoston, jota sitten koitetaan parsia. Tässä on aika merkittävä hyökkäysvektori. Mitä jos tehtäisiin nyt vähän yksinkertaisempana niin, että voi vain tallentaa uuteen tiedostoon tietyt sivut? Jää toki enemmän työtä käyttäjälle, mutta on sekin parempi kuin epäonnistuva vienti.

2024-11-06 13:25 UTC, EreMaijala commented on local/languages/finna/fi.ini
> +loan_history_append_file = "Valitse tiedosto, mihin lainahistoriaa jatketaan"
mihin => johon

2024-11-06 13:25 UTC, EreMaijala commented on local/languages/finna/fi.ini
> +loan_history_info = "Valitse aloitussivu lainahistorian lataamiselle. Sivuja ladataan ensimmäinen valittu sivu ja 9 seuraavaa."
*lainaushistoria
Tarviiko olla noin monimutkaisesti? "Sivuja ladataan korkeintaan 10"?

2024-11-06 13:25 UTC, EreMaijala commented on themes/finna2/templates/checkouts/downloadhistory.phtml
> +  <button data-lightbox-ignore class="btn btn-primary" type="submit" name="submitLoanHistoryRequest" value="<?=$this->transEscAttr('Submit')?>"><?=$this->transEsc('submit');?></button>
submit pienellä ei käänny

2024-11-06 13:27 UTC, EreMaijala commented
@LuomaJuha Perhaps just avoid the modal and display the download options on a separate page?

2024-11-06 17:21 UTC, LuomaJuha commented
@EreMaijala joo, yksinkertaistan ja poistan tuon tiedostoon jatkamisen. Voi tulla muuten jotain ylimäärästä säätöä tuosta.

2024-11-18 11:55 UTC, EreMaijala commented
Tuli mieleen jännä ajatus tuosta lainaushistorian lataamisesta: Mitä jos tekisikin sellaisen, että kun ladattavaa on liikaa, näytetään nappula "Lataa osa 1/5". Kun sitä klikkaa, se pistää lataukseen ekan osan ja vaihtaa nappulaksi "Lataa osa 2/5"? Sitten se voisi lisätä tiedoston nimeen myös osan numeron fiksusti, ja lataaminen olisi niin helppoa kuin tällä systeemillä vaan voi.

2024-11-19 08:16 UTC, LuomaJuha commented
@EreMaijala Poistan review:n ja laitan uudestaan kun on tuunattu

2025-01-15 12:48 UTC, EreMaijala requested changes

2025-01-15 12:48 UTC, EreMaijala commented on local/languages/finna/en-gb.ini
> +loan_history_info = "Pages downloaded at most %%total%%"
"Maximum pages to download with single request: %%total%%" ?

2025-01-15 12:48 UTC, EreMaijala commented on module/Finna/config/module.config.php
> +                        'Finna\AjaxHandler\AbstractIlsAndUserActionFactory',
Tee ennemmin GetTransactionHistoryFactory (tai GetCheckoutHistoryFactory, ks. alempana) joka periytyy AbstractIlsAndUserActionFactory:sta. ks. GetUserFinesFactory.

2025-01-15 12:48 UTC, EreMaijala commented on module/Finna/src/Finna/AjaxHandler/GetTransactionHistory.php
> + * GetFeed AJAX handler
höm

2025-01-15 12:48 UTC, EreMaijala commented on module/Finna/src/Finna/AjaxHandler/GetTransactionHistory.php
> + * GetFeed AJAX handler
kröhöm

2025-01-15 12:48 UTC, EreMaijala commented on module/Finna/src/Finna/AjaxHandler/GetTransactionHistory.php
> + * @author   Konsta Raunio <konsta.raunio@helsinki.fi>
höm

2025-01-15 12:48 UTC, EreMaijala commented on module/Finna/src/Finna/AjaxHandler/GetTransactionHistory.php
> + * @author   Konsta Raunio <konsta.raunio@helsinki.fi>
hömhöm

2025-01-15 12:48 UTC, EreMaijala commented on module/Finna/src/Finna/AjaxHandler/GetTransactionHistory.php
> +<?php
Käyttäisin nykyään transaction-sanan tilalla ennemmin vaikka checkout, kun transaction sekoittuu helposti maksamiseen.

2025-01-15 12:48 UTC, EreMaijala commented on module/Finna/src/Finna/Controller/AjaxController.php
> +            return $this->getFileResponse($data);
Eikä tämä nyt sotke kaikki muut paitsi file-tyyppisen vastauksen?

2025-01-15 12:50 UTC, EreMaijala commented
Lataus tarttee progress-indikaattorin. Nyt ei näy mitenkään, jos jotain tapahtuu.

2025-01-15 12:51 UTC, EreMaijala commented on local/config/finna/config.ini.sample
> +loan_history_download_batch_limit = 1000
Tämä ei näytä vaikuttavan dropdownissa näkyvään sivumäärään.

2025-01-15 13:56 UTC, LuomaJuha commented on module/Finna/config/module.config.php
> +                        'Finna\AjaxHandler\AbstractIlsAndUserActionFactory',
ooh, jönses mitenhä mä ton oon missannu!

2025-01-15 14:23 UTC, LuomaJuha commented on module/Finna/src/Finna/AjaxHandler/GetTransactionHistory.php
> + * GetFeed AJAX handler
:see_no_evil:

2025-01-15 17:44 UTC, LuomaJuha commented on module/Finna/src/Finna/Controller/AjaxController.php
> +            return $this->getFileResponse($data);
Splittasin sille filepolulle vähän oman tarkastelun.

2025-01-15 17:45 UTC, LuomaJuha commented on local/config/finna/config.ini.sample
> +loan_history_download_batch_limit = 1000
ny pitäis taas vaikuttaa!

2025-01-16 07:30 UTC, EreMaijala requested changes
Jotain hämärää tossa on edelleen on noiden sivutusten kanssa. Jos asetuksissa on 
```
[Catalog]
historic_loan_page_size = 3
loan_history_download_batch_limit = 2
```
Niin jos on 7 lainaa, kertoo oikein, että neljä sivua. Mutta kun laittaa latauksen menemään, niin saa tiedostot:

1. -1-1, jossa on 3 tietuetta
2. -2-2, jossa on toiset 3
3. -3-3, jossa on 1 tietue
4. -4-4, jossa ei ole mitään

Pitäisikö ton jälkimmäisen numeron tiedoston nimessä olla kokonaismäärä?

2025-01-16 09:09 UTC, LuomaJuha commented
Hmm, pitääkin katsoa mitäs siel tapahtuu. Toi vika oli ns viimeinen sivu. Veikkaan että jätän sen pois jos on vaan 1 sivu tuloksessa.

2025-02-10 11:29 UTC, EreMaijala commented
@LuomaJuha Tsekkaatko konfliktit? Dropdown-itemit tarttee nyt dropdown-item -luokan.

2025-02-10 11:31 UTC, EreMaijala approved these changes
Tämä toimii nyt nähdäkseni ihan hyvin ja voidaan mergetä, kun konfliktit on tsekattu. Käyttöliittymää voisi ehkä vielä miettiä. Voisi olla selkeämpi, jos lataus avaisi vaikka erillisen sivun, jossa olisi aina lataa seuraava osa -nappula tms.

Suosikkeihin kopioinnin pitäisi tehdä vastaavasti palanen kerrallaan, mutta ilman latausta.

2025-02-10 11:54 UTC, LuomaJuha commented
@EreMaijala Juu, mie katon! :)

2025-02-12 10:11 UTC, EreMaijala requested changes

2025-02-12 10:11 UTC, EreMaijala commented on local/languages/finna/en-gb.ini
> +download_checkout_history_info = ""
_html -pääte tälle

2025-02-12 10:21 UTC, EreMaijala approved these changes

2025-02-12 10:23 UTC, merged