[FINNA-2739] Unify confirm button styles and remove local adjustments
NatLibFi/NDL-VuFind2 pull request #3083
Opened 2024-11-12 11:26 UTC by LuomaJuha

- [ ] Vaatinee: #https://github.com/vufind-org/vufind/pull/4071

2024-12-09 09:52 UTC, EreMaijala requested changes
Vielä vähän erinäköiset nuo dropdownit (testattu macOS Firefox & Chrome):
![ kirjastokortti](https://github.com/user-attachments/assets/94e71a89-53a7-4a3e-ab3e-57a3f5a54a1f)

![lista](https://github.com/user-attachments/assets/86f2b41f-c697-43b4-982b-6b963ab106a7)

Sanoisin, että tuossa listan poistossa hover-tausta on paremman näköinen, kun se täyttää suunnilleen tuon alueen.

2024-12-10 09:23 UTC, EreMaijala requested changes
Melkein ok, mutta listan poistossa väliviivat ovat jotenkin "järeämmät". Kirjastokortin poisto näyttää nyt paremmalta.

2024-12-10 11:19 UTC, LuomaJuha commented
Joo, vähä border radiukset oli nihkeästi noissa.

2024-12-10 11:37 UTC, EreMaijala approved these changes

2024-12-10 11:37 UTC, merged