[FINNA-2865] Add site status bar
NatLibFi/NDL-VuFind2 pull request #3090
Opened 2024-11-28 13:00 UTC by aleksip

2024-12-02 12:57 UTC, EreMaijala approved these changes

2024-12-02 12:58 UTC, EreMaijala requested changes
Eiku ootas, lisää vielä en-gb.ini:iin käännökset, vaikka ne vastaisivatkin enumin arvoja.

2024-12-03 09:34 UTC, aleksip commented
Joo, oli unohtunut. Tässä samalla tuli vielä se asetuksen siirto toiseen paikkaan.

2024-12-04 09:15 UTC, EreMaijala approved these changes

2024-12-04 09:16 UTC, merged