[FINNA-2629] Improve hierarchy tree's visual presentation
NatLibFi/NDL-VuFind2 pull request #3096
Opened 2024-12-03 13:30 UTC by siiriylonen

2024-12-04 09:24 UTC, siiriylonen commented
(Väreistä sen verran että käytin valmiita muuttujia, jotka hieman tummempia kuin suunnitelmassa.
a2a2a2 -> 919191 & dfdfdf -> d1d1d1, voi vaihtaa niihinkin.)

2024-12-04 10:35 UTC, EreMaijala requested changes

2024-12-04 10:35 UTC, EreMaijala commented on themes/finna2/scss/finna-other.scss
> +            font-size: 18px;
Voisiko käyttää suhteellista kokoa tyyliin `1.2rem`?

2024-12-04 14:22 UTC, siiriylonen commented on themes/finna2/scss/finna-other.scss
> +            font-size: 18px;
Se on nyt 1.8rem, mutta buttonilla ei nyt näytä olevan se yleinen fontti, vaan inherit (html:stä??) 10px. (Että jos ok sellainen peritty laittaa suhteelliseksi niin nyt on.)

2024-12-09 11:59 UTC, EreMaijala commented on themes/finna2/scss/finna-other.scss
> +            font-size: 18px;
Uuh, meiltä puuttui se. #3100...

2024-12-09 12:06 UTC, siiriylonen commented on themes/finna2/scss/finna-other.scss
> +            font-size: 18px;
Aa, vaihdan luvun sen perusteella sitten vielä

2024-12-10 09:23 UTC, EreMaijala approved these changes

2024-12-10 09:23 UTC, merged