[FINNA-2838] Add Finna specific OAI metadata format
NatLibFi/NDL-VuFind2 pull request #3097
Opened 2024-12-03 13:56 UTC by LuomaJuha

Adds couple fields to be exposed in the OAI response.

2024-12-10 11:35 UTC, EreMaijala requested changes
Tässä voisi olla hyötyä siitä, että yläjuoksulla [tuo ensimmäinen blokki attachNonDeleted:stä](https://github.com/vufind-org/vufind/blob/482043dde05a2330eb06a7aec9dbca7386a6788c/module/VuFind/src/VuFind/OAI/Server.php#L447-L458) irrotettaisiin omaksi metodiksi, jota attachNonDeleted kutsuu, niin ei tarvitsisi koko metodia yliajaa.

2024-12-10 11:35 UTC, EreMaijala commented on local/config/finna/SearchApiRecordFields.yaml.sample
> +  description: Usage rights
`Usage rights (see [usage_rights_str_mv at https://www.kiwi.fi/display/Finna/Kenttien+mappaukset+eri+formaateista+Finnan+indeksiin](https://github.com/NatLibFi/RecordManager-Finna/blob/dev/mappings/usage_rights.map.sample))`

2024-12-10 11:35 UTC, EreMaijala commented on local/config/finna/SearchApiRecordFields.yaml.sample
> +  description: Usage rights extended
`Extended usage rights (see https://github.com/NatLibFi/RecordManager-Finna/blob/dev/mappings/usage_rights_ext.map.sample)`

2024-12-10 11:35 UTC, EreMaijala commented on local/config/finna/config.ini.sample
> +;finna_api_format_fields = "id,authors,cleanIsbn,cleanIssn,formats,title,images,mediaTypes,ctrlnum,institutions,year,recordFormat,sectors,majorGenres,usageRights,usageRightsExtended,measurements,coll
Tyhjä rivi takaisin ennen Proxy-sektiota.

2024-12-10 11:35 UTC, EreMaijala commented on module/Finna/src/Finna/OAI/Server.php
> +            return true;
Tämän pitäisi olla `return false;`

2024-12-20 14:01 UTC, EreMaijala requested changes

2024-12-20 14:01 UTC, EreMaijala commented on local/config/finna/SearchApiRecordFields.yaml.sample
> +  description: Ctrl num
Record control numbers

2024-12-20 14:01 UTC, EreMaijala commented on local/config/finna/SearchApiRecordFields.yaml.sample
> +  description: Major genres as array
Pelkkä `Major genres` (`type: array` kertoo tyypin)

2024-12-20 14:01 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/Feature/SolrFinnaTrait.php
> +            fn ($entry) => $entry instanceof \VuFind\I18n\TranslatableString ? $entry->__toString() : $entry,
Tässä pitäisi riittää `(string)$entry` kaikissa tapauksissa.

2024-12-23 09:32 UTC, LuomaJuha commented on module/Finna/src/Finna/RecordDriver/Feature/SolrFinnaTrait.php
> +            fn ($entry) => $entry instanceof \VuFind\I18n\TranslatableString ? $entry->__toString() : $entry,
ohops, totta tosiaan

2025-01-15 12:58 UTC, EreMaijala requested changes

2025-01-15 12:58 UTC, EreMaijala commented on local/config/finna/SearchApiRecordFields.yaml.sample
> +ctrlnum:
```suggestion
controlNumbers:
```

2025-01-15 12:58 UTC, EreMaijala commented on local/config/finna/config.ini.sample
> +;finna_api_format_fields = "id,authors,cleanIsbn,cleanIssn,formats,title,images,mediaTypes,ctrlnum,institutions,year,recordFormat,sectors,majorGenres,usageRights,usageRightsExtended,measurements,coll
```suggestion
;finna_api_format_fields = "id,authors,cleanIsbn,cleanIssn,formats,title,images,mediaTypes,controlNumbers,institutions,year,recordFormat,sectors,majorGenres,usageRights,usageRightsExtended,measurements,collections"
```

2025-01-15 12:58 UTC, EreMaijala commented on module/Finna/src/Finna/RecordDriver/Feature/SolrFinnaTrait.php
> +    public function getCtrlNum(): array
```suggestion
    public function getControlNumbers(): array
```

2025-01-15 12:58 UTC, EreMaijala commented on local/config/finna/SearchApiRecordFields.yaml.sample
> +  vufind.method: getCtrlNum
```suggestion
  vufind.method: getControlNumbers
```

2025-01-15 12:59 UTC, EreMaijala commented
Hyvältä näyttää, mutta ajattelin, että voisi vielä selkeyttää noita kenttien ja metodien nimiä.

2025-01-15 14:29 UTC, EreMaijala approved these changes

2025-01-15 14:29 UTC, merged