[FINNA-2373] Fix search filters on smaller screens for sr
NatLibFi/NDL-VuFind2 pull request #3110
Opened 2024-12-17 13:12 UTC by siiriylonen

2025-01-15 13:13 UTC, pasitiis commented on themes/finna2/js/finna-layout.js
> +  function onFocusOut(e) {
Nimeäisin funktion kuvaavammin.

2025-01-24 09:53 UTC, pasitiis commented on themes/finna2/templates/Recommend/SideFacetsDeferred.phtml
> +  <div class="header-container">
Pitäsikö luokan nimi olla side-facets-header-container tms.? Nyt ehkä vähän liian geneerinen.

2025-02-11 12:11 UTC, EreMaijala requested changes

2025-02-11 12:11 UTC, EreMaijala commented on themes/finna2/js/finna-layout.js
> +    $('.mobile-navigation .sidebar-navigation i').toggleClass('fa-arrow-down');
Ei ikonin luokkaa kovakoodattuna. Jos pitää JS:ssä vaihtaa ikonia, niin pitää laittaa templaatissa kaksi ikonia, joita vaihdellaan.

2025-02-11 12:11 UTC, EreMaijala commented on themes/finna2/js/finna-layout.js
> +    const container = document.querySelector(".side-facets-container-ajax");
Pitää tarkistaa, löytyikö container (tyyliin `if (!container) { return; }`).

2025-02-11 12:11 UTC, EreMaijala commented on themes/finna2/scss/finna/result-sidebar.scss
> +  background-color: $brand-primary;
$sidebar-background

2025-02-11 12:11 UTC, EreMaijala commented on themes/finna2/scss/finna/result-sidebar.scss
> +    background-color: $brand-primary;
$sidebar-background

2025-02-12 15:59 UTC, pasitiis commented
Rajauksen ohjeen tooltipin voisi vaihtaa BS5:sta Finnan omaan. En päässyt käsiksi BS5 tooltipien sisältöön VO:lla.

2025-02-14 13:15 UTC, pasitiis approved these changes
Testasin Voiceoverilla, näytti toimivan hyvin.

2025-02-14 13:38 UTC, EreMaijala requested changes
Kun tähän nyt

2025-02-14 13:38 UTC, EreMaijala commented on themes/finna2/js/finna-layout.js
> +    $('.mobile-navigation .sidebar-navigation, .sidebar .mylist-bar h1').off('click').on('click', function onClickMobileNav() {
Kun tähän nyt kosketaan, niin voisiko samalla siivota jQueryt pois?

2025-02-14 13:38 UTC, EreMaijala commented on themes/finna2/js/finna-layout.js
> +  function onSidebarBtnClick() {
Tän nimeksi jotain toimintaa kuvaavampaa, esim. toggleMobileSidebar (ja kuvaus sen mukaisesti). On sitten huomattavasti siistimpää kutsua keydown-handlerista (joka voisi muuten olla myös erillinen funktio).

2025-03-06 12:51 UTC, EreMaijala approved these changes

2025-03-06 12:51 UTC, merged